### ISSUE TITLE
stack fails to install `old-time` on Windows if ghc is specified in PATH

### ISSUE THREAD

**Issue by foreverbell** [commercialhaskell/stack#1189] opened 2015-10-18 03:17 UTC
Hello. 

I am using stack 0.1.6.0(`e22271f5ce9afa2cb5be3bad9cafa392c623f85c (2313 commits) x86_64`) on Windows 8.1, and was installing `old-time` by `stack install old-time`.

For some convenience reason, I put ghc binary path provided by stack in my PATH environment variable, i.e. `STACK_PATH\x86_64-windows\ghc-7.10.2\bin` (where `STACK_PATH=D:\Dev\stack` in this case). However, `old-time` fails to install, with the following output  

```
C:\Users\foreverbell>stack install old-time
Run from outside a project, using implicit global project config
Using resolver: lts-3.9 from implicit global project's config file: C:\Users\foreverbell\AppData\Roaming\stack\global-project\stack.yaml
Setting codepage to UTF-8 (65001) to ensure correct output from GHC
old-locale-1.0.0.7: configure
old-locale-1.0.0.7: build
old-locale-1.0.0.7: install
old-time-1.1.0.3: configure
old-time-1.1.0.3: build
Completed
--  While building package old-time-1.1.0.3 using:
      C:\Users\FOREVE~1\AppData\Local\Temp\stack2056\old-time-1.1.0.3\.stack-work\dist\d96ab9d9\setup\setup --builddir=.stack-work\dist\d96ab9d9\ build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Users\foreverbell\AppData\Roaming\stack\global-project\.stack-work\logs\old-time-1.1.0.3.log

    [1 of 1] Compiling Main             ( C:\Users\FOREVE~1\AppData\Local\Temp\stack2056\old-time-1.1.0.3\Setup.hs, C:\Users\FOREVE~1\AppData\Local\Temp\stack2056\old-time-1.1.0.3\.stack-work\dist\d96ab9d9\setup\Main.o )
    Linking C:\Users\FOREVE~1\AppData\Local\Temp\stack2056\old-time-1.1.0.3\.stack-work\dist\d96ab9d9\setup\setup.exe ...
    Configuring old-time-1.1.0.3...
    configure: WARNING: unrecognized options: --with-compiler, --with-gcc
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.exe
    checking for suffix of executables... .exe
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking sys/time.h usability... yes
    checking sys/time.h presence... yes
    checking for sys/time.h... yes
    checking sys/timeb.h usability... yes
    checking sys/timeb.h presence... yes
    checking for sys/timeb.h... yes
    checking time.h usability... yes
    checking time.h presence... yes
    checking for time.h... yes
    checking for ftime... yes
    checking for gmtime_r... yes
    checking for localtime_r... yes
    checking for gettimeofday... yes
    checking whether struct tm is in sys/time.h or time.h... time.h
    checking for struct tm.tm_zone... yes
    checking whether time.h and sys/time.h may both be included... yes
    checking for sys/time.h... (cached) yes
    checking whether altzone is declared... no
    configure: creating ./config.status
    config.status: creating include/HsTimeConfig.h
    configure: WARNING: unrecognized options: --with-compiler, --with-gcc
    Building old-time-1.1.0.3...
    Preprocessing library old-time-1.1.0.3...
    Time.hsc: In function 'main':
    Time.hsc:361:5: error: 'struct tm' has no member named 'tm_zone'
    Time.hsc:362:5: error: 'struct tm' has no member named 'tm_gmtoff'
    compiling .stack-work\dist\d96ab9d9\build\System\Time_hsc_make.c failed (exit code 1)
    command was: D:\Dev\stack\x86_64-windows\ghc-7.10.2\mingw\bin\gcc.exe -c .stack-work\dist\d96ab9d9\build\System\Time_hsc_make.c -o .stack-work\dist\d96ab9d9\build\System\Time_hsc_make.o -D__GLASGOW_HASKELL__=710 -Dmingw32_BUILD_OS=1 -Dx86_64_BUILD_ARCH=1 -Dmingw32_HOST_OS=1 -Dx86_64_HOST_ARCH=1 -Iinclude -I.stack-work\dist\d96ab9d9\build\autogen -include .stack-work\dist\d96ab9d9\build\autogen\cabal_macros.h -ID:\Dev\stack\x86_64-windows\ghc-7.10.2\lib\base_GDytRqRVSUX7zckgKqJjgw\include -ID:\Dev\stack\x86_64-windows\ghc-7.10.2\lib\integ_2aU3IZNMF9a7mQ0OzsZ0dS\include -ID:\Dev\stack\x86_64-windows\ghc-7.10.2\lib/include -ID:\Dev\stack\x86_64-windows\ghc-7.10.2/lib/include/
```

If the PATH is clean without ghc, everything works okay. 

It is a bug?

**Comment by borsboom** [comment] 2015-11-01 17:36
I haven't been able to reproduce your exact error, but I I did get a different error when I put the `ghc` matching the architecture of my `stack` executable (in my case, i386) on the PATH:

```
Run from outside a project, using implicit global project config
Using resolver: lts-3.9 from implicit global project's config file: C:\Users\emanu\AppData\Roaming\stack\global-project\stack.yaml
Setting codepage to UTF-8 (65001) to ensure correct output from GHC
old-locale-1.0.0.7: configure
old-locale-1.0.0.7: build
old-locale-1.0.0.7: install
old-time-1.1.0.3: configure
Completed
--  While building package old-time-1.1.0.3 using:
      C:\Users\emanu\AppData\Local\Temp\stack2656\old-time-1.1.0.3\.stack-work\dist\49224016\setup\setup --builddir=.stack-work\dist\49224016\ configure --with-ghc=C:\Users\emanu\AppData\Local\programs\stack\i386-windows\ghc-7.10.2\bin\ghc.exe --user --package-db=clear --package-db=global --package-db=C:\Users\emanu\AppData\Roaming\stack\snapshots\i386-windows\lts-3.9\7.10.2\pkgdb\ --libdir=C:\Users\emanu\AppData\Roaming\stack\snapshots\i386-windows\lts-3.9\7.10.2\lib --bindir=C:\Users\emanu\AppData\Roaming\stack\snapshots\i386-windows\lts-3.9\7.10.2\bin --datadir=C:\Users\emanu\AppData\Roaming\stack\snapshots\i386-windows\lts-3.9\7.10.2\share --libexecdir=C:\Users\emanu\AppData\Roaming\stack\snapshots\i386-windows\lts-3.9\7.10.2\libexec --sysconfdir=C:\Users\emanu\AppData\Roaming\stack\snapshots\i386-windows\lts-3.9\7.10.2\etc --docdir=C:\Users\emanu\AppData\Roaming\stack\snapshots\i386-windows\lts-3.9\7.10.2\doc\old-time-1.1.0.3 --htmldir=C:\Users\emanu\AppData\Roaming\stack\snapshots\i386-windows\lts-3.9\7.10.2\doc\old-time-1.1.0.3 --haddockdir=C:\Users\emanu\AppData\Roaming\stack\snapshots\i386-windows\lts-3.9\7.10.2\doc\old-time-1.1.0.3 --dependency=base=base-4.8.1.0-4411f755eeebe72a83715ecebc424dd9 --dependency=old-locale=old-locale-1.0.0.7-3588c6880f1cb77ccff98e204e99a556
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Users\emanu\AppData\Roaming\stack\global-project\.stack-work\logs\old-time-1.1.0.3.log

    [1 of 1] Compiling Main             ( C:\Users\emanu\AppData\Local\Temp\stack2656\old-time-1.1.0.3\Setup.hs, C:\Users\emanu\AppData\Local\Temp\stack2656\old-time-1.1.0.3\.stack-work\dist\49224016\setup\Main.o )
    Linking C:\Users\emanu\AppData\Local\Temp\stack2656\old-time-1.1.0.3\.stack-work\dist\49224016\setup\setup.exe ...
    Configuring old-time-1.1.0.3...
    setup: The package has a './configure' script. This requires a Unix
    compatibility toolchain such as MinGW+MSYS or Cygwin.
```

This makes me think Stack is skipping some possibly necessary environment setup if it detects a usable `ghc` on the PATH in Windows (I always run this way on OS X, and haven't had any trouble).  That may be a legitimate behaviour, because I could see insisting on changing the environment even with a usable `ghc` on the PATH causing different problems.  @snoyberg, any thoughts?

**Comment by snoyberg** [comment] 2015-11-01 19:31
Yup, this is behaving as expected. When Stack installs the toolchain
itself, it installs both GHC and MSYS2. However, when it detects GHC on the
PATH, it won't install MSYS2, since it has no reasonable way of doing so
without corrupting the toolchain.

**Comment by borsboom** [comment] 2015-11-03 00:10
Perhaps we could add a special case for when the `ghc` on the PATH is in Stack's own programs directory (i.e. `stack setup` installed it, and it's the same one that Stack would add to the path in its environment anyway).  It's pretty common for people to add those to their PATH (I do it myself as well).  Or, @snoyberg, is there a reason we should recommend _against_ adding Stack's `ghc` to the PATH on Windows?

@foreverbell: does using `stack --no-system-ghc` help?

**Comment by foreverbell** [comment] 2015-11-03 00:41
@borsboom Yes, `--no-system-ghc` works on my machine.

**Comment by normenmueller** [comment] 2016-11-05 13:14
Is there any update on this issue?

I'm on MS Windows 7 using

    $ stack --version
    Version 1.2.0, Git revision 123819b7d65df2ad7fe63fb5eb39a98536acb5f3 (4055 commits) x86_64 hpack-0.14.0

and getting the following error:

    $ stack build --no-system-ghc ghc-mod
    old-time-1.1.0.3: configure
    split-0.2.3.1: download
    [...]
    text-1.2.2.1: build
    text-1.2.2.1: copy/register
    
    --  While building package old-time-1.1.0.3 using:
          C:\cygwin64\tmp\stack11052\old-time-1.1.0.3\.stack-work\dist\b7fec021\setup\setup --builddir=.stack-work\dist\b7fec021 configure --with-ghc=C:\Users\normen.mueller\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc.EXE --with-ghc-pkg=C:\Users\normen.mueller\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\b7d00e9c\pkgdb --libdir=C:\sr\snapshots\b7d00e9c\lib --bindir=C:\sr\snapshots\b7d00e9c\bin --datadir=C:\sr\snapshots\b7d00e9c\share --libexecdir=C:\sr\snapshots\b7d00e9c\libexec --sysconfdir=C:\sr\snapshots\b7d00e9c\etc --docdir=C:\sr\snapshots\b7d00e9c\doc\old-time-1.1.0.3 --htmldir=C:\sr\snapshots\b7d00e9c\doc\old-time-1.1.0.3 --haddockdir=C:\sr\snapshots\b7d00e9c\doc\old-time-1.1.0.3 --dependency=base=base-4.9.0.0 --dependency=old-locale=old-locale-1.0.0.7-6glXNhHF891B41ZfuI8hU8 --extra-include-dirs=C:\Users\normen.mueller\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\include --extra-lib-dirs=C:\Users\normen.mueller\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\lib
        Process exited with code: ExitFailure 77
        Logs have been written to: C:\Users\normen.mueller\Sources\learning.haskell\Scratch\.stack-work\logs\old-time-1.1.0.3.log
    
        [1 of 1] Compiling Main             ( C:\cygwin64\tmp\stack11052\old-time-1.1.0.3\Setup.hs, C:\cygwin64\tmp\stack11052\old-time-1.1.0.3\.stack-work\dist\b7fec021\setup\Main.o )
        Linking C:\cygwin64\tmp\stack11052\old-time-1.1.0.3\.stack-work\dist\b7fec021\setup\setup.exe ...
        Configuring old-time-1.1.0.3...
        configure: WARNING: unrecognized options: --with-compiler
        checking for gcc... C:\Users\NORMEN~1.MUE\AppData\Local\Programs\stack\X86_64~1\GHC-80~1.1\mingw\bin\gcc.exe
        checking whether the C compiler works... no
        configure: error: in `/c/cygwin64/tmp/stack11052/old-time-1.1.0.3':
        configure: error: C compiler cannot create executables
        See `config.log' for more details
    
Any suggestions on how to proceed further?

**Comment by mgsloan** [comment] 2016-11-08 00:26
@normenmueller Not sure what could cause that.  Could try doing the install again.  This'd look like deleting the `C:\Users\NORMEN~1.MUE\AppData\Local\Programs\stack\X86_64~1\GHC-80~1.1` folder and files with the name `GHC-*.installed`?  Then try running setup again.

**Comment by snoyberg** [comment] 2019-03-20 08:09
The original issue is resolved by defaulting to `--no-system-ghc`, closing.

**Closed by snoyberg** 2019-03-20 08:09 UTC
Labels: component: windows, type: discuss
