### ISSUE TITLE
Certificate issue due to corporate proxy?

### ISSUE THREAD

**Issue by loopdigga98** [commercialhaskell/stack#4509] opened 2019-01-17 16:48 UTC
I am trying to build application
```
stack build
```

And get following error
```
Downloading lts-9.10 build plan ...
RedownloadHttpError (HttpExceptionRequest Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","The Haskell Stack")]
  path                 = "/fpco/lts-haskell/master//lts-9.10.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa)))))
```

I know that to solve this issue i need to disable certificate verification. Could you tell me please how to perform this?

**Comment by dbaynard** [comment] 2019-01-24 11:38
Duplicate of #907? Please reopen if that doesn't solve your problem.

**Closed by dbaynard** 2019-01-24 11:38 UTC
Labels: component: network-access, resolution: duplicate
