### ISSUE TITLE
Bash completion in .deb

### ISSUE THREAD

**Issue by magthe** [commercialhaskell/stack#1107] opened 2015-10-06 07:40 UTC
The `.deb` contains a bash completion file that has a bug:

    COMPREPLY=( $(usr/bin/stack "${CMDLINE[@]}") )

is missing a `/`.

Also, I don't know where that completion file comes from, if I knew I could have provided a merge request :)  (Or maybe it's auto-generated?)

**Comment by borsboom** [comment] 2015-10-06 13:25
Duplicate of #1056

**Closed by borsboom** 2015-10-06 13:25 UTC
