### ISSUE TITLE
hsc2hs breaks on Windows with many dependencies

### ISSUE THREAD

**Issue by mkscrg** [commercialhaskell/stack#1718] opened 2016-01-29 22:35 UTC
On Windows, Stack fails to build projects with `.hsc` files and many dependencies. The error looks like

```
--  While building package hsc2hs-windows-broken-0.0.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\setup-Simple-Cabal-1.22.5.0-ghc-7.10.3.exe --builddir=.stack-work\dist\2672c1f3 build exe:hsc2hs-windows-broken --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\vagrant\.stack-work\logs\hsc2hs-windows-broken-0.0.0.log

    Configuring hsc2hs-windows-broken-0.0.0...
    Preprocessing executable 'hsc2hs-windows-broken' for
    hsc2hs-windows-broken-0.0.0...
    setup-Simple-Cabal-1.22.5.0-ghc-7.10.3.exe:
    C:\Users\vagrant\AppData\Local\Programs\stack\x86_64-windows\ghc-7.10.3\bin\hsc2hs.exe:
    does not exist
```

Here's a Vagrant-ized Gist with repro instructions: https://gist.github.com/mkscrg/18c560b8eb303c6ebcf2

FWIW, this feels similar to #466 / #795 / [ghc#10777](https://ghc.haskell.org/trac/ghc/ticket/10777#ticket).

Workaround: move `.hsc` code into a Stack sub-project.

cc @bsummer4

**Comment by mgsloan** [comment] 2016-02-04 02:54
Based on that error message, it looks like `hsc2hs.exe` might be missing.  Alternatively, it is failing out with `does not exist`.  Strange!

Thanks for the vagrant repro.  This is most likely an upstream bug in Cabal, since stack doesn't know anything about `hsc2hs` (it literally is never mentioned in the stack codebase).

**Comment by mkscrg** [comment] 2016-02-04 03:23
Makes sense re. Cabal bug. However I can confirm that hsc2hs.exe does exist
in the VM at that path.

I'm not familiar enough with the stack/Cabal boundary to make a Cabal-based
repro. Can one of the stack maintainers do that and report the issue
upstream?

**Comment by mgsloan** [comment] 2016-02-04 04:11
The stack/Cabal boundary is pretty straightforward - it just invokes compiled Setup.hs files (even for the "simple" build type).

So, the issue might be visible when `stack build -v --cabal-verbose` builds the affected package.  The cabal invocations should be runnable on the commandline, so copy pasting them can lead to a reproduction independent of stack.

**Comment by mkscrg** [comment] 2016-02-04 04:22
Thanks! I'll give it a go

**Comment by ezyang** [comment] 2016-08-12 07:07
To just give a quick update from the Cabal update: the problem is that we are passing too many arguments to `hsc2hs`. The solution would be to use a response file, like was done in Haddock.

**Comment by mgsloan** [comment] 2016-10-18 21:24
Sounds like this is resolved in an updated Cabal version.

Closing this, as it's an old support ticket.  If you think this is in error, please comment with more info.

**Comment by borsboom** [comment] 2017-10-28 13:14
I don't think this is actually resolved upstream yet.  Still seems to happen with Cabal 2.0 and GHC 8.2.1, and the [Cabal issue](https://github.com/haskell/cabal/issues/3122) and [GHC issue](https://ghc.haskell.org/trac/ghc/ticket/13896) are still open.

**Comment by mgsloan** [comment] 2017-10-29 01:00
Ok, reopening!

**Closed** 2023-04-09 00:02 UTC
Labels: resolution: upstream issue
