### ISSUE TITLE
"Left ... Did not find .cabal" printed to console during `stack install` and `stack build`

### ISSUE THREAD

**Issue by rainbyte** [commercialhaskell/stack#2478] opened 2016-08-11 20:03 UTC
I'm experiencing this issue inside a docker container, based on haskell:7.10.3 image...

`stack  --version` says:
```
Version 1.1.2, Git revision cebe10e845fed4420b6224d97dcabf20477bbd4b (3646 commits) x86_64 hpack-0.14.0
```

When I run the cmd
```
stack install --stack-root $PWD/.stack-root/ --work-dir .stack-work-docker/ --local-bin-path artifacts/
```
It shows this
```
Downloading lts-6.10 build plan ...
Downloaded lts-6.10 build plan.
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpcomplete.com/00-index.tar.gz) ...
Downloading package index from https://s3.amazonaws.com/hackage.fpcomplete.com/00-index.tar.gz
Populating index cache ...
Populated index cache.
Did not find .cabal file for zot-0.0.3 with Git SHA of f9092bae03d0044d2b4e3f33609c9544e8c46b19
Left /src/.stack-root/indices/Hackage/git-update/all-cabal-hashes/.git/objects/pack: listDirectory: does not exist (No such file or directory)
Did not find .cabal file for zlib-lens-0.1.2.1 with Git SHA of b5797267b30c16afcccbd42fa0ce4b9fa58a7ca9
Left /src/.stack-root/indices/Hackage/git-update/all-cabal-hashes/.git/objects/pack: listDirectory: does not exist (No such file or directory)
```
And after various similar lines, I get
```
Left /src/.stack-root/indices/Hackage/git-update/all-cabal-hashes/.git/objects/pack: listDirectory: does not exist (No such file or directory)
Did not find .cabal file for AC-Vector-2.3.2 with Git SHA of 32d97a60969fe6912b33597e7399c407b5f2e39a
Left /src/.stack-root/indices/Hackage/git-update/all-cabal-hashes/.git/objects/pack: listDirectory: does not exist (No such file or directory)
/src/.stack-work-docker/downloaded/9rVosC0PeQVv/: getDirectoryContents: does not exist (No such file or directory)
```

**Comment by sjakobi** [comment] 2016-08-11 20:16
It looks like you don't have `git` installed (`stack` needs to [handle this more gracefully](https://github.com/commercialhaskell/stack/issues/2241) and/or simply [require `git`](https://github.com/commercialhaskell/stack/issues/2469)).

Does the issue go away when you install `git`?

**Comment by rainbyte** [comment] 2016-08-11 20:20
I thought about about git after reading issue #2175 comments.

`haskell:7.10.3` image doesn't have git, I'm downloading it right now.

**Comment by rainbyte** [comment] 2016-08-11 20:29
When running `stack build` with git installed, I got this:

```
Downloaded lts-6.10 build plan.    
Fetching package index ...remote: Counting objects: 223230, done.
remote: Compressing objects: 100% (180113/180113), done.
remote: Total 223230 (delta 59451), reused 176274 (delta 40861), pack-reused 0
Receiving objects: 100% (223230/223230), 52.49 MiB | 393.00 KiB/s, done.
Resolving deltas: 100% (59451/59451), completed with 1 local objects.
From https://github.com/commercialhaskell/all-cabal-hashes
 * [new tag]         current-hackage -> current-hackage
Fetched package index.    
Populated index cache.    
Did not find .cabal file for tardis-0.4.1.0 with Git SHA of fc6ca69c7721de063fdd0171474f2f5b80259d84
Right Nothing
Did not find .cabal file for servant-blaze-0.7.1 with Git SHA of a611898708511c515ae69860506efb2da87bbfc9
Right Nothing
Did not find .cabal file for scotty-0.11.0 with Git SHA of f0593dbc29ca6e3136514d735260c6870ba34fd1
Right Nothing
Did not find .cabal file for rest-types-1.14.1.1 with Git SHA of a62679783034be7952ad36b5dbe1e1f98691117b
Right Nothing
Did not find .cabal file for rest-stringmap-0.2.0.6 with Git SHA of 7f8c1e5b08f058362bb21f1eaf15fb3f2b020e2c
Right Nothing
Did not find .cabal file for rest-gen-0.19.0.3 with Git SHA of 688449798afd15591b2fb8e798002b6a17ca0bec
Right Nothing
```

And various similar lines (like in issue #2175)

**Comment by sjakobi** [comment] 2016-08-11 20:43
Ok, closing as a duplicate of #2241 and #2469 then. Thanks for the report!

**Closed by sjakobi** 2016-08-11 20:43 UTC
Labels: need confirmation
