### ISSUE TITLE
stack runghc does not care about extra-deps

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#2531] opened 2016-08-24 07:03 UTC
Right or wrong extra-deps in global project do not matter to `stack runghc`

```
$ cat $STACK_ROOT/global-project/stack.yaml 
extra-deps: 
- text-9.9.9.9
resolver: lts-6.7

$ stack runghc version-conflict.hs
Run from outside a project, using implicit global project config
Using resolver: lts-6.7 from implicit global project's config file: /vol/hosts/cueball/.stack/global-project/stack.yaml
hello
```

This may be related to #2530 .

**Comment by mpilgrem** [comment] 2024-03-03 00:26
I am closing this issue given the passage of time and because I can't reproduce the problem. For example, outside of a Stack project:
~~~text
stack runghc --package ansi-terminal-1.1 Main.hs
~~~

behaves differently depending on the `extra-deps` in the `stack.yaml` of the `global-project`. With:
~~~yaml
extra-deps:
- ansi-terminal-types-1.1
~~~

all is fine with `lts-22.12`. Without, Stack recommends:
~~~text
* Recommended action: try adding the following to your extra-deps in D:\sr\global-project\stack.yaml
           (project-level configuration):

           - ansi-terminal-types-1.1@sha256:135f6a381afa19d53d0a3fe40b6dd47e6666c538b09e4300fbb1438759df3248,1462
~~~

**Closed by mpilgrem** 2024-03-03 00:26 UTC
Labels: component: script interpreter
