### ISSUE TITLE
stack+ghcjs with two different resolvers breaks.

### ISSUE THREAD

**Issue by benclifford** [commercialhaskell/stack#2365] opened 2016-07-11 11:04 UTC
We have two ghcjs projects which use different resolver versions. Either project will build for a user from an empty home directory, but if a user tries to build both projects, one of them fails with the inability to find some libraries. Superficially it looks like whichever project happened to bootstrap ghcjs is the project that works.

I have attempted to assemble a minimal reproduction of the problem here:
https://github.com/BeautifulDestinations/issue-365-reproduction

This is with:

```
$ stack --version
Version 1.1.2, Git revision cebe10e845fed4420b6224d97dcabf20477bbd4b (3646 commits) x86_64 hpack-0.14.0
```

**Comment by mgsloan** [comment] 2016-07-19 22:09
Interesting!  I haven't yet looked at the repro, but my guess is that it has to do with the shared `.ghcjs` dir.

One possibility is that there are two different ghcjs tarballs, but they both think they are the same version (`0.2.0`).  I think in this case they will use the same global package DB despite being different.

**Comment by benclifford** [comment] 2016-07-22 14:35
The two stack.yaml files refer to the same URL:
https://github.com/nrolland/ghcjs/releases/download/v.0.2.0.20151230.3/ghcjs-0.2.0.20151230.3.tar.gz

Curiouser and curiouser, if I run in a clean environment:
```
cd project-b; stack setup; stack build
cd project-a;
rm -rfv .stack-work; stack setup; stack build  #A
rm -rfv .stack-work; stack setup; stack build  #B 
```
then #A fails but #B succeeds.

**Comment by tolysz** [comment] 2016-09-09 10:12
I been playing with multiple `ghcjs` version and resolvers eg.: https://github.com/tolysz/spock-ghcjs-sample

So I realised that `ghcjs` and `boot` might be exactly the same between different `lts`s or different `nightly`s (as I try to build them as soon as I see them) builds as long as the boot packages are not changed, there is like (a dozen of them). But then if the compiler version is the same `ghcjs` will try to use the same cache (per compiler) to save all builds.

My guess will be to make `ghcjs` `stack` aware and make it use some "custom" build prefix which stack could set, or make it guess the resolver.

**Comment by mgsloan** [comment] 2016-09-26 01:27
Yes, my guess that this is caused by many different ghcjs tarballs all claiming to be 0.2.0

**Comment by tolysz** [comment] 2016-09-26 09:23
I used different ghcjs versions per resolver, but they had the same `cabal` versions and still building in the same folder causes cache not updating.

**Comment by mgsloan** [comment] 2016-09-26 20:47
Yes, that will cause problems, unfortunately.  Not sure if there's much I can do about it :/

**Comment by snoyberg** [comment] 2020-02-04 12:30
The next version of Stack will no longer have GHCJS support, closing.

**Closed by snoyberg** 2020-02-04 12:30 UTC
Labels: component: ghcjs, resolution: upstream issue
