### ISSUE TITLE
ghc-pkg: cannot find package (after successful build) in 8.6.4 but not in 8.4.4

### ISSUE THREAD

**Issue by andrewufrank** [commercialhaskell/stack#5282] opened 2020-04-29 10:03 UTC
Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2
uname -a
Linux london 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux

### General summary/comments (optional)
 
I observe that a package is not found when registering which has in the same run be compiled. It seems not to occur with lts 12.26 (ghc 8.4.4) but with 13.12 (ghc 8.6.4).

### Steps to reproduce
I have two package, a `provider` and a `user`. The `user` imports the `provider`. Both packages build ok. 
1. remove all `.stack-work` directories, to start clean.
2. stack build   (in provider directory)  - ok 
3. stack build  (in user directory) - ok 
4. stack build --force-dirty (in provider directory) -> gives an error message
```
 stack build --force-dirty
provider-0.1.0: unregistering (--force-dirty specified)
provider> build (lib)
Preprocessing library for provider-0.1.0..
Building library for provider-0.1.0..
provider> copy/register
Installing library in /home/frank/Workspace8/uniformTest/user/.stack-work/install/x86_64-linux/010bb99b8c81a9d6caffe3c16fef7e2df01f6dc8f9e38c182820aa9ba59b78f2/8.6.4/lib/x86_64-linux-ghc-8.6.4/provider-0.1.0-CTeXvlyVqCDJJS5dGPsmCM
Registering library for provider-0.1.0..
Received ExitFailure 1 when running
Raw command: /home/frank/.stack/programs/x86_64-linux/ghc-8.6.4/bin/ghc-pkg-8.6.4 --user --no-user-package-db --package-db /home/frank/Workspace8/uniformTest/provider/.stack-work/install/x86_64-linux/010bb99b8c81a9d6caffe3c16fef7e2df01f6dc8f9e38c182820aa9ba59b78f2/8.6.4/pkgdb describe --simple-output provider --expand-pkgroot
Standard error:

ghc-pkg: cannot find package provider
```
-- the yaml are provider:
```
flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
resolver: lts-13.12
-- user: 
```
```
flags: {}
extra-package-dbs: []
packages:
- .
- ../provider
extra-deps:
resolver: lts-13.12
```
```
the verbose output is: 
frank@london:~/Workspace8/uniformTest/provider$ stack build --force-dirty --verbose
Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2
2020-04-29 11:57:42.671207: [debug] Checking for project config at: /home/frank/Workspace8/uniformTest/provider/stack.yaml
2020-04-29 11:57:42.671420: [debug] Loading project config file stack.yaml
2020-04-29 11:57:42.676549: [debug] SELECT COUNT(*) FROM "last_performed" WHERE ("action"=?) AND ("timestamp">=?); [PersistInt64 1,PersistUTCTime 2020-04-28 09:57:42.676505644 UTC]
2020-04-29 11:57:42.677131: [debug] Using package location completions from a lock file
2020-04-29 11:57:42.811214: [debug] Asking for a supported GHC version
2020-04-29 11:57:42.811512: [debug] Installed tools: 
 - ghc-8.0.2
 - ghc-8.6.5
 - ghc-8.2.2
 - ghc-8.4.3
 - ghc-8.6.4
 - ghc-8.4.4
 - ghc-7.10.3
2020-04-29 11:57:42.812014: [debug] Run process: /sbin/ldconfig -p
2020-04-29 11:57:42.812883: [debug] Process finished in 1ms: /sbin/ldconfig -p
2020-04-29 11:57:42.813052: [debug] Found shared library libtinfo.so.5 in 'ldconfig -p' output
2020-04-29 11:57:42.813428: [debug] Did not find shared library libtinfo.so.6
2020-04-29 11:57:42.813484: [debug] Did not find shared library libncursesw.so.6
2020-04-29 11:57:42.813520: [debug] Found shared library libgmp.so.10 in 'ldconfig -p' output
2020-04-29 11:57:42.813567: [debug] Did not find shared library libgmp.so.3
2020-04-29 11:57:42.813590: [debug] Potential GHC builds: standard
2020-04-29 11:57:42.813620: [debug] Found already installed GHC builds: standard
2020-04-29 11:57:42.813766: [debug] SELECT "id","actual_version","arch","ghc_path","ghc_size","ghc_modified","ghc_pkg_path","runghc_path","haddock_path","cabal_version","global_db","global_db_cache_size","global_db_cache_modified","info","global_dump" FROM "compiler_cache" WHERE "ghc_path"=?; [PersistText "/home/frank/.stack/programs/x86_64-linux/ghc-8.6.4/bin/ghc-8.6.4"]
2020-04-29 11:57:42.861799: [debug] Loaded compiler information from cache
2020-04-29 11:57:42.861946: [debug] Asking for a supported GHC version
2020-04-29 11:57:42.862811: [debug] Resolving package entries
2020-04-29 11:57:42.862861: [debug] Parsing the targets
2020-04-29 11:57:42.865285: [debug] Checking flags
2020-04-29 11:57:42.865321: [debug] SourceMap constructed
2020-04-29 11:57:42.869452: [debug] Starting to execute command inside EnvConfig
2020-04-29 11:57:42.870601: [debug] Finding out which packages are already installed
2020-04-29 11:57:42.870785: [debug] Run process: /home/frank/.stack/programs/x86_64-linux/ghc-8.6.4/bin/ghc-pkg-8.6.4 --global --no-user-package-db dump --expand-pkgroot
2020-04-29 11:57:42.895541: [debug] Process finished in 25ms: /home/frank/.stack/programs/x86_64-linux/ghc-8.6.4/bin/ghc-pkg-8.6.4 --global --no-user-package-db dump --expand-pkgroot
2020-04-29 11:57:42.896755: [debug] Ignoring package Cabal due to wanting version 2.4.1.0 instead of 2.4.0.1
2020-04-29 11:57:42.898110: [debug] Ignoring package haskeline due to wanting version 0.7.5.0 instead of 0.7.4.3
2020-04-29 11:57:42.898541: [debug] Run process: /home/frank/.stack/programs/x86_64-linux/ghc-8.6.4/bin/ghc-pkg-8.6.4 --user --no-user-package-db --package-db /home/frank/.stack/snapshots/x86_64-linux/010bb99b8c81a9d6caffe3c16fef7e2df01f6dc8f9e38c182820aa9ba59b78f2/8.6.4/pkgdb dump --expand-pkgroot
2020-04-29 11:57:42.927690: [debug] Process finished in 29ms: /home/frank/.stack/programs/x86_64-linux/ghc-8.6.4/bin/ghc-pkg-8.6.4 --user --no-user-package-db --package-db /home/frank/.stack/snapshots/x86_64-linux/010bb99b8c81a9d6caffe3c16fef7e2df01f6dc8f9e38c182820aa9ba59b78f2/8.6.4/pkgdb dump --expand-pkgroot
2020-04-29 11:57:42.929811: [debug] Run process: /home/frank/.stack/programs/x86_64-linux/ghc-8.6.4/bin/ghc-pkg-8.6.4 --user --no-user-package-db --package-db /home/frank/Workspace8/uniformTest/provider/.stack-work/install/x86_64-linux/010bb99b8c81a9d6caffe3c16fef7e2df01f6dc8f9e38c182820aa9ba59b78f2/8.6.4/pkgdb dump --expand-pkgroot
2020-04-29 11:57:42.946548: [debug] Process finished in 17ms: /home/frank/.stack/programs/x86_64-linux/ghc-8.6.4/bin/ghc-pkg-8.6.4 --user --no-user-package-db --package-db /home/frank/Workspace8/uniformTest/provider/.stack-work/install/x86_64-linux/010bb99b8c81a9d6caffe3c16fef7e2df01f6dc8f9e38c182820aa9ba59b78f2/8.6.4/pkgdb dump --expand-pkgroot
2020-04-29 11:57:42.946982: [debug] Constructing the build plan
2020-04-29 11:57:42.948116: [debug] Checking if we are going to build multiple executables with the same name
2020-04-29 11:57:42.948176: [debug] Executing the build plan
2020-04-29 11:57:42.948968: [debug] SELECT "id","directory","type","pkg_src","active","path_env_var","haddock" FROM "config_cache" WHERE "directory"=? AND "type"=?; [PersistText "/home/frank/Workspace8/uniformTest/provider/",PersistText "config"]
2020-04-29 11:57:42.949257: [debug] SELECT "id", "config_cache_id", "index", "option" FROM "config_cache_dir_option" WHERE ("config_cache_id"=?) ORDER BY "index"; [PersistInt64 1]
2020-04-29 11:57:42.949419: [debug] SELECT "id", "config_cache_id", "index", "option" FROM "config_cache_no_dir_option" WHERE ("config_cache_id"=?) ORDER BY "index"; [PersistInt64 1]
2020-04-29 11:57:42.949518: [debug] SELECT "id", "config_cache_id", "ghc_pkg_id" FROM "config_cache_dep" WHERE ("config_cache_id"=?); [PersistInt64 1]
2020-04-29 11:57:42.949614: [debug] SELECT "id", "config_cache_id", "component" FROM "config_cache_component" WHERE ("config_cache_id"=?); [PersistInt64 1]
2020-04-29 11:57:42.949968: [debug] Start: getPackageFiles /home/frank/Workspace8/uniformTest/provider/provider.cabal
2020-04-29 11:57:42.950483: [debug] Finished in 0ms: getPackageFiles /home/frank/Workspace8/uniformTest/provider/provider.cabal
2020-04-29 11:57:42.950971: [info] provider> build (lib)
2020-04-29 11:57:42.951261: [debug] Run process within /home/frank/Workspace8/uniformTest/provider/: /home/frank/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build lib:provider --ghc-options " -fdiagnostics-color=always"
2020-04-29 11:57:42.973371: [info] Preprocessing library for provider-0.1.0..
2020-04-29 11:57:42.973456: [info] Building library for provider-0.1.0..
2020-04-29 11:57:43.242837: [debug] Process finished in 291ms: /home/frank/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build lib:provider --ghc-options " -fdiagnostics-color=always"
2020-04-29 11:57:43.242926: [debug] Start: getPackageFiles /home/frank/Workspace8/uniformTest/provider/provider.cabal
2020-04-29 11:57:43.243615: [debug] Finished in 1ms: getPackageFiles /home/frank/Workspace8/uniformTest/provider/provider.cabal
2020-04-29 11:57:43.243905: [info] provider> copy/register
2020-04-29 11:57:43.244019: [debug] Run process within /home/frank/Workspace8/uniformTest/provider/: /home/frank/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 copy
2020-04-29 11:57:43.259428: [info] Installing library in /home/frank/Workspace8/uniformTest/user/.stack-work/install/x86_64-linux/010bb99b8c81a9d6caffe3c16fef7e2df01f6dc8f9e38c182820aa9ba59b78f2/8.6.4/lib/x86_64-linux-ghc-8.6.4/provider-0.1.0-CTeXvlyVqCDJJS5dGPsmCM
2020-04-29 11:57:43.265542: [debug] Process finished in 21ms: /home/frank/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 copy
2020-04-29 11:57:43.265710: [debug] Run process within /home/frank/Workspace8/uniformTest/provider/: /home/frank/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 register
2020-04-29 11:57:43.360517: [info] Registering library for provider-0.1.0..
2020-04-29 11:57:43.367207: [debug] Process finished in 101ms: /home/frank/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 register
2020-04-29 11:57:43.367328: [debug] Run process: /home/frank/.stack/programs/x86_64-linux/ghc-8.6.4/bin/ghc-pkg-8.6.4 --user --no-user-package-db --package-db /home/frank/Workspace8/uniformTest/provider/.stack-work/install/x86_64-linux/010bb99b8c81a9d6caffe3c16fef7e2df01f6dc8f9e38c182820aa9ba59b78f2/8.6.4/pkgdb describe --simple-output provider --expand-pkgroot
2020-04-29 11:57:43.384037: [error] Received ExitFailure 1 when running
Raw command: /home/frank/.stack/programs/x86_64-linux/ghc-8.6.4/bin/ghc-pkg-8.6.4 --user --no-user-package-db --package-db /home/frank/Workspace8/uniformTest/provider/.stack-work/install/x86_64-linux/010bb99b8c81a9d6caffe3c16fef7e2df01f6dc8f9e38c182820aa9ba59b78f2/8.6.4/pkgdb describe --simple-output provider --expand-pkgroot
Standard error:

ghc-pkg: cannot find package provider

```

**Comment by mpilgrem** [comment] 2024-05-01 21:19
I am going to close this issue given the passage of time and because I cannot reproduce it on Windows with GHC 8.6.5 (> GHC 8.6.4).

**Closed by mpilgrem** 2024-05-01 21:19 UTC
