### ISSUE TITLE
Invalid option: `stack build --no-run-tests --no-run-tests`

### ISSUE THREAD

**Issue by L-TChen** [commercialhaskell/stack#5081] opened 2019-11-12 13:48 UTC
### General summary/comments (optional)

Stack complains an invalid option `--no-run-tests` when it appears twice. Other options seem working fine. 

### Steps to reproduce

Run `stack build --no-run-tests --no-run-tests`. 

### Expected

It should be equivalent to `stack build --no-run-tests`.

### Actual

Stack reports:
```
Invalid option `--no-run-tests'
```

### Stack version

```
$ stack --version
Version 2.1.3 x86_64
Compiled with:
...
```

### Method of installation

* Installed via Homebrew. 
* Also on Travis by direct download.

**Comment by mpilgrem** [comment] 2024-03-20 13:48
I am closing this issue because this is the intended behaviour: flag `--no-run-tests` can be specified no more than once. This is true of other flags to `stack build` that can be specified no more than once.

**Closed by mpilgrem** 2024-03-20 13:48 UTC
