### ISSUE TITLE
`stack exec` not propagating signals

### ISSUE THREAD

**Issue by zimbatm** [commercialhaskell/stack#527] opened 2015-07-06 15:54 UTC
I would expect `stack exec` to only terminate if it's child process has died, and consequently forward it's INT/TERM signals to it.

When running end-to-end integration tests I execute a fresh set of haskell processes for each test to make sure their state is clean. On each test processes are started, checks are run and processes are stopped (or sometimes during the test to simulate failure). When using cabal sandbox I was executing the binary directly from within the `dist/` folder.

While migrating the project to using stack I was expecting to replace the `./dist/<project>/<project>` binary path with just `stack exec <project>`.

**Steps to reproduce:**

1. `stack exec -- sleep 10000 &`
2. `pid=$!`
3. `kill $pid`
4. `sleep 10000` is still running (eg: `ps aux | grep -v grep | grep sleep`)

**Expected:**

I would expect `stack exec` to forward INT/TERM signals to the child process and only terminate when the child-process has exited.

**Actual:**

`stack exec` dies and leaves a zombie process around

Here is the `stack ---version` output:
 
```
$ stack --version
Version 0.1.2.0, Git revision 65246552936b7da4b64b38372feac903d96a8911
```
Here is the command I ran **with `--verbose`**:

```
$ stack --verbose exec sleep -- 10000
Version 0.1.2.0, Git revision 65246552936b7da4b64b38372feac903d96a8911
2015-07-06 15:44:51.51753: [debug] Checking for project config at: /Users/zimbatm/stack.yaml @(stack-0.1.2.0:Stack.Config src/Stack/Config.hs:496:9)
2015-07-06 15:44:51.517853: [debug] Checking for project config at: /Users/stack.yaml @(stack-0.1.2.0:Stack.Config src/Stack/Config.hs:496:9)
2015-07-06 15:44:51.518093: [debug] Checking for project config at: /stack.yaml @(stack-0.1.2.0:Stack.Config src/Stack/Config.hs:496:9)
2015-07-06 15:44:51.518239: [debug] No project config file found, using defaults. @(stack-0.1.2.0:Stack.Config src/Stack/Config.hs:523:13)
2015-07-06 15:44:51.520458: [info] Using resolver: lts-2.17 from global config file: /Users/zimbatm/.stack/global/stack.yaml @(stack-0.1.2.0:Stack.Config src/Stack/Config.hs:302:32)
2015-07-06 15:44:51.530588: [debug] Run process: ghc --info @(stack-0.1.2.0:System.Process.Read src/System/Process/Read.hs:254:3)
2015-07-06 15:44:51.602371: [debug] Run process: ghc --numeric-version @(stack-0.1.2.0:System.Process.Read src/System/Process/Read.hs:254:3)
2015-07-06 15:44:51.634031: [debug] Run process: ghc-pkg --no-user-package-db field --simple-output Cabal id @(stack-0.1.2.0:System.Process.Read src/System/Process/Read.hs:254:3)
2015-07-06 15:44:51.662563: [debug] Run process: ghc-pkg --no-user-package-db list --global @(stack-0.1.2.0:System.Process.Read src/System/Process/Read.hs:254:3)
2015-07-06 15:44:51.693961: [debug] Run process: /bin/sleep 10000 @(stack-0.1.2.0:Stack.Exec src/Stack/Exec.hs:52:5)
### TERM signal is sent here ###
[1]    80002 terminated  stack --verbose exec sleep -- 10000
```

**Workaround:**

I'm not sure of the full implications but for now I first resolve the executable path using `stack exec which -- <executable>` and then invoke the executable directly.

**Comment by radix** [comment] 2015-07-06 18:12
maybe `stack exec` should use the `exec` syscall (to replace the current process) instead of spawning the program as a subprocess?

**Comment by manny-fp** [comment] 2015-07-06 18:20
@radix Do you know of a way to do that using System.Process?  It doesn't seem to be supported by the standard library.

**Comment by radix** [comment] 2015-07-06 18:29
@manny-fp sorry, no idea :) I'm a haskell noob :P

**Comment by DanBurton** [comment] 2015-07-06 18:53
While I would like to see stack do the right thing here, I think that
calling the binary directly is generally a better idea. In my mind, stack
exec is more for running GHC-related commands and scripts, since it sets
the GHC_PACKAGE_PATH. I would say that `stack exec which myexe` is the
"best way to use stack" in this case.

On Monday, July 6, 2015, Christopher Armstrong <notifications@github.com>
wrote:

> @manny-fp <https://github.com/manny-fp> sorry, no idea :) I'm a haskell
> noob :P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commercialhaskell/stack/issues/527#issuecomment-118949082>
> .
>


-- 
-- Dan Burton

**Comment by manny-fp** [comment] 2015-07-06 22:35
@DanBurton Once `stack install --path` is implemented, that'll also be a nice way to put an executable wherever you want it so you don't need to use `stack exec which` anymore.

**Comment by manny-fp** [comment] 2015-07-06 22:38
One way to fix the original issue might be to pass `create_group = True` to `CreateProcess`.  Not sure if that'll cause any problems, and no idea what the effect will be on Windows (if any).

**Comment by manny-fp** [comment] 2015-07-06 22:43
Aha, looks like [executeFile](https://www.stackage.org/haddock/lts-2.17/unix-2.7.0.1/System-Posix-Process.html#v:executeFile)  supports the posix `exec` system call.  We'd need to make use CPP to skip it on Windows and find another way on that OS.

**Comment by snoyberg** [comment] 2015-07-07 02:45
I'm +1 on using `executeFile`. In addition to the signal benefit, it should also be more efficient, which is nice. It appears that Windows has support for the same exec functions, so support should be possible. However, I wouldn't consider having that support a requirement to implementing this feature on non-Windows systems, since signals are a Unix-ism anyway.

**Comment by nh2** [comment] 2015-07-08 12:49
I'm not convinced that `exec()` is the right way to go here. This forbids `stack` to do anything (logging, measuring time or resource usage, reporting status) once the `exec`ed program is done or while it's executing (as `exec()` is a no-way-back syscall). If you want to recover such functionality, you'd have to `fork()` before `exec()`, and it is not a very safe thing to do to fork from the Haskell RTS.

Further, when you `exec()`, the child process inherits all your open file descriptors, leaking state from the `exec`ing process into the `exec`ed process. This problem can be avoided by enumerating all open file descriptors and closing them before `exec`, or making sure from the beginning that your files are all opened with the `O_CLOEXEC` flag (which is something that none of the Haskell libraries or the `base` do). See https://github.com/ndmitchell/shake/issues/253 for a detailed explanation.

--

Going back to the problem, @zimbatm as you noticed correctly, if you use `stack exec -- sleep 10000` then you can't kill the sleep by killing the PID of `stack exec`.

However, if you try it with `stack exec -- sleep 10000 | cat`, then killing `stack` suddenly does exactly what you expect.

That's because of these lines: https://github.com/commercialhaskell/stack/blob/56666e3b95579ec46919591448bcea12888f0f0e/src/Stack/Docker.hs#L259

```haskell
 isTerm = isStdinTerminal && isStdoutTerminal && isStderrTerminal
-- ...
             else concat [["--rm" | not (dockerPersist docker)]
                         ,["-t" | isTerm]
                         ,["-i"]]
```

So when you pipe `stack` into something else (e.g. `cat`), it doesn't pass the `-t` option to `docker run`, and not passing `-t` enables the `--sig-proxy` option that makes sure that when you send a signal (e.g. a SIGTERM via `kill`) to `docker run`, it forwards it to the program in your container.

If your terminal is interactive (which it is in the example you gave where no piping is happening, so `isTerm = True` and `-t` is passed to `docker run`), then `--sig-proxy` is not active. Then `docker run` processes the signal, exists, and your program (`sleep`) stays running; the only ways to kill it are `docker kill` and sending `kill` directly to the PID of `sleep`.

I believe that the right solution here is the Docker Pull Request https://github.com/docker/docker/pull/7567 that would make `--sig-proxy` work in both `-t` and non-`-t` mode.

I left a comment on this PR: https://github.com/docker/docker/pull/7567#issuecomment-119555862

**Comment by snoyberg** [comment] 2015-07-08 13:03
Just to clarify: the only way on a POSIX platform to create a child process is to `fork()` and then `exec()`, which is exactly what the process package does today. This is the one case where it's perfectly safe to use a system level `fork()` in a Haskell program, since the parent process will be wiped out and any weird RTS locks will be irrelevant.

I didn't read the initial bug report as being Docker-specific, am I wrong?

**Comment by nh2** [comment] 2015-07-08 13:16
> Just to clarify: the only way on a POSIX platform to create a child process is to fork() and then exec(), which is exactly what the process package does today. This is the one case where it's perfectly safe to use a system level fork() in a Haskell program, since the parent process will be wiped out and any weird RTS locks will be irrelevant.

That's right.

What was trying to say is: The current `popen()`/`createProcess` style setup in `stack` allows us to run things during or after the `docker run` command. If we switch that to `exec()`, that opportunity will be gone. If we want to regain it while keeping `exec()`, stack will have to `fork()`.

I realise that my comment made it sound like `popen`/`createProcess` avoid the `CLOEXEC` problems you'd get with `executeFile` - that's not the case, both ways have the file descriptor problem (as everything calls `exec()` in the end).

> I didn't read the initial bug report as being Docker-specific, am I wrong?

I'm not sure what you mean exactly, but I think that the initial bug is due to Docker not passign signals in TTY mode, and that it doesn't surface when piping the original poster's command line into a different program, as Docker handles signals correctly in that case (non-TTY mode).

**Comment by snoyberg** [comment] 2015-07-08 13:20
> I'm not sure what you mean exactly, but I think that the initial bug is due to Docker not passign signals in TTY mode

The initial bug report makes no mention of Docker, and provides reproduction steps that do not require Docker at all. I think you're conflating two very different issues together.

**Comment by nh2** [comment] 2015-07-08 13:20
Also, something that might be much more important to say than anything I've said above:

> maybe stack exec should use the exec syscall (to replace the current process) instead of spawning the program as a subprocess?

In my understanding, this wouldn't even make a difference, since no matter if it's `stack` or `docker run -t` that receives the signal - the passing on of the signal is interrupted between `docker run -t` and everything "below" it, so removing an extra layer at the top should not change the problem at all.

Switching to `executeFile` here would remove the need for `stack` to make sure it passes on the signals that it gets, but wouldn't change the fact that `docker run` doesn't pass them on.

**Comment by nh2** [comment] 2015-07-08 13:31
> The initial bug report makes no mention of Docker, and provides reproduction steps that do not require Docker at all. I think you're conflating two very different issues together.

Ah, hang on, now I see what you mean. Indeed I am conflating. I was continously running my testing in a directory with a Docker-enabled `stack.yaml`.

Please read all off my comments above with a "If you're running a Docker-enabled stack" in the front - sorry for the confusion :)

Yes, it looks right to me that in the non-Docker case, `executeFile` would solve the problem. But I also remember a version @manny-fp once made for me that worked like this, passing on the signal:

```patch
 execProcessAndExit :: FilePath -> [String] -> IO () -> IO ()
 execProcessAndExit cmnd args successPostAction =
   do (_, _, _, h) <- Proc.createProcess (Proc.proc cmnd args){Proc.delegate_ctlc = True}
+     _ <- installHandler sigTERM (Catch (Proc.terminateProcess h)) Nothing
```

That might work as well.

In any case, the same problem does also appear with Docker-enabled `stack exec`, and I think there the solution is not so easy - we might or might not want to track that in this issue (the title would fit for both Docker and non-Docker `stack exec`).

**Comment by nh2** [comment] 2015-07-08 13:39
> we might or might not want to track that in this issue

I filed the Docker-enabled part of this problem under https://github.com/commercialhaskell/stack/issues/547.

**Comment by manny-fp** [comment] 2015-07-28 19:50
Now, on master, `stack exec` (in the non-docker case) uses the `execve` system call instead of spawning a subprocess using `createProcess`, and the reproduction now behaves as expected:

```
$ stack exec -- sleep 10000 &
$ pid=$!
$ ps aux | grep -v grep | grep 'sleep 10000'
manny    30061  0.7  0.0   5880   612 pts/0    S    19:40   0:00 /bin/sleep 10000
$ kill $pid
[1]+  Terminated              stack exec -- sleep 10000
$ ps aux | grep -v grep | grep 'sleep 10000'
$
```

**Comment by manny-fp** [comment] 2015-07-30 05:55
Looks like this is causing the [stack exec ./foo.bat](https://stash.amgencss.fpcomplete.com/projects/HMST/repos/smart-device-sw/pull-requests/257/overview) integration test to fail, because the `execve` system call is more strict about scripts having a `#!` than `createProcess` was.

@snoyberg: Is it OK to require a script to have a `#!`? If so, we might need a bit of conditional logic to run a `foo.sh` on non-Windows platforms, since adding a `#!` to `foo.bat` would probably break the test on Windows.

**Comment by snoyberg** [comment] 2015-07-30 14:39
That's fine, but I'm surprised by this. System.Process should be using the same exec system calls under the surface.

**Comment by snoyberg** [comment] 2015-07-30 14:40
It seems that System.Process is using execvp and execvpe, which would explain why it can handle a missing shebang. Any possibility of using that in stack too?

**Comment by manny-fp** [comment] 2015-07-30 15:06
Done, and now `stack exec foo.bat` works.

**Closed by manny-fp** 2015-07-30 15:06 UTC
