### ISSUE TITLE
Support removing old build plans

### ISSUE THREAD

**Issue by kseo** [commercialhaskell/stack#2942] opened 2017-01-21 07:59 UTC
It would be nice if I can see the list of installed build plans and remove old ones using `stack` command. Old build plans take up too much space of my disk.

Removing files under ~/.stack/ is too error-prone.

http://stackoverflow.com/questions/39227397/how-to-remove-old-build-plans-installed-by-haskell-stack

**Comment by lwm** [comment] 2017-01-26 19:31
> Removing files under ~/.stack/ is too error-prone.

In this case, in the global project, it might be a bit tricky? Build plan files seem to be mixed around the place. However, for isolated projects, you are aware you can simply do a `ls .stack-work/install/<os>`?

I like the idea though, what would that interface look like? An argument on what Stack command? Would be nice on `stack clean` but doesn't fit (only for packages). Doesn't seem to fit on `stack build` either?

**Comment by mgsloan** [comment] 2017-02-01 00:12
Duplicate of https://github.com/commercialhaskell/stack/issues/133

**Closed by mgsloan** 2017-02-01 00:12 UTC
