### ISSUE TITLE
Stack upload is broken

### ISSUE THREAD

**Issue by wdanilo** [commercialhaskell/stack#4258] opened 2018-08-24 09:56 UTC
### General summary/comments (optional)

I'm trying to upload my package and while it was always working I've recently updated stack to the newest version and it's not working anymore:
 
```
stack upload .
Getting file list for /home/wdanilo/dev/lib/vector-text/
Building sdist tarball for /home/wdanilo/dev/lib/vector-text/
Checking package 'vector-text' for common mistakes
Package check reported the following warnings:
No 'description' field.
Hackage username: danilo2
Hackage password: 
<stdin>: hGetLine: end of file
```

Before I see the last line stack is hanging for couple of minutes and eats 100% of one of my CPU cores.

### Expected

It should upload the package to Hackage.

### Actual

Stack fails.

### Stack version

```
$ stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by dbaynard** [comment] 2018-08-26 22:06
There's been an issue with signatures (fixed in #4167) — see #3739.

Closing as duplicate of #4116.

The fix there is to update to master… but master has recently seen a super major change that requires rebuilding all your caches. There will be a new release (1.9.1) in the near future which will also contain the fix.

Try running with `--no-signature`, too.

**Closed by dbaynard** 2018-08-26 22:06 UTC
