### ISSUE TITLE
`ghcOptsCompleter` depends on GHC on PATH when Stack compiled; not optimal

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3699] opened 2017-12-23 12:48 UTC
In https://github.com/commercialhaskell/stack/issues/3693#issuecomment-353598592 , ghc is not on the path and so when building stack `ghc --show-options` cannot be run.  This isn't good for a couple reasons:

1. It will arbitrarily use a single version of GHC's options list, with other versions of the compiler.  If built with cabal-install, the ghc on the PATH might not even be the one it is using.

2. It will not adapt to other compilers in the future.  Right now this only applies to GHCJS since it is the only other compiler currently supported.

Instead it would be good to have a file that caches the output of `ghc --show-options` for different ghc versions.  This will add a bit of overhead, but I think that's ok.

**Comment by mpilgrem** [comment] 2024-02-07 23:08
`ghcOptsCompleter` is currently used with `stack build`, `stack ghci` and `stack script`. I can't see how Stack could anticipate which specific version of GHC was intended as the user types at the command line. Stack is intended to be built with Stack, is released relatively frequently, and is built with a relatively recent version of GHC. Popular GHC options do not change much between GHC versions, and an intended option missing from the Completer's list only means that the user has to type in full what they intended. Given that, it appears to me that the current approach is appropriate. Given the passage of time, I am going to close this issue.

**Closed by mpilgrem** 2024-02-07 23:08 UTC
Labels: newcomer friendly
