### ISSUE TITLE
Warning for absent custom-setup stanza is shown multiple times

### ISSUE THREAD

**Issue by duog** [commercialhaskell/stack#3078] opened 2017-03-20 21:20 UTC
### General summary/comments (optional)
The new absent custom-setup stanza warning is shown for each of the configure, build, haddock, copy/register steps. 
It is shown twice for the copy/register step when it triggers on a dependency. I haven't included the reproduction for this double appearance.

### Steps to reproduce

1. clone https://github.com/duog/stack-bug. This contains a stack.yaml that has a single location, the semigroupoids commit:https://github.com/ekmett/semigroupoids/tree/d5605e9c3773bad14f922e6e65ba13785edfa7e0

2. output from `stack build --haddock --verbose` is in the repo in the file `output`, [link](https://github.com/duog/stack-bug/blob/master/output)
### Expected
A single warning is present in output:
`Package semigroupoids uses a custom Cabal build, but does not use a custom-setup stanza
Not using the explicit setup deps approach based on configuration
Strongly recommend fixing the package's cabal file`

### Actual

the warning appears 4 times.

### Stack version

```
$ stack --version
Version 1.2.0, Git revision 241cd07d576d9c0c0e712e83d947e3dd64541c42 (4054 commits) x86_64 hpack-0.14.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mgsloan** [comment] 2017-03-20 22:01
Duplicate of https://github.com/commercialhaskell/stack/issues/3034 , which is resolved in the master version of stack (fix not yet in a released version)

**Closed by mgsloan** 2017-03-20 22:01 UTC
