### ISSUE TITLE
Weird "can't load .so/.DLL" error I believe because of a git repo as a dependency.

### ISSUE THREAD

**Issue by seanparsons** [commercialhaskell/stack#740] opened 2015-08-09 11:34 UTC
Minimally reproducing project (as far as I can make it) here: https://github.com/seanparsons/cantloaderror

    ➜  cantloaderror git:(master) stack build
    cantloaderror-0.1.0.0: build
    
    --  While building package cantloaderror-0.1.0.0 using:
          /home/sean/.stack/programs/x86_64-linux/ghc-7.10.1/bin/runhaskell -package=Cabal-1.22.2.0 -    clear-package-db -global-package-db -package-db=/home/sean/.stack/snapshots/x86_64-linux/nightly-    2015-07-30/7.10.1/pkgdb/ /tmp/stack26392/Setup.hs --builddir=.stack-work/dist/x86_64-linux/Cabal-    1.22.2.0/ build
        Process exited with code: ExitFailure 1
        Logs have been written to: "/home/sean/workspace/cantloaderror/.stack-work/logs/cantloaderror-    0.1.0.0.log"
    
        Building cantloaderror-0.1.0.0...
        Preprocessing executable 'cantloaderror' for cantloaderror-0.1.0.0...
        [2 of 3] Compiling CantLoadError.Types ( src/CantLoadError/Types.hs, .stack-work/dist/x86_64-    linux/Cabal-1.22.2.0/build/cantloaderror/cantloaderror-tmp/CantLoadError/Types.o )
        <command line>: can't load .so/.DLL for: /home/sean/workspace/cantloaderror/.stack-    work/install/x86_64-linux/nightly-2015-07-30/7.10.1/lib/x86_64-linux-ghc-    7.10.1/fastl_2Slugq3CyPh7AFUfPDWpX2/libHSfast-logger-2.4.0-2Slugq3CyPh7AFUfPDWpX2-    ghc7.10.1.so (/home/sean/workspace/cantloaderror/.stack-work/install/x86_64-linux/nightly-2015-07-    30/7.10.1/lib/x86_64-linux-ghc-7.10.1/fastl_2Slugq3CyPh7AFUfPDWpX2/libHSfast-logger-2.4.0-    2Slugq3CyPh7AFUfPDWpX2-ghc7.10.1.so: undefined symbol:     direczu3TcTyYedch32o1zzTH2MR00_SystemziDirectory_findExecutable4_info)

This was working when the amazonka library was depended on using extra-deps, but I needed the more recent version that is unreleased.

**Comment by chrisdone** [comment] 2015-08-09 11:40
Perhaps `directory` isn't specified as a package dependency in a place that it should be?

**Comment by seanparsons** [comment] 2015-08-09 11:41
@chrisdone Adding it to the .cabal file of my project doesn't change anything.

**Comment by chrisdone** [comment] 2015-08-09 11:43
Perhaps do a clean and rebuild?

**Comment by seanparsons** [comment] 2015-08-09 11:45
Still the same.

**Comment by bergmark** [comment] 2015-08-09 15:10
I've seen this error a few times as well, it seems to happen pretty randomly for me and a `stack clean` resolves it. I've also seen this happen while using `cabal-install`...

In my case there is no git repository involved.

**Comment by seanparsons** [comment] 2015-08-09 21:32
Again, ```stack clean``` does nothing. I didn't create the minimally reproducing project for my own entertainment.

**Comment by mgsloan** [comment] 2015-08-09 23:26
It reproduces for me!  Strange error, I have no idea what would cause this.

**Comment by snoyberg** [comment] 2015-08-10 03:53
I have the targets overhaul to work on for the next few days. If this is
still unresolved at that point, I can look into it

**Comment by seanparsons** [comment] 2015-08-12 23:22
This still occurs in 0.1.3.0.

**Comment by snoyberg** [comment] 2015-08-13 11:14
What's the reason for having `time` as an extra-dep? It's using the same version (1.5.0.1) that's provided in the snapshot.

(This wouldn't be a valid reason for the behavior, but I'm trying to understand what I'm looking at.)

**Comment by snoyberg** [comment] 2015-08-13 11:25
Just completed my build, and removing time-1.5.0.1 from extra-deps fixed the problem for me. @seanparsons can you confirm?

If that's the case, we need to decide what to do with this. We can write it off as a corner case until it crops up again, or investigate further. Given that this is a very large reproducing case, I'd rather wait for another example to crop up before diving in.

**Comment by samdoshi** [comment] 2015-08-13 12:29
Hi, I've got a minimised example of this issue: https://github.com/samdoshi/stack-error

If you clone it on OSX 10.10 and try and `stack build`, you get:
```
$  stack build
hmidi-0.2.2.0: configure
hmidi-0.2.2.0: build
hmidi-0.2.2.0: install
stack-error-0.1.0.0: configure
Configuring stack-error-0.1.0.0...
stack-error-0.1.0.0: build
Preprocessing executable 'stack-error' for stack-error-0.1.0.0...
[1 of 1] Compiling Main             ( src/Main.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/stack-error/stack-error-tmp/Main.o )
<command line>: can't load .so/.DLL for: /Users/sam/Dropbox/Projects/stack-error/.stack-work/install/x86_64-osx/lts-3.0/7.10.2/lib/x86_64-osx-ghc-7.10.2/hmidi-0.2.2.0-K5Hp8RffNhV6yaFNhdp3bc/libHShmidi-0.2.2.0-K5Hp8RffNhV6yaFNhdp3bc-ghc7.10.2.dylib (dlopen(/Users/sam/Dropbox/Projects/stack-error/.stack-work/install/x86_64-osx/lts-3.0/7.10.2/lib/x86_64-osx-ghc-7.10.2/hmidi-0.2.2.0-K5Hp8RffNhV6yaFNhdp3bc/libHShmidi-0.2.2.0-K5Hp8RffNhV6yaFNhdp3bc-ghc7.10.2.dylib, 5): Symbol not found: _kMIDIPropertyManufacturer
  Referenced from: /Users/sam/Dropbox/Projects/stack-error/.stack-work/install/x86_64-osx/lts-3.0/7.10.2/lib/x86_64-osx-ghc-7.10.2/hmidi-0.2.2.0-K5Hp8RffNhV6yaFNhdp3bc/libHShmidi-0.2.2.0-K5Hp8RffNhV6yaFNhdp3bc-ghc7.10.2.dylib
  Expected in: flat namespace
 in /Users/sam/Dropbox/Projects/stack-error/.stack-work/install/x86_64-osx/lts-3.0/7.10.2/lib/x86_64-osx-ghc-7.10.2/hmidi-0.2.2.0-K5Hp8RffNhV6yaFNhdp3bc/libHShmidi-0.2.2.0-K5Hp8RffNhV6yaFNhdp3bc-ghc7.10.2.dylib)
Completed all 2 a
--  While building package stack-error-0.1.0.0 using:
      /Users/sam/.stack/programs/x86_64-osx/ghc-7.10.2/bin/runhaskell -package=Cabal-1.22.4.0 -clear-package-db -global-package-db -package-db=/Users/sam/.stack/snapshots/x86_64-osx/lts-3.0/7.10.2/pkgdb/ /var/folders/s2/4_93jgb54fx5f8_twm8714sc0000gn/T/stack7864/Setup.hs --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ build exe:stack-error --ghc-options -hpcdir .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/hpc/.hpc/ -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
ctions.
$  stack --version
Version 0.1.3.1
```

If you comment out `hmidi` in the `build-depends` in `stack-error.cabal` then it compiles, similarly if you comment out `my_id` and the call to it, and reinstate all the midi stuff it compiles.

Looks to be an issue with template haskell.

If you can't reproduce I can try and get it do so on travis-ci

**Comment by snoyberg** [comment] 2015-08-13 13:05
@samdoshi That issue does not reproduce on my Windows box. A Travis-based repro would be great.

**Comment by samdoshi** [comment] 2015-08-13 14:04
@snoyberg Here you go: https://travis-ci.org/samdoshi/stack-error/branches

I've created four branches:
- **master**: the error
- **brew-ghc**: the same error, but using `brew` supplied `ghc`
- **working-th**: working code, with `hmidi` removed from `stack-error.cabal`
- **working-hmidi**: working code with `my_id` commented out

**Comment by samdoshi** [comment] 2015-08-13 14:18
I've also added a `cabal` branch, which doesn't use `stack`, it fails with the same error
```
<command line>: can't load .so/.DLL for: /Users/travis/.cabal/lib/x86_64-osx-ghc-7.10.2/hmidi-0.2.2.0-K5Hp8RffNhV6yaFNhdp3bc/libHShmidi-0.2.2.0-K5Hp8RffNhV6yaFNhdp3bc-ghc7.10.2.dylib (dlopen(/Users/travis/.cabal/lib/x86_64-osx-ghc-7.10.2/hmidi-0.2.2.0-K5Hp8RffNhV6yaFNhdp3bc/libHShmidi-0.2.2.0-K5Hp8RffNhV6yaFNhdp3bc-ghc7.10.2.dylib, 5): Symbol not found: _kMIDIPropertyManufacturer
```

I'm guessing this is an upstream issue then?

I'm afraid I'm a bit of a Haskell beginner, so I'm not quite sure where to take this next.

**Comment by snoyberg** [comment] 2015-08-13 14:22
I think this is a completely different issue actually, and is correct behavior. It looks like you need to tell GHC to add in an extra system library containing the _kMIDIPropertyManufacturer identifier. It's also likely to be impossible to get this to work on Linux, since that function won't exist on Linux.

**Comment by seanparsons** [comment] 2015-08-13 16:09
@snoyberg Surely all someone needs to do to get confirmation of this is to try building the project I posted right at the very start?

**Comment by samdoshi** [comment] 2015-08-13 17:01
It looks like my bug relates to this haskell/cabal#2715

**Comment by snoyberg** [comment] 2015-08-13 17:02
@seanparsons Indeed, I did confirm it, and then confirmed that removing the time extra-dep fixed the bug. Since these kinds of issues generally are non-obviously-deterministic, I wanted to confirm with you that making that change fixed it for you too.

**Comment by seanparsons** [comment] 2015-08-14 16:03
@snoyberg Aha! That does appear to have stopped it from happening, I'm baffled.

**Comment by snoyberg** [comment] 2015-08-15 18:23
It has to do most likely with where time falls in the dependency tree, specifically below some packages that ship with GHC. Generally it can be problematic to upgrade those. I don't know exactly what happened in this case, and whether it's a bug in GHC, Cabal, or stack, but given that this change works for now, closing.

**Closed by snoyberg** 2015-08-15 18:23 UTC
Labels: need-confirmation

**Comment by 5outh** [comment] 2015-10-25 23:26
@samdoshi I can't find a better place to ask, since the minimal example repository was deleted, but I'm having that exact problem when trying to build https://github.com/5outh/Bang; did you ever figure out the solution to the problem you were experiencing, or any possible causes?

Again, sorry for polluting a closed issue, just not sure where else to ask.

**Comment by garry-cairns** [comment] 2016-01-30 17:54
I too am getting this with a Yesod scaffolded site, with minimal changes. It was building fine then just stopped one day. Stack trace:

`<no location info>:
    <command line>: can't load .so/.DLL for: /home/garry/.stack/snapshots/x86_64-linux/lts-5.0/7.10.3/lib/x86_64-linux-ghc-7.10.3/yesod-core-1.4.19-2khL1Psa766GsQyshWLKC6/libHSyesod-core-1.4.19-2khL1Psa766GsQyshWLKC6-ghc7.10.3.so (/home/garry/.stack/snapshots/x86_64-linux/lts-5.0/7.10.3/lib/x86_64-linux-ghc-7.10.3/yesod-core-1.4.19-2khL1Psa766GsQyshWLKC6/libHSyesod-core-1.4.19-2khL1Psa766GsQyshWLKC6-ghc7.10.3.so: undefined symbol: warpzu3hKUmkinBwE2hEn1kQG9Cs_NetworkziWaiziHandlerziWarpziSettings_defaultSettings13_closure)
`

**Comment by garry-cairns** [comment] 2016-01-30 19:32
Downgrading to lts-4.2 seems to have fixed my issue.

**Comment by mgsloan** [comment] 2016-01-31 01:30
Note that the downgrading itself probably isn't the fix, just starting with a different snapshot.  Also, lts-4.* isn't recommended due to aeson-0.10 being a bit broken.  If this theory is correct, then deleting ~/.stack/snapshots should resolve the issue.

https://github.com/commercialhaskell/stack/issues/1476 is tracking adding support for selectively reinstalling packages.

**Comment by kionka** [comment] 2017-02-17 22:53
Just ran into this. `rm -r ~/.stack/snapshots` worked wonderfully. I am also using git repos in my stack build, so that does seem to be the problem.

For posterity here are my error messages:

```--  While building package th-lift-instances-0.1.11 using:
      /Users/user/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.0.0_ghc-8.0.1 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.0.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/user/.stack/programs/x86_64-osx/ghcjs-0.2.1.9007019_ghc-8.0.1/src/.stack-work/logs/th-lift-instances-0.1.11.log

    Configuring th-lift-instances-0.1.11...
    Building th-lift-instances-0.1.11...
    Preprocessing library th-lift-instances-0.1.11...
    [1 of 1] Compiling Instances.TH.Lift ( src/Instances/TH/Lift.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Instances/TH/Lift.o )
    <command line>: can't load .so/.DLL for: /Users/user/.stack/snapshots/x86_64-osx/lts-7.2/8.0.1/lib/x86_64-osx-ghc-8.0.1/primitive-0.6.1.0-Ip44DqhfCp21tTUYbecwa/libHSprimitive-0.6.1.0-Ip44DqhfCp21tTUYbecwa-ghc8.0.1.dylib (dlopen(/Users/user/.stack/snapshots/x86_64-osx/lts-7.2/8.0.1/lib/x86_64-osx-ghc-8.0.1/primitive-0.6.1.0-Ip44DqhfCp21tTUYbecwa/libHS
primitive-0.6.1.0-Ip44DqhfCp21tTUYbecwa-ghc8.0.1.dylib, 5): Library not loaded: /usr/local/opt/ghc/lib/ghc-8.0.1/transformers-0.5.2.0/libHStransformers-0.5.2.0-ghc8.0.1.dylib
      Referenced from: /Users/user/.stack/snapshots/x86_64-osx/lts-7.2/8.0.1/lib/x86_64-osx-ghc-8.0.1/primitive-0.6.1.0-Ip44DqhfCp21tTUYbecwa/libHSprimitive-0.6.1.0-Ip44DqhfCp21tTUYbecwa-ghc8.0.1.dylib
      Reason: image not found)


--  While building package profunctors-5.2 using:
      /Users/user/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.0.0_ghc-8.0.1 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.0.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/user/.stack/programs/x86_64-osx/ghcjs-0.2.1.9007019_ghc-8.0.1/src/.stack-work/logs/profunctors-5.2.log

    Configuring profunctors-5.2...
    Building profunctors-5.2...
    Preprocessing library profunctors-5.2...
    [ 1 of 15] Compiling Data.Profunctor.Unsafe ( src/Data/Profunctor/Unsafe.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Data/Profunctor/Unsafe.o )
    <command line>: can't load .so/.DLL for: /Users/user/.stack/snapshots/x86_64-osx/lts-7.2/8.0.1/lib/x86_64-osx-ghc-8.0.1/base-orphans-0.5.4-5IQvrjd7gNP548VkOOyIq6/libHSbase-orphans-0.5.4-5IQvrjd7gNP548VkOOyIq6-ghc8.0.1.dylib (dlopen(/Users/user/.stack/snapshots/x86_64-osx/lts-7.2/8.0.1/lib/x86_64-osx-ghc-8.0.1/base-orphans-0.5.4-5IQvrjd7gNP548VkOOyIq6
/libHSbase-orphans-0.5.4-5IQvrjd7gNP548VkOOyIq6-ghc8.0.1.dylib, 5): Library not loaded: /usr/local/opt/ghc/lib/ghc-8.0.1/base-4.9.0.0/libHSbase-4.9.0.0-ghc8.0.1.dylib
      Referenced from: /Users/user/.stack/snapshots/x86_64-osx/lts-7.2/8.0.1/lib/x86_64-osx-ghc-8.0.1/base-orphans-0.5.4-5IQvrjd7gNP548VkOOyIq6/libHSbase-orphans-0.5.4-5IQvrjd7gNP548VkOOyIq6-ghc8.0.1.dylib
      Reason: image not found)```

**Comment by mb21** [comment] 2017-09-26 08:16
I've been running into this intermittently when running `stack exec yesod devel` and at least in my case it was caused by something unexpected:

When adding a new module (like a yesod handler), I forgot to add it to my project's cabal file to the `exposed-modules` section. Adding it, made the `can't load .so/.DLL `-error go away.

**Comment by archywilhes** [comment] 2017-11-06 11:37
`rm -r ~/.stack/snapshots` didn't help. still got the problem while trying to install hakyll on my mac :'(

**Comment by stackptr** [comment] 2018-02-06 23:12
Ran into this today on macOS. Tried doing `stack clean` to no avail, but `stack clean --full` worked.

**Comment by dbaynard** [comment] 2018-11-14 16:59
Note that once #4385 is merged you can use `stack purge` as an alias to `stack clean --full`

**Comment by nikita-volkov** [comment] 2019-10-23 17:15
Constantly running into this, when I switch between a git dependency to a local one and go back. Tried all possible ways of solving it and nothing but removing `~/.stack/snapshots` helps.

Stack 2.1.3, OSX 10.15

**Comment by nikita-volkov** [comment] 2019-10-23 23:07
Found a better way of working around this: by deleting the broken package and its .so files in every snapshot.

Also you might be able to reproduce the issue by first setting the resolver to `resolver: https://raw.githubusercontent.com/metrix-ai/stack-snapshot/55.2/snapshot.yaml` and then switching to `resolver: https://raw.githubusercontent.com/metrix-ai/stack-snapshot/55.3.1/snapshot.yaml` and using the `predropWhile` function out of the "foldl" package.
