### ISSUE TITLE
stack init; stack ghci: unhelpful message

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack#764] opened 2015-08-12 05:01 UTC
$ stack init
    Writing default config file to: /home/b/LoByMyHand/vim-haskell-syntax/stack.yaml
    Basing on cabal files:
    - /home/b/LoByMyHand/vim-haskell-syntax/vim-haskell-syntax-tester.cabal

    Checking against build plan lts-2.21
    Selected resolver: lts-2.21
    Wrote project config to: /home/b/LoByMyHand/vim-haskell-syntax/stack.yaml
    $ stack ghci
    Configuring GHCi with the following packages: vim-haskell-syntax-tester
    GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
    <command line>: cannot satisfy -package tasty-0.10.1.2
        (use -v for more information)
    $ wat

          wat

    $ ls
    LICENSE          after                 dist        stack.yaml  vim-haskell-syntax-tester.cabal
    Setup.hs         cabal.config          matrix.txt  syntax
    UnicodeData.txt  cabal.sandbox.config  meta        test
    $ vim vim-haskell-syntax-tester.cabal
    $ vim stack build
    regex-tdfa-rc-1.1.8.3: download
    temporary-rc-1.2.0.3: download
    ...

It took me a few seconds to realize I needed to run stack build first.

**Comment by chrisdone** [comment] 2015-08-12 07:25
Dupe of #629, which I'll get round to ASAP as this keeps cropping up.

**Closed** 2015-08-12 13:00 UTC
