### ISSUE TITLE
Why does solver add dependencies in `lts` snapshot to extra-deps in stack.yaml?

### ISSUE THREAD

**Issue by crocket** [commercialhaskell/stack#1992] opened 2016-04-04 01:54 UTC
## What I was trying to do

I was trying to follow instructions on http://docs.haskellstack.org/en/stable/GUIDE/#external-dependencies

## Steps to reproduce the issue

* Execute `stack unpack yackage` to check out yackage-0.8.
* Add `acme-missiles 0.3` to `yackage`.
* Execute `stack init --force --solver` in yackage.

## What I expected to happen

only acme-missiles is added to extra-deps

## What happened

In addition to acme-missiles, `tar-0.5.0.1`, `text-1.2.2.1`, and `yaml-0.8.16` were added from `lts-5.11` to extra-deps.

## My thoughts

Is it a bug? Or, is it a duplicate issue?

**Comment by sjakobi** [comment] 2016-04-04 16:07
I can reproduce this bug with `stack-1.0.4`, but apparently it has already been fixed on the master branch.

You can upgrade to the current master with `stack upgrade --git`.

**Closed by sjakobi** 2016-04-04 16:07 UTC

**Comment by mgsloan** [comment] 2016-04-04 19:29
Yeah, likely a dupe of #1927 .  Please reopen if the problem still exists on HEAD version of stack.
