### ISSUE TITLE
stack build tries to look for shared object file of libHShoist-error and fails

### ISSUE THREAD

**Issue by bollu** [commercialhaskell/stack#3064] opened 2017-03-16 08:53 UTC
Please use the following schema for your bug report:

### General summary/comments (optional)
`stack build` tries to look for a `.so` file  (`libHShoist-error` - this corresponds to the `hoist-error` library) and fails. On the other hand, `cabal build` works perfectly (gives me compile errors).

### Steps to reproduce
1. run `stack build` on the project [bollu/simplexhc commit `c57db`](https://github.com/bollu/simplexhc/commit/c57db73a83925691b53e496b4f4c4f6df0ebb155)

### Expected
Build should run and it should either succeed or give me compiler errors.

### Actual
```bash
simplexhc-0.1.0.0: build (lib + exe)
Preprocessing library simplexhc-0.1.0.0...
[1 of 3] Compiling StgLanguage      ( src/StgLanguage.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/StgLanguage.o )
<command line>: can't load .so/.DLL for: libHShoist-error-0.1.0.2-L7lnlbTUTXu9RrA0QnpfTJ.dylib (dlopen(libHShoist-error-0.1.0.2-L7lnlbTUTXu9RrA0QnpfTJ.dylib, 5): image not found)

--  While building package simplexhc-0.1.0.0 using:
      /Users/bollu/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.0.0_ghc-8.0.1 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.0.0 build lib:simplexhc exe:simplexhc --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

[link to `--verbose` gist](https://gist.github.com/bollu/4a40f6d4903ab08d9cde10f52423075e#file-stack-dll-error-L89)

### Stack version

```
╰─$ stack --version                                                                                                                               1 
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

### Method of installation
* Via cabal-install

**Comment by domenkozar** [comment] 2017-03-16 12:35
Doesn't that usually means you forgot to specify `other-modules`?

**Comment by bollu** [comment] 2017-03-16 13:12
I don't think so, it is part of `build-depends` in the `.cabal` file . Also, since `cabal build` works, I think this is a stack problem

**Comment by mgsloan** [comment] 2017-03-16 20:43
Hmm, I can't reproduce the issue, I get normal compilation errors as expected.  Does forcing a rebuild of `libHShoist-error` work?  Try `stack exec -- ghc-pkg unregister libHShoist-error`

**Comment by mpilgrem** [comment] 2024-03-18 22:23
I am going to close this issue given the passage of time, it could not be reproduced at the time, and because other users have not reported similar issues subsequently.

**Closed by mpilgrem** 2024-03-18 22:23 UTC
