### ISSUE TITLE
LTS-5.0 definition doesn't work

### ISSUE THREAD

**Issue by phadej** [commercialhaskell/stack#1702] opened 2016-01-26 13:26 UTC
```
% stack --version
Version 1.0.3, Git revision 3ea8437e472bcc4c48a8a97285e1da6cb5ae9aa8 x86_64
% STACK_YAML=stack-lts-5.yaml stack build
Getting project config file from STACK_YAML environment
Downloaded lts-5.0 build plan.    
InvalidYaml (Just (YamlParseException {yamlProblem = "mapping values are not allowed in this context", yamlContext = "", yamlProblemMark = YamlMark {yamlIndex = 343, yamlLine = 12, yamlColumn = 14}}))
```

**Comment by alanz** [comment] 2016-01-26 13:28
FIW I had that problem with nightly-2016-01-24 too

**Comment by sjakobi** [comment] 2016-01-26 14:15
Could this be due to your versions of stack being built with that buggy version of aeson in lts-4?

Does the problem go away when you build stack with the provided `stack-7.8.yaml` or use e.g. stack-1.0.0?

**Comment by luigy** [comment] 2016-01-26 15:49
Currently there is no verification that the buildplan file was not corrupted when downloading and it won't redownload if the file already exists.

In the meantime you can remove the following files to force the download to happen and hopefully it won't be corrupted
`~/.stack/build-plan/lts-5.0.yaml` -- I'm curious to see what this file looks like, though
`~/.stack/build-plan-cache/x86_64-osx/lts-5.0.cache`  -- may vary according to you platform

**Comment by DanBurton** [comment] 2016-01-27 01:03
Is this a regression in stack-1.0.3? Or is it just an intermittent bug that happens when your download is corrupted? I'm using stack-1.0.2 and it seemed to download and parse the lts-5.0 build plan just fine.

**Comment by phadej** [comment] 2016-01-27 07:41
```

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 backend read error</title>
  </head>
  <body>
    <h1>Error 503 backend read error</h1>
    <p>backend read error</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-fra1224-FRA 1453811962 3734747786</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

Was the content of my `lts-5.0.yaml`

**Comment by mgsloan** [comment] 2016-01-27 07:56
Did it recover, or was this failure sticky?  From the logic [here](https://github.com/fpco/stack/blob/93d85ffe18a90ad660c48bfd15e06cd27e93c75b/src/Stack/BuildPlan.hs#L446), to me it seems like it ought to recover (as long as the server does send the right info)

**Comment by phadej** [comment] 2016-01-27 07:58
@mgsloan I had to remove the file manually
```
% stack --version                      
Version 1.0.3, Git revision 3ea8437e472bcc4c48a8a97285e1da6cb5ae9aa8 x86_64
```

**Comment by mgsloan** [comment] 2016-01-27 08:08
@phadej Interesting!  Looks like the code intended to handle this case, but used `download` instead of `redownload`, so the file didn't get overwritten.  I've pushed a fix.  Please re-open if this is still an issue.

**Closed by mgsloan** 2016-01-27 08:08 UTC
