### ISSUE TITLE
stack init --solver fail to parse cabal lines

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3642] opened 2017-12-12 10:39 UTC
Using Stack 1.6 and Cabal 2.0.0.1 when running `stack init --force --solver` I get:

```
[00:03:17] Retrying with packages from lts-9.18 as preferences...
[00:03:40] The following lines from cabal-install output could not be parsed: 
[00:03:40] auto-update-0.1.4 (via: tls-session-manager-0.0.0.2 warp-3.2.13
[00:03:40] fast-logger-2.4.10) (new package)
[00:03:40] bytestring-builder-0.10.8.1.0 (via: warp-3.2.13 wai-3.2.1.1 http2-1.6.3) (new
[00:03:40] package)
```

You can see the full trace at https://ci.appveyor.com/project/ndmitchell/hoogle/build/1.0.268

**Comment by mgsloan** [comment] 2017-12-12 11:13
Duplicate of https://github.com/commercialhaskell/stack/issues/3453 .  Would really appreciate someone fixing this.  Would be nice of cabal-install had machine readable output for solver results.  Alternatively, link against an API.

**Closed by mgsloan** 2017-12-12 11:13 UTC
