### ISSUE TITLE
There seems to be no way to build/install dependencies only.

### ISSUE THREAD

**Issue by pharaun** [commercialhaskell/stack#694] opened 2015-07-30 21:43 UTC
I need to be able to do this with stack somehow, and i tried to do this with

```
RUN     /root/stack exec -- \
            /root/.local/bin/cabal exec -- \
                /root/.local/bin/cabal install --enable-tests --enable-benchmarks --dependencies-only
```

But it made cabal angry with `GHC_PACKAGE_PATH` So it would be terrific if we could extend/add a way for stack to build with dependencies only so that i can take advantage of docker caching and not rebuild the container over and over due to changed source code.

**Comment by manny-fp** [comment] 2015-07-30 23:08
This looks like a duplicate of https://github.com/commercialhaskell/stack/issues/387.  Might be helpful to add this use case to that issue.

The `--only-snapshot` should mostly take care of this, so I'd recommend that if you don't have a lot of `extra-deps` in your stack.yaml.

Otherwise, a workaround might be something like this in your Dockerfile:

```
RUN stack build && stack clean <PACKAGES>
RUN stack build
```

There'd be the slight waste of the first RUN having to build your code only to clean it right after, but if you're not having to rebuild dependencies very often that would be minimal.

**Closed by manny-fp** 2015-07-30 23:08 UTC
