### ISSUE TITLE
Ability to use -Wall without -Werror

### ISSUE THREAD

**Issue by mightybyte** [commercialhaskell/stack#2035] opened 2016-04-14 17:24 UTC
I find it very useful to build with -Wall in situations where -Werror is not desirable.  `stack build --ghc-options="-Wall"` does not display any warnings, so this does not appear to be possible right now.

**Comment by mgsloan** [comment] 2016-04-14 19:34
The issue is probably that ghc does not rebuild when -Wall is added.  Does `stack build --ghc-options="-Wall -fforce-recomp"` do what you want?

It may also be due to building multiple packages concurrently.  In that case you need to look at build logs for warnings, or build the package individually.

**Comment by mightybyte** [comment] 2016-04-14 20:06
It was definitely building before.  `-fforce-recomp` didn't help either.  Build logs are displayed with `--pedantic`, so it seems like they should be able to be displayed similarly (without taking the -j1 hit) for an option that has `-Wall` without `-Werror`.

**Comment by mgsloan** [comment] 2016-04-14 20:36
It works for me.  Can you please provide a repro based on publically available code?

Might also be worthwhile trying with HEAD stack, though I doubt that's the difference.

**Comment by mightybyte** [comment] 2016-04-18 23:11
git clone https://github.com/jaspervdj/digestive-functors.git
    cd digestive-functors
    stack build --ghc-options="-Wall"

I'm using this version of stack:

    Version 1.0.4, Git revision cf18703b1392a96a5a4896a560309e501af63260 (3220 commits) x86_64

**Comment by snoyberg** [comment] 2016-04-28 06:34
This is most likely caused by logs for multi-package projects being sent to log files instead of to the console. If you want to see the output on the console, you need to specify just one package to build, e.g.:

    stack build --ghc-options="-Wall" --file-watch digestive-functors-snap

Does that work?

**Comment by mightybyte** [comment] 2016-04-28 23:27
That works, but it is not a sufficient solution IMO.  `stack build --pendantic` shows warnings even when building multiple packages, so there's clearly no technical reason the same can't be done for -Wall.  I want to be seeing warnings as often as possible, not just when building a single package.  Getting -Wall behavior also shouldn't require any extra characters to be typed on the command line.

**Comment by mgsloan** [comment] 2016-04-29 00:13
The reason that `stack build --pedantic` shows warnings for all packages is because it causes them to be errors.  Erroring builds are always shown to the user.

I thoroughly agree that we should be able to show all output, and potentially even make it a default.  Sounds like this is the main issue here, and it's currently tracked by https://github.com/commercialhaskell/stack/issues/426, so marking as a dupe of that.

**Closed** 2016-04-29 00:13 UTC
Labels: resolution: duplicate

**Comment by mgsloan** [comment] 2016-04-29 03:25
Might also be running into https://github.com/commercialhaskell/stack/issues/2063

**Comment by mightybyte** [comment] 2016-04-29 14:04
Sounds good.  If #426 is the dupe for this, my main thought is that it should be possible to configure the option from the stack.yaml file so it can be set on a per-project basis rather than whenever developers think to do it.
