### ISSUE TITLE
Build failure with multiple sublibraries

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#5264] opened 2020-04-21 04:14 UTC
Opening the issue mainly so I can point to something from Stackage. Discovered on the Stackage build server, exact details unclear. Discussed already briefly with @mihaimaruseac. Error message:

```
singleBuild: invariant violated: multiple results when describing installed package (PackageName "z-typerep-map-z-typerep-extra-impls",[DumpPackage {dpGhcPkgId = "typerep-map-0.3.3.0-G31jbHp6ZLNL1lI7xDvBCI-typerep-extra-impls", dpPackageIdent = PackageIdentifier {pkgName = PackageName "z-typerep-map-z-typerep-extra-impls", pkgVersion = mkVersion [0,3,3,0]}, dpParentLibIdent = Just (PackageIdentifier {pkgName = PackageName "typerep-map", pkgVersion = mkVersion [0,3,3,0]}), dpLicense = Just (MPL (mkVersion [2,0])), dpLibDirs = ["/var/stackage/work/unpack-dir/.stack-work/install/x86_64-linux/5205855089ba0955c14ff75f5d693cb77fc57f4dcd0e417285b7ba64a5a860ea/8.8.3/lib/x86_64-linux-ghc-8.8.3/typerep-map-0.3.3.0-G31jbHp6ZLNL1lI7xDvBCI-typerep-extra-impls"], dpLibraries = ["HStyperep-map-0.3.3.0-G31jbHp6ZLNL1lI7xDvBCI-typerep-extra-impls"], dpHasExposedModules = True, dpExposedModules = fromList [ModuleName ["Data","TypeRep","CMap"],ModuleName ["Data","TypeRep","OptimalVector"],ModuleName ["Data","TypeRep","Vector"]], dpDepends = ["base-4.13.0.0","containers-0.6.2.1","deepseq-1.4.4.0","vector-0.12.1.2-53Y44dCp1VMIZPSwzrCJEe"], dpHaddockInterfaces = ["/var/stackage/work/unpack-dir/.stack-work/install/x86_64-linux/5205855089ba0955c14ff75f5d693cb77fc57f4dcd0e417285b7ba64a5a860ea/8.8.3/doc/typerep-map-0.3.3.0/typerep-map.haddock"], dpHaddockHtml = Just "/var/stackage/work/unpack-dir/.stack-work/install/x86_64-linux/5205855089ba0955c14ff75f5d693cb77fc57f4dcd0e417285b7ba64a5a860ea/8.8.3/doc/typerep-map-0.3.3.0", dpIsExposed = False},DumpPackage {dpGhcPkgId = "typerep-map-0.3.2-1d9Eb1gxhv0C8Ldi4IOt1H-typerep-extra-impls", dpPackageIdent = PackageIdentifier {pkgName = PackageName "z-typerep-map-z-typerep-extra-impls", pkgVersion = mkVersion [0,3,2]}, dpParentLibIdent = Just (PackageIdentifier {pkgName = PackageName "typerep-map", pkgVersion = mkVersion [0,3,2]}), dpLicense = Just MIT, dpLibDirs = ["/var/stackage/work/unpack-dir/.stack-work/install/x86_64-linux/5205855089ba0955c14ff75f5d693cb77fc57f4dcd0e417285b7ba64a5a860ea/8.8.3/lib/x86_64-linux-ghc-8.8.3/typerep-map-0.3.2-1d9Eb1gxhv0C8Ldi4IOt1H-typerep-extra-impls"], dpLibraries = ["HStyperep-map-0.3.2-1d9Eb1gxhv0C8Ldi4IOt1H-typerep-extra-impls"], dpHasExposedModules = True, dpExposedModules = fromList [ModuleName ["Data","TypeRep","CMap"],ModuleName ["Data","TypeRep","OptimalVector"],ModuleName ["Data","TypeRep","Vector"]], dpDepends = ["base-4.13.0.0","containers-0.6.2.1","deepseq-1.4.4.0","vector-0.12.1.2-53Y44dCp1VMIZPSwzrCJEe"], dpHaddockInterfaces = ["/var/stackage/work/unpack-dir/.stack-work/install/x86_64-linux/5205855089ba0955c14ff75f5d693cb77fc57f4dcd0e417285b7ba64a5a860ea/8.8.3/doc/typerep-map-0.3.2/typerep-map.haddock"], dpHaddockHtml = Just "/var/stackage/work/unpack-dir/.stack-work/install/x86_64-linux/5205855089ba0955c14ff75f5d693cb77fc57f4dcd0e417285b7ba64a5a860ea/8.8.3/doc/typerep-map-0.3.2", dpIsExposed = False}])
```

**Comment by snoyberg** [comment] 2020-04-21 04:17
See https://github.com/commercialhaskell/stackage/commit/d3aed566e695fd4f82b06bac83528b7c9528e869

**Comment by snoyberg** [comment] 2020-04-21 04:19
Ah, looks like the bug may be simpler than I thought: `ghc-pkg unregister` needs to be told explicitly to unregister the sublibraries. Just a guess.

**Comment by mpilgrem** [comment] 2023-06-17 16:55
On the assumption that the guess was a good one, I am going to close this as a duplicate of (now fixed) https://github.com/commercialhaskell/stack/issues/6046.

**Closed by mpilgrem** 2023-06-17 16:55 UTC
