### ISSUE TITLE
removing ~/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.4/ causes system ghc to be used

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/stack#5174] opened 2020-02-13 02:19 UTC
### General summary/comments (optional)
It seems I had a broken or incomplete `~/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.4/` and this was causing stack to fallback to use system ghc-8.6.5 instead for lts-12 builds...!

### Steps to reproduce
1. `mv ~/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.4{,.moved}`
2. Run command `stack --resolver lts-12 build` in a project.

### Expected
stack should warn that chosen/found ghc is not ghc-8.4.4.

### Actual
```
WARNING: Ignoring Cabal's bounds on containers (>=0.4.2.1 && <0.6); using containers-0.6.0.1.
Reason: trusting snapshot over cabal file dependency information.
WARNING: Ignoring stm's bounds on base (>=4.3 && <4.12); using base-4.12.0.0.
Reason: trusting snapshot over cabal file dependency information.
:
```

### Stack version
stack-2.1.3.1-1.fc31.x86_64
### Method of installation
* An unofficial package repository

https://copr.fedorainfracloud.org/coprs/petersen/stack2/

**Comment by mpilgrem** [comment] 2024-03-11 22:37
I am closing this issue with the passage of time and because I could not reproduce it with a current version of Stack.

**Closed by mpilgrem** 2024-03-11 22:37 UTC
