### ISSUE TITLE
Failure to compile cryptohash-sha256 on Windows, incorrect configure

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#5408] opened 2020-10-02 18:05 UTC
### Steps to reproduce

1. Use Windows
2. `stack install cryptohash-sha256 --resolver=nightly-2020-09-29 -j1`

### Expected

Expect that to work.

### Actual

```
C:\Neil>stack install cryptohash-sha256 --resolver=nightly-2020-09-29 -j1
cryptohash-sha256> configure
cryptohash-sha256> Configuring cryptohash-sha256-0.11.101.0...
cryptohash-sha256> Warning: Packages using 'cabal-version: >= 1.10' must specify the
cryptohash-sha256> 'default-language' field for each component (e.g. Haskell98 or Haskell2010).
cryptohash-sha256> If a component uses different languages in different modules then list the
cryptohash-sha256> other ones in the 'other-languages' field.
cryptohash-sha256> build
cryptohash-sha256> Preprocessing library for cryptohash-sha256-0.11.101.0..
cryptohash-sha256> Building library for cryptohash-sha256-0.11.101.0..
cryptohash-sha256> [1 of 2] Compiling Crypto.Hash.SHA256.FFI
cryptohash-sha256> ghc.exe: could not execute: C:/GitLabRunner/builds/2WeHDSFP/0/ghc/ghc/inplace/mingw/bin/ld.exe

--  While building package cryptohash-sha256-0.11.101.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_3.2.0.0_ghc-8.10.2.exe --builddir=.stack-work\dist\a3a5fe88 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

### Stack version

```
Version 2.3.3, Git revision cb44d51bed48b723a5deb08c3348c0b3ccfc437e x86_64 hpack-0.33.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

### Notes

Seems like you are running configure. Installing this package with `cabal` doesn't run configure. When running configure, its passing a `GitLabRunner` directory that I don't have.

**Comment by expipiplus1** [comment] 2020-11-21 09:00
I believe this is an instance of this: https://gitlab.haskell.org/ghc/ghc/-/issues/18550

**Comment by mpilgrem** [comment] 2024-03-10 18:29
I am closing given the passage of time, the GHC issue is closed, and I cannot reproduce on Windows 11 wth a current version of Stack and LTS 22.13:
~~~text
stack build cryptoshash-sha256
~~~

works as expected.

**Closed by mpilgrem** 2024-03-10 18:29 UTC
