### ISSUE TITLE
ExitFailure after enabling executable profiling

### ISSUE THREAD

**Issue by wereHamster** [commercialhaskell/stack#1246] opened 2015-10-27 23:32 UTC
I have a project where I installed all dependencies using `stack build`, then decided that I want to profile the executable and tried reinstalling all dependencies with `stack build --executable-profiling`. Did not work:

```
$ stack build --executable-profiling --library-profiling                                                                                                                                                                                 byteable-0.1.1: copying precompiled package
bytestring-mmap-0.2.2: copying precompiled package
cereal-0.4.1.1: copying precompiled package
HUnit-1.2.5.2: copying precompiled package
Progress: 4/102Running $HOME/.stack/programs/x86_64-osx/ghc-7.10.2/bin/ghc-pkg register --force $HOME/.stack/snapshots/x86_64-osx/nightly-2015-10-12/7.10.2/pkgdb/HUnit-1.2.5.2-c3de451656bce8031e960442488eda4f.conf exited with ExitFailure 1
Reading package info from "$HOME/.stack/snapshots/x86_64-osx/nightly-2015-10-12/7.10.2/pkgdb/HUnit-1.2.5.2-c3de451656bce8031e960442488eda4f.conf" ... done.

HUnit-1.2.5.2: Warning: haddock-interfaces: $HOME/.stack/snapshots/x86_64-osx/nightly-2015-10-12/7.10.2/doc/HUnit-1.2.5.2/HUnit.haddock doesn't exist or isn't a file
HUnit-1.2.5.2: package(s) with this id already exist: HUnit-1.2.5.2
HUnit-1.2.5.2: package HUnit-1.2.5.2 is already installed
HUnit-1.2.5.2: Package names may be treated case-insensitively in the future.
Package HUnit-1.2.5.2 overlaps with: HUnit-1.2.5.2 (ignoring)
HUnit-1.2.5.2: dependency "base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f" doesn't exist (ignoring)
HUnit-1.2.5.2: dependency "deepseq-1.4.1.1-5de90d6c626db2476788444fb08c1eb3" doesn't exist (ignoring)


Running $HOME/.stack/programs/x86_64-osx/ghc-7.10.2/bin/ghc-pkg register --force $HOME/.stack/snapshots/x86_64-osx/nightly-2015-10-12/7.10.2/pkgdb/cereal-0.4.1.1-e7af0306d1317407815a09e40431fc3f.conf exited with ExitFailure 1
Reading package info from "$HOME/.stack/snapshots/x86_64-osx/nightly-2015-10-12/7.10.2/pkgdb/cereal-0.4.1.1-e7af0306d1317407815a09e40431fc3f.conf" ... done.

cereal-0.4.1.1: Warning: haddock-interfaces: $HOME/.stack/snapshots/x86_64-osx/nightly-2015-10-12/7.10.2/doc/cereal-0.4.1.1/cereal.haddock doesn't exist or isn't a file
cereal-0.4.1.1: package(s) with this id already exist: cereal-0.4.1.1
cereal-0.4.1.1: package cereal-0.4.1.1 is already installed
cereal-0.4.1.1: Package names may be treated case-insensitively in the future.
Package cereal-0.4.1.1 overlaps with: cereal-0.4.1.1 (ignoring)
cereal-0.4.1.1: dependency "array-0.5.1.0-d4206b835b96b5079d918fa1eab1a9a8" doesn't exist (ignoring)
cereal-0.4.1.1: dependency "base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f" doesn't exist (ignoring)
cereal-0.4.1.1: dependency "bytestring-0.10.6.0-6e8453cb70b477776f26900f41a5e17a" doesn't exist (ignoring)
cereal-0.4.1.1: dependency "containers-0.5.6.2-2b49cce16f8a2908df8454387e550b93" doesn't exist (ignoring)
cereal-0.4.1.1: dependency "ghc-prim-0.4.0.0-af16264bc80979d06e37ac63e3ba9a21" doesn't exist (ignoring)


Running $HOME/.stack/programs/x86_64-osx/ghc-7.10.2/bin/ghc-pkg register --force $HOME/.stack/snapshots/x86_64-osx/nightly-2015-10-12/7.10.2/pkgdb/bytestring-mmap-0.2.2-e74c183b3cc040c37590e7280de70831.conf exited with ExitFailure 1
Reading package info from "$HOME/.stack/snapshots/x86_64-osx/nightly-2015-10-12/7.10.2/pkgdb/bytestring-mmap-0.2.2-e74c183b3cc040c37590e7280de70831.conf" ... done.

bytestring-mmap-0.2.2: Warning: haddock-interfaces: $HOME/.stack/snapshots/x86_64-osx/nightly-2015-10-12/7.10.2/doc/bytestring-mmap-0.2.2/bytestring-mmap.haddock doesn't exist or isn't a file
bytestring-mmap-0.2.2: package(s) with this id already exist: bytestring-mmap-0.2.2
bytestring-mmap-0.2.2: package bytestring-mmap-0.2.2 is already installed
bytestring-mmap-0.2.2: Package names may be treated case-insensitively in the future.
Package bytestring-mmap-0.2.2 overlaps with: bytestring-mmap-0.2.2 (ignoring)
bytestring-mmap-0.2.2: dependency "base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f" doesn't exist (ignoring)
bytestring-mmap-0.2.2: dependency "bytestring-0.10.6.0-6e8453cb70b477776f26900f41a5e17a" doesn't exist (ignoring)
bytestring-mmap-0.2.2: dependency "unix-2.7.1.0-75051e1ddce506fe76a9ea932b926357" doesn't exist (ignoring)


Running $HOME/.stack/programs/x86_64-osx/ghc-7.10.2/bin/ghc-pkg register --force $HOME/.stack/snapshots/x86_64-osx/nightly-2015-10-12/7.10.2/pkgdb/byteable-0.1.1-4711df568158362d44734aacd1813e82.conf exited with ExitFailure 1
Reading package info from "$HOME/.stack/snapshots/x86_64-osx/nightly-2015-10-12/7.10.2/pkgdb/byteable-0.1.1-4711df568158362d44734aacd1813e82.conf" ... done.

byteable-0.1.1: Warning: haddock-interfaces: $HOME/.stack/snapshots/x86_64-osx/nightly-2015-10-12/7.10.2/doc/byteable-0.1.1/byteable.haddock doesn't exist or isn't a file
byteable-0.1.1: package(s) with this id already exist: byteable-0.1.1
byteable-0.1.1: package byteable-0.1.1 is already installed
byteable-0.1.1: Package names may be treated case-insensitively in the future.
Package byteable-0.1.1 overlaps with: byteable-0.1.1 (ignoring)
byteable-0.1.1: dependency "base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f" doesn't exist (ignoring)
byteable-0.1.1: dependency "bytestring-0.10.6.0-6e8453cb70b477776f26900f41a5e17a" doesn't exist (ignoring)
```

After deleting `$HOME/.stack/snapshots` it worked almost. Snap still can't be compiled with profiling enabled, but that's another issue.

**Comment by borsboom** [comment] 2015-10-31 23:09
@snoyberg: the "copying precompiled package" messages make me suspicious.  Could this be a problem when a precompiled package is copied and then later rebuilt with profiling?

**Comment by borsboom** [comment] 2015-11-01 18:36
This looks like it may be a duplicate of #1188.

**Comment by borsboom** [comment] 2015-11-07 23:12
Closing as a duplicate of #1188 which is hopefully fixed in master now.

**Closed by borsboom** 2015-11-07 23:12 UTC
Labels: type: bug
