### ISSUE TITLE
first time running `stack test` issues with lock

### ISSUE THREAD

**Issue by wolftune** [commercialhaskell/stack#1031] opened 2015-09-23 05:14 UTC
when I run `stack test` for the first time and it installs extra dependencies for testing, it doesn't close stack properly before moving into running the tests and then the tests hang when stack sees a lock file. I have to manually kill the stack process and then run `stack test` again, and then it works.

I've noticed this on several occasions but infrequently because I rarely rebuild from nothing. Others had this issue too.

**Comment by snoyberg** [comment] 2015-09-24 03:12
Pinging @rrnewton.

@wolftune Started in the next release on Stack (0.1.5.0) locking will be opt in, so this shouldn't affect you.

**Comment by rrnewton** [comment] 2015-10-06 15:25
I'd still like to fix this for when `STACK_LOCK=true`.  Can you paste an explicit reproducer?  We're using `stack test` with locking for all our Jenkins/Travis builds and we haven't run into this problem.

**Comment by wolftune** [comment] 2015-10-06 15:33
@rrnewton we had this happening on our project https://github.com/snowdriftcoop/snowdrift — it's cumbersome, and I don't have time to make a specific reproducible small repo. You could try building our code, following the instructions as usual but adding that lock statement… thing is, it only happens the one time when the test dependencies haven't been built yet.

**Comment by rrnewton** [comment] 2015-10-07 14:06
A big reproducer is fine.  

On an ubuntu 14.04 system it complained about wanting postgres-9.3 specifically so I expanded the deps to:

```
sudo apt-get install git postgresql postgresql-client libgmp-dev zlib1g-dev libpq-dev libtinfo-dev postgresql-9.3 postgresql-common
```

Then it was happy, could find `pg_config` and `libpq-fe.h`.  But still I struck out with this error:

```
Progress: 1/2starting test program
building foundation
test: InvalidYaml (Just (YamlException "Yaml file not found: config/postgresql.yml"))
Test suite failure for package Snowdrift-0.1.4
    test:  exited with: ExitFailure 1
```

 How about a `Dockerfile` that builds it ;-)?

**Comment by wolftune** [comment] 2015-10-07 16:13
@rrnewton that's really strange, we've had *tons* of people build on Ubuntu 14.04 with our exact instructions, including myself and the live site itself. I *do* have postgresql-9.3 installed but *not* manually. I only installed the items listed in our requirements.

If you look at the package settings for postgresql, you'll see it has a hard dependency on postgresql-9.3 — so something is clearly wrong with your system. It is ignoring hard-dependencies when installing. That is not common at all, and there really is no need for Docker here.

**Comment by rrnewton** [comment] 2015-10-08 17:37
Ah, yeah, I missed the `sdm` call.  This is a remarkably well set up list of build instructions.

I just find docker handy for at least *attempting* hermetic reproducibility when running a series of commands.  I tried running with the below Dockerfile, located in a checkout of snowdrift (with dockerignore ignoring `.git`) but ran into the following error.

```
FROM fpco/stack-build:lts-3.6
RUN apt-get update
RUN apt-get install -y git postgresql postgresql-client libgmp-dev zlib1g-dev libpq-dev libtinfo-dev
ADD . snowdrift/
RUN cd snowdrift && stack setup
RUN cd snowdrift && stack build cabal-install yesod-bin
RUN cd snowdrift && stack build
RUN cd snowdrift && stack exec sdm init
RUN cd snowdrift && STACK_LOCK=true stack test
```

```
fatal: Not a git repository (or any of the parent directories): .git

/snowdrift/src/Application.hs:75:13:
    Exception when trying to run compile-time code:
      readCreateProcess: git "show-ref" "refs/heads/master" (exit 128): failed
    Code: mkVersion
    In the splice: $mkVersion
Completed all 110 actions.
```

I'm (slowly) trying again now without ignoring the `.git` directory....

**Comment by rrnewton** [comment] 2015-10-08 17:44
Here's a more self-contained version that clones the snowdrift repo:

```Dockerfile
FROM fpco/stack-build:lts-3.6
RUN apt-get update
RUN apt-get install -y git postgresql postgresql-client libgmp-dev zlib1g-dev libpq-dev libtinfo-dev
RUN git clone https://github.com/snowdriftcoop/snowdrift.git && \
    cd snowdrift && git checkout 3f03768af6f7065973edd3d30e932ba97dbaa3ef
RUN cd snowdrift && stack setup
RUN cd snowdrift && stack build cabal-install yesod-bin
RUN cd snowdrift && stack build
RUN cd snowdrift && stack exec sdm init
RUN cd snowdrift && STACK_LOCK=true stack test
```

**Comment by wolftune** [comment] 2015-10-08 19:56
@rrnewton was there a question for me in that stuff or you're set on just this is a reproducible case?

**Comment by rrnewton** [comment] 2015-10-08 21:50
Giving up on this as a reproducer for now -- the above Dockerfile must be incomplete, because it runs into this:

```
starting test program
building foundation
test: libpq: failed (could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
)
```

(And should for anyone else too, if it's in fact perfectly reproducible!)

Usually it would be easier to make a small test case to reproduce... I just wanted to push on this one a bit because we have plenty of other repos that run `stack test` on a fresh checkout (in travis and jenkins jobs) and *don't* exhibit the problem described by this issue.

**Comment by wolftune** [comment] 2015-10-09 00:05
@rrnewton incidentally, it's very strange that you haven't simply been able to build outside of Docker etc. just as a normal project, per our instructions. I would like to get to the bottom of that, although maybe it's not priority enough. I have no idea why you'd have any issues.

**Comment by mgsloan** [comment] 2015-11-24 08:34
Locking is no longer a default, closing.

**Closed by mgsloan** 2015-11-24 08:34 UTC
Labels: need repro, type: bug
