### ISSUE TITLE
Stack doesn't detect library needs reinstalled with new shared dependency to resolve build conflict

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1192] opened 2015-10-18 17:44 UTC
Might be a mischaracterization.

```
/home/callen/work/bloodhound/src/Database/Bloodhound/Client.hs:266:40:
    Couldn't match expected type ‘NHTS.Status’
                with actual type ‘http-types-0.8.6:Network.HTTP.Types.Status.Status’
    NB: ‘NHTS.Status’
          is defined in ‘Network.HTTP.Types.Status’
              in package ‘http-types-0.9’
        ‘http-types-0.8.6:Network.HTTP.Types.Status.Status’
          is defined in ‘Network.HTTP.Types.Status’
              in package ‘http-types-0.8.6’
    In the first argument of ‘NHTS.statusCode’, namely
      ‘(responseStatus resp)’
    In the first argument of ‘(==)’, namely
      ‘NHTS.statusCode (responseStatus resp)’
```

the thing returning `Status` from `0.8.6` is http-client Status.

https://github.com/bitemyapp/bloodhound/blob/master/stack-7.10.yaml

https://github.com/bitemyapp/bloodhound/blob/master/bloodhound.cabal

http-client doesn't have an upper bound on http-types. I'm not sure what's going on here. I tried wiping out `.stack-work` to no avail. I think my version of http-client needed recompiled against the new http-types but Stack doesn't seem to detect that this is necessary. Forcing a rebuild of http-client by choosing a specific version in my stack-yaml fixed this.

**Comment by snoyberg** [comment] 2015-10-19 05:25
Could possibly be related to:

https://github.com/haskell/cabal/issues/2830

More information that's needed for this:

1. As usual, the `stack build --verbose` output
2. Confirm: are you using the newest Stack release? I put in a workaround for that Cabal issue since 0.1.5.0
3. What's the output of `ghc-pkg list`?

**Comment by bitemyapp** [comment] 2015-10-19 16:14
@snoyberg I've tried, but don't think I can readily reproduce this. I'd need to think carefully about what sequence of changes to my stack/Cabal and builds were involved.

**Comment by borsboom** [comment] 2015-11-03 18:49
Since we don't have a reproduction, I'll close this for now.  Please re-open if you see this happen again.

**Closed by borsboom** 2015-11-03 18:49 UTC
Labels: need repro
