### ISSUE TITLE
Can Stack use proxy in Linux like http://<user:password>@<proxy>:<port>/ ?

### ISSUE THREAD

**Issue by dmitry-sensei** [commercialhaskell/stack#915] opened 2015-09-04 05:04 UTC
Can Stack use proxy in Linux like <user:password>@<proxy>:<port> ?
Now I have such proxy
$env:grep -i proxy
NO_PROXY=localhost,127.0.0.0/8,::1
http_proxy=http://<user:password>@<proxy>:<port>/ 
FTP_PROXY=http://<user:password>@<proxy>:<port>/ 
https_proxy=http://<user:password>@<proxy>:<port>/ 
HTTPS_PROXY=http://<user:password>@<proxy>:<port>/ 
no_proxy=localhost,127.0.0.0/8,::1
HTTP_PROXY=http://<user:password>@<proxy>:<port>/ 

$ stack update
InvalidProxyEnvironmentVariable "http://<user:password>@<proxy>:<port>/ "

**Comment by snoyberg** [comment] 2015-09-04 05:07
You haven't included a hostname or port number in those values.

**Comment by dmitry-sensei** [comment] 2015-09-04 05:12
Github did not show "more" "less" sings :) I mean http://user:password@192.168.20.234:8080/

**Comment by snoyberg** [comment] 2015-09-04 05:15
What's your --version output? And can you try upgrading to the latest release?

**Comment by dmitry-sensei** [comment] 2015-09-04 05:17
Version 0.1.4.0, Git revision 3a665fe1bc52776041a1c25cc47734e691805b6c (1724 commits) X86_64

Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid

**Comment by snoyberg** [comment] 2015-09-04 05:25
I'm unable to reproduce. For the record, I tried:

```
#!/bin/bash

export HTTP_PROXY=http://user:password@192.168.20.234:8080/
export HTTPS_PROXY=http://user:password@192.168.20.234:8080/
export http_proxy=http://user:password@192.168.20.234:8080/
export https_proxy=http://user:password@192.168.20.234:8080/
export NO_PROXY=localhost,127.0.0.0/8,::1
export no_proxy=localhost,127.0.0.0/8,::1

stack update
```

**Comment by dmitry-sensei** [comment] 2015-09-04 05:27
I'll check it in deep :) May be some issues will be found from me

**Comment by dmitry-sensei** [comment] 2015-09-04 05:37
If do You use password with ## symbols? i.e ##8888## ?

**Comment by dmitry-sensei** [comment] 2015-09-04 06:43
Yes, @snoyberg . Problem exists in ## (spec.symbols) in password. Can You fix it? I can't change password on office proxy :(

**Comment by snoyberg** [comment] 2015-09-04 06:57
That's a reserved character, and likely just needs to be percent encoded
(%23 I believe). Can you give that a shot? I'm not at my computer.

**Comment by dmitry-sensei** [comment] 2015-09-04 07:23
Replaced.

Now InvalidProxyEnvironmentVariable is not exist. But:

stack update
Updating package index Hackage (mirrored at https://github.com/commercialhaskell/all-cabal-hashe                                                                                                Fetching package index ...Running /usr/bin/git fetch --tags --depth=1 exited with ExitFailure 128
fatal: unable to access 'https://github.com/commercialhaskell/all-cabal-hashes.git/': Failed to connect to xxx.xxx.xxx.xxx port xxxx: Connection timed out
Some ideas?

**Comment by snoyberg** [comment] 2015-09-04 09:24
No idea. I'd recommend testing things out with the http-client library
directly, which is where all of the logic we've been discussing is living.

**Comment by snoyberg** [comment] 2015-09-06 07:43
Actually, that issue has nothing to do with stack itself, it seems that `git` is unable to make HTTP connections either. I'd recommend checking out:

http://stackoverflow.com/questions/128035/how-do-i-pull-from-a-git-repository-through-an-http-proxy

I don't believe there is anything we can change in stack for this, closing.

**Closed by snoyberg** 2015-09-06 07:43 UTC

**Comment by dmitry-sensei** [comment] 2015-09-06 11:19
Thanks. Most likely You're right
