### ISSUE TITLE
Stack clean does not work correctly with --nix

### ISSUE THREAD

**Issue by ElvishJerricco** [commercialhaskell/stack#3468] opened 2017-10-03 23:08 UTC
When using nix integration, `stack clean` does not work. I'm not sure if there's any reason it should need GHC at all for `clean`, but it exits with a `No compiler found, ...` error message when the user does not have GHC installed in their user profile. Presumably Stack is not performing `clean` from within the nix shell, or it should not need GHC at all.

EDIT: This is a regression in Stack 1.5. This worked in 1.4.

**Comment by mgsloan** [comment] 2017-10-04 01:02
That is just part of stack's normal environment setup.  There isn't currently an environment type / code to load it that reflects "I need to use Cabal but I don't need GHC".  I'm not sure this is important, AFIACT a compiler was also needed in stack-1.4, not convinced there was a regression here.

`stack clean` is implemented by running Cabal clean (roughly kinda like `runghc Setup.hs clean`), so this does require GHC.

`stack clean --full` could potentially be implemented to not need the compiler, since it just recursively deletes the work dirs.

Leaning towards wontfix, I don't see why this matters.  Why would you ever want to clean if you don't have a compiler?  Would accept a PR that makes loading the full env unnecessary for `stack clean --full`.

**Comment by ElvishJerricco** [comment] 2017-10-04 01:05
@mgsloan the regression is that Stack should enter the Nix shell when doing `clean` with `—nix`, like it does for every other command. Entering the Nix shell would provide it with the GHC it needs. Excuse my irrelevant commentary on whether GHC should be necessary for `clean` at all =P

**Comment by mgsloan** [comment] 2017-10-04 01:17
Updated the first paragraph of my comment above.  I think the commit linked there is definitely the cause of the issue.  A couple possible solutions:

* Have `stack clean` enter nix shell, but not docker containers.  Problem with this approach is it won't work for docker + nix.
* Have `stack clean --full` not enter either nix or docker containers.  `stack clean` would enter both, which is an enhancement, current code path demands you have cabal / ghc outside of your docker / nix.  Can also maybe make `stack clean --full` skip demanding a ghc / cabal be installed.

I'll give it a shot.

**Comment by mgsloan** [comment] 2017-10-04 02:05
I've split off https://github.com/commercialhaskell/stack/issues/3469 and opened https://github.com/commercialhaskell/stack/pull/3470 .  Can you please check if that change fixes the issue?  Thanks!  The solution is not ideal: https://github.com/commercialhaskell/stack/issues/3471

**Comment by ElvishJerricco** [comment] 2017-10-04 19:55
That appears to have fixed it. Thanks!

**Comment by mgsloan** [comment] 2017-10-04 23:38
Great, merged!  Thanks for confirming

**Closed by mgsloan** 2017-10-04 23:38 UTC
Labels: component: nix, help wanted
