### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by joelburget** [commercialhaskell/stack#2844] opened 2016-12-13 16:12 UTC
I tried installing on Ubuntu Xenial but `apt-get` failed because of an invalid FP Complete GPG signature.

### Steps to reproduce

I tried building the following Dockerfile (with steps taken from the [Install/upgrade guide](https://github.com/commercialhaskell/stack/blob/master/doc/install_and_upgrade.md)).

```
from ubuntu:xenial

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 575159689BEFB442 && echo 'deb http://download.fpcomplete.com/ubuntu xenial main' | tee /etc/apt/sources.list.d/fpco.list && apt-get update && apt-get install -y stack
```

`docker build .` shows some warnings:

```
Reading package lists...
W: GPG error: http://download.fpcomplete.com/ubuntu xenial Release: The following signatures were invalid: BADSIG 575159689BEFB442 FPComplete <dev@fpcomplete.com>
W: The repository 'http://download.fpcomplete.com/ubuntu xenial Release' is not signed.
Reading package lists...
```

ultimately resulting in an error:

```
WARNING: The following packages cannot be authenticated!
  stack
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
The command '/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 575159689BEFB442 && echo 'deb http://download.fpcomplete.com/ubuntu xenial main' | tee /etc/apt/sources.list.d/fpco.list && apt-get update && apt-get install -y stack' returned a non-zero code: 100
```

I expected the docker image to build but it failed on the `RUN` line.

### Other Info

I'm running this using Docker for Mac, macOS Sierra 10.12.1.

**Comment by mgsloan** [comment] 2016-12-17 21:24
Thanks for the repro, but I can't reproduce the problem, running docker on linux.  Is it at all possible that this is due to using Docker for Mac?

**Comment by joelburget** [comment] 2016-12-18 18:36
Not really sure -- I don't have a non-mac to test it on. FWIW @bts also reproed on Mac.

**Comment by borsboom** [comment] 2016-12-18 22:48
It works for me:

```
$ uname -a
Darwin eb-mbp14a.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64

$ docker --version
Docker version 1.12.0, build 8eab29e

$ docker build .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu:xenial
xenial: Pulling from library/ubuntu
b3e1c725a85f: Pull complete
4daad8bdde31: Pull complete
63fe8c0068a8: Pull complete
4a70713c436f: Pull complete
bd842a2105a8: Pull complete
Digest: sha256:7a64bc9c8843b0a8c8b8a7e4715b7615e4e1b0d8ca3c7e7a76ec8250899c397a
Status: Downloaded newer image for ubuntu:xenial
 ---> 104bec311bcd
Step 2 : RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 575159689BEFB442 && echo 'deb http://download.fpcomplete.com/ubuntu xenial main' | tee /etc/apt/sources.list.d/fpco.list && apt-get update && apt-get install -y stack
 ---> Running in 01b593df0418
Executing: /tmp/tmp.W73LfSUbcc/gpg.1.sh --keyserver
hkp://keyserver.ubuntu.com:80
--recv-keys
575159689BEFB442
gpg: requesting key 9BEFB442 from hkp server keyserver.ubuntu.com
gpg: key 9BEFB442: public key "FPComplete <dev@fpcomplete.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
deb http://download.fpcomplete.com/ubuntu xenial main
Ign:1 http://download.fpcomplete.com/ubuntu xenial InRelease
Get:2 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:3 http://download.fpcomplete.com/ubuntu xenial Release [1797 B]
Get:4 http://download.fpcomplete.com/ubuntu xenial Release.gpg [490 B]
Get:5 http://download.fpcomplete.com/ubuntu xenial/main amd64 Packages [916 B]
[...]
Fetched 24.6 MB in 21s (1163 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  binutils ca-certificates cpp cpp-5 g++ g++-5 gcc gcc-5 git git-man ifupdown
  iproute2 isc-dhcp-client isc-dhcp-common krb5-locales less libasan2
  libasn1-8-heimdal libatm1 libatomic1 libbsd0 libc-dev-bin libc6-dev libcc1-0
  libcilkrts5 libcurl3-gnutls libdns-export162 libedit2 liberror-perl
  libexpat1 libffi-dev libffi6 libgcc-5-dev libgdbm3 libgmp-dev libgmp10
  libgmpxx4ldbl libgnutls30 libgomp1 libgssapi-krb5-2 libgssapi3-heimdal
  libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal libhogweed4
  libhx509-5-heimdal libidn11 libisc-export160 libisl15 libitm1 libk5crypto3
  libkeyutils1 libkrb5-26-heimdal libkrb5-3 libkrb5support0 libldap-2.4-2
  liblsan0 libmnl0 libmpc3 libmpfr4 libmpx0 libnettle6 libp11-kit0 libperl5.22
  libpopt0 libquadmath0 libroken18-heimdal librtmp1 libsasl2-2
  libsasl2-modules libsasl2-modules-db libsqlite3-0 libssl1.0.0
  libstdc++-5-dev libtasn1-6 libtsan0 libubsan0 libwind0-heimdal libx11-6
  libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxmuu1 libxtables11
  linux-libc-dev make manpages manpages-dev netbase openssh-client openssl
  patch perl perl-modules-5.22 rename rsync xauth xz-utils zlib1g-dev
Suggested packages:
  binutils-doc cpp-doc gcc-5-locales g++-multilib g++-5-multilib gcc-5-doc
  libstdc++6-5-dbg gcc-multilib autoconf automake libtool flex bison gdb
  gcc-doc gcc-5-multilib libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg
  libasan2-dbg liblsan0-dbg libtsan0-dbg libubsan0-dbg libcilkrts5-dbg
  libmpx0-dbg libquadmath0-dbg gettext-base git-daemon-run
  | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-arch
  git-cvs git-mediawiki git-svn ppp rdnssd iproute2-doc resolvconf
  avahi-autoipd isc-dhcp-client-ddns apparmor glibc-doc gmp-doc libgmp10-doc
  libmpfr-dev gnutls-bin krb5-doc krb5-user libsasl2-modules-otp
  libsasl2-modules-ldap libsasl2-modules-sql libsasl2-modules-gssapi-mit
  | libsasl2-modules-gssapi-heimdal libstdc++-5-doc make-doc man-browser
  ssh-askpass libpam-ssh keychain monkeysphere ed diffutils-doc perl-doc
  libterm-readline-gnu-perl | libterm-readline-perl-perl openssh-server
The following NEW packages will be installed:
  binutils ca-certificates cpp cpp-5 g++ g++-5 gcc gcc-5 git git-man ifupdown
  iproute2 isc-dhcp-client isc-dhcp-common krb5-locales less libasan2
  libasn1-8-heimdal libatm1 libatomic1 libbsd0 libc-dev-bin libc6-dev libcc1-0
  libcilkrts5 libcurl3-gnutls libdns-export162 libedit2 liberror-perl
  libexpat1 libffi-dev libffi6 libgcc-5-dev libgdbm3 libgmp-dev libgmp10
  libgmpxx4ldbl libgnutls30 libgomp1 libgssapi-krb5-2 libgssapi3-heimdal
  libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal libhogweed4
  libhx509-5-heimdal libidn11 libisc-export160 libisl15 libitm1 libk5crypto3
  libkeyutils1 libkrb5-26-heimdal libkrb5-3 libkrb5support0 libldap-2.4-2
  liblsan0 libmnl0 libmpc3 libmpfr4 libmpx0 libnettle6 libp11-kit0 libperl5.22
  libpopt0 libquadmath0 libroken18-heimdal librtmp1 libsasl2-2
  libsasl2-modules libsasl2-modules-db libsqlite3-0 libssl1.0.0
  libstdc++-5-dev libtasn1-6 libtsan0 libubsan0 libwind0-heimdal libx11-6
  libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxmuu1 libxtables11
  linux-libc-dev make manpages manpages-dev netbase openssh-client openssl
  patch perl perl-modules-5.22 rename rsync stack xauth xz-utils zlib1g-dev
0 upgraded, 102 newly installed, 0 to remove and 4 not upgraded.
Need to get 69.8 MB of archives.
After this operation, 293 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 libatm1 amd64 1:2.5.1-1.5 [24.2 kB]
Get:2 http://download.fpcomplete.com/ubuntu xenial/main amd64 stack amd64 1.3.0-0~xenial [11.3 MB]
[...]
Selecting previously unselected package stack.
Preparing to unpack .../stack_1.3.0-0~xenial_amd64.deb ...
Unpacking stack (1.3.0-0~xenial) ...
[...]
Setting up stack (1.3.0-0~xenial) ...
[...]
173 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
 ---> 07724d0c4274
Removing intermediate container 01b593df0418
Successfully built 07724d0c4274
```

**Comment by mgsloan** [comment] 2017-01-31 03:05
Closing since we can't reproduce the issue.

**Closed by mgsloan** 2017-01-31 03:05 UTC
Labels: further investigation required
