### ISSUE TITLE
Stack 1.6 linking issues on Arch Linux

### ISSUE THREAD

**Issue by ruuda** [commercialhaskell/stack#3518] opened 2017-10-26 19:17 UTC
### General summary/comments

I am testing the [Stack 1.6.0 pre-release](https://github.com/commercialhaskell/stack/releases/tag/v1.6.0.20171022). I am trying to build [ruuda/christmas-tree](https://github.com/ruuda/christmas-tree), commit `a48012e`. I can build it fine with Stack 1.5.1, but not with the 1.6.0 pre-release; the output is as follows:

```
Linking /home/ruud/.stack/setup-exe-cache/x86_64-linux-tinfo6-nopie/tmp-Cabal-simple_mPHDZzAJ_1.24.0.0_ghc-8.0.1 ...

In file included from /tmp/ghc2706_0/ghc_1.c:1:0: error: 

In file included from /home/ruud/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.1/lib/ghc-8.0.1/include/Rts.h:217:0: error:
    

/home/ruud/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.1/lib/ghc-8.0.1/include/rts/storage/ClosureMacros.h:505:5: error:
     warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#if ZERO_SLOP_FOR_LDV_PROF || ZERO_SLOP_FOR_SANITY_CHECK
    ^

... (more of those, it's a GHC bug which I thought was fixed at some point) ...

/usr/bin/ld: /home/ruud/.stack/setup-exe-src/setup-shim-mPHDZzAJ.o: relocation R_X86_64_32S against symbol `stg_bh_upd_frame_info' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /tmp/ghc2706_0/ghc_2.o: relocation R_X86_64_32 against symbol `ZCMain_main_closure' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/ruud/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.1/lib/ghc-8.0.1/Cabal-1.24.0.0/libHSCabal-1.24.0.0.a(Simple__35.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/ruud/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.1/lib/ghc-8.0.1/Cabal-1.24.0.0/libHSCabal-1.24.0.0.a(Simple__48.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/ruud/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.1/lib/ghc-8.0.1/Cabal-1.24.0.0/libHSCabal-1.24.0.0.a(Simple__33.o): relocation R_X86_64_32S against symbol `stg_upd_frame_info' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/ruud/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.1/lib/ghc-8.0.1/Cabal-1.24.0.0/libHSCabal-1.24.0.0.a(Command__75.o): relocation R_X86_64_32S against symbol `stg_upd_frame_info' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/ruud/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.1/lib/ghc-8.0.1/Cabal-1.24.0.0/libHSCabal-1.24.0.0.a(Command__24.o): relocation R_X86_64_32S against symbol `stg_upd_frame_info' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/ruud/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.1/lib/ghc-8.0.1/Cabal-1.24.0.0/libHSCabal-1.24.0.0.a(Command__185.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/ruud/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.1/lib/ghc-8.0.1/Cabal-1.24.0.0/libHSCabal-1.24.0.0.a(Command__66.o): relocation R_X86_64_32 against symbol `Cabalzm1zi24zi0zi0_DistributionziSimpleziCommand_zdLrbGjpolyzugo3_closure' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/ruud/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.1/lib/ghc-8.0.1/Cabal-1.24.0.0/libHSCabal-1.24.0.0.a(Command__55.o): relocation R_X86_64_32S against symbol `stg_bh_upd_frame_info' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/ruud/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.1/lib/ghc-8.0.1/Cabal-1.24.0.0/libHSCabal-1.24.0.0.a(Command__65.o): relocation R_X86_64_32 against symbol `Cabalzm1zi24zi0zi0_DistributionziSimpleziCommand_zdLrbGipolyzugo2_closure' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/ruud/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.1/lib/ghc-8.0.1/Cabal-1.24.0.0/libHSCabal-1.24.0.0.a(Configure__329.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC

... thousands of those ...

/usr/bin/ld: /home/ruud/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.0.1/lib/ghc-8.0.1/rts/libCffi.a(ffi64.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
`clang' failed in phase `Linker'. (Exit code: 1)
Exit code ExitFailure 1 while running ["ghc","-rtsopts","-threaded","-clear-package-db","-global-package-db","-hide-all-packages","-package","base","-main-is","StackSetupShim.mainOverride","-package","Cabal-1.24.0.0","/home/ruud/.stack/setup-exe-src/setup-mPHDZzAJ.hs","/home/ruud/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs","-o","/home/ruud/.stack/setup-exe-cache/x86_64-linux-tinfo6-nopie/tmp-Cabal-simple_mPHDZzAJ_1.24.0.0_ghc-8.0.1"] in /tmp/stack2688/
```

### Steps to reproduce

```
git clone https://github.com/ruuda/christmas-tree
cd christmas-tree
git checkout a48012e
stack build
````

I removed my `~/.stack/config.yaml` but that does not resolve the issue. The project's `stack.yaml` looks like this:

```yaml
resolver: lts-7.13
extra-deps:
  - serialport-0.4.7
```

I think Stack might have downloaded the wrong compiler here; it downloaded a `nopie` compiler but then complains about `-fPIC`. I am using Arch Linux.

### Expected

The build should succeed.

### Actual

Thousands of linker complaints.

### Stack version

```
Version 1.6.0.20171022, Git revision 7bddfaf7f9f8cd9ec1c710fa83e77262e494eee4 (5285 commits) x86_64 hpack-0.18.1
```

### Method of installation

* Adjusted the `stack-static` AUR pkgbuild for 1.6.0 pre-release. It downloads the tar from Github.

**Comment by mgsloan** [comment] 2017-10-26 21:31
Thanks for the report!  Is it possible that this is related to changes in arch and not changes in stack?

Haven't seen this particular issue, but there's been lots of bug reports recently about ncurses / nopie and arch linux, which largely seem to be from upstream changes:

* https://github.com/commercialhaskell/stack/issues/3509
* https://bugs.archlinux.org/task/56101
* https://github.com/commercialhaskell/stack/issues/3507
* https://github.com/commercialhaskell/stack/issues/2712#issuecomment-339171287

**Comment by ruuda** [comment] 2017-10-27 15:24
If I downgrade to 1.5.1 I can build again.

I did have trouble with ncurses and nopie in the past, the first was resolved by installing an AUR package, the second was resolved by somebody uploading the right bindist so Stack could download it. There was a comment about that in an issue here somewhere, but I cannot find it at the moment.

**Comment by mgsloan** [comment] 2017-10-28 08:31
Hmm, can you please try with this patch? https://github.com/commercialhaskell/stack/pull/3521  It might solve the issue here.

**Comment by ruuda** [comment] 2017-10-28 14:17
When I build Stack `53a0e618` and then run `stack setup`, I get the following message:

```
No information found for ghc-8.0.1.
Supported versions for OS key 'linux64-ncurses6-nopie': GhcVersion 8.0.2, GhcVersion 8.2.1
```

When I change the resolver to the GHC 8.0.2-based `lts-9.9`, it downloads `ghc-ncurses6-nopie-8.0.2`, which works fine.

**Comment by henrique-almeida** [comment] 2017-10-28 17:34
sed -i 's/-fno-PIE/-no-pie/g' ~/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.2.1/lib/ghc-8.2.1/settings
fixed it for me (issue #2712)

**Comment by mgsloan** [comment] 2017-10-29 00:22
Interesting!  Pinging @borsboom

**Comment by borsboom** [comment] 2017-10-30 12:09
I think @ruuda's approach is right, it's just that I guess nobody built a compatible ghc-8.0.1 bindist.  Probably best to upgrade to ghc-8.0.2 anyway.

**Comment by Earnestly** [comment] 2017-12-03 22:24
Arch Linux has adopted `--enable-default-pie` for their gcc package.  I believe other distributions are slowly adopting the same disposition as well.  If you want to continue building static packages you'll need to use `-no-pie` on those distributions as it is no longer the default behaviour.

**Comment by borsboom** [comment] 2017-12-23 23:05
There seems to be so much contradictory information coming in.  Starting with a totally fresh Arch system, the following commands worked for me, so I think selection of the `tinfo6-nopie` variant is right for what should be the most common Arch case:

```
pacman -Syu make gcc
curl -sSL https://get.haskellstack.org/ |sh
stack new test
cd test
stack build
stack exec test-exe
```

However, building `network`, `bindings-uname`, and others failed with a linker error mentioning "recompile with -fPIC".  I edited the GHC `settings` file and added `-fPIC` to the "C compiler link flags" and then building those worked as well

So that leaves me with a couple of questions:

 1. How can we automatically determine whether `-fPIC` is needed?
 2. Why are others having what appear to be completely different problems?  Perhaps it's related to the presence of the `ncurses5-compat-lib` package, and we should stop recommending it?

**Comment by borsboom** [comment] 2017-12-23 23:30
One more observation: downgrading to stack-1.5.1 does _not_ solve the problem for me.

**Comment by borsboom** [comment] 2017-12-24 02:37
@NorfairKing told me that adding `-no-pie` to the "C compiler link flags" in `settings` works for him and is the better approach than using `-fPIC`.  I can confirm that works for me as well.  Someone mentioned that older versions of `gcc` don't support `-no-pie`, but I wonder if we can assume that any distribution that's using PIE by default is also using a newer version of `gcc` (it at least ought to work on more cases).

What's weird is that it looks like GHC _should_ be passing in `-no-pie` automatically (introduced in http://git.haskell.org/ghc.git/commitdiff/fefe02c0324a25a52455a61f7f6e48be6d82d1ab), but haven't dug into it yet.

**Comment by borsboom** [comment] 2017-12-24 02:50
Relevant information also in https://github.com/commercialhaskell/stack/issues/3648

**Comment by borsboom** [comment] 2017-12-24 12:35
It turns out the regular `tinfo6` bindist (without `nopie`) seems to work fine on Arch since GHC 8.0.2!  Perhaps  the extra `nopie` settings are actually interfering GHC's own logic.

**Comment by borsboom** [comment] 2017-12-24 14:20
More potentially relevant information in https://github.com/commercialhaskell/stack/issues/3630.

**Comment by borsboom** [comment] 2017-12-24 15:00
I've tested without `nopie` on a number of distributions now and the only one that seems to be a problem is Gentoo/Sabayon, which actually has quite a different gcc setup (it's `Gentoo Hardened` but not `--enable-default-pie`, which unfortunately we combined into 'nopie').

My current thinking is that we should remove the `configure-env`s for GHC >= 8.0.2 in stack-setup-2.yaml since that should simplify things for more people.  Unfortunately, this will complicate things for Gentoo users but we can document that and add a special case for Gentoo in the next Stack release (any thoughts @rdnetto?)

**Comment by borsboom** [comment] 2017-12-24 22:57
Alright, I think I have something that's going to work for both Arch and Gentoo (and also tested on Ubuntu 18.04 and Fedora 27).  I've removed the `configure-env`s from the nopie "builds" so that Stack will stop trying to set the flags and let GHC's own logic (since 8.0.2) do it properly.  But since that fails on Gentoo, I've patched the GHC bindists and added a check to their `configure` script for the Gentoo case.  GHC's `configure` is really the right place for this sort of thing (rather than extra logic in Stack) and also means we can potentially contribute fixes upstream.  Please give this a try using:

```
stack setup --setup-info-yaml=https://raw.githubusercontent.com/fpco/stackage-content/nopie-fixes-arch-gentoo/
```

Strangely, Gentoo seems to need `--no-pie` instead of `-no-pie` (note the number of dashes).

**Comment by rdnetto** [comment] 2017-12-26 01:10
I've confirmed that Stack 1.6.1 works with the modified YAML under Sabayon with GCC 5.4.0, though I had to change the command to:
```
stack --resolver=lts-10.0 setup --setup-info-yaml=https://raw.githubusercontent.com/fpco/stackage-content/nopie-fixes-arch-gentoo/stack/stack-setup-2.yaml
```
(I think you might have truncated the URL)

I'm happy with any solution that works seamlessly, particularly if we can upstream it into GHC.

**Comment by ruuda** [comment] 2017-12-27 13:53
With the `--setup-info-yaml=` from [the above comment](https://github.com/commercialhaskell/stack/issues/3518#issuecomment-353899981), I observe the same issues as in the original report:

    ...
    relocation R_X86_64_32S against ``.rodata' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Nonrepresentable section on output
    clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
    `clang' failed in phase `Linker'. (Exit code: 1)

My `CC` and `CXX` are set to `clang` and `clang++`. This is with Stack version 1.6.3, Git revision b27e629b8c4ce369e3b8273f04db193b060000db (5454 commits) x86_64 hpack-0.20.0

**Comment by borsboom** [comment] 2017-12-27 14:16
@ruuda You might be on your own for this one... we endeavour to have `stack setup` work out-of-the-box for standard configurations of common distros, but we can't support every possible deviation (especially when many of these are more properly handled by GHC itself than Stack; in fact much of the reason we're having this current issue is because Stack tried to work around missing support in GHC and ended up interfering on newer versions of GHC).

Did you have `CC` and `CXX` set this way when Stack first installed GHC?  It not, GHC's `configure` script may have set itself up for gcc instead of clang.  In that case, try running `stack setup --reinstall` so that it'll be set up properly for clang.

**Comment by ruuda** [comment] 2017-12-27 14:46
Yes, I did have those set during initial install. I cleaned my `~/.stack` directory before doing the `stack setup`. `stack setup` failed to compile a sanity check after downloading and installing GHC. I also tried with `CC=gcc CXX=g++`, but this fails with the same error, except that it now says “gcc failed in phase Linker” rather than “clang failed”.

Doing a `stack setup` of LTS 9.10 with GHC 8.0.2 does work fine with the `--setup-info-yaml`; it was LTS 7.13 with GHC 8.0.1 that failed. But LTS 9.10 also works fine without passing the custom `--setup-info-yaml`.

It is not a big issue for me, I can upgrade all my projects to a more recent LTS.

**Comment by borsboom** [comment] 2017-12-27 14:47
@ruuda Ah, that explains it.  GHC didn't add `-no-pie` support until 8.0.2.

**Comment by borsboom** [comment] 2017-12-30 14:13
I've merged https://github.com/fpco/stackage-content/pull/34, which should fix this for new `stack setup`s, at least for GHC >= 8.0.2 (older GHC versions don't support pie-by-default gcc properly).  Please try `stack setup --reinstall` if you're experiencing these linking errors.

Closing this issue, but if it's not solved for you feel free to re-open.

**Closed by borsboom** 2017-12-30 14:13 UTC
Labels: component: arch-linux

**Comment by borsboom** [comment] 2017-12-30 14:46
I've updated the FAQ entry here: https://github.com/commercialhaskell/stack/pull/3725

**Comment by theolaurent** [comment] 2018-01-06 09:07
Hi guys.
What about GHCJS, which according to https://docs.haskellstack.org/en/stable/ghcjs/ seems to be based at most on 8.0.1 ?
Is there an (even ugly) workaround to make it work ?

**Comment by borsboom** [comment] 2018-01-06 13:56
@theolaurent: It would be very nice to get updated "repacks" of GHCJS that use GHC 8.0.2 or newer (for reasons other than this as well).  That deserves a separate issue.

In terms of workaround for now, see https://docs.haskellstack.org/en/stable/faq/#i-get-strange-ld-errors-about-recompiling-with-fpic.

**Comment by kindaro** [comment] 2018-01-24 15:15
I will leave a **brief report** of my success building things with all four of `ghc-7.10.3` `ghc-8.0.1` `ghc-8.0.2` `ghc-8.2.2` on the same ArchLinux machine.

Perhaps it is redundant, but actually I don't think the FAQ article linked above is comprehensive. Though I do find it insightful, perhaps it might be improved, or otherwise someone may stumble on this issue as I did and find my report helpful.

* The build with `ghc-8.0.2` & `ghc-8.2.2` is straightforward:
  1. [This `haskell-stack-git` package from `aur`](https://aur.archlinux.org/packages/haskell-stack-git) builds like a charm.
  2. As a dependency it lists `ncurses-full` or `ncurses-full-git`. It is indeed necessary to install one of these (at your preference), as it provides shared libraries such as `libtinfo.so` of version 6.

* The build with `ghc-7.10.3` & `ghc-8.0.1` will not succeed. These older compilers will not even get installed with `stack setup`. I advise the following measures:
  1. Prepare `stack.yaml` files that declare an appropriate resolver and, additionally, `ghc-build: standard`.
  2. The older compilers need ncurses 5 rather than 6. So, obtain `ncurses5-compat-libs` from `aur` and `makepkg` it. You will not be able to install the package with `pacman -U` without removing `ncurses-full` or `ncurses-full-git` first, which will render the newer `ghc-8.0.2` & `ghc-8.2.2` compilers unusable. So, you will have to manually extract `usr/lib/libncursesw.so.5.9` and place it at `/usr/lib/libtinfo.so.5`. (There is a system of symlinks to be found in `ncurses5-compat-libs` that maps from one library path to another and then another that I neglected to reconstruct awhole but I guess you may if you wish.) Now you should be able to `stack setup` the older compilers.
  3. After installing the compilers, fix the corresponding `~/.stack/programs/.../lib/.../settings` files, adding `-no-pie` at `C compiler flags`, just as described in the Stack FAQ. At this point your projects should start to compile. Hooray!

The **minimal `stack.yaml` files** for the older compilers:

*ghc-7.10.3*
```
resolver: lts-6.35
ghc-build: standard
```
*ghc-8.0.1*
```
resolver: lts-7.24
ghc-build: standard
```

*I hope this somewhat longish installation is not too out of place here.*

**Comment by fosskers** [comment] 2018-01-25 16:53
During an attempt at compiling a git clone of ghcjs:
```
colin@yumi ~/c/h/ghcjs> stack build
No information found for ghc-8.0.1.
Supported versions for OS key 'linux64-tinfo6-nopie': GhcVersion 8.0.2, GhcVersion 8.2.1, GhcVersion 8.2.2
```
The same thing occurs if following the usual instructions for using GHCjs w/ stack [found here](https://docs.haskellstack.org/en/stable/ghcjs/).
