### ISSUE TITLE
Stack setup fails when %USERPROFILE% contains diacritics

### ISSUE THREAD

**Issue by osoftware** [commercialhaskell/stack#3976] opened 2018-04-18 20:16 UTC
### Steps to reproduce

1. On Windows 10, create a user account that contains a diacritic, in my case it is `Bartłomiej`. 
2. Run `stack new x haskeleton`,  `cd x`.
3. Run `stack setup --verbose`.

### Expected

Command finishes.

### Actual

```
$ stack setup --verbose
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
2018-04-18 22:08:01.286158: [debug] Checking for project config at: C:\x\stack.yaml
@(Stack\Config.hs:842:9)
2018-04-18 22:08:01.290157: [debug] Loading project config file stack.yaml
@(Stack\Config.hs:868:13)
2018-04-18 22:08:01.296155: [debug] Decoding build plan from: C:\sr\build-plan\lts-11.5.yaml
@(Stack\Snapshot.hs:150:5)
2018-04-18 22:08:01.297153: [debug] Trying to decode C:\sr\build-plan-cache\lts-11.5.cache
@(Data\Store\VersionTagged.hs:66:5)
2018-04-18 22:08:01.299578: [debug] Success decoding C:\sr\build-plan-cache\lts-11.5.cache
@(Data\Store\VersionTagged.hs:70:13)
2018-04-18 22:08:01.299578: [debug] Using standard GHC build
@(Stack\Setup.hs:617:9)
2018-04-18 22:08:01.315812: [debug] Performing a sanity check on: C:\Users\Bartłomiej\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc.EXE
@(Stack\Setup.hs:1587:5)
2018-04-18 22:08:01.317820: [debug] Run process: C:\Users\Bartłomiej\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc.EXE C:\Users\Bartłomiej\AppData\Local\Temp\stack-sanity-check3148\Main.hs -no-user-package-db
@(System\Process\Log.hs:37:3)
The GHC located at C:\Users\Bart┼éomiej\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc.EXE failed to compile a sanity check. Please see:

    http://docs.haskellstack.org/en/stable/install_and_upgrade/

for more information. Exception was:
Running C:\Users\Bart┼éomiej\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc.EXE C:\Users\Bart┼éomiej\AppData\Local\Temp\stack-sanity-check3148\Main.hs -no-user-package-db in directory C:\Users\Bart┼éomiej\AppData\Local\Temp\stack-sanity-check3148\ exited with ExitFailure 1

[1 of 1] Compiling Main             ( C:\Users\Bart´┐Żomiej\AppData\Local\Temp\stack-sanity-check3148\Main.hs, C:\Users\Bart´┐Żomiej\AppData\Local\Temp\stack-sanity-check3148\Main.o )
Linking C:\Users\Bart´┐Żomiej\AppData\Local\Temp\stack-sanity-check3148\Main.exe ...

C:\Users\BARTOM~1\AppData\Local\Temp\ghc5296_0\ghc_6.rsp: commitBuffer: invalid argument (invalid character)

```

### Stack version

```
$ stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

### Method of installation

* Official binary, downloaded from stackage.org

**Comment by nh2** [comment] 2018-05-03 16:35
Please close this as a duplicate of #3988, which covers this issue precisely and we are working on it.

**Closed** 2018-05-05 16:43 UTC
