### ISSUE TITLE
stack should have flag for BSD3 or LGPL license

### ISSUE THREAD

**Issue by PierreVDL** [commercialhaskell/stack#2915] opened 2017-01-11 08:38 UTC
A user that wants to compile and link with only packages with BSD3 licenses
has to do the following in his stack.yaml file.

1.  Add 
`ghc-variant: integersimple`
The user has to know than integersimple signal the usage of BSD3, since it is 'just' one BSD3 package that can replace a package with a LGPL license.
2. For each package (like e.g. text) that is NOT using default BSD3 packages:
A.  add
```
 extra-deps:
  - text-1.2.2.1
```
B. Find out the flags to make it BSD3, and set them to the appropriate values
       (in the case of text, the flag is integer-simple (differently written than the ghc-variant ;-) )
```
flags: 
  text: 
     integer-simple: true
```
Note: already for integer-gmp the user might need to configure up to 41 packages (see https://www.stackage.org/package/integer-gmp)

I would like that by just choosing the resolver
(e.g. lts-bsd3-7.15) 
or by adding a single license-flag 
the user gets a BSD3, LGPL, ... build.

**Comment by lwm** [comment] 2017-01-14 01:01
Duplicate of https://github.com/commercialhaskell/stack/issues/577?

**Comment by mgsloan** [comment] 2017-01-31 23:57
Does indeed seem like a dupe of #577, closing.  Thanks for the feedback, though!

**Closed by mgsloan** 2017-01-31 23:57 UTC
