### ISSUE TITLE
stack ghci: missing library

### ISSUE THREAD

**Issue by sid-kap** [commercialhaskell/stack#1700] opened 2016-01-26 03:58 UTC
I am running stack Version 1.0.2, Git revision fa09a980d8bb3df88b2a9193cd9bf84cc6c419b3 (3084 commits) x86_64, on Ubuntu 15.04.

When I run `stack ghci` in my project, I get the following output:

```
Configuring GHCi with the following packages: bindings-hdf5
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
[1 of 4] Compiling Bindings.HDF5.Types ( /home/sidharth/clones/bindings-dsl/bindings-hdf5/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Bindings/HDF5/Types.hs, interpreted )
[2 of 4] Compiling Bindings.HDF5.HighLevelAPI ( /home/sidharth/clones/bindings-dsl/bindings-hdf5/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Bindings/HDF5/HighLevelAPI.hs, interpreted )

ByteCodeLink: can't find label
During interactive linking, GHCi couldn't find the following symbol:
  H5LTpath_valid
This may be due to you not asking GHCi to load extra object files,
archives or DLLs needed by your current session.  Restart GHCi, specifying
the missing library using the -L/path/to/object/dir and -lmissinglibname
flags, or simply by naming the relevant files on the GHCi command line.
Alternatively, this link failure might indicate a bug in GHCi.
If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org


<no location info>:
    Could not find module ‘Bindings.HDF5’
    It is a member of the hidden package ‘bindings-hdf5-0.1.1@bindi_D7RrcSnzrhZ9CrrUR1QvzD’.
Leaving GHCi.
```

This is for the bindings-hdf5 package (https://github.com/jwiegley/bindings-dsl/tree/master/bindings-hdf5). I believe this issue might have something to do with the fact that, on Ubuntu 15.04, the hdf5.h header file (which is included simply as `#include <hdf5.h>`) is not in any of the default include locations (/usr/include), but in a different location (/usr/include/hdf5/serial). `stack build` only worked on this project by either adding the line 

```
pkgconfig-depends: hdf5
```

or

```
include-dirs: /usr/include/hdf5/serial
extra-lib-dirs: /usr/lib/x86_64-linux-gnu/hdf5/serial
```

to the cabal file.

I have tried running `stack ghci -- -I/usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5`, which generated the output:

```
The following errors occurred while parsing the build targets:
- Directory not found: -I/usr/include/hdf5/serial
- Directory not found: -L/usr/lib/x86_64-linux-gnu/hdf5/serial
- Directory not found: -lhdf5
```

Am I approaching this the right way? I think this issue might be similar to #498, but it seems that the fix for #498 is already been merged, so this must be a different problem.

**Comment by mgsloan** [comment] 2016-01-26 05:18
Hi, thanks for the detailed report!  I'm thinking this is likely the same issue as https://github.com/commercialhaskell/stack/issues/970 .  That is, `stack ghci` doesn't use the configuration that results from the custom Setup.hs.  This theory is supported by the presence of a custom configuration: https://github.com/jwiegley/bindings-dsl/blob/master/bindings-hdf5/Setup.hs

Also related is https://github.com/commercialhaskell/stack/issues/1656 , though that's about `extra-lib-dirs` in the stack.yaml file rather than the cabal file.

So, I think this is pretty well tracked by other tickets, except for one point: that the invocation of ghci does not pay attention to `pkgconfig-depends`, `include-dirs`, and `extra-lib-dirs` in the cabal file.  Due to this extra aspect, I'm leaving the ticket open to track it.  Perhaps considering these details is irrelevant if the root cause is resolved (using the configured ghc flags).

**Comment by mgsloan** [comment] 2016-01-28 04:59
A GHC bug which is potentially related: https://ghc.haskell.org/trac/ghc/ticket/11042 Looks like the fix made it into GHC 8

**Comment by RyanGlScott** [comment] 2016-04-25 23:24
This just bit me today. I can't `stack ghci` [this project](https://github.com/iu-parfunc/bindings-hpx/tree/ce4d16c6841a01b5a5e253c297e060ca54cf572a) since it relies on `pkgconfig-depends` to figure out where C dependencies live.

**Comment by mgsloan** [comment] 2016-04-25 23:39
Resolving this issue could be a simple matter of wrapping up that info as ghci options here https://github.com/commercialhaskell/stack/blob/6f7871b893de2792ad9b9a02d934dfa72f8d9090/src/Stack/Package.hs#L308 .  PRs appreciated!

**Comment by mgsloan** [comment] 2017-03-24 04:03
I think this may have been resolved for some time, after https://github.com/commercialhaskell/stack/commit/e11c78c0ceb801db2b2904a693565924417da672

I can't get those examples to build, so can't test with ghci. Please comment / reopen if not

**Closed by mgsloan** 2017-03-24 04:03 UTC
Labels: awaiting pr, component: ghci, type: bug
