### ISSUE TITLE
Changing build options rebuild all dependencies

### ISSUE THREAD

**Issue by maxigit** [commercialhaskell/stack#1415] opened 2015-11-24 10:01 UTC
I'm trying to optimize a program so I do `stack build --executalbe-profiling` and it take forevers, stack rebuild all the dependencies (which is fine, once). If do the just `stack build` (because I forgot the `--executable-profiling` flags) it rebuild again all dependencies . If do again `stack build --executable-profiling` (because I remember to add the flag), it's rebuilding everything again and that takes forever each time ...

I'm surprised by this behavior because I though stack was keeping every build in cache.
(I'm using stack 1.8).

**Comment by borsboom** [comment] 2015-11-25 13:38
I believe this is a duplicate of #1132.

**Closed by borsboom** 2015-11-25 13:38 UTC
Labels: type: enhancement, type: performance
