### ISSUE TITLE
Provide some way to test for `extra-source-files` problems

### ISSUE THREAD

**Issue by seagreen** [commercialhaskell/stack#2120] opened 2016-05-10 20:49 UTC
This has happened before, but I just ran into [an issue again](https://github.com/seagreen/hjsonschema/pull/34) where a line missing from `.cabal`'s `extra-source-files` caused tests to fail once the library was uploaded and then downloaded from Hackage. Because tests passed on my development computer though I didn't notice until after uploading and getting a report from a user.

Would it be a good idea to provide an argument to `stack test` (or perhaps even change `stack test` itself?!) so that the command only sees the view of the filesystem that would exist after Hackage upload & download?

The other option is for me to never use `stack upload .`, instead always using `stack sdist`, untarring the results, and testing them before uploading to Hackage. That seems like work that should be automated though:/

**Comment by mgsloan** [comment] 2016-05-10 23:44
I thoroughly agree, this is a dupe of: https://github.com/commercialhaskell/stack/issues/717

PRs appreciated

**Closed by mgsloan** 2016-05-10 23:44 UTC
