### ISSUE TITLE
Stack breaks randomly after update and rebuilds too much packages

### ISSUE THREAD

**Issue by wdanilo** [commercialhaskell/stack#3227] opened 2017-06-22 10:01 UTC
### General summary
I've updated stack to v 1.4 and different errors started to appear:

First of all, stack throws some random errors while compiling my project. I try to compile it after total cleanup: removing local .stack-work, home stack settings and running stack setup. When running stack build I get random erros like `ghc-pkg: cannot find package case-insensitive`. However, after running it second time I got error about missmatched names in package database. After running it yet another time everything compiled fine. If I clean the project, the situation repeats.

It seems it is somehow connected to another strange behavior I encounter in stack 1.4. If I use local libraries in my stack yaml config file (like `packages: ../libs/somelib`) and I change the lib and the sources contain an error, stack reports me the error. However, after changing the code and running stack build again, stack unregisters every package and builds everything from scratch (currently there are 130 packages so it takes ages after simple code change). 

### Expected

Stack should not throw errors OR these errors should not disappear after re-running compilation and stack should not unregister everything when encountering an error in a library being developed.

### Stack version

Version 1.4.0 x86_64 hpack-0.17.0

### Method of installation

Official binary, Gentoo)

**Comment by wdanilo** [comment] 2017-06-22 11:56
Ok, sorry guys, this issue is incorrect. On  another screen I've been running `stack build --file-watch` and it was interferring with building the project. By the way, it is a bug - if you run 2 stacks on libs that use themselves, they just clash. We should either dont allow running more than one stack or fix it. :)

**Comment by mgsloan** [comment] 2017-08-07 00:44
Thanks for the report!  Duplicate of https://github.com/commercialhaskell/stack/issues/2958

**Closed by mgsloan** 2017-08-07 00:44 UTC
Labels: resolution: duplicate
