### ISSUE TITLE
Can't pass --flag more than once

### ISSUE THREAD

**Issue by nh2** [commercialhaskell/stack#3040] opened 2017-03-03 16:27 UTC
Using stack `1.3.2`, `stack build --help` says

```
  --flag PACKAGE:[-]FLAG   Override flags set in stack.yaml (applies to local
                           packages and extra-deps)
```

but I can't seem to pass `--flag mypackage:myflag1 --flag mypackage:myflag2` because the latter overrides the former instead of adding the two flags.

How do I pass more than one flag on the command line?

**Comment by mgsloan** [comment] 2017-03-06 22:31
I've tried creating a minimal repro of this: [issue3040.zip](https://github.com/commercialhaskell/stack/files/822711/issue3040.zip) , but I can't reproduce the issue:

```
mgsloan@computer:~/fpco/test-stack/issue3040$ stack build --flag issue3040:flag1 --flag issue3040:flag2
...
mgsloan@computer:~/fpco/test-stack/issue3040$ stack exec issue3040-exe
flag1 enabled
flag2 enabled
```

**Comment by mgsloan** [comment] 2017-03-19 00:05
Closing as an old support ticket.

**Closed by mgsloan** 2017-03-19 00:05 UTC
Labels: need repro
