### ISSUE TITLE
`stack upload` should not apply pvp-bounds on self dependencies

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#3413] opened 2017-09-04 07:54 UTC
`stack upload` fails with a cryptic error message when the stack configuration has `pvp-bounds: both`. My package upload failed with the following error message:

```
Uploading monad-recorder-0.1.0.tar.gz... unhandled status code: 400
Error: Invalid package

The package has an extraneous version range for a dependency on an internal library: monad-recorder >=0.1.0 && <0.2. This version range includes the current package but isn't needed as the current package's library will always be used.
Upload failed on monad-recorder-0.1.0.tar.gz
```

This happened because my test-suite depended on `monad-recorder` itself and `pvp-bounds` option applied bounds to this package as well which hackage did not like. 

```
  build-depends:
      base       >= 4.8 && < 5
    , hspec      >= 2.0 && < 3
    , monad-recorder
```
This condition is difficult to debug and therefore stack should avoid applying the bounds on self package itself.

**Comment by borsboom** [comment] 2017-09-04 13:41
Duplicate of #3290

**Closed by borsboom** 2017-09-04 13:41 UTC
