### ISSUE TITLE
Stack 0.1.5 Re-registers packages

### ISSUE THREAD

**Issue by NightRa** [commercialhaskell/stack#1073] opened 2015-09-28 13:34 UTC
Stack 0.1.5.0 seems to try to do duplicate builds when building stack master 06a4b270de2d2dcbd3ee8abe98078151c4a8f075: (Stack just switched from LTS 3.0 to LTS 3.7)
```
Running D:\Users\NightRa\AppData\Local\Programs\stack\i386-windows\ghc-7.10.2\bin\ghc-pkg.exe register --no-user-package-db --package-db=D:\Users\NightRa\AppData\Roaming\stack\snapshots\i386-windows\lts-3.7\7.10.2\pkgdb\ --force D:\Users\NightRa\AppData\Roaming\stack\snapshots\i386-windows\nightly-2015-09-20\7.10.2\pkgdb\word8-0.1.2-d97021102fda7d999fe668184e4efb39.conf exited with ExitFailure 1
Reading package info from "D:\\Users\\NightRa\\AppData\\Roaming\\stack\\snapshots\\i386-windows\\nightly-2015-09-20\\7.10.2\\pkgdb\\word8-0.1.2-d97021102fda7d999fe668184e4efb39.conf" ... done.
word8-0.1.2: Warning: haddock-interfaces: D:\Users\NightRa\AppData\Roaming\stack\snapshots\i386-windows\nightly-2015-09-20\7.10.2\doc\word8-0.1.2\word8.haddock doesn't exist or isn't a file
word8-0.1.2: package(s) with this id already exist: word8-0.1.2
word8-0.1.2: package word8-0.1.2 is already installed
word8-0.1.2: Package names may be treated case-insensitively in the future.
Package word8-0.1.2 overlaps with: word8-0.1.2 (ignoring)
```
```
Running D:\Users\NightRa\AppData\Local\Programs\stack\i386-windows\ghc-7.10.2\bin\ghc-pkg.exe register --no-user-package-db --package-db=D:\Users\NightRa\AppData\Roaming\stack\snapshots\i386-windows\lts-3.7\7.10.2\pkgdb\ --force D:\Users\NightRa\AppData\Roaming\stack\snapshots\i386-windows\lts-3.7\7.10.2\pkgdb\connection-0.2.5-afc332f0539e3961ae62a5ad89eb29e6.conf exited with ExitFailure 1
Reading package info from "D:\\Users\\NightRa\\AppData\\Roaming\\stack\\snapshots\\i386-windows\\lts-3.7\\7.10.2\\pkgdb\\connection-0.2.5-afc332f0539e3961ae62a5ad89eb29e6.conf" ... done.
connection-0.2.5: Warning: haddock-interfaces: D:\Users\NightRa\AppData\Roaming\stack\snapshots\i386-windows\lts-3.7\7.10.2\doc\connection-0.2.5\connection.haddock doesn't exist or isn't a file
connection-0.2.5: package(s) with this id already exist: connection-0.2.5
connection-0.2.5: package connection-0.2.5 is already installed
connection-0.2.5: Package names may be treated case-insensitively in the future.
Package connection-0.2.5 overlaps with: connection-0.2.5 (ignoring)
```

**Comment by snoyberg** [comment] 2015-09-28 18:27
Check the change log, I think this is a Windows fix for long file paths
showing through.

**Comment by NightRa** [comment] 2015-09-28 18:29
@snoyberg Ah, makes sense.
One think we should do then is towards the next version, warn explicitly that .stack needs to be cleaned.

**Comment by snoyberg** [comment] 2015-09-28 18:36
We'll include something in the release notes. Technically, such cleaning
isn't necessary, the old files will just be ignored.

**Comment by NightRa** [comment] 2015-09-28 18:37
When this error occurs (not for each package, not sure when exactly), stack stops the build proccess.

**Comment by snoyberg** [comment] 2015-09-28 18:40
I don't see information on that in the original report, can you clarify?

**Comment by NightRa** [comment] 2015-09-28 20:34
These errors occured while installing the dependencies for building. 
When such an error occurs, it spits out this message and stops immediately, in the middle of the build proccess of fetching and installing dependencies.

**Comment by snoyberg** [comment] 2015-09-29 04:53
Relevant PR: #1027 

@anton-dessiatov any thoughts on this report?

**Comment by anton-dessiatov** [comment] 2015-09-29 07:36
I would doubt that this issue is related to my PR because of two reasons:

1. Stack-0.1.5.0 was released prior to merging PR #1027, and if I got it right, this issue showed up when running released 0.1.5.0 version, not the 'master' one (which was about to be built).
2. My PR only changed paths to every package's build artifacts directories (.stack-work/dist/<whatever>) and it looks like this issue is related to inconsistencies between actual package database contents and what stack expected to have there.

Looks like we need a reproducible test case. I would think that it's more likely related to changing LTS snapshot.

**Comment by snoyberg** [comment] 2015-09-29 07:40
I think you're right, I had read the issue as using stack master, but it
does look like it's using stack 0.1.5.0

**Comment by snoyberg** [comment] 2015-09-30 06:56
I'm unable to reproduce the problem on my Windows machine. Are you able to reproduce the problem still? Can you provide more information on what exactly you were doing on the system at the time? From what I can see, the most likely reason for this would have been two `stack build`s running at the same time.

Full logs would also be useful, I think Stack was doing a precompiled package copy when this occurred, but I'm not certain.

**Comment by snoyberg** [comment] 2015-10-09 05:29
Closing due to lack of repro or additional logs.

**Closed by snoyberg** 2015-10-09 05:29 UTC
Labels: component: windows, need repro
