### ISSUE TITLE
Simplifier ticks exhausted when building with profiling on M1

### ISSUE THREAD

**Issue by ttylec** [commercialhaskell/stack#5657] opened 2021-12-22 10:05 UTC
### General summary/comments (optional)

Using stack to building `shake` with profiling enabled on apple silicon I got 

```
[...]
shake               > Simplifier ticks exhausted
shake               >   When trying UnfoldingDone $s#_s2kWs
shake               >   To increase the limit, use -fsimpl-tick-factor=N (default 100).
[...]
```

Plain cabal build with profiling works.

Discovered when trying to build haskell-language-server with profiling.

### Steps to reproduce

```
stack --resolver lts-18.18 build shake --profile
```

### Expected

Shake is build with profiling.

### Actual

```
$  stack --resolver lts-18.18 build shake --profile
[...]
shake               > [19 of 73] Compiling Development.Shake.Internal.Value
shake               > [20 of 73] Compiling Development.Shake.Internal.FilePattern
shake               > Simplifier ticks exhausted
shake               >   When trying UnfoldingDone $s#_s2kWs
shake               >   To increase the limit, use -fsimpl-tick-factor=N (default 100).
shake               >
shake               >   If you need to increase the limit substantially, please file a
shake               >   bug report and indicate the factor you needed.
shake               >
shake               >   If GHC was unable to complete compilation even with a very large factor
shake               >   (a thousand or more), please consult the "Known bugs or infelicities"
shake               >   section in the Users Guide before filing a report. There are a
shake               >   few situations unlikely to occur in practical programs for which
shake               >   simplifier non-termination has been judged acceptable.
shake               >
shake               >   To see detailed counts use -ddump-simpl-stats
shake               >   Total ticks: 171006
```

### Stack version

```
$ stack --version
Version 2.7.3, Git revision c2402f3d559e29a1d671ac82e09692ecfca3e467 (dirty) (78 commits) aarch64
```

### Method of installation

ghcup

**Comment by ttylec** [comment] 2021-12-22 10:36
After reading https://github.com/commercialhaskell/stack/issues/4840#issuecomment-504714906 I am not sure anymore that this is a bug, or bug in stack at least, but don't know how/where to classify that.

**Comment by mpilgrem** [comment] 2024-03-28 20:18
I am going to close this issue given the passage of time and because I could not reproduce it on a Mac mini/M1 with Stack 2.13.1 and:
~~~zsh
stack --snapshot lts-22.14 build shake --profile
~~~

**Closed by mpilgrem** 2024-03-28 20:18 UTC
