### ISSUE TITLE
`stack test` doesn't install data files

### ISSUE THREAD

**Issue by mtolly** [commercialhaskell/stack#548] opened 2015-07-08 20:25 UTC
Running `stack test` doesn't copy the package's data files to the install directory, so the paths returned by `getDataFileName` don't exist. Running `stack build` beforehand does copy the data files.

**Steps to reproduce:**

`demo.cabal`:

```
name:                 demo
version:              0.1.0.0
build-type:           Simple
cabal-version:        >=1.10
data-files:           data.txt

library
  default-language:     Haskell2010

test-suite demo-test
  type:                 exitcode-stdio-1.0
  main-is:              Main.hs
  other-modules:        Paths_demo
  build-depends:        base
  default-language:     Haskell2010
```

`stack.yaml`:

```yaml
flags: {}
packages:
- '.'
extra-deps: []
resolver: lts-2.17
```

`Main.hs`:

```hs
module Main where

import Paths_demo

main :: IO ()
main = getDataFileName "data.txt" >>= readFile >>= putStr
```

`data.txt`:

```
This is a data file.
```

**Expected:**

Running the test prints out the contents of the data file.

**Actual:**

Starting from a clean directory (no `.stack-work`):

```
$ stack --version
Version 0.1.2.0, Git revision 0a44a92ff39f05882f4bfb4bd74381e0599fcd8b

$ stack test
demo-0.1.0.0: configure (test)
Configuring demo-0.1.0.0...
demo-0.1.0.0: build (test)
Preprocessing test suite 'demo-test' for demo-0.1.0.0...
[1 of 2] Compiling Paths_demo       ( .stack-work/dist/x86_64-osx/Cabal-1.18.1.5/build/autogen/Paths_demo.hs, .stack-work/dist/x86_64-osx/Cabal-1.18.1.5/build/demo-test/demo-test-tmp/Paths_demo.o )
[2 of 2] Compiling Main             ( Main.hs, .stack-work/dist/x86_64-osx/Cabal-1.18.1.5/build/demo-test/demo-test-tmp/Main.o )
Linking .stack-work/dist/x86_64-osx/Cabal-1.18.1.5/build/demo-test/demo-test ...
demo-0.1.0.0: test (suite: demo-test)
demo-test: /Users/mtolly/git/demo/.stack-work/install/x86_64-osx/lts-2.17/7.8.4/share/x86_64-osx-ghc-7.8.4/demo-0.1.0.0/data.txt: openFile: does not exist (No such file or directory)
Test suite failure for package demo-0.1.0.0
    demo-test:  exited with: ExitFailure 1
Logs printed to console

$ stack build
demo-0.1.0.0: configure
Configuring demo-0.1.0.0...
demo-0.1.0.0: build
Building demo-0.1.0.0...
Preprocessing library demo-0.1.0.0...
In-place registering demo-0.1.0.0...
demo-0.1.0.0: install
Installing library in
/Users/mtolly/git/demo/.stack-work/install/x86_64-osx/lts-2.17/7.8.4/lib/x86_64-osx-ghc-7.8.4/demo-0.1.0.0
Registering demo-0.1.0.0...

$ stack test
demo-0.1.0.0: configure (test)
Configuring demo-0.1.0.0...
demo-0.1.0.0: build (test)
Preprocessing test suite 'demo-test' for demo-0.1.0.0...
demo-0.1.0.0: test (suite: demo-test)
This is a data file.
```

[Here are verbose versions](http://pastebin.com/XPthLa8G) of the commands.

**Comment by snoyberg** [comment] 2015-07-09 15:17
This is unfortunately the way that Cabal works. One possibility to work around this would be to perform a `runghc Setup.hs install` before running the test suites, though that has the very real potential of corrupting the package database and forcing lots of recompilation in the next step. I'm afraid that this may simply be a "broken by design" aspect of the Cabal build system that we can't work around.

**Comment by snoyberg** [comment] 2015-07-13 02:19
I'm going to close as wontfix. We currently don't do things that inherently contradict the way the Cabal build system itself works. I'd recommend considering other ways of dealing with data files during tests, possibly even moving over to something like [file-embed](https://www.stackage.org/package/file-embed).

**Closed by snoyberg** 2015-07-13 02:19 UTC

**Comment by johntyree** [comment] 2015-07-14 02:57
It seems really strange to take a "wont fix" position on this given stack's normal behavior of "do whatever tedious prerequisites are necessary then do what I want."

I just spent 45 minutes trying to figure out why "stack test" does everything except this... which makes all my tests fail. I doubt I'll be the last.

Specifically, if `stack build` works, I don't understand why we wouldn't automatically just run that before running `stack test` if there are data-files and the test-suite depends on `Paths_pkgnm`, or even just all the time.

**Comment by snoyberg** [comment] 2015-07-14 03:05
The problem is that we can actually break other things by implementing
this, not to mention slowing things dramatically in general. To get the
behavior you're describing, we'd have to do cabal copy before test, which
has the potential to copy over a broken executable, or install data files
that are incompatible with the version of the library already registered.

We could improve this in theory by setting the data directory to something
completely different during test configures than normal configures, but
this will involve having to recompile lots of modules every time we switch
between test and build, which due to the stateful nature of cabal actually
happens a lot.

The point is: there's no solution I see here that doesn't make someone
miserable. I think the current trade off makes the fewest people miserable.
I'm not saying it's good, I'm saying it's the best I can think of.

And I really do recommend avoiding data files whenever possible, especially
in test suites.

**Comment by johntyree** [comment] 2015-07-14 06:23
What is your alternative to using `data-files` for most use cases? In my case, it's text data and could be easily stuffed as a value into a Data module or something similar, but what about images? Game files? Music?

**Comment by mtolly** [comment] 2015-07-14 15:31
I assume @snoyberg recommends his [`file-embed`](https://www.stackage.org/package/file-embed) package, which is indeed very nice. Lets you embed any binary file directly into the executable, exposed to your code as a bytestring. Unfortunately, I am sometimes unable to use Template Haskell, for example due to [this bug](https://github.com/haskell-game/sdl2/issues/41) which breaks GHCi and Template Haskell when linking in SDL2 on Windows.

Another option is to use a package like [`FindBin`](http://hackage.haskell.org/package/FindBin) to locate the executable at runtime and then just put assets in a folder next to that.

**Comment by snoyberg** [comment] 2015-07-14 17:47
I haven't had to distribute game files/music files with a cabal package in the past, but even ignoring this issue, I wouldn't use `data-files`, since I wouldn't want the binary assets shipped with the source code (at least not in the tarball). When I've needed things like this in the past, I've always downloaded the data separate from the executable. Also, if we're really talking about building a game in Haskell, you don't want Cabal to be in charge of installing your files, you'll have a real package installer.

There are other non-TH approaches, such as using a code preprocessor to turn generate a file with string literals containing the data files.
