### ISSUE TITLE
stack.exe crashes / segfaults on windows 7, 32-bit

### ISSUE THREAD

**Issue by nehaljwani** [commercialhaskell/stack#4280] opened 2018-09-02 13:35 UTC
### Steps to reproduce

Download stack from https://get.haskellstack.org/stable/windows-i386.zip, unzip it, run stack.exe --help or stack.exe --version

### Expected

No crash/segmentation fault

### Actual

Segmentation Fault after output.

```
$ ./stack.exe --help
...
Segmentation fault
```

### Stack version

```
$ ./stack.exe --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) i386 hpack-0.28.2
Segmentation fault
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by nehaljwani** [comment] 2018-09-02 13:40
The v1.6.5 version doesn't suffer from this problem.

**Comment by nehaljwani** [comment] 2018-09-02 14:00
Could be related to https://ghc.haskell.org/trac/ghc/ticket/15154#no1

**Comment by mihaimaruseac** [comment] 2018-09-03 19:48
Unfortunately, I don't have access to a Windows box to reproduce, but this should be easily solvable by bisecting between the two versions.

**Comment by nehaljwani** [comment] 2018-09-03 20:34
@mihaimaruseac Would you have the information regarding which version of ghc was used to build 1.6.5 windows 32 bit version of stack (which has been released as a binary)?

**Comment by mihaimaruseac** [comment] 2018-09-05 03:39
I don't :( Maybe @borsboom

**Comment by snoyberg** [comment] 2019-04-14 05:00
Questions:

1. Does this also occur with Stack 1.9.3?
2. Can you include the `--verbose` output?

It seems most likely that this is an upstream issue and that we'll be unable to resolve this.

**Comment by nehaljwani** [comment] 2019-04-14 05:28
I opened the ticket here after starting from https://github.com/jgm/pandoc/issues/4283 . It is no longer an issue for me. The bug has probably been fixed upstream.

**Comment by qlobafftar** [comment] 2019-04-15 05:14
stack.exe ver. 1.9.3 for i386 still crashes under win32 and win64. --verbose flag doesn't give any information.

Output:
c:\User\Programs\stack>stack.exe --verbose
Missing: COMMAND|FILE

Usage: stack.exe [--help] [--version] [--numeric-version]
                 [--hpack-numeric-version] [--docker*] [--nix*]
                 ([--verbosity VERBOSITY] | [-v|--verbose] | [--silent])
                 [--[no-]time-in-log] [--stack-root STACK-ROOT]
                 [--work-dir WORK-DIR] [--[no-]system-ghc] [--[no-]install-ghc]
                 [--arch ARCH] [--ghc-variant VARIANT] [--ghc-build BUILD]
                 [-j|--jobs JOBS] [--extra-include-dirs DIR]
                 [--extra-lib-dirs DIR] [--with-gcc PATH-TO-GCC]
                 [--with-hpack HPACK] [--[no-]skip-ghc-check] [--[no-]skip-msys]

                 [--local-bin-path DIR] [--[no-]modify-code-page]
                 [--[no-]allow-different-user] [--[no-]dump-logs]
                 [--resolver RESOLVER] [--compiler COMPILER] [--[no-]terminal]
                 [--color WHEN] [--terminal-width INT] [--stack-yaml STACK-YAML]

                 COMMAND|FILE

c:\User\Programs\stack>stack.exe
stack - The Haskell Tool Stack

Usage: stack.exe [--help] [--version] [--numeric-version]
                 [--hpack-numeric-version] [--docker*] [--nix*]
                 ([--verbosity VERBOSITY] | [-v|--verbose] | [--silent])
                 [--[no-]time-in-log] [--stack-root STACK-ROOT]
                 [--work-dir WORK-DIR] [--[no-]system-ghc] [--[no-]install-ghc]
                 [--arch ARCH] [--ghc-variant VARIANT] [--ghc-build BUILD]
                 [-j|--jobs JOBS] [--extra-include-dirs DIR]
                 [--extra-lib-dirs DIR] [--with-gcc PATH-TO-GCC]
                 [--with-hpack HPACK] [--[no-]skip-ghc-check] [--[no-]skip-msys]

                 [--local-bin-path DIR] [--[no-]modify-code-page]
                 [--[no-]allow-different-user] [--[no-]dump-logs]
                 [--resolver RESOLVER] [--compiler COMPILER] [--[no-]terminal]
                 [--color WHEN] [--terminal-width INT] [--stack-yaml STACK-YAML]

                 COMMAND|FILE

Available options:
  --help                   Show this help text
  --version                Show version
  --numeric-version        Show only version number
  --hpack-numeric-version  Show only hpack's version number
  --docker*                Run 'stack --docker-help' for details
  --nix*                   Run 'stack --nix-help' for details
  --verbosity VERBOSITY    Verbosity: silent, error, warn, info, debug
  -v,--verbose             Enable verbose mode: verbosity level "debug"
  --silent                 Enable silent mode: verbosity level "silent"
  --[no-]time-in-log       Enable/disable inclusion of timings in logs, for the
                           purposes of using diff with logs
  --stack-root STACK-ROOT  Absolute path to the global stack root directory
                           (Overrides any STACK_ROOT environment variable)
  --work-dir WORK-DIR      Relative path of work directory (Overrides any
                           STACK_WORK environment variable, default is
                           '.stack-work')
  --[no-]system-ghc        Enable/disable using the system installed GHC (on the

                           PATH) if it is available and its version matches.
                           Disabled by default.
  --[no-]install-ghc       Enable/disable downloading and installing GHC if
                           necessary (can be done manually with stack setup)
  --arch ARCH              System architecture, e.g. i386, x86_64
  --ghc-variant VARIANT    Specialized GHC variant, e.g. integersimple
                           (incompatible with --system-ghc)
  --ghc-build BUILD        Specialized GHC build, e.g. 'gmp4' or 'standard'
                           (usually auto-detected)
  -j,--jobs JOBS           Number of concurrent jobs to run
  --extra-include-dirs DIR Extra directories to check for C header files
  --extra-lib-dirs DIR     Extra directories to check for libraries
  --with-gcc PATH-TO-GCC   Use gcc found at PATH-TO-GCC
  --with-hpack HPACK       Use HPACK executable (overrides bundled Hpack)
  --[no-]skip-ghc-check    Enable/disable skipping the GHC version and
                           architecture check
  --[no-]skip-msys         Enable/disable skipping the local MSYS installation
                           (Windows only)
  --local-bin-path DIR     Install binaries to DIR
  --[no-]modify-code-page  Enable/disable setting the codepage to support UTF-8
                           (Windows only)
  --[no-]allow-different-user
                           Enable/disable permission for users other than the
                           owner of the stack root directory to use a stack
                           installation (POSIX only)
  --[no-]dump-logs         Enable/disable dump the build output logs for local
                           packages to the console
  --resolver RESOLVER      Override resolver in project file
  --compiler COMPILER      Use the specified compiler
  --[no-]terminal          Enable/disable overriding terminal detection in the
                           case of running in a false terminal
  --color WHEN             Specify when to use color in output; WHEN is
                           'always', 'never', or 'auto'. On Windows versions
                           before Windows 10, for terminals that do not support
                           color codes, the default is 'never'; color may work
                           on terminals that support color codes
  --terminal-width INT     Specify the width of the terminal, used for
                           pretty-print messages
  --stack-yaml STACK-YAML  Override project stack.yaml file (overrides any
                           STACK_YAML environment variable)

Available commands:
  build                    Build the package(s) in this directory/configuration
  install                  Shortcut for 'build --copy-bins'
  uninstall                DEPRECATED: This command performs no actions, and is
                           present for documentation only
  test                     Shortcut for 'build --test'
  bench                    Shortcut for 'build --bench'
  haddock                  Shortcut for 'build --haddock'
  new                      Create a new project from a template. Run `stack
                           templates' to see available templates. Note: you can
                           also specify a local file or a remote URL as a
                           template.
  templates                List the templates available for `stack new'.
                           Templates are drawn from
                           https://github.com/commercialhaskell/stack-templates
                           Note: `stack new' can also accept a template from a
                           local file or a remote URL.
  init                     Create stack project config from cabal or hpack
                           package specifications
  solver                   Add missing extra-deps to stack project config
  setup                    Get the appropriate GHC for your project
  path                     Print out handy path information
  ls                       List command. (Supports snapshots and dependencies)
  unpack                   Unpack one or more packages locally
  update                   Update the package index
  upgrade                  Upgrade to the latest stack
  upload                   Upload a package to Hackage
  sdist                    Create source distribution tarballs
  dot                      Visualize your project's dependency graph using
                           Graphviz dot
  ghc                      Run ghc
  hoogle                   Run hoogle, the Haskell API search engine. Use 'stack

                           exec' syntax to pass Hoogle arguments, e.g. stack
                           hoogle -- --count=20
  exec                     Execute a command
  run                      Build and run an executable. Defaults to the first
                           available executable if none is provided as the first

                           argument.
  ghci                     Run ghci in the context of package(s) (experimental)
  repl                     Run ghci in the context of package(s) (experimental)
                           (alias for 'ghci')
  runghc                   Run runghc
  runhaskell               Run runghc (alias for 'runghc')
  script                   Run a Stack Script
  eval                     Evaluate some haskell code inline. Shortcut for
                           'stack exec ghc -- -e CODE'
  clean                    Clean the local packages
  list-dependencies        List the dependencies
  query                    Query general build information (experimental)
  ide                      IDE-specific commands
  docker                   Subcommands specific to Docker use
  config                   Subcommands specific to modifying stack.yaml files
  image                    Subcommands specific to imaging
  hpc                      Subcommands specific to Haskell Program Coverage

stack's documentation is available at https://docs.haskellstack.org/

with --verbose flag it crashes earlier

**Comment by nehaljwani** [comment] 2019-04-15 05:23
Re-opening, as the issue still persists. Could anyone please confirm the version of GHC that stack 1.9.3  was compiled with?

**Comment by snoyberg** [comment] 2019-04-15 06:15
Stack 1.9.3 is built with GHC 8.2.2. However, I don't see a crash in the output you've provided above.

**Comment by qlobafftar** [comment] 2019-04-15 16:05
There is no crash message in windows console.
"stack.exe --verbose" crashes before printing "Available options"
"stack.exe" crashes before program returns.
here is an output from stack upgrade from 1.6.5 to 1.9.3:
`D:\prog\haskell\purescript>stack upgrade
Current Stack version: 1.6.5, available download version: 1.9.3
Newer version detected, downloading
Querying for archive location for platform: windows-i386-static
Querying for archive location for platform: windows-i386
Downloading from: https://github.com/commercialhaskell/stack/releases/download/v
1.9.3/stack-1.9.3-windows-i386.tar.gz
Download complete, testing executable
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commi
ts) i386 hpack-0.31.1

Warning: Exception occured when trying to perform binary upgrade:
         Control.Exception.Safe.throwString called with:

Non-success exit code from running newly downloaded executable
Called from:
  throwString (src/Stack\Upgrade.hs:179:23 in stack-1.6.5-2pDIODVZj6MKnO4gyxOhTV
:Stack.Upgrade)


         Falling back to source upgrade
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpc

Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpc

Downloading timestamp
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpc

Downloading snapshot
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpc

Updating index
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpc

Updated package index downloaded
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpc

Update complete
Populated index cache.
stack-1.9.3: download
auto-update-0.1.4: configure
base-compat-0.9.3: download
annotated-wl-pprint-0.7.0: download
Win32-notify-0.3.0.3: download
annotated-wl-pprint-0.7.0: configure
Win32-notify-0.3.0.3: configure
base-compat-0.9.3: configure
Progress: 4/173
--  While building custom Setup.hs for package base-compat-0.9.3 using:
      C:\sr\setup-exe-cache\i386-windows\Cabal-simple_Z6RU0evB_2.0.1.0_ghc-8.2.2
.exe --builddir=.stack-work\dist\010ee936 configure --with-ghc=C:\Users\user\App
Data\Local\Programs\stack\i386-windows\ghc-8.2.2\bin\ghc.EXE --with-ghc-pkg=C:\U
sers\user\AppData\Local\Programs\stack\i386-windows\ghc-8.2.2\bin\ghc-pkg.EXE --
user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\cd3007d
2\pkgdb --libdir=C:\sr\snapshots\cd3007d2\lib --bindir=C:\sr\snapshots\cd3007d2\
bin --datadir=C:\sr\snapshots\cd3007d2\share --libexecdir=C:\sr\snapshots\cd3007
d2\libexec --sysconfdir=C:\sr\snapshots\cd3007d2\etc --docdir=C:\sr\snapshots\cd
3007d2\doc\base-compat-0.9.3 --htmldir=C:\sr\snapshots\cd3007d2\doc\base-compat-
0.9.3 --haddockdir=C:\sr\snapshots\cd3007d2\doc\base-compat-0.9.3 --dependency=b
ase=base-4.10.1.0 --extra-include-dirs=C:\Users\user\AppData\Local\Programs\stac
k\i386-windows\msys2-20180531\mingw32\include --extra-lib-dirs=C:\Users\user\App
Data\Local\Programs\stack\i386-windows\msys2-20180531\mingw32\bin --extra-lib-di
rs=C:\Users\user\AppData\Local\Programs\stack\i386-windows\msys2-20180531\mingw3
2\lib
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Windows\Temp\stack-upgrade5344\stack-1.9.3\.st
ack-work\logs\base-compat-0.9.3.log

    Configuring base-compat-0.9.3...
    Cabal-simple_Z6RU0evB_2.0.1.0_ghc-8.2.2.exe: The program 'ghc-pkg' is requir
ed
    but the version of
    C:\Users\user\AppData\Local\Programs\stack\i386-windows\ghc-8.2.2\bin\ghc-pk
g.EXE
    could not be determined.


--  While building custom Setup.hs for package Win32-notify-0.3.0.3 using:
      C:\sr\setup-exe-cache\i386-windows\Cabal-simple_Z6RU0evB_2.0.1.0_ghc-8.2.2
.exe --builddir=.stack-work\dist\010ee936 configure --with-ghc=C:\Users\user\App
Data\Local\Programs\stack\i386-windows\ghc-8.2.2\bin\ghc.EXE --with-ghc-pkg=C:\U
sers\user\AppData\Local\Programs\stack\i386-windows\ghc-8.2.2\bin\ghc-pkg.EXE --
user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\cd3007d
2\pkgdb --libdir=C:\sr\snapshots\cd3007d2\lib --bindir=C:\sr\snapshots\cd3007d2\
bin --datadir=C:\sr\snapshots\cd3007d2\share --libexecdir=C:\sr\snapshots\cd3007
d2\libexec --sysconfdir=C:\sr\snapshots\cd3007d2\etc --docdir=C:\sr\snapshots\cd
3007d2\doc\Win32-notify-0.3.0.3 --htmldir=C:\sr\snapshots\cd3007d2\doc\Win32-not
ify-0.3.0.3 --haddockdir=C:\sr\snapshots\cd3007d2\doc\Win32-notify-0.3.0.3 --dep
endency=Win32=Win32-2.5.4.1 --dependency=base=base-4.10.1.0 --dependency=contain
ers=containers-0.5.10.2 --dependency=directory=directory-1.3.0.2 --extra-include
-dirs=C:\Users\user\AppData\Local\Programs\stack\i386-windows\msys2-20180531\min
gw32\include --extra-lib-dirs=C:\Users\user\AppData\Local\Programs\stack\i386-wi
ndows\msys2-20180531\mingw32\bin --extra-lib-dirs=C:\Users\user\AppData\Local\Pr
ograms\stack\i386-windows\msys2-20180531\mingw32\lib
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Windows\Temp\stack-upgrade5344\stack-1.9.3\.st
ack-work\logs\Win32-notify-0.3.0.3.log

    Configuring Win32-notify-0.3.0.3...
    Cabal-simple_Z6RU0evB_2.0.1.0_ghc-8.2.2.exe: The program 'ghc-pkg' is requir
ed
    but the version of
    C:\Users\user\AppData\Local\Programs\stack\i386-windows\ghc-8.2.2\bin\ghc-pk
g.EXE
    could not be determined.


--  While building custom Setup.hs for package annotated-wl-pprint-0.7.0 using:
      C:\sr\setup-exe-cache\i386-windows\Cabal-simple_Z6RU0evB_2.0.1.0_ghc-8.2.2
.exe --builddir=.stack-work\dist\010ee936 configure --with-ghc=C:\Users\user\App
Data\Local\Programs\stack\i386-windows\ghc-8.2.2\bin\ghc.EXE --with-ghc-pkg=C:\U
sers\user\AppData\Local\Programs\stack\i386-windows\ghc-8.2.2\bin\ghc-pkg.EXE --
user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\cd3007d
2\pkgdb --libdir=C:\sr\snapshots\cd3007d2\lib --bindir=C:\sr\snapshots\cd3007d2\
bin --datadir=C:\sr\snapshots\cd3007d2\share --libexecdir=C:\sr\snapshots\cd3007
d2\libexec --sysconfdir=C:\sr\snapshots\cd3007d2\etc --docdir=C:\sr\snapshots\cd
3007d2\doc\annotated-wl-pprint-0.7.0 --htmldir=C:\sr\snapshots\cd3007d2\doc\anno
tated-wl-pprint-0.7.0 --haddockdir=C:\sr\snapshots\cd3007d2\doc\annotated-wl-ppr
int-0.7.0 --dependency=base=base-4.10.1.0 --extra-include-dirs=C:\Users\user\App
Data\Local\Programs\stack\i386-windows\msys2-20180531\mingw32\include --extra-li
b-dirs=C:\Users\user\AppData\Local\Programs\stack\i386-windows\msys2-20180531\mi
ngw32\bin --extra-lib-dirs=C:\Users\user\AppData\Local\Programs\stack\i386-windo
ws\msys2-20180531\mingw32\lib
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Windows\Temp\stack-upgrade5344\stack-1.9.3\.st
ack-work\logs\annotated-wl-pprint-0.7.0.log

    Configuring annotated-wl-pprint-0.7.0...
    Cabal-simple_Z6RU0evB_2.0.1.0_ghc-8.2.2.exe: The program 'ghc-pkg' is requir
ed
    but the version of
    C:\Users\user\AppData\Local\Programs\stack\i386-windows\ghc-8.2.2\bin\ghc-pk
g.EXE
    could not be determined.


--  While building custom Setup.hs for package auto-update-0.1.4 using:
      C:\sr\setup-exe-cache\i386-windows\Cabal-simple_Z6RU0evB_2.0.1.0_ghc-8.2.2
.exe --builddir=.stack-work\dist\010ee936 configure --with-ghc=C:\Users\user\App
Data\Local\Programs\stack\i386-windows\ghc-8.2.2\bin\ghc.EXE --with-ghc-pkg=C:\U
sers\user\AppData\Local\Programs\stack\i386-windows\ghc-8.2.2\bin\ghc-pkg.EXE --
user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\cd3007d
2\pkgdb --libdir=C:\sr\snapshots\cd3007d2\lib --bindir=C:\sr\snapshots\cd3007d2\
bin --datadir=C:\sr\snapshots\cd3007d2\share --libexecdir=C:\sr\snapshots\cd3007
d2\libexec --sysconfdir=C:\sr\snapshots\cd3007d2\etc --docdir=C:\sr\snapshots\cd
3007d2\doc\auto-update-0.1.4 --htmldir=C:\sr\snapshots\cd3007d2\doc\auto-update-
0.1.4 --haddockdir=C:\sr\snapshots\cd3007d2\doc\auto-update-0.1.4 --dependency=b
ase=base-4.10.1.0 --extra-include-dirs=C:\Users\user\AppData\Local\Programs\stac
k\i386-windows\msys2-20180531\mingw32\include --extra-lib-dirs=C:\Users\user\App
Data\Local\Programs\stack\i386-windows\msys2-20180531\mingw32\bin --extra-lib-di
rs=C:\Users\user\AppData\Local\Programs\stack\i386-windows\msys2-20180531\mingw3
2\lib
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Windows\Temp\stack-upgrade5344\stack-1.9.3\.st
ack-work\logs\auto-update-0.1.4.log

    Configuring auto-update-0.1.4...
    Cabal-simple_Z6RU0evB_2.0.1.0_ghc-8.2.2.exe: The program 'ghc-pkg' is requir
ed
    but the version of
    C:\Users\user\AppData\Local\Programs\stack\i386-windows\ghc-8.2.2\bin\ghc-pk
g.EXE
    could not be determined.`

**Comment by snoyberg** [comment] 2019-04-15 17:16
Again, I want to warn in advance: we may not be able to resolve this issue and may have to close it. That said, some further questions:

* Does this occur on 64-bit versions of Windows 7?
* Does this occur on Windows 10?
* Are you able to use a 32-bit version of Stack on a 64-bit version of Windows successfully?

**Comment by qlobafftar** [comment] 2019-04-15 17:56
The problem occurs on Windows 7 64 bit and Windows 7 32 bit when I use 32-bit version of Stack downloaded from Releases page and unpacked or installed (.zip, .tar.gz or installer.exe files). 
Stack 1.6.5 32bit is the last working version on Win 7.
 I also checked version 1.9.3 on Windows 10 64bit: there is no crashes with 32bit and 64bit versions.

**Comment by snoyberg** [comment] 2019-04-16 03:32
Neither I nor, to my knowledge, any other Stack contributor has access to a Windows 7 machine. Windows 7 ended mainstream support from Microsoft on January 13, 2015, and will finish extended support in less than a year. If you're able to isolate where this problem is coming from, I'd consider a patch. But outside of that, I believe we're going to have to close as wontfix.

Also, the output above is pretty jumbled, but it looks like the error message is coming from `ghc-pkg.exe`.

Finally: the `stack --verbose` output above identically matches what occurs on my OS X machine. `--verbose` does not list commands. `--verbose` is a modifier to other valid commands.

**Comment by snoyberg** [comment] 2019-04-18 07:15
Closing, as we are not in a position to support Windows 7 anymore.

**Closed by snoyberg** 2019-04-18 07:15 UTC
Labels: component: code quality, component: windows, further investigation required, help wanted, need confirmation, type: bug
