### ISSUE TITLE
--test-arguments does not handle single quotes

### ISSUE THREAD

**Issue by brandon-leapyear** [commercialhaskell/stack#5472] opened 2021-01-13 20:39 UTC
### General summary/comments (optional)

Passing arguments with spaces in `--test-arguments` is inconsistent with normal shell quoting.

Related to #2210, but I figured this is a small enough bug that could be fixed independently of the greater discussion.

### Steps to reproduce

For example:

1. Make a test suite whose `Main.hs` file is just

    ```hs
    import System.Environment
    main :: IO ()
    main = getArgs >>= print
    ```

1. `stack test --ta 'a "b c"'`
1. `stack test --ta "a 'b c'"`

### Expected

The two invocations are equivalent in the shell world, as single quotes/double quotes only change special character interpretation / variable interpolation. I would expect this to both output
```
$ stack test --ta 'a "b c"'
["a", "b c"]
$ stack test --ta "a 'b c'"
["a", "b c"]
```

### Actual

```
$ stack test --ta 'a "b c"'
["a", "b c"]
$ stack test --ta "a 'b c'"
["a", "'b", "c'"]
```

### Stack version

```
$ stack --version
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0
```

### Method of installation

Official binary?

**Comment by sjakobi** [comment] 2021-02-02 15:05
Duplicate of https://github.com/commercialhaskell/stack/issues/3091?!

**Closed** 2022-05-16 18:50 UTC
