### ISSUE TITLE
Installing idris segfaults

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1795] opened 2016-02-15 20:09 UTC
```
$ stack install idris
Run from outside a project, using implicit global project config
Using resolver: lts-5.1 from implicit global project's config file: /home/callen/.stack/global-project/stack.yaml
async-2.0.2: configure
terminfo-0.4.0.2: download
async-2.0.2: build
cheapskate-0.1.0.4: configure
cheapskate-0.1.0.4: build
annotated-wl-pprint-0.7.0: configure
async-2.0.2: copy/register
annotated-wl-pprint-0.7.0: build
terminfo-0.4.0.2: configure
annotated-wl-pprint-0.7.0: copy/register
terminfo-0.4.0.2: build
fsnotify-0.2.1: configure
fsnotify-0.2.1: build
terminfo-0.4.0.2: copy/register
fsnotify-0.2.1: copy/register
haskeline-0.7.2.2: download
haskeline-0.7.2.2: configure
cheapskate-0.1.0.4: copy/register
Progress: 6/7
--  While building package haskeline-0.7.2.2 using:
      /home/callen/.stack/programs/x86_64-linux/ghc-7.10.3/bin/ghc --make -odir /tmp/stack27899/haskeline-0.7.2.2/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/setup -hidir /tmp/stack27899/haskeline-0.7.2.2/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/setup -i -i. -package=Cabal-1.22.5.0 -clear-package-db -global-package-db -package-db=/home/callen/.stack/snapshots/x86_64-linux/lts-5.1/7.10.3/pkgdb /tmp/stack27899/haskeline-0.7.2.2/Setup.hs -o /tmp/stack27899/haskeline-0.7.2.2/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/setup/setup
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/callen/.stack/global-project/.stack-work/logs/haskeline-0.7.2.2.log

    [1 of 1] Compiling Main             ( /tmp/stack27899/haskeline-0.7.2.2/Setup.hs, /tmp/stack27899/haskeline-0.7.2.2/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/setup/Main.o )
    Linking /tmp/stack27899/haskeline-0.7.2.2/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/setup/setup ...
    collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
    compilation terminated.
```

Had to set async's version manually because LTS 5.1 is ahead of Idris 0.10 at the moment.

```
extra-deps:
  - async-2.0.2
```

**Comment by sjakobi** [comment] 2016-02-15 23:35
Looks like an issues with `haskeline` specifically. I couldn't reproduce this on my system (Ubuntu 14.04 64bit).

https://github.com/judah/haskeline/issues/16 might be related.

**Comment by mgsloan** [comment] 2016-02-16 01:25
I believe that this means that `ld` is segfaulting.  See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=33357 .  Perhaps you've got a broken ld, or unusual version of such tools?

Alternatively, though highly unlikely, it could be a ghc bug which produces output which causes ld to crash.

**Comment by mgsloan** [comment] 2016-02-16 01:26
(closing the issue, but feel free to continue adding info)

**Closed by mgsloan** 2016-02-16 01:25 UTC
