### ISSUE TITLE
Mention `resolver` option in `stack install --help` 

### ISSUE THREAD

**Issue by geraldus** [commercialhaskell/stack#1556] opened 2015-12-22 07:34 UTC
Hi friends!

It's not clean that it is possible to specify resolver for `stack install` from command's help.  It will be nice to mention such option there.

Thank you! (:

**Comment by mgsloan** [comment] 2015-12-23 01:26
Thanks for the report!  I agree this should be fixed.

Dupe of #1462 , and tracked by #1333

**Closed by mgsloan** 2015-12-23 01:26 UTC
Labels: resolution: duplicate
