### ISSUE TITLE
stach hoogle fails on Windows 8.1 and Stack 1.2.0

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#2611] opened 2016-09-19 15:37 UTC
### Steps to reproduce

For example:
1. After upgrade to stack 1.2.0
2. Run command `stack hoogle String`.
3. It fails
### Expected

To succeed
### Actual

stack hoogle --verbose String

```Version 1.2.0 x86_64 hpack-0.14.0
2016-09-19 18:34:32.278564: [debug] Checking for project config at: C:\Users\home\stack.yaml
@(Stack\Config.hs:792:9)
2016-09-19 18:34:32.279565: [debug] Checking for project config at: C:\Users\stack.yaml
@(Stack\Config.hs:792:9)
2016-09-19 18:34:32.279565: [debug] Checking for project config at: C:\stack.yaml
@(Stack\Config.hs:792:9)
2016-09-19 18:34:32.280065: [debug] No project config file found, using defaults.
@(Stack\Config.hs:814:13)
2016-09-19 18:34:32.284569: [info] Run from outside a project, using implicit global project config
@(Stack\Config.hs:431:13)
2016-09-19 18:34:32.285070: [debug] Trying to decode C:\stack\build-plan-cache\x86_64-windows\lts-7.0.cache
@(Data\Store\VersionTagged.hs:68:5)
2016-09-19 18:34:32.297582: [debug] Success decoding C:\stack\build-plan-cache\x86_64-windows\lts-7.0.cache
@(Data\Store\VersionTagged.hs:72:13)
2016-09-19 18:34:32.301585: [debug] Getting system compiler version
@(Stack\Setup.hs:354:17)
2016-09-19 18:34:32.321104: [debug] Using standard GHC build
@(Stack\Setup.hs:535:9)
2016-09-19 18:34:32.321604: [debug] Getting global package database location
@(Stack\GhcPkg.hs:54:5)
2016-09-19 18:34:32.321604: [debug] Asking GHC for its version
2016-09-19 18:34:32.322105: [debug] Getting Cabal package version
@(Stack\Setup\Installed.hs:101:13)@(Stack\GhcPkg.hs:171:5)2016-09-19 18:34:32.322605: [debug] Run process: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --no-us
er-package-db list --global

@(System\Process\Read.hs:277:3)
2016-09-19 18:34:32.323606: [debug] Run process: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc.EXE --numeric-version
2016-09-19 18:34:32.324107: [debug] Run process: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --no-user-package-db field --simple-output Cabal version
@(System\Process\Read.hs:277:3)@(System\Process\Read.hs:277:3)

2016-09-19 18:34:32.345126: [debug] Process finished in 18 ms: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc.EXE --numeric-version
@(System\Process\Read.hs:277:3)
2016-09-19 18:34:32.378657: [debug] Process finished in 54 ms: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --no-user-package-db list --global
@(System\Process\Read.hs:277:3)
2016-09-19 18:34:32.397175: [debug] Process finished in 69 ms: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --no-user-package-db field --simple-output Cabal ve
rsion
@(System\Process\Read.hs:277:3)
2016-09-19 18:34:32.397676: [debug] Resolving package entries
@(Stack\Setup.hs:234:5)
2016-09-19 18:34:32.399678: [debug] Starting to execute command inside EnvConfig
@(Stack\Runners.hs:166:18)
2016-09-19 18:34:32.415192: [debug] Run process: C:\Users\home\AppData\Roaming\cabal\bin\hoogle.EXE --numeric-version
@(System\Process\Read.hs:277:3)
2016-09-19 18:34:32.432208: [debug] Process finished in 16 ms: C:\Users\home\AppData\Roaming\cabal\bin\hoogle.EXE --numeric-version
@(System\Process\Read.hs:277:3)
2016-09-19 18:34:32.432709: [warn] Hoogle isn't installed or is too old. Automatically installing (use --no-setup to disable) ...
@(Stack\Hoogle.hs:47:25)
2016-09-19 18:34:32.432709: [debug] Trying to decode C:\stack\indices\Hackage\00-index.cache
@(Data\Store\VersionTagged.hs:68:5)
2016-09-19 18:34:32.530801: [debug] Success decoding C:\stack\indices\Hackage\00-index.cache
@(Data\Store\VersionTagged.hs:72:13)
2016-09-19 18:34:32.675437: [info] Minimum version is hoogle-5.0. Found acceptable hoogle-5.0.4 in your index, installing it.
@(Stack\Hoogle.hs:120:17)
2016-09-19 18:34:32.696957: [debug] Checking for project config at: C:\Users\home\stack.yaml
@(Stack\Config.hs:792:9)
2016-09-19 18:34:32.697460: [debug] Checking for project config at: C:\Users\stack.yaml
@(Stack\Config.hs:792:9)
2016-09-19 18:34:32.697460: [debug] Checking for project config at: C:\stack.yaml
@(Stack\Config.hs:792:9)
2016-09-19 18:34:32.697958: [debug] No project config file found, using defaults.
@(Stack\Config.hs:814:13)
2016-09-19 18:34:32.701962: [info] Run from outside a project, using implicit global project config
@(Stack\Config.hs:431:13)
2016-09-19 18:34:32.702462: [debug] Trying to decode C:\stack\build-plan-cache\x86_64-windows\lts-7.0.cache
@(Data\Store\VersionTagged.hs:68:5)
2016-09-19 18:34:32.707968: [debug] Success decoding C:\stack\build-plan-cache\x86_64-windows\lts-7.0.cache
@(Data\Store\VersionTagged.hs:72:13)
2016-09-19 18:34:32.712472: [debug] Getting system compiler version
@(Stack\Setup.hs:354:17)
2016-09-19 18:34:32.731990: [debug] Using standard GHC build
@(Stack\Setup.hs:535:9)
2016-09-19 18:34:32.732491: [debug] Getting global package database location
@(Stack\GhcPkg.hs:54:5)2016-09-19 18:34:32.732491: [debug] Asking GHC for its version
2016-09-19 18:34:32.732491: [debug] Getting Cabal package version

@(Stack\Setup\Installed.hs:101:13)@(Stack\GhcPkg.hs:171:5)

2016-09-19 18:34:32.733492: [debug] Run process: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --no-user-package-db list --global
@(System\Process\Read.hs:277:3)2016-09-19 18:34:32.734492: [debug] Run process: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc.EXE --numeric-version
2016-09-19 18:34:32.734492: [debug] Run process: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --no-user-package-db field --simple-output Cabal version

@(System\Process\Read.hs:277:3)@(System\Process\Read.hs:277:3)

2016-09-19 18:34:32.760016: [debug] Process finished in 14 ms: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc.EXE --numeric-version
@(System\Process\Read.hs:277:3)
2016-09-19 18:34:32.798052: [debug] Process finished in 55 ms: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --no-user-package-db list --global
@(System\Process\Read.hs:277:3)
2016-09-19 18:34:32.799053: [debug] Process finished in 52 ms: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --no-user-package-db field --simple-output Cabal ve
rsion
@(System\Process\Read.hs:277:3)
2016-09-19 18:34:32.799053: [debug] Resolving package entries
@(Stack\Setup.hs:234:5)
2016-09-19 18:34:32.800554: [debug] Starting to execute command inside EnvConfig
@(Stack\Runners.hs:166:18)
2016-09-19 18:34:32.801055: [debug] Parsing the cabal files of the local packages
@(Stack\Build\Source.hs:282:5)
2016-09-19 18:34:32.801055: [debug] Parsing the targets
@(Stack\Build\Source.hs:219:5)
2016-09-19 18:34:32.801555: [debug] Finding out which packages are already installed
@(Stack\Build\Installed.hs:73:5)
2016-09-19 18:34:32.802556: [debug] Run process: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --global --no-user-package-db dump --expand-pkgroot
@(System\Process\Read.hs:277:3)
2016-09-19 18:34:32.942187: [debug] Process finished in 121 ms: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --global --no-user-package-db dump --expand-pkgroo
t
@(System\Process\Read.hs:277:3)
2016-09-19 18:34:32.951696: [debug] Run process: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --user --no-user-package-db --package-db C:\stack\snapshots\480be
ed7\pkgdb dump --expand-pkgroot
@(System\Process\Read.hs:277:3)
2016-09-19 18:34:33.004746: [debug] Process finished in 52 ms: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --user --no-user-package-db --package-db C:\stack\s
napshots\480beed7\pkgdb dump --expand-pkgroot
@(System\Process\Read.hs:277:3)
2016-09-19 18:34:33.005747: [debug] Run process: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --user --no-user-package-db --package-db C:\stack\global-project\
.stack-work\install\570eae67\pkgdb dump --expand-pkgroot
@(System\Process\Read.hs:277:3)
2016-09-19 18:34:33.056294: [debug] Process finished in 50 ms: C:\Users\home\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --user --no-user-package-db --package-db C:\stack\g
lobal-project.stack-work\install\570eae67\pkgdb dump --expand-pkgroot
@(System\Process\Read.hs:277:3)
2016-09-19 18:34:33.057295: [debug] Constructing the build plan
@(Stack\Build\ConstructPlan.hs:157:5)
2016-09-19 18:34:33.057796: [debug] Trying to decode C:\stack\indices\Hackage\00-index.cache
@(Data\Store\VersionTagged.hs:68:5)
2016-09-19 18:34:33.180412: [debug] Success decoding C:\stack\indices\Hackage\00-index.cache
@(Data\Store\VersionTagged.hs:72:13)
2016-09-19 18:34:33.429145: [error]
While constructing the build plan, the following exceptions were encountered:

In the dependencies for hoogle-5.0.4:
    haskell-src-exts-1.17.1 must match >=1.18 && <1.19 (latest applicable is 1.18.2)

@(Stack\Build\ConstructPlan.hs:195:13)
Plan construction failed.

```

### Stack version

```

$ stack --version
Version 1.2.0 x86_64 hpack-0.14.0

```

### Method of installation

* stack upgrade

Windows 8.1 x64
```

**Comment by mgsloan** [comment] 2016-09-26 02:50
I believe this is a dupe of https://github.com/commercialhaskell/stack/issues/2526

**Comment by varosi** [comment] 2016-09-26 12:18
It fails in project (LTS-6.10), too:

> Hoogle isn't installed or is too old. Automatically installing (use --no-setup to disable) ...
> Minimum version is hoogle-5.0. Found acceptable hoogle-5.0.4 in your index, installing it.
> 
> While constructing the build plan, the following exceptions were encountered:
> 
> In the dependencies for hoogle-5.0.4:
>     haskell-src-exts-1.17.1 must match >=1.18 && <1.19 (latest applicable is 1.18.2)
> 
> Plan construction failed.

**Comment by mgsloan** [comment] 2016-09-26 23:05
Oh I see. Yes, that should get fixed.

**Comment by vdukhovni** [comment] 2016-11-20 20:01
I see the same thing with stack `lts-7.9` on both Linux and MacOS/X:
```
$ stack hoogle takeCE
Hoogle isn't installed or is too old. Automatically installing (use --no-setup to disable) ...
Populated index cache.    
Minimum version is hoogle-5.0. Found acceptable hoogle-5.0.4 in your index, installing it.

While constructing the build plan, the following exceptions were encountered:

In the dependencies for hoogle-5.0.4:
    haskell-src-exts-1.17.1 must match >=1.18 && <1.19 (latest applicable is 1.18.2)

Plan construction failed.
```

**Comment by mgsloan** [comment] 2017-03-18 22:26
Closing as dupe of https://github.com/commercialhaskell/stack/issues/2524

**Closed by mgsloan** 2017-03-18 22:26 UTC
Labels: component: hoogle, type: bug
