### ISSUE TITLE
stack and ghc-head?

### ISSUE THREAD

**Issue by phadej** [commercialhaskell/stack#485] opened 2015-07-02 08:39 UTC
Is it possible at all? I tried `stack setup --system-ghc` but it didn't work, it started to download *ghc-7.10.1`:

https://travis-ci.org/futurice/fum2github/jobs/69253335

**Comment by snoyberg** [comment] 2015-07-02 10:53
See https://github.com/commercialhaskell/stack/issues/423 for a discussion which ended with adding --skip-GHC-check. If this works for you, it would be great if you could add it to the FAQ for others in the future.

**Comment by alanz** [comment] 2015-07-02 11:29
Here is an example of using stack with ghc head

https://github.com/alanz/ghc-exactprint/blob/wip/test.sh
and
https://github.com/alanz/ghc-exactprint/blob/wip/stack-7.11.yaml

Very straightforward, but using system-installed ghc head

**Comment by phadej** [comment] 2015-07-03 08:07
Seems it "works":
- `.travis.yml`: https://github.com/futurice/fum2github/blob/travis-head/.travis.yml
- example build: https://travis-ci.org/futurice/fum2github/jobs/69402198
except when it encounters stuff which doesn't work with GHC-7.11

Thanks for the tip. @snoyberg should we add this to travis page in https://github.com/commercialhaskell/stack/issues/458 or have a separate entry in FAQ?

**Comment by alanz** [comment] 2015-07-03 08:13
PS, semigroupoids does work with 7.11, you just need to add extra deps to your `stack.yaml`

```
extra-deps:
- semigroupoids-5.0.0.2
- bifunctors-5
- profunctors-5.1.1
- free-4.12.1
```

**Comment by phadej** [comment] 2015-07-03 08:52
@alanz, seems that had to add `lens-4.11` too in my example. It almost makes sense to have *mini-stackage* for kmett-universe.

**Comment by snoyberg** [comment] 2015-07-03 11:13
Having it on the Travis page seems fine to me. Looks like the problem is resolved now, closing.

**Closed by snoyberg** 2015-07-03 11:13 UTC
Labels: need-confirmation
