### ISSUE TITLE
Ghc fail with "ghc: internal error: evacuate: strange closure type 30052320" when compiling Data.Containers

### ISSUE THREAD

**Issue by xelxebar** [commercialhaskell/stack#906] opened 2015-09-02 20:02 UTC
## Overview

When attempting a global package install, `ghc` fails with the following error while compiling a `Data.Containers` dependency:

    ghc: internal error: evacuate: strange closure type 30052320

## Environment

    $ uname -a
    Linux introdus 4.1.6.201508230818-1-grsec #1 SMP PREEMPT Sun Aug 23 12:49:40 EDT 2015 x86_64 GNU/Linux

    $ stack --version
    Version 0.1.3.0

    $ stack exec ghc -- --version
    Run from outside a project, using implicit global config
    Using resolver: lts-3.4 from global config file: /home/x/.stack/global/stack.yaml
    The Glorious Glasgow Haskell Compilation System, version 7.10.2

## Complete Error Log

    --  While building package mono-traversable-0.9.3 using:
      /home/x/.stack/programs/x86_64-linux/ghc-7.10.2/bin/runhaskell -package=Cabal-1.22.4.0 -clear-package-db -global-package-db -package-db=/home/x/.stack/snapshots/x86_64-linux/lts-3.4/7.10.2/pkgdb/ /tmp/stack21199/Setup.hs --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/ build --ghc-options -hpcdir .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/hpc/.hpc/ -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure (-6)
    Logs have been written to: /home/x/.stack/global/.stack-work/logs/mono-traversable-0.9.3.log

    Configuring mono-traversable-0.9.3...
    Building mono-traversable-0.9.3...
    Preprocessing library mono-traversable-0.9.3...
    [1 of 7] Compiling Data.ByteVector  ( src/Data/ByteVector.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Data/ByteVector.o )
    [2 of 7] Compiling Data.MonoTraversable ( src/Data/MonoTraversable.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Data/MonoTraversable.o )

    src/Data/MonoTraversable.hs:79:1: Warning:
        Module ‘Control.Monad.Trans.Error’ is deprecated:
          Use Control.Monad.Trans.Except instead

    src/Data/MonoTraversable.hs:143:24: Warning:
        In the use of type constructor or class ‘ErrorT’
        (imported from Control.Monad.Trans.Error):
        Deprecated: "Use Control.Monad.Trans.Except instead"

    src/Data/MonoTraversable.hs:216:36: Warning:
        In the use of type constructor or class ‘ErrorT’
        (imported from Control.Monad.Trans.Error):
        Deprecated: "Use Control.Monad.Trans.Except instead"

    src/Data/MonoTraversable.hs:431:32: Warning:
        In the use of ‘Unsafe.inlinePerformIO’
        (imported from Data.ByteString.Internal):
        Deprecated: "If you think you know what you are doing, use 'unsafePerformIO'. If you are sure you know what you are doing, use 'unsafeDupablePerformIO'. If you enjoy sharing an address space with a malevolent agent of chaos, try 'accursedUnutterablePerformIO'."

    src/Data/MonoTraversable.hs:433:29: Warning:
        In the use of ‘Unsafe.inlinePerformIO’
        (imported from Data.ByteString.Internal):
        Deprecated: "If you think you know what you are doing, use 'unsafePerformIO'. If you are sure you know what you are doing, use 'unsafeDupablePerformIO'. If you enjoy sharing an address space with a malevolent agent of chaos, try 'accursedUnutterablePerformIO'."

    src/Data/MonoTraversable.hs:734:40: Warning:
        In the use of type constructor or class ‘ErrorT’
        (imported from Control.Monad.Trans.Error):
        Deprecated: "Use Control.Monad.Trans.Except instead"

    src/Data/MonoTraversable.hs:842:50: Warning:
        In the use of type constructor or class ‘ErrorT’
        (imported from Control.Monad.Trans.Error):
        Deprecated: "Use Control.Monad.Trans.Except instead"

    src/Data/MonoTraversable.hs:953:52: Warning:
        In the use of type constructor or class ‘ErrorT’
        (imported from Control.Monad.Trans.Error):
        Deprecated: "Use Control.Monad.Trans.Except instead"

    src/Data/MonoTraversable.hs:1081:44: Warning:
        In the use of type constructor or class ‘ErrorT’
        (imported from Control.Monad.Trans.Error):
        Deprecated: "Use Control.Monad.Trans.Except instead"

    src/Data/MonoTraversable.hs:1200:40: Warning:
        In the use of type constructor or class ‘ErrorT’
        (imported from Control.Monad.Trans.Error):
        Deprecated: "Use Control.Monad.Trans.Except instead"

    src/Data/MonoTraversable.hs:1201:14: Warning:
        In the use of data constructor ‘ErrorT’
        (imported from Control.Monad.Trans.Error):
        Deprecated: "Use Control.Monad.Trans.Except instead"
    [3 of 7] Compiling Data.GrowingAppend ( src/Data/GrowingAppend.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Data/GrowingAppend.o )
    [4 of 7] Compiling Data.Containers  ( src/Data/Containers.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Data/Containers.o )

    src/Data/Containers.hs:23:1: Warning:
        The import of ‘Data.Monoid’ is redundant
          except perhaps to import instances from ‘Data.Monoid’
        To import instances alone, use: import Data.Monoid()
    ghc: internal error: evacuate: strange closure type 30052320
        (GHC version 7.10.2 for x86_64_unknown_linux)
        Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

## Addendum

I am fairly new to `stack` and Haskell in general, so please forgive any silly mistakes I may have made. If any further information is needed, I will me more than happy to provide as much as I can. Thank you!

**Comment by snoyberg** [comment] 2015-09-03 09:46
First step would be to see how reproducible this is:

* What happens if you rerun the same build command?
* What happens if you delete your ~/.stack directory and rerun the same build command?

AFAICT, there's no silly mistake, this is just a GHC bug.

**Comment by xelxebar** [comment] 2015-09-04 20:52
@snoyberg Thank you for the suggestions. I'm having trouble deterministically reproducing this error. Here is the install command I'm running:

    stack install codex

I've nuked `~/.stack` several times and effectively run `stack setup && stack install codex`. However, the install variously works and fails, mostly the latter. Sometimes stack will report that two packages failed to install, each with the same "closure" error from ghc, so I'm guessing that stack is parallelizing the installs.

Before reporting the issue here, I discussed this with @geekosaur in the IRC channel #haskell on freenode. He mentioned that this closure error could be the result of some memory corruption, though unlinely.

I'm unsure how to proceed at this point and any advice would be most welcome. Thank you!

**Comment by snoyberg** [comment] 2015-09-05 20:38
I think a GHC issue about this would be the best next step.

**Comment by snoyberg** [comment] 2015-09-06 07:53
Closing this, as it's not a stack issue.

**Comment by geekosaur** [comment] 2015-09-06 13:49
On Fri, Sep 4, 2015 at 4:52 PM, Brandon Wilson <notifications@github.com>
wrote:

> Before reporting the issue here, I discussed this with @geekosaur
> <https://github.com/geekosaur>
>
> in the IRC channel #haskell on freenode. He mentioned that this closure
> error could be the result of some memory corruption, though unlinely.
>
>
FWIW there was a bit of information loss here... the only times I've seen
or heard of that error *from ghc itself* involved .hi file mismatches, so I
suggested starting with stack because --- while it is a long shot --- other
things that would produce it seemed even longer shots.

-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by snoyberg** [comment] 2015-09-06 13:50
Thanks or clarifying, reopening pending a bit more investigation then.

**Comment by snoyberg** [comment] 2015-09-06 14:18
@xelxebar Can I ask you to try upgrading to the latest stack and trying to reproduce the problem again? Also, have you tried running a memtest on your system? I've seen no other reports similar to this.

**Comment by xelxebar** [comment] 2015-09-06 15:09
@geekosaur Thank you for the clarification. Also, apologies for misrepresenting what you had told me.

@snoyberg I was able to reproduce this with stack version `Version 0.1.4.1 (UNKNOWN commits) X86_64`, installed by issuing `stack install stack` from the version stated above.

I haven't performed a memtest yet; I will try that soon and report back.

Thank you again for your help.

**Comment by mgsloan** [comment] 2015-09-08 00:36
Here's another report of the same issue: https://github.com/commercialhaskell/stack-ide/issues/61

Are you on OSX?

**Comment by snoyberg** [comment] 2015-09-13 10:52
Any progress on the memtest?

**Comment by snoyberg** [comment] 2015-09-21 03:29
Closing due to lack of feedback.

**Closed by snoyberg** 2015-09-21 03:29 UTC
