### ISSUE TITLE
Concurrent invocations of stack fail with obscure message

### ISSUE THREAD

**Issue by facundominguez** [commercialhaskell/stack#3496] opened 2017-10-17 12:22 UTC
I'm using stack-1.5.1 on centos6.8 in a docker container with 8 cores.

Invoking stack as follows
```
stack install Cabal Glob HUnit HUnit-approx MonadRandom QuickCheck StateVar abstract-deque abstract-par aeson aeson-compat aeson-pretty ansi-terminal ansi-wl-pprint appar array asn1-encoding asn1-parse asn1-types async attoparsec attoparsec-iso8601 auto-update base base-compat base-orphans base-prelude base16-bytestring base64-bytestring bifunctors binary binary-parser bits blaze-builder blaze-html blaze-markup blaze-textual broadcast-chan byteable byteorder bytes bytestring bytestring-builder bytestring-trie cabal-doctest call-stack case-insensitive cassava cereal cereal-vector charset choice clock cmdargs code-page comonad conduit conduit-extra connection constraints containers contravariant convertible cookie cpphs cpu criterion cryptohash cryptohash-md5 cryptohash-sha1 cryptonite data-binary-ieee754 data-default-class deepseq digest direct-sqlite directory distributive dlist double-conversion easy-file entropy erf exceptions fail fast-logger file-embed filepath foldl foundation ghc-boot ghc-boot-th ghc-events ghc-prim ghci haar hashable hashable-time hashtables haskeline haskell-src-exts hastache hex hoopl hourglass hpc hspec hspec-core hspec-discover hspec-expectations hsyslog http-api-data http-client http-client-tls http-date http-media http-types http2 ieee754 inline-c integer-gmp integer-logarithms intervals iproute js-flot js-jquery language-java lbfgs lifted-async lifted-base loch-th logict math-functions megaparsec memory microlens microlens-th mime-types mmorph monad-control monad-logger monad-logger-syslog monad-loops monad-par monad-par-extras monad-primitive mtl mwc-random nats neat-interpolation network network-info network-uri old-locale old-time opaleye optparse-applicative parallel parsec parsers path path-pieces pcg-random pem persistent persistent-postgresql persistent-sqlite persistent-template placeholders pointless-fun polyparse postgresql-binary postgresql-libpq postgresql-simple pretty primitive process product-profunctors profunctors psqueues quickcheck-io random reflection regex-base regex-tdfa resource-pool resourcet safe safe-exceptions scientific semigroups servant servant-client servant-server setenv silently simple-sendfile singletons siphash smallcheck socks split sqlite-simple stache statistics stm stm-chans streaming streaming-commons string-conversions stringsearch success syb system-filepath tagged tasty tasty-discover tasty-golden tasty-hspec tasty-hunit tasty-quickcheck tasty-smallcheck tasty-th template-haskell temporary terminfo text text-format tf-random th-desugar th-expand-syns th-lift th-lift-instances th-orphans th-reify-many time time-locale-compat tls transformers transformers-base transformers-compat unbounded-delays unix unix-compat unix-time unordered-containers uri-bytestring utf8-string uuid uuid-types vault vector vector-algorithms vector-binary-instances vector-th-unbox void wai wai-app-static wai-extra wai-logger warp word8 x509 x509-store x509-system x509-validation yaml zip-archive zlib
```

produces the following error:
```
...

call-stack-0.1.0: build
abstract-deque-0.3: configure
abstract-deque-0.3: build
cpu-0.1.2: configure
call-stack-0.1.0: copy/register
cpu-0.1.2: build
cryptohash-md5-0.11.100.1: configure
abstract-deque-0.3: copy/register
cryptohash-md5-0.11.100.1: build
convertible-1.1.1.0: configure
cpu-0.1.2: copy/register
convertible-1.1.1.0: build
easy-file-0.2.1: configure
cryptohash-md5-0.11.100.1: copy/register
easy-file-0.2.1: build
easy-file-0.2.1: copy/register
convertible-1.1.1.0: copy/register
Progress: 31/162
/root/.stack/indices/Hackage/packages/double-conversion/2.0.2.0/double-conversion-2.0.2.0.tar.gz.tmp: renameFile:renamePath:rename: does not exist (No such file or directory)

/root/.stack/indices/Hackage/packages/direct-sqlite/2.3.19/direct-sqlite-2.3.19.tar.gz.tmp: renameFile:renamePath:rename: does not exist (No such file or directory)

/root/.stack/indices/Hackage/packages/digest/0.0.1.2/digest-0.0.1.2.tar.gz.tmp: renameFile:renamePath:rename: does not exist (No such file or directory)

/root/.stack/indices/Hackage/packages/code-page/0.1.3/code-page-0.1.3.tar.gz.tmp: renameFile:renamePath:rename: does not exist (No such file or directory)

/root/.stack/indices/Hackage/packages/cryptohash-sha1/0.11.100.1/cryptohash-sha1-0.11.100.1.tar.gz.tmp: renameFile:renamePath:rename: does not exist (No such file or directory)

/root/.stack/indices/Hackage/packages/cereal-vector/0.2.0.1/cereal-vector-0.2.0.1.tar.gz.tmp: renameFile:renamePath:rename: does not exist (No such file or directory)

/root/.stack/indices/Hackage/packages/charset/0.3.7.1/charset-0.3.7.1.tar.gz.tmp: renameFile:renamePath:rename: does not exist (No such file or directory)

/root/.stack/indices/Hackage/packages/data-binary-ieee754/0.4.4/data-binary-ieee754-0.4.4.tar.gz.tmp: renameFile:renamePath:rename: does not exist (No such file or directory)

/root/.stack/indices/Hackage/packages/bytestring-trie/0.2.4.1/bytestring-trie-0.2.4.1.tar.gz.tmp: renameFile:renamePath:rename: does not exist (No such file or directory)

/root/.stack/indices/Hackage/packages/broadcast-chan/0.1.1/broadcast-chan-0.1.1.tar.gz.tmp: renameFile:renamePath:rename: does not exist (No such file or directory)

/root/.stack/indices/Hackage/packages/byteorder/1.0.4/byteorder-1.0.4.tar.gz.tmp: renameFile:renamePath:rename: does not exist (No such file or directory)

/root/.stack/indices/Hackage/packages/cabal-doctest/1.0.2/cabal-doctest-1.0.2.tar.gz.tmp: renameFile:renamePath:rename: does not exist (No such file or directory)

...
```
I'm using the following custom snapshot:
```
resolver: lts-8.18

packages:
- constraints-0.9
- haar-0.1
- lbfgs-0.1
- pcg-random-0.1.3.4
- tasty-discover-1.1.0
- QuickCheck-2.8.2
- haskell-src-exts-1.19.1
- hlint-2.0.9
- ghc-events-0.6.0
```

**Comment by facundominguez** [comment] 2017-10-17 12:24
@qnikst has seen similar errors in windows with 2 cores. But I don't know which set of dependencies he was using at the time.

**Comment by mgsloan** [comment] 2017-10-17 22:12
So I believe that this error is coming from the rename file here: https://github.com/commercialhaskell/stack/blob/master/src/Network/HTTP/Download/Verified.hs#L229

I don't see how it's possible for it to make it to that rename file without the file at `fptmp` existing.  Perhaps it needs to create the directory?  I don't think that's it because then `withBinaryFile` would just fail directly.

Best way to get this resolved would be to try modifying the stack code to get it to go away.  One thing to try is adding a user of `ensureDir (parent fptmp)`.  It may also be worthwhile to do some hacky debugging like adding thread delay before the download, and before the rename, with logging, and checking if the directory / files exist when they are supposed to.

If you do not want to try to fix it, then I suggest posting up a minimal reproduction project.  That makes it a lot easier for someone to work on fixing this.

**Comment by facundominguez** [comment] 2017-10-18 12:13
Thanks for looking at it. It seems the problem was that I was doing concurrent invocations of `stack install`, which are interfering with each other.

By enabling more verbose output it became clear that more than one `stack` was running. It would be nice if stack could check this with a lock file and complain with a comprehensible message.

**Comment by mgsloan** [comment] 2017-10-19 05:17
Hmm, yeah, there are a number of issues with concurrent use of stack that should be addressed with lock files.

**Comment by ehamberg** [comment] 2018-02-04 14:03
I also hit this issue today due to concurrent invocations of `stack`. Didn't know that wasn't supported.

**Comment by mgsloan** [comment] 2019-01-02 20:54
@minad Hi! I'm not very active in stack maintenance these days, so the decision is up to the active maintainers (pinging @mihaimaruseac).

Certainly it makes sense to me to have some form of locking for build.  It might make sense to nest the lock files within the dist directories, so that independent builds can still be done concurrently.

**Comment by mihaimaruseac** [comment] 2019-01-03 17:57
@minad Sure, that could work.

**Comment by snoyberg** [comment] 2019-04-08 12:13
#2730 covers the build case. The error mentioned here about file downloads does not apply anymore with Pantry, so closing

**Closed by snoyberg** 2019-04-08 12:13 UTC
Labels: component: build, type: bug
