### ISSUE TITLE
stack test fails to apply language extensions field from .cabal

### ISSUE THREAD

**Issue by gambogi** [commercialhaskell/stack#1469] opened 2015-12-05 04:27 UTC
When using stack test, caused a recompile which yielded errors related to OverloadedStrings not being set.
Adding `{-# LANGUAGE OverloadedStrings #-}` to the top of the file in question fixed the issue. The commit in question can be found [here](https://github.com/gambogi/csh-eval/commit/c3679380565a88f0dd3521fc2e3431f709ff3be4) and the corresponding broken and fixed circle builds can be found [here](https://circleci.com/gh/ComputerScienceHouse/csh-eval/314) and [here](https://circleci.com/gh/ComputerScienceHouse/csh-eval/315) respectively. 

If this isn't a stack issue, apologies. Stephen Demos (@sdemos) can also provide background.

Thanks,
Matt

**Comment by mgsloan** [comment] 2015-12-05 05:19
Hmm, I cannot reproduce the issue with latest stack.  All that should be necessary is `stack build` followed by `stack test`, yes?

It's actually the domain of the [`Cabal`](https://github.com/haskell/cabal) library to invoke GHC with the default-extensions from the cabal file.  Since stack isn't involved at all with this part of things, I'm going to close this.  `stack clean` may be helpful in such circumstances.

**Closed** 2015-12-05 05:20 UTC

**Comment by sdemos** [comment] 2015-12-05 22:18
The issue came up when `stack test` was run without `stack build` being run first. One of the files was changed, and so when `stack test` was run, it needed to rebuild that file as part of our library dependency, which it did without including the `default-extensions` field from our cabal file. 

The reason that I suspect this is a stack issue is I assumed that stack is responsible for discovering unresolved dependencies in the build process and then instructing cabal to fix them each individually. If that is not the case, we will throw this over to the cabal folks instead.

**Comment by sdemos** [comment] 2015-12-05 22:39
I took a second look at it and it actually looks like the failures are from doctest, not stack. Sorry for the bother!
