### ISSUE TITLE
`stack init --solver` adds packages from the snapshot

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/stack#2029] opened 2016-04-13 04:59 UTC
Stumbled today over the following, trying to build a `stack.yaml` for [sol/tinc](https://github.com/sol/tinc) @ `c751c66`
```bash
tinc $ stack init --solver
stack init --solver
Using cabal packages:
- tinc.cabal
[...]
Selecting the best among 7 snapshots...
[...]
Selected resolver: nightly-2016-04-12
*** Resolver nightly-2016-04-12 will need external packages:
    language-dot not found
        - tinc requires -any

Using resolver: nightly-2016-04-12
Using compiler: ghc-7.10.3
Asking cabal to calculate a build plan...
Trying with packages from nightly-2016-04-12 as hard constraints...
Successfully determined a build plan with 3 external dependencies.
Initialising configuration using resolver: nightly-2016-04-12
Total number of user packages considered: 1
Warning! 3 external dependencies were added.
Writing configuration to file: stack.yaml
All done.
```
Looking at the generated `stack.yaml` we find:
```yaml
extra-deps:
- language-dot-0.0.8
- text-1.2.2.1
- yaml-0.8.17
```

yet, `text-1.2.2.1` and `yaml-0.8.17` are in [nightly-2016-04-12](https://www.stackage.org/nightly-2016-04-12).

**Comment by sjakobi** [comment] 2016-04-13 06:45
Looks like a duplicate of https://github.com/commercialhaskell/stack/issues/1927.

`stack upgrade --git` should fix this. Please reopen if it doesn't!

**Closed by sjakobi** 2016-04-13 06:45 UTC
