### ISSUE TITLE
--ghc-options="many flags here" does not always work

### ISSUE THREAD

**Issue by DouglasRaillard** [commercialhaskell/stack#5418] opened 2020-10-28 11:16 UTC
### General summary/comments (optional)

Giving multiple options in one `--ghc-options` does not always work, e.g. `--ghc-options="-O2 -fllvm"`.

### Steps to reproduce

```
stack build distributive --ghc-options="-fllvm -O2"
```

Bug report against `distributive` project: https://github.com/ekmett/distributive/issues/57

### Expected

Stack should warn against bundling multiple options. Instead `--ghc-options=-O2 --ghc-options=-fllvm` works everywhere.
Official documentation should be updated accordingly to:  https://docs.haskellstack.org/en/stable/GUIDE/#ghc-options

### Actual

The package fails to build.

```
$ stack build distributive --ghc-options="-fllvm -O2" --verbose
Version 2.6.0, Git revision 9621945bf7fe6d0a526ee6b6f183d3c821143979 (8254 commits) PRE-RELEASE x86_64 hpack-0.33.0
2020-10-28 11:06:25.181064: [debug] Checking for project config at: /home/prog/stack.yaml
2020-10-28 11:06:25.181509: [debug] Loading project config file stack.yaml
2020-10-28 11:06:25.193537: [debug] (SQL) SELECT COUNT(*) FROM "last_performed" WHERE ("action"=?) AND ("timestamp">=?); [PersistInt64 1,PersistUTCTime 2020-10-27 11:06:25.193467001 UTC]
2020-10-28 11:06:25.195176: [debug] Using package location completions from a lock file
2020-10-28 11:06:25.201398: [debug] Loaded snapshot from Pantry database.
2020-10-28 11:06:25.411864: [debug] Running hpack on /home/prog/package.yaml
2020-10-28 11:06:25.418737: [debug] hpack output unchanged in /home/prog/foo.cabal
2020-10-28 11:06:25.421680: [debug] Asking for a supported GHC version
2020-10-28 11:06:25.421900: [debug] Installed tools: 
 - ghc-tinfo6-8.8.3
 - ghc-tinfo6-8.10.2
 - ghc-tinfo6-8.6.5
2020-10-28 11:06:25.422046: [debug] Run process: /sbin/ldconfig -p
2020-10-28 11:06:25.424717: [debug] Process finished in 3ms: /sbin/ldconfig -p
2020-10-28 11:06:25.426693: [debug] Did not find shared library libtinfo.so.5
2020-10-28 11:06:25.426934: [debug] Found shared library libtinfo.so.6 in /usr/lib/
2020-10-28 11:06:25.427031: [debug] Found shared library libncursesw.so.6 in 'ldconfig -p' output
2020-10-28 11:06:25.427145: [debug] Found shared library libgmp.so.10 in 'ldconfig -p' output
2020-10-28 11:06:25.427364: [debug] Did not find shared library libgmp.so.3
2020-10-28 11:06:25.427419: [debug] Potential GHC builds: tinfo6, ncurses6
2020-10-28 11:06:25.427520: [debug] Found already installed GHC builds: tinfo6
2020-10-28 11:06:25.428014: [debug] (SQL) SELECT "id","actual_version","arch","ghc_path","ghc_size","ghc_modified","ghc_pkg_path","runghc_path","haddock_path","cabal_version","global_db","global_db_cache_size","global_db_cache_modified","info","global_dump" FROM "compiler_cache" WHERE "ghc_path"=?; [PersistText "/home/prog/.stack/programs/x86_64-linux/ghc-tinfo6-8.10.2/bin/ghc-8.10.2"]
2020-10-28 11:06:25.488860: [debug] Loaded compiler information from cache
2020-10-28 11:06:25.489022: [debug] Asking for a supported GHC version
2020-10-28 11:06:25.490258: [debug] Resolving package entries
2020-10-28 11:06:25.490395: [debug] Parsing the targets
2020-10-28 11:06:25.494642: [debug] Checking flags
2020-10-28 11:06:25.494730: [debug] SourceMap constructed
2020-10-28 11:06:25.502948: [debug] Starting to execute command inside EnvConfig
2020-10-28 11:06:25.505553: [debug] Finding out which packages are already installed
2020-10-28 11:06:25.505791: [debug] Run process: /home/prog/.stack/programs/x86_64-linux/ghc-tinfo6-8.10.2/bin/ghc-pkg-8.10.2 --global --no-user-package-db dump --expand-pkgroot
2020-10-28 11:06:25.542852: [debug] Process finished in 37ms: /home/prog/.stack/programs/x86_64-linux/ghc-tinfo6-8.10.2/bin/ghc-pkg-8.10.2 --global --no-user-package-db dump --expand-pkgroot
2020-10-28 11:06:25.548751: [debug] Ignoring package haskeline due to wanting version 0.8.1.0 instead of 0.8.0.1
2020-10-28 11:06:25.553479: [debug] Run process: /home/prog/.stack/programs/x86_64-linux/ghc-tinfo6-8.10.2/bin/ghc-pkg-8.10.2 --user --no-user-package-db --package-db /home/prog/.stack/snapshots/x86_64-linux-tinfo6/c7ab6811fc6c94e1e7ff26d3bcd0676418abdd61c1d832eea2f73f961d7ab831/8.10.2/pkgdb dump --expand-pkgroot
2020-10-28 11:06:25.594796: [debug] Process finished in 41ms: /home/prog/.stack/programs/x86_64-linux/ghc-tinfo6-8.10.2/bin/ghc-pkg-8.10.2 --user --no-user-package-db --package-db /home/prog/.stack/snapshots/x86_64-linux-tinfo6/c7ab6811fc6c94e1e7ff26d3bcd0676418abdd61c1d832eea2f73f961d7ab831/8.10.2/pkgdb dump --expand-pkgroot
2020-10-28 11:06:25.596406: [debug] Run process: /home/prog/.stack/programs/x86_64-linux/ghc-tinfo6-8.10.2/bin/ghc-pkg-8.10.2 --user --no-user-package-db --package-db /home/prog/.stack-work/install/x86_64-linux-tinfo6/c7ab6811fc6c94e1e7ff26d3bcd0676418abdd61c1d832eea2f73f961d7ab831/8.10.2/pkgdb dump --expand-pkgroot
2020-10-28 11:06:25.653478: [debug] Process finished in 57ms: /home/prog/.stack/programs/x86_64-linux/ghc-tinfo6-8.10.2/bin/ghc-pkg-8.10.2 --user --no-user-package-db --package-db /home/prog/.stack-work/install/x86_64-linux-tinfo6/c7ab6811fc6c94e1e7ff26d3bcd0676418abdd61c1d832eea2f73f961d7ab831/8.10.2/pkgdb dump --expand-pkgroot
2020-10-28 11:06:25.654386: [debug] Constructing the build plan
2020-10-28 11:06:25.656254: [debug] Parsing cabal file for distributive (from Hackage)
2020-10-28 11:06:25.656865: [debug] Got blob from Pantry database for distributive-0.6.2@sha256:2ace9babcdbd1c2db28638c200405fb85e3660fe19ceae4f03082590adc2c487,3198
2020-10-28 11:06:25.664862: [debug] Checking if we are going to build multiple executables with the same name
2020-10-28 11:06:25.665109: [debug] Executing the build plan
2020-10-28 11:06:25.668620: [debug] (SQL) SELECT "id","platform_ghc_dir","compiler","cabal_version","package_key","options_hash","haddock","library" FROM "precompiled_cache" WHERE "platform_ghc_dir"=? AND "compiler"=? AND "cabal_version"=? AND "package_key"=? AND "options_hash"=? AND "haddock"=?; [PersistText "x86_64-linux-tinfo6/",PersistText "ghc-8.10.2",PersistText "3.2.0.0",PersistText "5954b4025c6ebe3d6ed82f2b1a78c71a8f8c1f5446f3f4e86a664c0bb17c7635,959",PersistByteString "\DLE\250@*\206\SUB\147\160A\b\165:6[\131K\232 \139\DLExfF!\210\&5L\246r\200\t\DLE",PersistBool False]
2020-10-28 11:06:25.675110: [debug] Loaded package from Pantry: distributive-0.6.2@sha256:2ace9babcdbd1c2db28638c200405fb85e3660fe19ceae4f03082590adc2c487,3198 (from Hackage)
2020-10-28 11:06:25.682594: [debug] (SQL) SELECT "id","directory","type","pkg_src","active","path_env_var","haddock" FROM "config_cache" WHERE "directory"=? AND "type"=?; [PersistText "/tmp/stack-0adabee7a73b631c/distributive-0.6.2/",PersistText "config"]
2020-10-28 11:06:25.683664: [debug] (SQL) UPDATE "config_cache" SET "active"=? WHERE ("directory"=?) AND ("type"=?); [PersistBool False,PersistText "/tmp/stack-0adabee7a73b631c/distributive-0.6.2/",PersistText "config"]
2020-10-28 11:06:25.684053: [info] distributive> configure
2020-10-28 11:06:25.685556: [debug] Run process within /tmp/stack-0adabee7a73b631c/distributive-0.6.2/: /home/prog/.stack/programs/x86_64-linux/ghc-tinfo6-8.10.2/bin/ghc-8.10.2 --make -odir /tmp/stack-0adabee7a73b631c/distributive-0.6.2/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/setup -hidir /tmp/stack-0adabee7a73b631c/distributive-0.6.2/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/setup -i -i. -clear-package-db -global-package-db -package-db=/home/prog/.stack/snapshots/x86_64-linux-tinfo6/c7ab6811fc6c94e1e7ff26d3bcd0676418abdd61c1d832eea2f73f961d7ab831/8.10.2/pkgdb -package-db=/home/prog/.stack-work/install/x86_64-linux-tinfo6/c7ab6811fc6c94e1e7ff26d3bcd0676418abdd61c1d832eea2f73f961d7ab831/8.10.2/pkgdb -hide-all-packages -package-id=Cabal-3.2.0.0 -package-id=base-4.14.1.0 -package-id=cabal-doctest-1.0.8-8FuiLtyYbOyAYReyoJWbHo -optP-include -optP/tmp/stack-0adabee7a73b631c/distributive-0.6.2/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/setup/setup_macros.h /tmp/stack-0adabee7a73b631c/distributive-0.6.2/Setup.lhs /home/prog/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -main-is StackSetupShim.mainOverride -o /tmp/stack-0adabee7a73b631c/distributive-0.6.2/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/setup/setup -threaded -O2 "-fllvm -O2"
2020-10-28 11:06:25.776142: [warn] distributive> ghc: unrecognised flag: -fllvm -O2
2020-10-28 11:06:25.782312: [warn] distributive> 
2020-10-28 11:06:25.782577: [warn] distributive> Usage: For basic information, try the `--help' option.
2020-10-28 11:06:25.791906: [error] 
--  While building package distributive-0.6.2 (scroll up to its section to see the error) using:
      /home/prog/.stack/programs/x86_64-linux/ghc-tinfo6-8.10.2/bin/ghc-8.10.2 --make -odir /tmp/stack-0adabee7a73b631c/distributive-0.6.2/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/setup -hidir /tmp/stack-0adabee7a73b631c/distributive-0.6.2/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/setup -i -i. -clear-package-db -global-package-db -package-db=/home/prog/.stack/snapshots/x86_64-linux-tinfo6/c7ab6811fc6c94e1e7ff26d3bcd0676418abdd61c1d832eea2f73f961d7ab831/8.10.2/pkgdb -package-db=/home/prog/.stack-work/install/x86_64-linux-tinfo6/c7ab6811fc6c94e1e7ff26d3bcd0676418abdd61c1d832eea2f73f961d7ab831/8.10.2/pkgdb -hide-all-packages -package-id=Cabal-3.2.0.0 -package-id=base-4.14.1.0 -package-id=cabal-doctest-1.0.8-8FuiLtyYbOyAYReyoJWbHo -optP-include -optP/tmp/stack-0adabee7a73b631c/distributive-0.6.2/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/setup/setup_macros.h /tmp/stack-0adabee7a73b631c/distributive-0.6.2/Setup.lhs /home/prog/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -main-is StackSetupShim.mainOverride -o /tmp/stack-0adabee7a73b631c/distributive-0.6.2/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/setup/setup -threaded -O2 "-fllvm -O2"
    Process exited with code: ExitFailure 1
```

### Stack version

```
$ stack --version
Version 2.6.0, Git revision 9621945bf7fe6d0a526ee6b6f183d3c821143979 (8254 commits) PRE-RELEASE x86_64 hpack-0.33.0
```
Note: I was previously using stack 2.3.1 from my distro and the issue was identical.

### Method of installation

* Built from git

**Comment by mpilgrem** [comment] 2024-03-10 12:56
I am closing, as I could not reproduce with the current version of Stack using a plain vanilla project `boo` (`stack new boo`) and:
~~~text
stack --verbose build --ghc-options "-O2 -fllvm" --cabal-verbose
~~~

Stack passes the options to Cabal (the library), using its [`--ghc-options` option](https://cabal.readthedocs.io/en/stable/setup-commands.html#cmdoption-runhaskell-Setup.hs-configure-prog-options) (extract):
~~~text
Run process within ...: ...\Cabal-simple_9p6GVs8J_3.10.1.0_ghc-9.6.4.exe ... configure ... --ghc-options "-O2 -fllvm" ...
~~~

and Cabal (the library) passes the options on to GHC (extract):
~~~text
Running: "...\ghc-9.6.4\bin\ghc-9.6.4.exe" "--make" ... "-O2" "-fllvm" ...
~~~

**Closed by mpilgrem** 2024-03-10 12:56 UTC
