### ISSUE TITLE
1.9.1 fails with "I don't know how to install GHC on your system configuration, please install manually"

### ISSUE THREAD

**Issue by ThomasLocke** [commercialhaskell/stack#4362] opened 2018-10-18 10:41 UTC
### General summary/comments (optional)
Using stack on Slackware Linux 14.2 (x86_64). 

stack 1.6.5 works flawlessly, 1.9.1 returns _I don't know how to install GHC on your system configuration, please install manually_ when running `stack build`

### Steps to reproduce
1. Run command `stack new myproj`
2. Run command `cd myproj`
3. Run command `stack build`

It fails at step 3.

### Expected
I expect 1.9.1 builds my projects, similar as to how 1.6.5 does it.

### Actual
I get the error _I don't know how to install GHC on your system configuration, please install manually_

```
$ stack build --verbose
2018-10-18 12:37:21.393172: [debug] Checking for project config at: /home/thomas/myproj/stack.yaml
2018-10-18 12:37:21.393378: [debug] Loading project config file stack.yaml
2018-10-18 12:37:21.395132: [debug] Decoding build plan from: /home/thomas/.stack/build-plan/lts-11.22.yaml
2018-10-18 12:37:21.395210: [debug] Trying to decode /home/thomas/.stack/build-plan-cache/lts-11.22.cache
2018-10-18 12:37:21.403246: [debug] Success decoding /home/thomas/.stack/build-plan-cache/lts-11.22.cache
2018-10-18 12:37:21.403692: [debug] Run process: /sbin/ldconfig -p
2018-10-18 12:37:21.408474: [debug] Process finished in 5ms: /sbin/ldconfig -p
2018-10-18 12:37:21.409755: [debug] Did not find shared library libtinfo.so.5
2018-10-18 12:37:21.409868: [debug] Did not find shared library libtinfo.so.6
2018-10-18 12:37:21.409968: [debug] Did not find shared library libncursesw.so.6
2018-10-18 12:37:21.410042: [debug] Found shared library libgmp.so.10 in 'ldconfig -p' output
2018-10-18 12:37:21.410142: [debug] Did not find shared library libgmp.so.3
2018-10-18 12:37:21.410184: [debug] Potential GHC builds: 
2018-10-18 12:37:21.410221: [debug] Found already installed GHC builds: 
I don't know how to install GHC on your system configuration, please install manually
```

### Stack version

```
$ stack --version
Version 1.9.1, Git revision f9d0042c141660e1d38f797e1d426be4a99b2a3c (6168 commits) x86_64 hpack-0.31.0
```

### Method of installation
* Official binary, downloaded from stackage.org or fpcomplete's package repository
https://github.com/commercialhaskell/stack/releases/download/v1.9.1/stack-1.9.1-linux-x86_64-static.tar.gz

**Comment by dbaynard** [comment] 2018-10-18 21:08
I'm not familiar with Slackware. It isn't directly supported by <https://www.haskell.org/ghc/distribution_packages.html>. Where did your GHC come from before?

Typically these sorts of issues can be resolved by installing the correct libtinfo — that may be worth a try.

**Comment by ThomasLocke** [comment] 2018-10-19 06:57
https://haskell-lang.org/get-started/linux

There's no mention of Slackware not being supported, it just says "Linux" at the top. And as stated, 1.6.5 and prior versions work just fine. It's 1.9.1 that is acting up.

I'll take a look at the libtinfo stuff in Slackware, but isn't that something that should've been solved in the static executable?

Note that I also get these two lines when using 1.6.5

2018-10-18 12:37:21.409755: [debug] Did not find shared library libtinfo.so.5
2018-10-18 12:37:21.409868: [debug] Did not find shared library libtinfo.so.6

And yet it still works just fine.

**Comment by ThomasLocke** [comment] 2018-10-19 08:16
Installing libtinfo-5 doesn't change anything. It still fails.

I had the same problem with 1.7.1, but back then I suspected it was because of 1.7.1 being dynamically linked. Since 1.9.1 is now statically linked, and I still have the issue, it's probably safe to say that that was not the problem with 1.7.1

Oh and to answer your question @dbaynard: My GHC's comes from stack. 1.6.5 simply installs the GHC I need for the project that is being build. It just works. Obviously something changed from 1.6.5 to >= 1.7.1 that affects how GHC is installed by stack.

Looking a bit at the stack code, the error seems to stem from the ´UnsupportedSetupConfiguration´ exception in ´src/Stack/Setup.hs´. It's unclear to me why >=1.7.1 doesn't work when 1.6.5 clearly supports Slackware Linux. Maybe >=1.7.1 is just a bit more picky about certain particulars?

**Comment by borsboom** [comment] 2018-10-19 23:39
The logic to choose a GHC changed significantly in stack-1.7.1, and has remained the same in 1.9.1.  It now makes a list of candidate bindists based on which dynamic libraries it finds on the system, and then will install the best match.  If it can't find any candidates, it gives up with this error.  The old behaviour was that it would check for certain specific conditions to use a specific bindist, and if none of those conditions were met it would install a default.

Overall, the new approach improves things for most cases, but it looks like it may have made things worse on Slackware.  Based on your output above, it would seem that the shared library detection isn't working at all on your system.

Stack uses the output of `ldconfig -p` (which lists shared libraries) to find what is installed.  Try running `ldconfig -p|grep 'tinfo\|ncurses'`, and it should show one or more libtinfo or libncurses libraries.

Stack looks for `ldconfig` in the system PATH as well as `/sbin` and `/usr/sbin`, so I'd also be curious about the output of `which ldconfig`.

**Comment by ThomasLocke** [comment] 2018-10-22 05:52
@borsboom 

```bash
$ ldconfig -p|grep 'tinfo\|ncurses'
libncursesw.so.5 (libc6,x86-64) => /lib64/libncursesw.so.5                                                                                                                                                                                                             
libncursesw.so.5 (libc6,x86-64) => /usr/lib64/libncursesw.so.5                                                                                                                                                                                                         
libncursesw.so (libc6,x86-64) => /usr/lib64/libncursesw.so                                                                                                                                                                                                             
libncurses.so.5 (libc6,x86-64) => /lib64/libncurses.so.5                                                                                                                                                                                                               
libncurses.so.5 (libc6,x86-64) => /usr/lib64/libncurses.so.5                                                                                                                                                                                                           
libncurses.so (libc6,x86-64) => /usr/lib64/libncurses.so                                                                                                                                                                                                               
libncurses++w.so.5 (libc6,x86-64) => /usr/lib64/libncurses++w.so.5                                                                                                                                                                                                     
libncurses++w.so (libc6,x86-64) => /usr/lib64/libncurses++w.so                                                                                                                                                                                                         
libncurses++.so.5 (libc6,x86-64) => /usr/lib64/libncurses++.so.5                                                                                                                                                                                                       
libncurses++.so (libc6,x86-64) => /usr/lib64/libncurses++.so
```

```bash
$ which ldconfig
/sbin/ldconfig
```

It is worth noting, that `ldconfig` requires root on Slackware, and I'm using stack as a non-priviliged user. How does stack >=1.7.1 execute ldconfig? Some sort of sudo thing?

**Comment by ThomasLocke** [comment] 2018-10-22 08:29
I may have found a solution to this issue:

```yaml
nix:
  enable: true
```

Adding the above to `stack.yaml` appears to solve the issue of installing GHC.

Since I'm not an expert stack user and nix is something completely new to me, I'd love some feedback on the strengths and weaknesses of this solution.

**Comment by ThomasLocke** [comment] 2018-10-22 10:17
@borsboom 

```bash
$ ldconfig -p|grep 'tinfo\|ncurses'
libncursesw.so.5 (libc6,x86-64) => /lib64/libncursesw.so.5
libncursesw.so.5 (libc6,x86-64) => /usr/lib64/libncursesw.so.5
libncursesw.so (libc6,x86-64) => /usr/lib64/libncursesw.so
libncurses.so.5 (libc6,x86-64) => /lib64/libncurses.so.5
libncurses.so.5 (libc6,x86-64) => /usr/lib64/libncurses.so.5
libncurses.so (libc6,x86-64) => /usr/lib64/libncurses.so
libncurses++w.so.5 (libc6,x86-64) => /usr/lib64/libncurses++w.so.5
libncurses++w.so (libc6,x86-64) => /usr/lib64/libncurses++w.so
libncurses++.so.5 (libc6,x86-64) => /usr/lib64/libncurses++.so.5
libncurses++.so (libc6,x86-64) => /usr/lib64/libncurses++.so
```

```bash
$ which ldconfig
/sbin/ldconfig
```

I just executed `/sbin/ldconfig -p` and it returned at long list of stuff, so that part seems to work just fine. (I initially thought ldconfig required root - before I noticed the -p flag)

**Comment by ThomasLocke** [comment] 2018-10-22 10:18
I may have found a solution to this issue:

```yaml
nix:
  enable: true
```

Adding the above to `stack.yaml` appears to solve the issue of installing GHC.

Since I'm not an expert stack user and nix is something completely new to me, I'd love some feedback on the strengths and weaknesses of this solution. For now I'm not really sure how this will affect my haskell-ide-engine  / atom setup.

**Comment by ThomasLocke** [comment] 2018-10-23 07:57
I just installed Slackware -current (sort of a pre-release of the next official Slackware 15.0), and stack >=1.7.1 works just fine here. It does report that it is not a supported distro, but it installed GHC just fine, and compiled a few of my projects without issues.

So this seems to be a problem specific to stack >=1.7.1 and Slackware 14.2.

I'm thinking it's not worth it to spend too much time on this for now. I can live with stack 1.6.5 until Slackware 15.0 emerges.

**Comment by borsboom** [comment] 2018-10-24 12:33
Interesting, it does look like `ldconfig` is behaving the way Stack expects it to and Stack should be able to find those libraries.  I think fixing this will take some debugging work on Slackware itself.

**Comment by rikvdkleij** [comment] 2018-10-27 15:03
I had also a linker issue with installing GHC-8.4.3 on Ubuntu. Deleting `.stack` folder did not help. Could only get it working by enabling nix.

After deleting `.stack` and new attempt to build project:
```
Preparing to install GHC (tinfo6) to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-tinfo6-8.4.3.                                      
Installed GHC.                                                                      
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                                 
Downloading root                                                                                 
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                                 
Downloading timestamp                                                                            
Downloading snapshot                                                                             
Downloading mirrors                                                                              
Cannot update index (no local copy)                                                              
Downloading index                                                                                
Updated package index downloaded                                                                 
Update complete                                                                                  
Populated index cache.    
[1 of 2] Compiling Main             ( /home/rik/.stack/setup-exe-src/setup-mPHDZzAJ.hs, /home/rik/.stack/setup-exe-src/setup-mPHDZzAJ.o )
[2 of 2] Compiling StackSetupShim   ( /home/rik/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /home/rik/.stack/setup-exe-src/setup-shim-mPHDZzAJ.o )
Linking /home/rik/.stack/setup-exe-cache/x86_64-linux-tinfo6/tmp-Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3 ...
/usr/bin/ld.gold: error: cannot find -lgmp
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwplusBigNatWord_info: error: undefined reference to '__gmpn_add_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwminusBigNatWord_info: error: undefined reference to '__gmpn_sub_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwtimesBigNatWord_info: error: undefined reference to '__gmpn_mul_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwgo_info: error: undefined reference to '__gmpn_add'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwminusBigNat_info: error: undefined reference to '__gmpn_sub'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwtimesBigNat_info: error: undefined reference to '__gmpn_mul'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_neqIntegerzh_info: error: undefined reference to '__gmpn_cmp'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_neqIntegerzh_info: error: undefined reference to '__gmpn_cmp'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_eqIntegerzh_info: error: undefined reference to '__gmpn_cmp'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_eqIntegerzh_info: error: undefined reference to '__gmpn_cmp'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwquotBigNatWord_info: error: undefined reference to '__gmpn_divrem_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_orInteger_info: error: undefined reference to '__gmpn_sub_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_orInteger_info: error: undefined reference to '__gmpn_sub_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_orInteger_info: error: undefined reference to '__gmpn_sub_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwquotRemBigNat_info: error: undefined reference to '__gmpn_tdiv_qr'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_quotRemInteger_info: error: undefined reference to '__gmpn_divrem_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_quotRemInteger_info: error: undefined reference to '__gmpn_divrem_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_quotRemInteger_info: error: undefined reference to '__gmpn_divrem_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_remInteger_info: error: undefined reference to '__gmpn_mod_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):integerzmgmp_GHCziIntegerziType_remInteger_info: error: undefined reference to '__gmpn_mod_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_rshift: error: undefined reference to '__gmpn_rshift'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_rshift_2c: error: undefined reference to '__gmpn_rshift'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_lshift: error: undefined reference to '__gmpn_lshift'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_get_d: error: undefined reference to '__gmpz_get_d'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_get_d: error: undefined reference to '__gmpz_get_d_2exp'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_gcd_word: error: undefined reference to '__gmpn_gcd_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_gcd_1: error: undefined reference to '__gmpn_gcd_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_gcd_1: error: undefined reference to '__gmpn_gcd_1'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_gcd: error: undefined reference to '__gmpz_init'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_gcd: error: undefined reference to '__gmpz_gcd'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_gcd: error: undefined reference to '__gmpz_clear'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_tdiv_q: error: undefined reference to '__gmpn_tdiv_qr'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_tdiv_q: error: undefined reference to '__gmpn_tdiv_qr'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_tdiv_r: error: undefined reference to '__gmpn_tdiv_qr'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_and_n: error: undefined reference to '__gmpn_and_n'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_andn_n: error: undefined reference to '__gmpn_andn_n'
/home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(wrappers.o):function integer_gmp_mpn_ior_n: error: undefined reference to '__gmpn_ior_n'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building simple Setup.hs using:
      /home/rik/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/bin/ghc -rtsopts -threaded -clear-package-db -global-package-db -hide-all-packages -package base -main-is StackSetupShim.mainOverride -package Cabal-2.2.0.1 /home/rik/.stack/setup-exe-src/setup-mPHDZzAJ.hs /home/rik/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -o /home/rik/.stack/setup-exe-cache/x86_64-linux-tinfo6/tmp-Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3
    Process exited with code: ExitFailure 1
```

**Comment by skapazzo** [comment] 2018-11-30 00:16
I encountered the same situation as @ThomasLocke with stack 1.9.1 and on Slackware 14.2.
I solved it by installing ncurses-6 from the slackware-current repo, I'll have to test my system further to see if there are side effects to this.
I also tried installing a libtinfo-5 package (from alienBob, probably the same as ThomasLocke used) but it wasn't recognized by ldconfig (it actually only installs some symlinks as a workaround) and so didn't solve the problem.

**Comment by teto** [comment] 2018-11-30 00:25
Got a similar problem on nixos too.

**Comment by ThomasLocke** [comment] 2018-12-04 08:00
@skapazzo any news on how the ncurses-6 package from -current behaves on Slackware 14.2? Should I dare installing it on my workstation?  :)

**Comment by skapazzo** [comment] 2018-12-04 13:46
@ThomasLocke I haven't encountered any problems yet, ncurses-6 should be highly backwards compatible as far as I know. I haven't tried rebuilding some of the more fragile packages yet, I hope to have time today though, I'll let you know. I also don't know yet if any libtinfo symlinks are needed.
To be safe you could keep an ncurses-5.9 package handy to easily rollback.
It definitely solved the stack issue.

**Comment by skapazzo** [comment] 2018-12-05 13:59
I had some time to look around a bit more and found some other possible solutions:

1. add `ghc-build: standard` to your global stack.yaml. This forces stack to use standard GHC builds and makes it skip the search for these libraries. This seems to be the easiest user-side solution. I tested this briefly with a standard Slackware 14.2 installation plus the alienBob libtinfo package and it looks good for now.
2. add another workaround in Setup.hs in GetGHCBuilds similar to one already present for Arch Linux that looks in /usr/lib64/ for the libraries if `ldconfig -p` fails (now it looks only in /usr/lib/).
The first workaround was added with https://github.com/commercialhaskell/stack/commit/e0b9b13865b3e906dfe3a91a8e458b703503dd88.
This could be another simple solution that doesn't need any user intervention but would still be a workaround, I tested it quickly by recompiling stack with today's commits and it appears to work too (also on a standard slackware14.2 installation with alienBob's libtinfo package). I hope to find time later to clean out my modification and make a fork available to prepare for a possible pull request.

**Comment by skapazzo** [comment] 2018-12-20 11:51
This issue should be solved now. Pinging @ThomasLocke.
The complete solution for slackware 14.2 and probably older versions requires the libtinfo package from Alien BOB (Eric Hameleers) repository or manually creating the appropriate symlinks. Slackware current and future versions shouldn't need this anymore.
It works locally for me with the stock ncurses package, do we need somebody else to test it before closing this issue?

**Comment by ThomasLocke** [comment] 2018-12-21 10:56
:+1:

**Comment by praduca** [comment] 2018-12-25 01:39
I can confirm a very close behaviour on nixos (unstable), and it doesn't appear to be caused by this library. I could even execute  ` stack new test rio`   and compile this test project successfully, but when trying on another project it fails with the above message. (The project  is dino-rush - https://github.com/jxv/dino-rush).
It seems that something other than missing libs is going on, with libtinfo doesn't even been part of nixos and the ncurses libs mentioned making no effect (at least on one of the projects, and the project is a command line one).

**Comment by qrilka** [comment] 2018-12-25 05:59
@praduca `dino-rush` appears to be using LTS-9.14 and that snapshot is based on GHC-8.0.2, NixOS currently appears to be supporting GHC starting with version 8.2.2. I suppose you could either upgrade `dino-rush` to a fresher LTS or use GHC from some of earlier nixpkgs commits

**Comment by snoyberg** [comment] 2019-04-15 08:07
It looks like the original problem on Slackware has been resolved, closing.

**Closed by snoyberg** 2019-04-15 08:07 UTC
Labels: component: installer, further investigation required, new-distro-support
