### ISSUE TITLE
Internal error: unable to commit [ENOUGH] bytes of memory

### ISSUE THREAD

**Issue by tanguyandreani** [commercialhaskell/stack#4232] opened 2018-08-14 14:40 UTC
### General summary/comments (optional)

When running `stack ghci`
 for the first time and it tries to install it I get `Internal error: unable to commit [ENOUGH] bytes of memory` where ENOUGH is approx. a gigabyte. My server has *only* 1G of ram.

BUT, after that, ghci runs fine and is indeed installed in  `.stack`.

I could use a swap file or just upgrade my server but I thought it wasn’t normal for stack to consume such an amount of memory.

### Steps to reproduce

On a DigitalOcean 1G droplet:

1. Install stack
2. `stack ghci`

### Stack version

```
$ stack --version
Version 1.7.1, Git revision [...] x86_64 hpack-0.28.2
```

### Method of installation

*  `curl https://get.haskellstack.org | sh`

**Comment by RoelofWobben** [comment] 2018-08-14 14:50
very wierd.  
So if I understand you well. the installation does not end with a message that stack is installed somewhere.

**Comment by tanguyandreani** [comment] 2018-08-14 14:53
No, unless run in verbose mode.


14. Aoû 2018 16:50 de notifications@github.com <mailto:notifications@github.com>:

**Comment by RoelofWobben** [comment] 2018-08-14 15:06
oke, we will investigate this.

**Comment by tanguyandreani** [comment] 2018-08-14 15:10
I don’t know if it helps but it also happens when running ‘stack ghc’ or just ‘stack’ in a new project for the first time when no ghc is installed.

I encountered the very same error two months ago I believe and I’m pretty sure I solved it by temporarily upgrading my droplet with a few gb of memory.

**Comment by RoelofWobben** [comment] 2018-08-14 15:11
Can you add a swap file to your enviroment and try again to install stack.

**Comment by RoelofWobben** [comment] 2018-08-14 15:12
then it looks not a bug in stack but a problem with your digital ocean enviroment.

**Comment by tanguyandreani** [comment] 2018-08-14 15:15
I’m testing with Fedora 28 right now. (I was using Debian 9.)

**Comment by tanguyandreani** [comment] 2018-08-14 15:29
So it is normal for stack to consume more than 1G of memory for running ? I mean, of course the issue is the memory here since I solved it the issue by adding more.

**Comment by RoelofWobben** [comment] 2018-08-14 18:03
Can you paste a log where we can see where the memory is too little.

**Comment by tanguyandreani** [comment] 2018-08-14 18:09
Here it is: 
http://ix.io/1kbn

**Comment by RoelofWobben** [comment] 2018-08-14 20:43
oke, that problem is well known and being solved in one of the next versions.
Can I close this issue or do you have other questions

**Comment by tanguyandreani** [comment] 2018-08-14 20:44
No it’s fine you can close it. Thanks.

**Closed** 2018-08-14 20:44 UTC
Labels: component: ghci, further investigation required, type: discuss

**Comment by bsdshell** [comment] 2019-07-19 17:14
when I try to use stack build for regex-tdfa, I have the same memory issue in my Ubuntu 1G vm.
