### ISSUE TITLE
Stack not rebuilding

### ISSUE THREAD

**Issue by nnmm** [commercialhaskell/stack#573] opened 2015-07-13 13:05 UTC
I'd expect "stack build" to rebuild the project if I change something in the source directory. This is only the case if I change the Main.hs or .cabal files, for all other files in the source directory, "stack build" exits without doing anything. 

A crude workaround is alternating "stack build" and "stack build --pedantic" (both are succeeding), even though "stack build --pedantic" has the same behavior.

Version 0.1.2.0, Git revision 65246552936b7da4b64b38372feac903d96a8911
Ubuntu 14.04 x86_64

```
executable mybinary
  main-is:            Main.hs
  build-depends:      base
                    , ...
  hs-source-dirs:     src
  default-language:   Haskell2010
```

**Comment by manny-fp** [comment] 2015-07-13 13:07
Thanks for the report, but please see https://github.com/commercialhaskell/stack/blob/master/CONTRIBUTING.md and format the report accordingly, providing the required information.

**Comment by snoyberg** [comment] 2015-07-13 14:24
This is a dupe of https://github.com/commercialhaskell/stack/issues/481, let's track the issue there.

**Closed by snoyberg** 2015-07-13 14:24 UTC
