### ISSUE TITLE
Stack strange behavior: The following packages specified by flags or options are not found: persistent-sqlite yaml

### ISSUE THREAD

**Issue by vrom911** [commercialhaskell/stack#3917] opened 2018-03-13 12:58 UTC
### General summary/comments
I'm trying to move to `nightly-2018-03-13` in [`o-clock`](https://github.com/serokell/o-clock) package. Previously I had [this `stack.yaml`](https://github.com/serokell/o-clock/blob/d1edad1943c3a49b65ac648e68c1b069b04c2ec9/stack.yaml) and it worked fine. Now I'm trying with this `stack.yaml` :
```yaml
resolver: nightly-2018-03-13
```
But it give unexpected and strange error:
```
$ stack build
The following packages specified by flags or options are not found: persistent-sqlite yaml
```
This is weird as I don't have any of these packages in dependencies:
```
$ stack list-dependencies --test --bench
Cabal 2.2.0.0
Glob 0.9.2
HUnit 1.6.0.0
QuickCheck 2.11.3
ansi-terminal 0.8.0.2
ansi-wl-pprint 0.6.8.2
array 0.5.2.0
async 2.1.1.1
base 4.11.0.0
base-compat 0.9.3
basement 0.0.7
binary 0.8.5.1
bytestring 0.10.8.2
call-stack 0.1.0
clock 0.7.2
code-page 0.1.3
colour 2.3.4
concurrent-output 1.10.4
constraints 0.10
containers 0.5.11.0
deepseq 1.4.3.0
directory 1.3.1.5
dlist 0.8.0.4
doctest 0.14.1
exceptions 0.8.3
filepath 1.4.2
gauge 0.2.1
ghc 8.4.1
ghc-boot 8.4.1
ghc-boot-th 8.4.1
ghc-paths 0.1.0.9
ghc-prim 0.5.2.0
ghci 8.4.1
hashable 1.2.7.0
haskell-lexer 1.0.1
hedgehog 0.5.2
hpc 0.6.0.3
hspec 2.4.8
hspec-core 2.4.8
hspec-discover 2.4.8
hspec-expectations 0.8.2
integer-gmp 1.0.1.0
lifted-async 0.9.3.3
lifted-base 0.2.3.11
logict 0.6.0.2
markdown-unlit 0.5.0
mmorph 1.1.1
monad-control 1.0.2.3
mtl 2.2.2
o-clock 1.0.0
optparse-applicative 0.14.2.0
parsec 3.1.13.0
pretty 1.1.3.6
pretty-show 1.6.16
primitive 0.6.3.0
process 1.6.3.0
quickcheck-io 0.2.0
random 1.1
regex-base 0.93.2
regex-tdfa 1.2.3
resourcet 1.2.0
rts 1.0
semigroups 0.18.4
setenv 0.1.1.3
smallcheck 1.1.3.1
stm 2.4.5.0
syb 0.7
tagged 0.8.5
tasty 0.12.0.1
tasty-hedgehog 0.1.0.2
tasty-hspec 1.1.3.3
tasty-quickcheck 0.9.2
tasty-smallcheck 0.8.1
template-haskell 2.13.0.0
terminal-size 0.3.2.1
terminfo 0.4.1.1
text 1.2.3.0
tf-random 0.5
th-lift 0.7.8
tiempo 0.0.1.1
time 1.5.0.1
time-units 1.0.0
transformers 0.5.5.0
transformers-base 0.4.4
transformers-compat 0.6.0.6
type-spec 0.3.0.1
unbounded-delays 0.1.1.0
unix 2.7.2.2
unliftio-core 0.1.1.0
vector 0.12.0.1
wl-pprint-annotated 0.1.0.0
```

Adding `persistent-sqlite` and `yaml` to `extra-deps` doesn't help either.

### Steps to reproduce
1. Clone [`o-clock`](https://github.com/serokell/o-clock) 
2. Change current `stack.yaml` file to use `nightly-2018-03-13` resolver
3. Run `stack build`

### Expected
Build without problem (probably telling me which dependencies are missing in the snapshot).
### Actual
```
$ stack build
The following packages specified by flags or options are not found: persistent-sqlite yaml
```

Here is the output of `stack build --verbose` command : 
* https://gist.github.com/vrom911/c0305debca84dd895d27b28da43df0a7

### Stack version

My `stack` version is 
```
$ stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```
### Method of installation

```
curl -sSL https://get.haskellstack.org/ | sh
```

**Comment by k-bx** [comment] 2018-03-13 13:03
`stack new --resolver nightly-2018-03-13 foo simple-hpack` command fails with the same error

**Comment by mgsloan** [comment] 2018-03-13 19:53
Yes, this is indeed weird behavior.  It was caused by a rather ugly hack which is fixed in the development version of stack - https://github.com/commercialhaskell/stack/pull/3916 .  Looks like there might be a bugfix release soon with the fix.

Hopefully we'll be able to get those packages back into stackage, so that this won't be an issue for any lts snapshots.

**Closed by mgsloan** 2018-03-13 19:53 UTC
