### ISSUE TITLE
Correct "stack test --coverage" results requires a "stack clean"

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1411] opened 2015-11-24 03:49 UTC
I found this while turning https://github.com/mgsloan/multi-test-suite into an integration test.  Running `stack test` followed by `stack test --coverage` results in empty coverage reports.  This appears to be an issue with GHC recompilation checking, as instead doing `stack test --coverage --ghc-options -fforce-recomp` solves the problem.

I'm not sure what to do about this.  The best thing I can think of is a bit tricky - detect when this flag is newly enabled or disabled and supply `--ghc-options --fforce-recomp` for this circumstance.

**Comment by borsboom** [comment] 2016-01-06 14:59
On OS X, the `--ghc-options -fforce-recomp` seems to trigger this build error:

    ld: -rpath can only be used when creating a dynamic final linked image
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sjakobi** [comment] 2016-04-25 10:35
Looks like #1997 is related, possibly a duplicate.

**Comment by mpilgrem** [comment] 2023-09-23 22:38
The `stack.yaml` in the original repository was using lts-3.9 (GHC 7.10.2), which is no longer supported by modern Stack. I can't reproduce any problem with `stack test` followed by `stack text --coverage`, so I am going to close this issue.

**Closed by mpilgrem** 2023-09-23 22:38 UTC
Labels: type: bug
