### ISSUE TITLE
`stack install` to a specific destination.

### ISSUE THREAD

**Issue by zimbatm** [commercialhaskell/stack#539] opened 2015-07-07 16:38 UTC
I have a project managed by stack and everything is going well during development. Now I want to distribute the resulting binaries.

Usually C projects have either a `--prefix` argument during the `./configure` step or `make install` accepts a DEST or PREFIX argument. Some other packaging systems (like rubygems) also have the `--user` vs `--system` switches. I couldn't find anything equivalent in the `stack install` command.

**Steps to reproduce:**

1. `stack install --help` and look for a destination option

**Expected:**

`stack install --help` has a destination option. Let's say `--prefix PATH` such as:
```
$ stack install --prefix /usr/local my-project
Copying from /Users/zimbatm/code/github.com/zimbatm/my-project/.stack-work/install/x86_64-osx/lts-2.7/7.8.4/bin/my-project to /usr/local/bin/my-project

Installed executables to /usr/local/bin/:
- my-project
```

**Actual:**

```
$ stack install my-project
Copying from /Users/zimbatm/code/github.com/zimbatm/my-project/.stack-work/install/x86_64-osx/lts-2.7/7.8.4/bin/my-project to /Users/zimbatm/.local/bin/my-project

Installed executables to /Users/zimbatm/.local/bin/:
- my-project
```
Well you get the point
 
 ```
$ stack --version
Version 0.1.2.0, Git revision 65246552936b7da4b64b38372feac903d96a8911
```

EDIT: I tried looking in the code where `$HOME/.local/bin` is set but couldn't find it. I think it's because stack is invoking `cabal install`

**Comment by radix** [comment] 2015-07-07 16:52
This is a duplicate of #342.

**Closed by radix** 2015-07-07 16:52 UTC
