### ISSUE TITLE
Docker-based stack build fails with permission denied

### ISSUE THREAD

**Issue by jrryjcksn** [commercialhaskell/stack#2921] opened 2017-01-13 21:31 UTC
### General summary/comments
I've been trying to learn stack and following the basic tutorial. I have a very simple app and I tried to enable docker for builds. Whenever I run with docker enabled in my stack.yaml, I get a permission error unless I turn off set-user:
~~~~
> stack build
/opt/stackage/lts-7/ghc/lib/ghc-8.0.1/package.conf.d: canonicalizePath: permission denied (Permission denied)
~~~~
If I turn off set-user, the build succeeds but my output files are owned by root.

### Steps to reproduce

Create a new simple app:
~~~~
jrj-centos:/tmp> stack new simple simple
Downloading template "simple" to create project "simple" in simple/ ...
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- simple/simple.cabal

Selecting the best among 9 snapshots...

* Matches lts-7.15

Selected resolver: lts-7.15
Initialising configuration using resolver: lts-7.15
Total number of user packages considered: 1
Writing configuration to file: simple/stack.yaml
All done.
~~~~
Update stack.yaml to include:
~~~~
docker:
  enable: true
~~~~

Build with docker:
~~~~
jrj-centos:/tmp> cd simple/
jrj-centos:/tmp/simple> stack build
/opt/stackage/lts-7/ghc/lib/ghc-8.0.1/package.conf.d: canonicalizePath: permission denied (Permission denied)
~~~~

### Expected
I expected the build to work as it does without docker.

### Actual
I got a permission denied error.
Here is the verbose output:

https://gist.github.com/jrryjcksn/99a4a17fce0a71169be2582123657ad6

### Stack version
jrj-centos:/tmp/simple> stack --version
Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 (4395 commits) x86_64 hpack-0.15.0

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

Running on CentOS 7 (VM)

**Comment by utdemir** [comment] 2017-01-14 00:08
I had a similar problem, and I remember setting 

```
docker: 
  enable: true
  set-user: false
```

fixed it.

**Comment by jrryjcksn** [comment] 2017-01-14 00:17
Thank you. I also tried that and the build worked so it's a good workaround
but all the output files ended up owned by root. I can deal with that but I
believe it's still a bug. :-)

Best regards,
--Jerry

**Comment by Tritlo** [comment] 2017-01-16 14:20
I am having the same error. I tried again, setting the resolver to 7.14 and sourcing from fpco/stack-build:lts-7.14, and it seems to be working fine. The error is then probably from some change in the base docker image between 7.14 and 7.15.

**Comment by jrryjcksn** [comment] 2017-01-16 14:40
Thank you for the help! I'll switch to 7.14.

**Comment by borsboom** [comment] 2017-01-16 23:57
Looks like a duplicate of #2919, closing in favour of the (slightly) earlier issue.

**Comment by borsboom** [comment] 2017-01-17 12:56
@jrryjcksn Did switching to lts-7.14 work?

**Comment by jrryjcksn** [comment] 2017-01-17 15:46
No, I'm getting the same error.

**Comment by borsboom** [comment] 2017-01-17 19:08
Can you try the just-pushed `lts-16`?

**Comment by jrryjcksn** [comment] 2017-01-17 22:43
Same behavior :-(


On Tue, Jan 17, 2017 at 12:08 PM, Emanuel Borsboom <notifications@github.com

**Comment by borsboom** [comment] 2017-02-19 21:32
I was able to reproduce this on CentOS 7.0 and 7.2, using docker's `overlay` and `devicemapper` storage driver.  It is now fixed on the master branch.  Please re-open this issue if you upgrading to the latest code doesn't fix for you.

```
$ stack --version
Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 (4395 commits) x86_64 hpack-0.15.0

$ stack build
/opt/stackage/lts-7/ghc/lib/ghc-8.0.1/package.conf.d: canonicalizePath: permission denied (Permission denied)

$ stack upgrade --git --source-only
Cloning stack
Cloning into 'stack'...
[...]
Copied executables to /home/vagrant/.local/bin:
- stack

$ hash -r

$ stack --version
Version 1.3.3, Git revision 9571c194e36b15b592b0c3cd6d4e69781fd80726 x86_64 hpack-0.17.0

$ stack build
simple-0.1.0.0: configure (exe)
Configuring simple-0.1.0.0...
simple-0.1.0.0: build (exe)
Preprocessing executable 'simple' for simple-0.1.0.0...
[1 of 1] Compiling Main             ( src/Main.hs, .stack-work/dist/x86_64-linux-dk8f95e9fa3844906120c49d668d3f868f/Cabal-1.24.0.0/build/simple/simple-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux-dk8f95e9fa3844906120c49d668d3f868f/Cabal-1.24.0.0/build/simple/simple ...
simple-0.1.0.0: copy/register
Installing executable(s) in
/home/vagrant/simple/.stack-work/install/x86_64-linux-dk8f95e9fa3844906120c49d668d3f868f/lts-7.15/8.0.1/bin
```

**Closed by borsboom** 2017-02-19 21:32 UTC
Labels: resolution: duplicate
