### ISSUE TITLE
Cannot build only a single component

### ISSUE THREAD

**Issue by ksvanhorn** [commercialhaskell/stack#1554] opened 2015-12-22 03:28 UTC
I've been going through the "In-depth guide to stack" document at https://www.fpcomplete.com/blog/2015/08/new-in-depth-guide-stack. In the section "Components, --test, and --bench", when I follow along and do "stack clean" followed by "stack build :helloworld-test", stack insists on building everything, including building and installing the executable. According to all documentation I can find, it should not build the executable.

Here is the full output I get:
[output.txt](https://github.com/commercialhaskell/stack/files/69268/output.txt)

**Comment by mgsloan** [comment] 2015-12-23 01:19
Stack can build a single component.  The issue is that it needs to build all the executables along with the library.  This happened due to a few things:

* https://github.com/commercialhaskell/stack/issues/1203 causing a move to `copy` + `register` instead of `install`

* The copy command fails when building only some executables: https://github.com/haskell/cabal/issues/2780

Closing as a dupe of https://github.com/commercialhaskell/stack/issues/1406 , and bumping that issue's priority.

**Closed by mgsloan** 2015-12-23 01:19 UTC
