### ISSUE TITLE
stack ghci TARGET fails to change directory to target, TemplateHaskell relative paths will be off.

### ISSUE THREAD

**Issue by AaronFriel** [commercialhaskell/stack#674] opened 2015-07-25 20:47 UTC
To demonstrate this, set up a new stack.yaml, and install a yesod project in a subdirectory. I have done this here:

https://github.com/AaronFriel/stackghcibug

In the repository root (`./stackghcibug`) try this command:

```
stack ghci yesod-project
```

This will fail with this error:

```
[1 of 8] Compiling Settings         ( /home/developer/github/stackghcibug/yesod-project/Settings.hs, interpreted )

/home/developer/github/stackghcibug/yesod-project/Settings.hs:103:25:
    Exception when trying to run compile-time code:
      config/settings.yml: openBinaryFile: does not exist (No such file or directory)
    Code: embedFile configSettingsYml
    In the splice: $(embedFile configSettingsYml)
Failed, modules loaded: none.
>
```

The problem is that `stack ghci TARGET` does not change directory to the target, and relative paths will not resolve correctly for, e.g., TemplateHaskell.

A workaround is to do this instead:

```
$ cd TARGET/
$ stack --stack-yaml ../stack.yaml ghci TARGET
```

This should be the default behavior of `stack ghci`.

**Comment by chrisdone** [comment] 2015-08-06 18:32
Cloning and building to reproduce.

**Comment by snoyberg** [comment] 2015-10-09 05:55
I think we're going to need to close this as wontfix. This won't be solvable in the general case because once there are multiple packages involved, we can't tell ghci about two different working directories. Instead of trying to do something semi-smart, I recommend we just keep it simple: don't change the working directory, and make the working directory be the user's responsibility.

**Closed by snoyberg** 2015-10-09 05:55 UTC
Labels: component: ghci, need repro, resolution: wontfix
