### ISSUE TITLE
--haddock ignored from outside a project

### ISSUE THREAD

**Issue by osbugs** [commercialhaskell/stack#2600] opened 2016-09-15 19:10 UTC
In my global configuration `.stack/global-project/stack.yaml` I have:

```
build:
  haddock: true
  haddock-deps: true
```

However, when building the `free` package using `stack install free` I get:

```
…
free-4.12.4: configure
free-4.12.4: build
free-4.12.4: copy/register
Completed 19 action(s).
```

Please notice the absence of the call to haddock. On the other hand, when I compile using `stack install free --haddock`, haddock gets called as expected:

```
free-4.12.4: configure
free-4.12.4: build
free-4.12.4: haddock
free-4.12.4: copy/register
Completed 19 action(s).
Updating Haddock index for snapshot packages in
/home/thomas/.stack/snapshots/x86_64-linux/lts-7.0/8.0.1/doc/index.html
```

So it seems to me as if stack was ignoring the haddock option from the global configuration file.

**Comment by mgsloan** [comment] 2016-09-26 02:21
I believe this is because haddocking dependencies is done on a by-need basis, in order to document local packages.

What do you think, @borsboom ?  Should `haddock: true` apply to non-local packages?

**Comment by mgsloan** [comment] 2017-03-18 23:52
I can't reproduce this issue, so closing as need-repro:

```
mgsloan@computer:~/fpco/test-stack/issue2705$ mv ~/.stack/ ~/.stack-old
mgsloan@computer:~/fpco/test-stack/issue2705$ stack test
Downloaded lts-8.5 build plan.    
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                                 
Downloading root                                                                                 
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                                 
Downloading timestamp                                                                            
Downloading snapshot                                                                             
Downloading mirrors                                                                              
Cannot update index (no local copy)                                                              
Downloading index                                                                                
Updated package list downloaded                                                                  
Populated index cache.                                                                           
Warning: File listed in issue2705.cabal file does not exist: README.md
[1 of 2] Compiling Main             ( /home/mgsloan/.stack/setup-exe-src/setup-mPHDZzAJ.hs, /home/mgsloan/.stack/setup-exe-src/setup-mPHDZzAJ.o )
[2 of 2] Compiling StackSetupShim   ( /home/mgsloan/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /home/mgsloan/.stack/setup-exe-src/setup-shim-mPHDZzAJ.o )
Linking /home/mgsloan/.stack/setup-exe-cache/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/tmp-Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 ...
issue2705-0.1.0.0: configure (lib + exe + test)
Configuring issue2705-0.1.0.0...
issue2705-0.1.0.0: build (lib + exe + test)
Preprocessing library issue2705-0.1.0.0...
[1 of 1] Compiling Lib              ( src/Lib.hs, .stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-1.24.2.0/build/Lib.o )
Preprocessing executable 'issue2705-exe' for issue2705-0.1.0.0...
[1 of 1] Compiling Main             ( app/Main.hs, .stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-1.24.2.0/build/issue2705-exe/issue2705-exe-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-1.24.2.0/build/issue2705-exe/issue2705-exe ...
Preprocessing test suite 'issue2705-test' for issue2705-0.1.0.0...
[1 of 1] Compiling Main             ( test/Spec.hs, .stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-1.24.2.0/build/issue2705-test/issue2705-test-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-1.24.2.0/build/issue2705-test/issue2705-test ...
Warning: File listed in issue2705.cabal file does not exist: README.md
issue2705-0.1.0.0: copy/register
Installing library in
/home/mgsloan/fpco/test-stack/issue2705/.stack-work/install/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/lts-8.5/8.0.2/lib/x86_64-linux-ghc-8.0.2/issue2705-0.1.0.0-AuYk635UKm79MA9kwgNCye
Installing executable(s) in
/home/mgsloan/fpco/test-stack/issue2705/.stack-work/install/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/lts-8.5/8.0.2/bin
Registering issue2705-0.1.0.0...
issue2705-0.1.0.0: test (suite: issue2705-test)
             
Progress: 1/2Test suite not yet implemented                                                                                                       
Completed 2 action(s).
```

**Closed by mgsloan** 2017-03-18 23:52 UTC
Labels: type: discuss
