### ISSUE TITLE
Up-to-date check is not working properly on Windows

### ISSUE THREAD

**Issue by Pzixel** [commercialhaskell/stack#5143] opened 2020-01-08 17:18 UTC
### Steps to reproduce

1. Create a new "Hello world" project
2. Run command `stack run`. Observe "Hello world" in output as expected
3. Make it non-compiling (e.g. create function without an accompanying binding)
4. Run command `stack run`. See compilation error (as expected)
5. Run command `stack run`.

### Expected

Compilation failes as per step 4

### Actual

"Hello world" is prompted as per step 2

If you suspect that a stack command misbehaved, please include the output of that command in `--verbose` mode.

Vebose log: https://gist.github.com/Pzixel/9d171ea09cc02f6ebb2580b474c4f280

### Stack version

```
$ stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary

### Related pictures

![image](https://user-images.githubusercontent.com/11201122/72000308-12118080-3254-11ea-9c4c-eb3d47fa5357.png)

**Comment by mpilgrem** [comment] 2024-03-11 00:18
I am closing this issue given the passage of time and because I could not reproduce the problem with Stack 2.15.3 on Windows 11.

**Closed by mpilgrem** 2024-03-11 00:18 UTC
