### ISSUE TITLE
`stack ghci` doesn't work while `stack build` does

### ISSUE THREAD

**Issue by Fuuzetsu** [commercialhaskell/stack#665] opened 2015-07-23 09:44 UTC
I have a project here where `stack build` works happily but `stack ghci` does not. I would expect that if `stack build` can build the project, `stack ghci` should have no problem giving me a repl. I inline the description of the particular issue from the mailing list:

```
We have a test with

#include <Rversion.h>

This is provided by the R language. On my system, the R/lib is in a
non-standard location.

Nevertheless, my CPP/gcc are wrapped in a script which uses NIX_LDFLAGS
env var which amongst other things has
-L/nix/store/jvvpcckvzybr7y0zmj1x5psb5sy7ipa7-R-3.2.1/lib

So everything works when I stack build.

But when I try to use ‘stack ghci’ on the project, I get

     fatal error: Rversion.h: No such file or directory
     #include <Rversion.h>

Is there anything I can do so ‘stack ghci’ just works like ‘stack build’
does?
```

In my case it is about CPP being used but this is a bit of a general question.

Using stack from a day or so old git checkout.

**Comment by rrnewton** [comment] 2015-07-24 16:47
The [LVish project](https://github.com/iu-parfunc/lvars/tree/83bdeea8f3fef052ee491e852bf4ad0f5efda663) is also one where stack build works and `stack ghci` fails on stack 0.1.2.0.  In its case it fails with the following on Mac OS:

```
$ stack ghci
Configuring GHCi with the following packages: concurrent-skiplist, lvish, par-classes, par-collections, test-par-collections, par-mergesort, par-transformers
GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
<command line>: cannot satisfy -package criterion
    (use -v for more information)
```

Well, I also think it is too bad that `stack ghci` stops working when a build error breaks `stack build`.  That is, a lot of the time I want to poke around in the repl, or at least use the dependencies when I just broke the build.  For example, with stack itself, if you put garbage in a module (say, `Main.hs` for the executable), then:

```
$ stack ghci
Configuring GHCi with the following packages: stack
GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
<command line>: cannot satisfy -package stack
    (use -v for more information)
```

**Comment by Fuuzetsu** [comment] 2015-07-24 17:27
Yes, test/bench dependencies are another thing that doesn't work out of the box in `stack ghci` though I can somewhat forgive that seeing as the default is ‘load everything’. Still, it could be smarter.

**Comment by duplode** [comment] 2015-07-26 22:51
> That looks like maybe a mixup with the dependencies of the different targets. I.e. `criterion` should only be required for benchmark targets, and thus wasn't built by `stack build`alone.

I met the same issue when trying to use my GitHub fork of `zip-conduit` as a dependency, like this:

``` yaml
# stack.yaml snippet.
packages:
- '.'
- location:
    git: https://github.com/duplode/zip-conduit
    commit: 1eefc8bd91d5f38b760bce1fb8dd16d6e05a671d
    extra-dep: true
```

In such a situation one would never be interested in running the benchmarks of `zip-conduit`, as it is just another dependency. Adding the `extra-dep` flag didn't help.

**Comment by duplode** [comment] 2015-07-27 01:28
> Adding the extra-dep flag didn't help.

Never mind my complaint above - the `extra-dep` field is wrongly indented. Still, my (non-)issue has lead me to wonder whether it would be appropriate to fix this with a `treat-as-dep-in-ghci` field (ideally with a less clunky name). By the way, the "load everything in GHCi" behaviour is, as implied in Fuuzetsu's comment, by design. See #130 for the rationale.

**Comment by chrisdone** [comment] 2015-08-06 18:19
Continuing test/bench dependencies in #629 with PR #726.

**Comment by chrisdone** [comment] 2015-08-06 18:33
@Fuuzetsu Do you have a minimal test project I can clone to reproduce and fix?

**Comment by mitchellwrosen** [comment] 2015-08-09 04:08
@chrisdone I can describe how to make one, it's simple:

```
$ stack new
$ vi new-template.cabal
-- add 'tasty' dependency to new-template-test suite
$ stack build
$ stack ghci
Configuring GHCi with the following packages: new-template
GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
<command line>: cannot satisfy -package tasty
    (use -v for more information)
```

**Comment by chrisdone** [comment] 2015-08-09 15:15
I think @mitchellwrosen your problem differs to that of @Fuuzetsu.

**Comment by Fuuzetsu** [comment] 2015-08-09 17:38
Yes, it does. I'm a bit constrained on time right now but maybe I can produce something soon, sorry for delays.

**Comment by mitchellwrosen** [comment] 2015-08-09 17:42
Oops, I was looking at @rrnewton's comment. Sorry!

**Comment by rpglover64** [comment] 2015-08-18 18:51
I think I'm having this same issue... to reproduce:

```
git clone https://github.com/Gabriel439/Haskell-Turtle-Library.git
cd Haskell-Turtle-Library
git checkout da98f7e
stack init
stack build
stack ghci
```
Expected behavior: ghci is launched with the project loaded
Actual behavior:
```
Configuring GHCi with the following packages: turtle
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
<command line>: cannot satisfy -package criterion-1.1.0.0
    (use -v for more information)
```

**Comment by chrisdone** [comment] 2015-08-18 19:17
@rpglover64 Are you on a recent stack?

**Comment by rpglover64** [comment] 2015-08-18 19:19
Version 0.1.3.0, Git revision 385332dc7bdc98e541358ec6f191a727adb75cb4

**Comment by chrisdone** [comment] 2015-08-18 19:36
Your problem's been fixed since then, try latest master. :-)

**Comment by rpglover64** [comment] 2015-08-18 19:39
I'm _almost_ annoyed at how fast stack is moving... On the other hand, my issues are getting fixed. :smiley: 

Thanks.

**Comment by ezyang** [comment] 2015-09-02 06:36
Hi guys, I've opened a GHC ticket to track this issue. https://ghc.haskell.org/trac/ghc/ticket/10827

**Comment by chrisdone** [comment] 2015-09-02 09:43
Thanks @ezyang!

**Comment by mgsloan** [comment] 2015-11-05 06:45
I'm going to close this issue, since it's old and the GHCi support has had lots of improvements since then.  Feel free to open additional issues with concrete cases of the GHCI support being problematic.

Also, I've added some warnings which hopefully will make it clearer why things don't work, at least in the presence of extension flags: https://github.com/commercialhaskell/stack/issues/1270

**Closed by mgsloan** 2015-11-05 06:45 UTC
Labels: blocked, component: ghci, type: bug
