### ISSUE TITLE
Error while building `basement` with GHC 9.6.5 on Linux/x86_64

### ISSUE THREAD

**Issue by dan010** [commercialhaskell/stack#6599] opened 2024-06-04 01:50 UTC
Encountered the error below while building the rpki-prover. I have been stacked for weeks on this error

**basement                     > hsc2hs-ghc-9.6.5: .stack-work/dist/x86_64-linux-tinfo6/ghc-9.6.5/build/Basement/Terminal/Size_hsc_make: createProcess: posix_spawnp: permission denied (Permission denied)**

**Comment by mpilgrem** [comment] 2024-06-04 10:44
@dan010, I see you are on Linux/x86_64 - what distribution? Also, what snapshot? Is your problem specific to GHC 9.6.5 and `hsc2hs-ghc-9.6.5`?

I see https://github.com/haskell-foundation/foundation has been archived since 2023-09-20. Does that mean `basement` is no longer maintained?

**Comment by mpilgrem** [comment] 2024-06-04 10:55
On Ubuntu 22.04.13 (via WSL 2), I could not reproduce a problem building `basement` in isolation:
~~~text
$ stack unpack basemnent
$ cd basement-0.0.16
$ stack init # Picks lts-22.24 (GHC 9.6.5)
$ stack build
~~~

**Comment by mpilgrem** [comment] 2024-06-04 11:15
Describe your Stack setup: what version are you using (`stack --version`)? How did you install Stack?

**Comment by dan010** [comment] 2024-06-04 11:55
> Describe your Stack setup: what version are you using (`stack --version`)? How did you install Stack?
> 
> EDIT: Can you build `basement` in isolation, like I did in my post above?

The version of stack is **Version 2.15.7, Git revision f590e0165b5ab92f5f7f87f8aa55852e1972ee25 x86_64 hpa ck-0.36.0**

and this is the command that I used to install the stack **curl -sSL https://get.haskellstack.org/ | sh**

**Comment by mpilgrem** [comment] 2024-06-04 22:22
I could not reproduce the problem building `rpki-prover` on Ubuntu 22.04.13 (via WSL 2):
~~~text
$ git clone https://github.com/lolepezy/rpki-prover.git
$ cd rpki-prover
$ cp package-template.yaml package.yaml
$ sudo apt-get install ... # Install missing C libraries
$ stack build
...
rpki-prover                  > copy/register
Installing library in .../rpki-prover/.stack-work/install/x86_64-linux-tinfo6/29f0bb150080a27478147fb33b836f432c34eac00995111c1e969189e12a621d/9.6.5/lib/x86_64-linux-ghc-9.6.5/rpki-prover-0.9.3-2RYavTphtkE8c7OjKmjC4C
Installing executable rpki-prover in .../rpki-prover/.stack-work/install/x86_64-linux-tinfo6/29f0bb150080a27478147fb33b836f432c34eac00995111c1e969189e12a621d/9.6.5/bin
Registering library for rpki-prover-0.9.3..
Completed 179 action(s).
~~~

**Comment by hasufell** [comment] 2024-06-04 23:53
> I think my problem is on .stack-work symlinked onto a noexec filesystem since it have a permission denied on error message. 

I don't think noexec filesystems are expected to work.

**Comment by dan010** [comment] 2024-06-05 02:18
> I could not reproduce the problem building `rpki-prover` on Ubuntu 22.04.13 (via WSL 2):
> 
> ```
> $ git clone https://github.com/lolepezy/rpki-prover.git
> $ cd rpki-prover
> $ cp package-template.yaml package.yaml
> $ sudo apt-get install ... # Install missing C libraries
> $ stack build
> ...
> rpki-prover                  > copy/register
> Installing library in .../rpki-prover/.stack-work/install/x86_64-linux-tinfo6/29f0bb150080a27478147fb33b836f432c34eac00995111c1e969189e12a621d/9.6.5/lib/x86_64-linux-ghc-9.6.5/rpki-prover-0.9.3-2RYavTphtkE8c7OjKmjC4C
> Installing executable rpki-prover in .../rpki-prover/.stack-work/install/x86_64-linux-tinfo6/29f0bb150080a27478147fb33b836f432c34eac00995111c1e969189e12a621d/9.6.5/bin
> Registering library for rpki-prover-0.9.3..
> Completed 179 action(s).
> ```

I am using a rhel 9 not ubuntu.

**Comment by mpilgrem** [comment] 2024-06-05 09:06
@dan010, I don't have access to Red Hat Enterprise Linux 9, but it seems to me unlikely that it cannot do what Ubuntu 22.04.13 can do.

On the subject a 'no-exec' filesystem, your original problem appears to be with the `hsc2hs-ghc-9.6.5` executable. That executable is located in the same directory as GHC itself (see `stack path --compiler-bin` for its location). What is does is create a C program that gets automatically compiled and run. That program outputs Haskell code. See: https://downloads.haskell.org/ghc/9.6.5/docs/users_guide/utils.html#writing-haskell-interfaces-to-c-code-hsc2hs

I assume that happens in the Cabal library's `dist` directory (see `stack path --dist-dir` for its location). If that location is somewhere where an executable file is forbidden to execute, then it is not surprising that your build is failing. The solution is to move the Haskell project to a location where executables can execute.

**Comment by dan010** [comment] 2024-06-06 07:27
> @dan010, I don't have access to Red Hat Enterprise Linux 9, but it seems to me unlikely that it cannot do what Ubuntu 22.04.13 can do.
> 
> On the subject a 'no-exec' filesystem, your original problem appears to be with the `hsc2hs-ghc-9.6.5` executable. That executable is located in the same directory as GHC itself (see `stack path --compiler-bin` for its location). What is does is create a C program that gets automatically compiled and run. That program outputs Haskell code. See: https://downloads.haskell.org/ghc/9.6.5/docs/users_guide/utils.html#writing-haskell-interfaces-to-c-code-hsc2hs
> 
> I assume that happens in the Cabal library's `dist` directory (see `stack path --dist-dir` for its location). If that location is somewhere where an executable file is forbidden to execute, then it is not surprising that your build is failing. The solution is to move the Haskell project to a location where executables can execute.

Here is the output of stack path --dist-dir
**Warning: Warning (added by new or init): Some packages were found to be
         incompatible with the resolver and have been left commented out in the
         packages section. You can omit this message by removing it from
         stack.yaml
.stack-work/dist/x86_64-linux-tinfo6/ghc-9.4.8**

when I tried to access this path .stack-work/dist/x86_64-linux-tinfo6/ghc-9.4.8 it return no such file or directory

**Comment by mpilgrem** [comment] 2024-06-06 12:23
@dan010, that output is odd on two counts:
* the first message is because a [`user-message:` key](https://docs.haskellstack.org/en/stable/yaml_configuration/#user-message) has been added to the project-level configuration file (`stack.yaml`), but that key is absent from the file that is included with the project https://github.com/lolepezy/rpki-prover/blob/master/stack.yaml; and
* GHC 9.4.8 is specified by the LTS 21.22 to 21.25 [snapshots](https://www.stackage.org/lts-21.25), but that is not the snapshot/resolver specified by that project.

I suggest you start from scratch:
* delete the Stack root (likely `~/.stack`, `stack path --stack-root` will confirm where)
* perhaps, also delete the Stack executable (at `which stack`) and reinstall Stack
* delete the `rpki-prover` project directory and re-clone it (somewhere where executables have permission to execute)

**Comment by dan010** [comment] 2024-06-07 00:50
> @dan010, that output is odd on two counts:
> 
> * the first message is because a [`user-message:` key](https://docs.haskellstack.org/en/stable/yaml_configuration/#user-message) has been added to the project-level configuration file (`stack.yaml`), but that key is absent from the file that is included with the project https://github.com/lolepezy/rpki-prover/blob/master/stack.yaml; and
> * GHC 9.4.8 is specified by the LTS 21.22 to 21.25 [snapshots](https://www.stackage.org/lts-21.25), but that is not the snapshot/resolver specified by that project.
> 
> I suggest you start from scratch:
> 
> * delete the Stack root (likely `~/.stack`, `stack path --stack-root` will confirm where)
> * perhaps, also delete the Stack executable (at `which stack`) and reinstall Stack
> * delete the `rpki-prover` project directory and re-clone it (somewhere where executables have permission to execute) - follow the same steps as those I set out above.

Do you have a recommended way on how to reinstall the stack?

**Comment by mpilgrem** [comment] 2024-06-07 15:11
@dan010, you have two main choices to install Stack:
* what you did before: https://docs.haskellstack.org/en/stable/install_and_upgrade/
* install GHCup, and use that tool to manage versions of Stack: https://www.haskell.org/ghcup/

You'll want to install GHCup anyway if (a) you are using the Haskell add-ins for popular code file editors, such as Visual Studio Code and/or (b) you are using Cabal (the tool).

**Comment by dan010** [comment] 2024-06-07 15:14
> @dan010, you have two main choices to install Stack:
> 
> * what you did before: https://docs.haskellstack.org/en/stable/install_and_upgrade/
> * install GHCup, and use that tool to manage versions of Stack: https://www.haskell.org/ghcup/
> 
> You'll want to install GHCup anyway if (a) you are using the Haskell add-ins for popular code file editors, such as Visual Studio Code and/or (b) you are using Cabal (the tool).

I also tried to install GHCup but I encountered error as well.

**Comment by mpilgrem** [comment] 2024-06-13 09:24
@dan010, absent better information about how the system on which you are seeking to use Haskell tools is configured and what you are experiencing when you try to install/use them, I think I can't provide further help. It does not appear to relate to Stack's code base. GHCup's repository is here: https://github.com/haskell/ghcup-hs/issues. Can we close this issue?

**Closed** 2024-07-12 22:24 UTC
Labels: needs reproduction, further investigation required, component: build, component: linux
