### ISSUE TITLE
An extra-dep that is an executable (like yesod-bin) is not built with 'stack build'

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack#1581] opened 2015-12-30 20:59 UTC
See [Snowdrift master](https://github.com/snowdriftcoop/snowdrift.git) e.g. [0f698958d374e43ae277014d2545592611043824](https://github.com/snowdriftcoop/snowdrift/commit/630af0c79b424f1ee2d1c1fb90877452205d9e37).

On that commit, "stack build" won't build the yesod-bin fork specified in the stack.yaml. "stack build yesod-bin" does build it, however, and then "stack exec -- yesod" runs the correct version of the utility.

```
$ rm -fr .stack-work
$ stack build
....
Completed 8 action(s).
$ stack exec -- which yesod
/home/b/.local/bin/yesod  #    <--- :(
$ stack build yesod-bin
....
$ stack exec -- which yesod
/home/b/src/Haskell/snowdrift/sd-original/.stack-work/install/x86_64-linux/lts-3.6/7.10.2/bin/yesod # <---  :)
```

I would expect "stack build" to build the version of yesod-bin listed in the yaml.

**Comment by luigy** [comment] 2015-12-30 23:11
>Whether a package should be treated as a dependency: a package marked `extra-dep: true` will only be built if demanded by a non-dependency, and its test suites and benchmarks will not be run.

the behavior should be more clear after #1501

**Comment by mgsloan** [comment] 2015-12-30 23:12
Dupe of https://github.com/commercialhaskell/stack/issues/250 .

One option would be to not treat it as an extra-dep.  Another option would be to add it as a `build-tool` in some cabal file.

I think the recommended option is just to know that you need to `stack build yesod-bin`.

**Closed by mgsloan** 2015-12-30 23:12 UTC
