### ISSUE TITLE
00-index.tar does not exist

### ISSUE THREAD

**Issue by rrnewton** [commercialhaskell/stack#1147] opened 2015-10-12 13:15 UTC
[In this log](http://tester-lin.soic.indiana.edu:8080/job/ghostbuster_gadts/342/STACK_YAML=stack.yaml,label=hive/console), we had the following failure:

```
/u/parfunc/.stack/indices/Hackage/00-index.tar: openBinaryFile: does not exist (No such file or directory)
```

That's a new one to me.  This was with stack `0.1.3.0`.  I upgraded these systems to 0.1.5 and I'll see if this continues to happen.

The thing is... subsequent stack invocations managed to fix the problem.  So either it was intrinsically transient (race condition) or they repaired it (yay).  I imagine with `global-stack-root` (`~/.stack`) being in NFS, race conditions would be more likely to manifest.  (BUT this was _with_ locking!!)

**Comment by CodyReichert** [comment] 2016-04-04 17:48
Hi, I think I can reproduce this problem (at least, there's _one_ way to repro this):

1. Our `stack.yaml` contains the following for package-indicies:

```yaml
resolver: lts-5.10
package-indices:
  - name: hackage
    ...
    gpg-verify: true
    require-hashes: true
```
(there's more, but the GPG part is all that matters)

2. Update the `resolver` LTS version and run `stack build` in the root directory.
3. It's starts the process:
```
Caching build plan
Fetched package index.
...
```
But since I **don't** have a GPG key it fails with this error:
```
gpg: Signature made Mon 04 Apr 2016 10:20:55 AM CDT using RSA key ID D6CF60FD
gpg: Can't check signature: No public key
error: could not verify the tag 'current-hackage'
```
That's expected.
4. Run `stack build` again, and you get the following error:
```
Caching build plan
/home/cody/.stack/indices/hackage/00-index.tar: openBinaryFile: does not exist (No such file or directory)
```

--

So it looks like stack is downloading the `00-index.cache` file, but it fails before it can actually build the cache. When I try and rebuild, it throws an error that `00-index.tar` doesn't exist. Probably because `00-index.cache` already exists.

--

I'm sure there's any easier way to repro this, but those are the steps I took.

Also, if I just run `$ rm ~/.stack/00-index.cache` and re-run `$ stack build` it works correctly.

**Comment by CodyReichert** [comment] 2016-04-04 17:53
Oh also: I can reproduce this on multiple stack versions: `0.1.3` all the way to `1.0.4`

**Comment by mgsloan** [comment] 2016-04-04 19:26
Looks like [here](https://github.com/commercialhaskell/stack/blob/5f7ba827e4e5cb8c50bc9e5322e660861a51f355/src/Data/Binary/VersionTagged.hs#L74), we need to either check for file existence, or catch this exception.

**Comment by snoyberg** [comment] 2017-07-05 16:57
Has anyone seen this recently? The relevant bits of code have changed significantly since this issue was opened, so it wouldn't surprise me if the problem has disappeared.

**Comment by mgsloan** [comment] 2017-08-07 01:53
Closing this.  Feel free to open a new issue if something similar arises.

**Closed by mgsloan** 2017-08-07 01:53 UTC
Labels: need repro
