### ISSUE TITLE
Stack exec does not properly pass arguments to command on windows

### ISSUE THREAD

**Issue by themoritz** [commercialhaskell/stack#813] opened 2015-08-18 14:40 UTC
On windows, stack does not pass all the arguments that come after the double dash `--` to the command. The following works:

    stack exec cabal -- install

But the following does not (it shows stack's version):

    stack exec cabal -- --version

This shows stack's usage (i.e. stack thinks the --global option is intended for stack):

    stack exec cabal -- install --global

All the above commands work as expected on linux.

**Comment by chrisdone** [comment] 2015-08-18 16:01
Huh. Is this an optparse-applicative thing?

**Comment by borsboom** [comment] 2015-08-23 23:06
It seems to work for me:
```
C:\Users\emanu>stack exec cabal -- --version
Run from outside a project, using implicit global config
Using resolver: lts-3.0 from global config file: C:\Users\emanu\AppData\Roaming\stack\global\stack.yaml
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library
```
I tried this on Windows 10, using stack build from master.

@themoritz, can you try it with the latest master, and can you provide more details about your environment if it still fails?

**Comment by snoyberg** [comment] 2015-09-06 07:59
I've confirmed that this works as expected on Windows as well, closing due to lack of repro.

**Comment by themoritz** [comment] 2015-09-28 10:56
I can confirm that this is no longer an issue in newer stack versions (just tested with 0.1.5.0 on Windows 10). Sorry for the repro delay.

**Comment by snoyberg** [comment] 2015-09-28 18:21
No problem thanks for the confirmation

**Closed by snoyberg** 2015-09-28 18:21 UTC
Labels: component: options parsing, need repro

**Comment by jgm** [comment] 2015-11-15 05:45
I'm getting the issue reported above, with stack 0.1.6.0, 32-bit Windows, downloaded from the releases page.  This is on Windows 7.

```
stack exec cabal -- --version
```
returns the version of stack, not cabal.  I can't use stack exec on this machine because of this problem.

**Comment by jgm** [comment] 2015-11-15 05:48
I found a strange workaround.  This works:
```
stack exec cabal -- -- --version
```

**Comment by borsboom** [comment] 2015-11-18 18:09
@jgm: I haven't been able to reproduce this on Windows, using stack-0.1.6.0 from the releases page (or stack built from master).  There have been some changes to command-line argument parsing since 0.1.6.0 was released; perhaps try building the latest stack from master?

**Comment by bdoering** [comment] 2015-11-24 21:51
@jgm, I am having the same experience. Using `-- --` as a delimiter works, using only `--` does result in a usage message. I am using stack version 0.1.8.0 x86_64 on Windows 7, installed with `stack upgrade` (but identical behavior was visible with the earlier stack 0.1.4).

**Comment by jgm** [comment] 2015-11-24 22:35
I was on Windows 7 too; I wonder if this is Windows-version
dependent?

+++ Björn Döring [Nov 24 15 13:51 ]:

**Comment by mgsloan** [comment] 2015-11-24 23:47
Seems like this is worthy of re-opening, if it reliably repros on windows 7 (though, I haven't tried it).  I wonder what it is about windows 7 argument parsing that does this?  Is there something that can be done about it?

I'm almost inclined to say "Lets document the limitation somewhere, and encourage use of bash or powershell instead".

**Comment by jgm** [comment] 2015-11-25 00:22
I was using powershell in Windows 7.

+++ Michael Sloan [Nov 24 15 15:47 ]:

**Comment by bdoering** [comment] 2015-11-25 06:20
Me too. I just checked and it works as expected with the standard `cmd` shell, but powershell requires the double `-- --`.

**Comment by mgsloan** [comment] 2015-11-25 06:26
Ahah!  So really it's a powershell thing, interesting!

**Comment by themoritz** [comment] 2015-11-25 07:27
I can confirm all of the above. When I originally posted this issue I was using powershell on Win 7, too.

**Comment by borsboom** [comment] 2015-11-25 12:13
I just tried PowerShell on Windows 10, and it didn't seem to exhibit this problem.  I don't know anything about PowerShell, but [this stackoverflow Q/A](http://stackoverflow.com/questions/12197823/powershell-why-do-i-need-to-escape-a-double-dash-parameter-in-args) looks possibly relevant; it seems PowerShell interprets `--` itself for function calls, and maybe the Windows 7 version has a bug where it also does that when calling an external command.  Have any of you tried quoting the `--`, e.g.:

    stack exec cabal "--" --version

If it's a PowerShell issue where it's not actually passing the first `--` to `stack`, I think we'll just have to accept that, especially if it's fixed in Windows 10 (it's not so unlike having to remember to escape or quote arguments containing '*' or other characters the shell interprets when using bash).  An FAQ entry is probably in order, though.

**Comment by jgm** [comment] 2015-11-25 17:38
+++ Emanuel Borsboom [Nov 25 15 04:13 ]:
>   I just tried PowerShell on Windows 10, and it didn't seem to exhibit
>   this problem. I don't know anything about PowerShell, but [1]this
>   stackoverflow Q/A looks possibly relevant; it seems PowerShell
>   interprets -- itself for function calls, and maybe the Windows 7
>   version has a bug where it also does that when calling an external
>   command. Have any of you tried quoting the --, e.g.:
>stack exec cabal "--" --version

I just did, and I can confirm that quoting the "--" makes it
work properly.  I also tried writing a small program that
just prints the outputs of System.Environment.getArgs, and
that reveals that the `--` is not being passed through as an
argument.

So, I think your diagnosis is correct, and a FAQ entry
suffices to fix this.

**Comment by borsboom** [comment] 2015-11-26 15:27
I've added a FAQ entry: http://docs.haskellstack.org/en/stable/faq.html#why-is-the-argument-separator-ignored-in-windows-powershell
