### ISSUE TITLE
Allow stack ghci on a single file

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#2513] opened 2016-08-18 04:14 UTC
Split from #2510 .

The `stack ghci` command currently does not work as expected on a file, it only works on a project. Even though `stack exec ghci` works, the first intuition is always to use stack ghci so we should make that work as expected.

**Comment by mgsloan** [comment] 2016-08-20 02:32
Dupe of https://github.com/commercialhaskell/stack/issues/1361 , re-open if not.

**Closed by mgsloan** 2016-08-20 02:32 UTC
Labels: component: ghci, type: enhancement
