### ISSUE TITLE
Non-reproducable error `Access violation in generated code when reading 0000004300000000`

### ISSUE THREAD

**Issue by pjljvandelaar** [commercialhaskell/stack#4062] opened 2018-06-04 13:42 UTC
I am using the latest release.
I ran `stack test` on the `sqatt` project.
I got
```
...
[0merf-2.0.0.0: download[0m
[0merf-2.0.0.0: configure[0m
[0mcode-page-0.1.3: copy/register[0m
[0merf-2.0.0.0: build[0m
[0mextra-1.6.5: configure[0m
[0merf-2.0.0.0: copy/register[0m
[0mhostname-1.0: download[0m
[0mextra-1.6.5: build[0m
[0mhostname-1.0: configure[0m
[0mhostname-1.0: build[0m
[0mcereal-0.5.5.0: copy/register[0m
[0mhspec-discover-2.4.8: configure[0m
[0mhostname-1.0: copy/register[0m
[0mansi-terminal-0.8.0.2: copy/register[0m
[0mhspec-discover-2.4.8: build[0m
[0mhspec-expectations-0.8.2: configure[0m
[0mhspec-expectations-0.8.2: build[0m
[0mansi-wl-pprint-0.6.8.2: configure[0m
[0mextra-1.6.5: copy/register[0m
[0minteger-logarithms-1.0.2.1: using precompiled package[0m
Progress 18/85: ansi-wl-pprint-0.6.8.2, hspec-discover-2.4.8, hspec-expectations-0.8.2, integer-logarithms-1.0.2.1ghc-pkg.EXE: cannot find package integer-logarithms-1.0.2.1
[0mjs-flot-0.8.3: download[0m
[0mhspec-expectations-0.8.2: copy/register[0m
[0mansi-wl-pprint-0.6.8.2: build[0m
[0mjs-jquery-3.3.1: download[0m
[0mjs-flot-0.8.3: configure[0m
[0mansi-wl-pprint-0.6.8.2: copy/register[0m
[0mjs-flot-0.8.3: build[0m
[0mjs-jquery-3.3.1: configure[0m
[0mhspec-discover-2.4.8: copy/register[0m
[0mmanaged-1.0.6: download[0m
[0mmonad-loops-0.4.3: download[0m
[0mjs-jquery-3.3.1: build[0m
[0mmanaged-1.0.6: configure[0m
[0mjs-flot-0.8.3: copy/register[0m
[0mmtl-2.2.2: using precompiled package[0m
Progress 23/85: js-jquery-3.3.1, managed-1.0.6, monad-loops-0.4.3, mtl-2.2.2ghc-pkg.EXE: cannot find package mtl-2.2.2
[0mjs-jquery-3.3.1: copy/register[0m
Progress 25/85: managed-1.0.6, monad-loops-0.4.3, network-2.6.3.5, optional-args-1.0.2Access violation in generated code when reading 0000004300000000
```

stack continued normally after typing again `stack test`.

I consider the error message important enough to report it anyway.
If you disagree, feel free to close the issue immediate.

**Comment by mihaimaruseac** [comment] 2018-06-04 14:50
Could also be caused by GHC compiling or by some template Haskell code that was compiled at the time.

**Comment by dbaynard** [comment] 2018-06-26 23:50
Duplicate of #3765 

Also @pjljvandelaar try upgrading to the git master branch of stack, as your log had other errors which have recently been fixed.

**Closed by dbaynard** 2018-06-26 23:50 UTC
