### ISSUE TITLE
haskell-scratch as base image for container image

### ISSUE THREAD

**Issue by cocreature** [commercialhaskell/stack#590] opened 2015-07-15 06:08 UTC
When I set the relevant part of my config to
```
image:
  container:
    base: snoyberg/haskell-scratch
```
and then run `stack image container` the files somehow don't seem to be in the image. When I use `docker run <imagename> /usr/local/bin/<executable>` I get `no such file or directory`. However if I specify `fpco/stack-build` as a base image and run the exact same command it works just fine.

I am not quite sure how to debug this since being very minimal there is not even an `ls` or a `/bin/ls` in the image.

**Comment by dysinger** [comment] 2015-07-20 20:00
/cc @manny-fp 

It's hard to debug those scratch images.  I was having the same problem when I was writing that 5MB haskell web server blog post.

Let me see if I can reproduce over here....

yep.

It works if I change the base image to `fpco/ubuntu-with-libgmp:14.04` though (which is just straight up ubuntu:14.04 from the docker guys extended with the libgmp runtime package).

**Comment by dysinger** [comment] 2015-07-20 20:01
This is most likely a problem with that image not being able to link up everything correctly.

**Comment by dysinger** [comment] 2015-07-20 20:06
I'm going to close this because I think it's an image problem.  We don't really have a good way to debug that image either since it's soooooo bare bones.  I don't think @snoyberg wants to pursue the tiny image thing, it was just an exercise to see if it would work.  A 150-175MB image isn't so bad.

**Comment by dysinger** [comment] 2015-07-20 20:07
(Reopen if you think I'm completely wrong of course)

**Closed by dysinger** 2015-07-20 20:07 UTC
