### ISSUE TITLE
Suppress `7z x` output in `stack setup` on Windows (WAS: `stack --verbosity=error setup` on Windows)

### ISSUE THREAD

**Issue by hdgarrood** [commercialhaskell/stack#1991] opened 2016-04-04 01:38 UTC
I am trying to set up Windows CI for purescript via appveyor, and I noticed that `stack setup` prints a massive amount of information which I don't really care about, at least, not when it succeeds. From reading the output of `stack --help` it appeared to me that using `--verbosity=error` would remove this output, but adding this option doesn't seem to have had any effect.

Here is the build: https://ci.appveyor.com/project/hdgarrood/purescript/build/13

**Comment by hdgarrood** [comment] 2016-04-04 01:39
Just to clarify: the command I'm using is `stack --no-terminal --verbosity=error setup`.

**Comment by borsboom** [comment] 2016-04-04 17:01
I think this is mostly the output of the GHC decompression being run as a subprocess, which stack's --verbosity doesn't effect.  That said, there are probably ways we could suppress this output.  The workaround I've seen people use is to run `stack setup >nul` (e.g. [appveyor.yml](https://github.com/commercialhaskell/stack/blob/master/appveyor.yml)).

**Comment by hdgarrood** [comment] 2016-04-04 17:10
Yeah, I have something similar now, but simply suppressing the output is not quite what I'd consider ideal - if an error occurs during decompression, I do want to see it.

Currently I have `stack setup --verbosity=error 2>&1 >stack-setup.log || type stack-setup.log` which does seem to do what I want.

**Comment by sjakobi** [comment] 2016-07-15 13:47
Closing as a duplicate of #1212.

**Closed by sjakobi** 2016-07-15 13:47 UTC
Labels: type: enhancement
