### ISSUE TITLE
GHCJS stack path not consistent

### ISSUE THREAD

**Issue by shulhi** [commercialhaskell/stack#2436] opened 2016-08-04 06:00 UTC
I have two projects, one is a GHC project and the other is GHCJS project. 

For the GHCJS project, my `stack.yaml` looks like the normal setup as outlined in Stack's official guide for setting up GHCJS project. 

Running `stack --compiler ghcjs-0.2.0.20160414_ghc-7.10.3 path` on GHCJS project return,

```
...
compiler-exe: /home/shulhi/.stack/programs/x86_64-linux/ghcjs-0.2.0.20160414_ghc-7.10.3/bin/ghcjs
compiler-bin: /home/shulhi/.stack/programs/x86_64-linux/ghcjs-0.2.0.20160414_ghc-7.10.3/bin
...
```

But when running the same command on GHC project, I get
```
compiler-exe: /home/shulhi/.cabal/bin/ghcjs
compiler-bin: /home/shulhi/.cabal/bin
```

I was expecting to get the same result as running on GHCJS project. Is this an intended behavior?

**Comment by mgsloan** [comment] 2016-08-04 16:43
`compiler-exe: /home/shulhi/.cabal/bin/ghcjs`

I'm surprised you get ghcjs for a ghc project.  What's with that?

This does seem to be intended behavior.  `.cabal/bin/` is probably on your PATH, and so stack is using the ghc from there since its version matches.  We're planning to change the behavior to default to using a stack installed ghc, since it sometimes causes people problems: https://github.com/commercialhaskell/stack/issues/2221

**Comment by shulhi** [comment] 2016-08-04 23:14
@mgsloan 

If I run `stack path` on the GHC project, I get
```
compiler-exe: /home/shulhi/.cabal/bin/ghc
compiler-bin: /home/shulhi/.cabal/bin
```

But I want to compile it againts GHCJS, thus the `--compiler` flag. I have conditional macro for that GHC project that has GHCJS stuff in it. It works fine if I import that GHC project (it's a library) into GHCJS project and compile it. That will trigger the macro. But I want to be able to compile the GHC project with GHCJS flag on a standalone basis. I believe that's what `--compiler` is for. 

Do you know any way I could overwrite the `compiler-exe` and `compiler-bin`?

**Comment by mgsloan** [comment] 2016-08-05 01:41
Ah, I see. Strange!  Does `compiler-check: match-exact` in your stack.yaml fix it too?  (instead of `--no-system-ghc`)

In order to find your GHCJS packages, they will need to be in the stack configuration - it won't see things you've previously built / installed.

**Comment by shulhi** [comment] 2016-08-05 03:28
Yeah having `compiler-check: match-exact` works too. 

I don't quite understand that I need to have GHCJS in the stack (still new to Haskell/Stack). Does that mean I need to maintain two different `stack.yaml`, one for building with GHC and the other for GHCJS? My initial understanding was that I can do that by having `--compiler` flag. The official stack docs seems to imply that unless I misunderstand how it works. Thanks again for taking the time to answer my queries.

**Comment by mgsloan** [comment] 2016-08-05 21:29
Yeah, actually you don't need a separate stack.yaml, as long as the build with GHC doesn't depend on any packages that are GHCJS-only.

**Comment by mgsloan** [comment] 2016-10-18 21:29
Closing this, as it's an old support ticket.  If you think this is in error, please comment with more info.

**Closed by mgsloan** 2016-10-18 21:29 UTC
Labels: type: question
