### ISSUE TITLE
Foreign libraries not found

### ISSUE THREAD

**Issue by fosskers** [commercialhaskell/stack#3041] opened 2017-03-03 17:44 UTC
Within the past few days I've noticed stack failing to find C libraries whose shared object files are definitely present on my system in the usual places. At the moment I'm trying to depend on [cairo](https://hackage.haskell.org/package/cairo), but this has happened to me for another package too.

### My Config + System

```console
colin@yumi ~/c/h/spatialsort> aura -Ql cairo
...
cairo /usr/lib/libcairo.so
...
```

```console
colin@yumi ~/c/h/spatialsort> stack --version
Version 1.3.2 x86_64
```

```console
colin@yumi ~/c/h/spatialsort> stack path --extra-include-dirs
  # nothing
```

My stack config is the default, using `lts-8.3` (although the failure also occurs on `7.3` for me).

### Steps to reproduce

```console
git clone git@github.com:fosskers/spatialsort.git
cd spatialsort
stack build
```

### Expected

For cairo to build.

### Actual

```console
colin@yumi ~/c/h/spatialsort> stack build
cairo-0.13.3.1: configure
adjunctions-4.3: configure
adjunctions-4.3: build
adjunctions-4.3: copy/register
Progress: 2/7
--  While building package cairo-0.13.3.1 using:
      /tmp/stack5178/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 configure --with-ghc=/home/colin/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc --with-ghc-pkg=/home/colin/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/colin/.stack/snapshots/x86_64-linux/lts-8.3/8.0.2/pkgdb --libdir=/home/colin/.stack/snapshots/x86_64-linux/lts-8.3/8.0.2/lib --bindir=/home/colin/.stack/snapshots/x86_64-linux/lts-8.3/8.0.2/bin --datadir=/home/colin/.stack/snapshots/x86_64-linux/lts-8.3/8.0.2/share --libexecdir=/home/colin/.stack/snapshots/x86_64-linux/lts-8.3/8.0.2/libexec --sysconfdir=/home/colin/.stack/snapshots/x86_64-linux/lts-8.3/8.0.2/etc --docdir=/home/colin/.stack/snapshots/x86_64-linux/lts-8.3/8.0.2/doc/cairo-0.13.3.1 --htmldir=/home/colin/.stack/snapshots/x86_64-linux/lts-8.3/8.0.2/doc/cairo-0.13.3.1 --haddockdir=/home/colin/.stack/snapshots/x86_64-linux/lts-8.3/8.0.2/doc/cairo-0.13.3.1 --dependency=array=array-0.5.1.1 --dependency=base=base-4.9.1.0 --dependency=bytestring=bytestring-0.10.8.1 --dependency=mtl=mtl-2.2.1-BLKBelFsPB3BoFeSWSOYj6 --dependency=text=text-1.2.2.1-Ji7hMs2U4BkBwavd4taEVR --dependency=utf8-string=utf8-string-1.0.1.1-1DpjxLeTvGg7ttZZojxJR5
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/colin/code/haskell/spatialsort/.stack-work/logs/cairo-0.13.3.1.log

    [1 of 2] Compiling Main             ( /tmp/stack5178/cairo-0.13.3.1/Setup.hs, /tmp/stack5178/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/Main.o )
    [2 of 2] Compiling StackSetupShim   ( /home/colin/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /tmp/stack5178/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/StackSetupShim.o )
    Linking /tmp/stack5178/cairo-0.13.3.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup ...
    Configuring cairo-0.13.3.1...
    setup: Missing dependency on a foreign library:
    * Missing C library: cairo
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
```

**Comment by mgsloan** [comment] 2017-03-07 05:01
Hmm, curious, not sure what's going on there.  What does `ldconfig -p | grep libcairo` say?

**Comment by fosskers** [comment] 2017-03-07 15:31
```
colin@yumi ~/c/h/spatialsort> ldconfig -p | grep libcairo
	libcairo.so.2 (libc6,x86-64) => /usr/lib/libcairo.so.2
	libcairo.so (libc6,x86-64) => /usr/lib/libcairo.so
	libcairo-script-interpreter.so.2 (libc6,x86-64) => /usr/lib/libcairo-script-interpreter.so.2
	libcairo-script-interpreter.so (libc6,x86-64) => /usr/lib/libcairo-script-interpreter.so
	libcairo-gobject.so.2 (libc6,x86-64) => /usr/lib/libcairo-gobject.so.2
	libcairo-gobject.so (libc6,x86-64) => /usr/lib/libcairo-gobject.so
```

**Comment by mgsloan** [comment] 2017-03-07 22:38
Yeah, that seems reasonable.  Do things relying on cairo build with cabal-install? (is this stack specific?)

**Comment by fosskers** [comment] 2017-03-08 04:20
Ah ha, good call Mike. 

```
colin@yumi ~/c/h/cairotest> cabal install --only-dependencies 
Warning: The package list for 'hackage.haskell.org' is 69 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Notice: installing into a sandbox located at
/home/colin/code/haskell/cairotest/.cabal-sandbox
Configuring gtk2hs-buildtools-0.13.2.1...
Building gtk2hs-buildtools-0.13.2.1...
Installed gtk2hs-buildtools-0.13.2.1
Downloading cairo-0.13.3.1...
Configuring cairo-0.13.3.1...
Failed to install cairo-0.13.3.1
Build log ( /home/colin/code/haskell/cairotest/.cabal-sandbox/logs/cairo-0.13.3.1.log ):
cabal: Entering directory '/tmp/cabal-tmp-24081/cairo-0.13.3.1'
[1 of 1] Compiling Main             ( /tmp/cabal-tmp-24081/cairo-0.13.3.1/dist/dist-sandbox-98298b63/setup/setup.hs, /tmp/cabal-tmp-24081/cairo-0.13.3.1/dist/dist-sandbox-98298b63/setup/Main.o )
Linking /tmp/cabal-tmp-24081/cairo-0.13.3.1/dist/dist-sandbox-98298b63/setup/setup ...
Configuring cairo-0.13.3.1...
setup: Missing dependency on a foreign library:
* Missing C library: cairo
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.
cabal: Leaving directory '/tmp/cabal-tmp-24081/cairo-0.13.3.1'
cabal: Error: some packages failed to install:
cairo-0.13.3.1 failed during the configure step. The exception was:
ExitFailure 1
```
^ this is a test project which only depends on `cairo >= 0.13`.

**Comment by fosskers** [comment] 2017-03-08 15:58
For the record:
```
colin@yumi ~> cabal --version
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library 
```

**Comment by mgsloan** [comment] 2017-03-08 20:27
Not sure what could be going wrong there.  Perhaps this is helpful? http://stackoverflow.com/a/34283527/1164871

**Comment by mgsloan** [comment] 2017-03-19 00:06
Closing since it seems that the issue is not specific to stack.  If you figure it out, please add a comment explaining the issue / resolution!

**Closed by mgsloan** 2017-03-19 00:06 UTC

**Comment by fosskers** [comment] 2017-03-19 00:35
Apologies, I haven't checked the solution yet.

**Comment by mgsloan** [comment] 2017-03-19 02:37
No worries!  I went on an issue-closing spree today.

**Comment by fosskers** [comment] 2017-03-20 03:00
The trail of breadcrumbs leads here: https://stackoverflow.com/questions/22343259/cryptopp-foreign-library-dependency

But the mystery continues.

**Comment by fosskers** [comment] 2017-03-20 03:03
Giving up for now.
