### ISSUE TITLE
Provide a complete list of available resolvers

### ISSUE THREAD

**Issue by spl** [commercialhaskell/stack#1855] opened 2016-02-29 07:52 UTC
It would be useful to see a complete list of the available resolvers.

The [documentation](http://docs.haskellstack.org/en/stable/yaml_configuration/#resolver) uses “e.g.” and “looks like” to provide possible patterns of resolver names, but it doesn't give any indication of the bounds of those patterns, instead relying on reader knowledge to fill in the details or on guesses to see if a certain pattern works.

Ideally, I would like to be able to go to an explicit list of resolvers and see what I can use. Also, ideally, this list would have some documentation about each that explains it and how it is different from other (related) resolvers. A more minimal, but still useful, solution would be to add more description on the resolver patterns, or to add links to more details, to the aforementioned documentation.

**Comment by harendra-kumar** [comment] 2016-02-29 08:22
It is supposed to be covered under  #1614 .

**Comment by spl** [comment] 2016-02-29 08:31
Great! Thanks! I hope the documentation will be updated to mention the relevant commands once they are completed.

**Comment by harendra-kumar** [comment] 2016-02-29 10:12
Nobody seems to be working on it right now. A PR would be welcome in case you are interested.

**Comment by sjakobi** [comment] 2016-07-14 14:09
Closing this as a duplicate of #1614.

**Closed by sjakobi** 2016-07-14 14:09 UTC
Labels: resolution: duplicate
