### ISSUE TITLE
STACK_YAML, custom stack.yaml file location

### ISSUE THREAD

**Issue by ozgurakgun** [commercialhaskell/stack#2721] opened 2016-10-19 10:37 UTC
Hi,

I am using the STACK_YAML environment variable to select a stack.yaml file per GHC version, as suggested in the [FAQ](https://github.com/commercialhaskell/stack/blob/master/doc/faq.md#how-can-i-make-sure-my-project-builds-against-multiple-ghc-versions).

I realised that this doesn't quite work when the stack.yaml file is in a subdirectory though.
Say I have the following setup:

```
myapp.cabal
stack/7.10.yaml
stack/8.0.yaml
```

Then:
- `cp stack/7.10.yaml stack.yaml ; stack build` works, but
- `STACK_YAML=stack/7.10.yaml stack build` doesn't.

(I used `cp` here, but I am sure a symlink would also work.)

I am not sure if this will be considered a bug or a feature request. But, to me, making the two options above behave the same seems like a good idea. It would definitely be the least surprising behaviour for me at least.

Just for the record: for my example currently stack looks for a .cabal file under the `stack/` directory and fails since there is none.

Cheers!

**Comment by lwm** [comment] 2016-10-19 11:12
I can reproduce with:

```
$ stack new new-template && cd new-template
$ mkdir stack && mv stack.yaml stack/
$ STACK_YAML=stack/stack.yaml stack build
```

I think this is expected. As you can see from the Stack project itself, they keep their [stack-7.8.yaml](https://github.com/commercialhaskell/stack/blob/master/stack-7.8.yaml) and their [stack-8.0.yaml](https://github.com/commercialhaskell/stack/blob/master/stack-8.0.yaml) in the root of the project - where the `stack.cabal` file is.

You can work around this (I think!?) with (working from my reproduction example): 

```
$ STACK_YAML=stack/stack.yaml stack build --stack-root=$(pwd)
```

**Comment by ozgurakgun** [comment] 2016-10-19 12:58
@lwm thanks for the reproduction snippet and the workaround. I will use the workaround for now.

**Comment by ozgurakgun** [comment] 2016-10-19 13:16
Oh, I spoke too early. Setting `--stack-root` to the current directory forces stack to download/create directories like indices/build-plan/etc in the current directory. So not so good. :(

I tried `--project-root=$(pwd)` as an alternative, but it is not accepted by stack.

**Comment by lwm** [comment] 2016-10-19 13:55
Ah yes, it was wrong:

```
  --stack-root STACK-ROOT  Absolute path to the global stack root directory
                           (Overrides any STACK_ROOT environment variable)
```

I think I'll just wait for the others to chime in, other than making more noise ;)

**Comment by sjakobi** [comment] 2016-10-19 14:20
I first thought that the problem was the relative path in `STACK_YAML` but the real issue is probably that in your `stack.yaml`s, you either explicitly define

```
packages:
  - '.'
```

or don't define `packages` at all, so it defaults to using `.`.

For the repro, the easiest fix is to define `packages: ['..']` in `stack/stack.yaml`.

Does that work for you, too, @ozgurakgun? Do you still think that stack should behave differently here?

I think we could maybe improve the error message: Currently it says:

```
$ STACK_YAML=stack/stack.yaml stack build
Getting project config file from STACK_YAML environment
No .cabal file found in directory /home/simon/tmp/repro2721/stack/
```

We could change it to something like:

```
stack looks for packages in the directories configured in the 'packages' variable defined in <stack.yaml>

    packages:
       <Your config here>

The entry of `'.'` points at <full path>, but no .cabal file could be found there.
```

**Comment by ozgurakgun** [comment] 2016-10-19 14:30
@sjakobi Indeed, I do have "." in my stack.yaml file.

I still think that path should be relative to the current working directory, instead of where stack.yaml happens to be stored.

Separately: Would exposing `--project-root` be a good idea? It is listed in the output of `stack path`.

**Comment by sjakobi** [comment] 2016-10-19 14:37
> I still think that path should be relative to the current working directory, instead of where stack.yaml happens to be stored.

You can also call stack from any subdirectory of a project and I don't think that would still work if you make  `packages` paths relative to $PWD.

> Would exposing --project-root be a good idea?

Can you expand a bit on that idea? What would that achieve?

**Comment by ozgurakgun** [comment] 2016-10-19 15:15
Regarding whether the paths in the stack.yaml file should be relative to file location or $PWD is a design decision, I suppose. The latter seems better to me, but I can understand either option.

A `--project-root` command line option would be for overwriting what stack considers as project root, explicitly. AFAIU, at the moment the project root is implicitly set to be the same as stack.yaml's directory.

**Comment by mgsloan** [comment] 2016-10-19 23:20
$PWD relative paths seems non-useful, because stack.yaml is a project configuration file.

We do take a `--work-dir` to specify the relative position of `.stack-work`.  Due to limitations in Cabal, we cannot make this an absolute directory.

**Comment by ozgurakgun** [comment] 2016-10-19 23:24
@mgsloan I take your point regarding not being $PWD relative.

I am not sure how `--work-dir` is relevant here though, as the problem is to do with not finding the .cabal file.

**Comment by mgsloan** [comment] 2016-10-19 23:31
Good point, I only read some of this issue. `..` in your stack.yaml files should be sufficient, if I understand correctly.

**Comment by lwm** [comment] 2016-10-22 11:39
> For the repro, the easiest fix is to define packages: ['..'] in stack/stack.yaml.

Confirming that this works.

> AFAIU, at the moment the project root is implicitly set to be the same as stack.yaml's directory.

It's not the case the case, I think, it depends on the `packages` value.

#2729 brings https://github.com/commercialhaskell/stack/issues/2721#issuecomment-254827203's error message changes which are much clearer IMHO.

**Comment by mgsloan** [comment] 2017-03-18 23:55
Closing, since package paths are relative to the stack.yaml file, not PWD.

**Closed by mgsloan** 2017-03-18 23:55 UTC
Labels: component: output (UI/UX), type: discuss
