### ISSUE TITLE
Stack fails to build without Setup.hs

### ISSUE THREAD

**Issue by eborden** [commercialhaskell/stack#4517] opened 2019-01-18 16:23 UTC
### General summary/comments

`cabal` is able to build without a `Setup.hs` by defaulting to the most basic `Setup.hs`. `stack` should have feature parity in this respect.

### Steps to reproduce

1. `git clone git@github.com:haskell/network.git`
2. `cd network`
3. `stack init`
4. `stack build`

### Expected

`stack` should build with a default `Setup.hs` when no `Setup.hs` is present.

### Actual

`stack` cannot build without a `Setup.hs`.

```
$ stack init
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- ./

Selecting the best among 15 snapshots...

Downloaded lts-13.3 build plan.    
Didn't see cheapskate-0.1.1.1@sha256:f03d9784fd13cc970ecf5be8792f6c592e3127dce208efad07d614f86ec3c655,3114 in your package indices.
Updating and trying again.
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                                 
Downloading timestamp                                                                            
Downloading snapshot                                                                             
Updating index                                                                                   
Updated package index downloaded                                                                 
Update complete                                                                                  
Populated index cache.    
* Matches lts-13.3

Selected resolver: lts-13.3
Initialising configuration using resolver: lts-13.3
Total number of user packages considered: 1
Writing configuration to file: stack.yaml
All done.

$ stack build
No Setup.hs or Setup.lhs file found in /home/eborden/code/network/
```

### Stack version

```
$ stack --version
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by dbaynard** [comment] 2019-01-24 11:55
Are you missing a `cd network` between your steps 1 and 2? With that, I can't reproduce (stack throws an error because there's an existing stack.yaml file in the network source tree).

**Comment by eborden** [comment] 2019-01-24 15:17
`master` of `network` has changed since this was produced. :man_facepalming: 

You could do the following to repro:

1. `git clone git@github.com:haskell/network.git`
2. `cd network`
3. `rm Setup.hs`
4. `stack build`

**Comment by mihaimaruseac** [comment] 2019-01-25 00:54
Just confirmed this. It even manifests when doing `stack unpack network` in step 1. 

As expected, `stack init` works even if there's no `Setup.hs` but not the build.

This should be easy, I think: just beforeexecuting the build plan, we should output the basic `Setup.hs` if none is found and then proceed with the build as before. I marked it as an easy PR.

**Comment by dbaynard** [comment] 2019-01-25 08:09
It's because `network` uses `build-type: configure`. Without the `Setup.hs` file it shouldn't build.

**Comment by mihaimaruseac** [comment] 2019-01-25 16:25
You are right. It builds without the `Setup.hs` file for a package using `build-type: Simple` (I tested on `io-manager`).

Closing this as it is actually not a Stack bug.

**Closed by mihaimaruseac** 2019-01-25 16:25 UTC
Labels: component: build, newcomer friendly, type: bug

**Comment by eborden** [comment] 2019-01-25 16:49
Great catch! `network` recently moved away from a more complex `Setup.hs` to simple. I'll fix the cabal file.

**Comment by eborden** [comment] 2019-01-25 16:57
Hmm, actually `network` still needs `Configure`. Is there any reason that `stack` can't synthesize the default `Configure` `Setup.hs`?

**Comment by mihaimaruseac** [comment] 2019-01-25 17:57
I guess scope creep as then you'll have to maintain multiple versions of `Setup.hs` that you can synthesize.

However, if you'd like to send a PR, that would be welcome

**Comment by dbaynard** [comment] 2019-01-28 15:35
I think I need to document the `configure` behaviour, too, in #4494
