### ISSUE TITLE
"Internal error when calculating transitive package dependencies" running stack haddock

### ISSUE THREAD

**Issue by newhoggy** [commercialhaskell/stack#5284] opened 2020-04-30 03:56 UTC
### Steps to reproduce

$ git@github.com:haskell-works/hw-ip.git
$ cd hw-ip
$ stack init
$ stack haddock

### Expected

This should work.  For example `cabal v2-haddock` works.

### Actual

```
$ stack haddock
hw-ip> configure (lib + internal-lib + exe)
Configuring hw-ip-2.4.2.0...
hw-ip> build (lib + internal-lib + exe)
Preprocessing library for hw-ip-2.4.2.0..
Building library for hw-ip-2.4.2.0..
Preprocessing library 'hw-ip-gen' for hw-ip-2.4.2.0..
Building library 'hw-ip-gen' for hw-ip-2.4.2.0..
Preprocessing executable 'hw-ip' for hw-ip-2.4.2.0..
Building executable 'hw-ip' for hw-ip-2.4.2.0..
hw-ip> haddock
Preprocessing library for hw-ip-2.4.2.0..
Running Haddock on library for hw-ip-2.4.2.0..
Haddock coverage:
   0% (  0 /  1) in 'HaskellWorks.Data.Network.Ip'
  Missing documentation for:
    Module header
   0% (  0 / 16) in 'HaskellWorks.Data.Network.Ip.Internal.Appar'
  Missing documentation for:
    Module header
    fourOctetsToWord32 (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:27)
    #<*># (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:37)
    octet (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:41)
    whitespace (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:48)
    ipv4Address (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:51)
    ipv4NetMask (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:58)
    digit (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:64)
    digits (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:67)
    ipv4Block (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:70)
    word32x4ToWords (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:77)
    bitPower (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:80)
    blockSize (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:83)
    bitPower128 (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:86)
    blockSize128 (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:89)
    readsPrecOnParser (src/HaskellWorks/Data/Network/Ip/Internal/Appar.hs:92)
   0% (  0 /  3) in 'HaskellWorks.Data.Network.Ip.Validity'
  Missing documentation for:
    Module header
    Canonical (src/HaskellWorks/Data/Network/Ip/Validity.hs:3)
    Unaligned (src/HaskellWorks/Data/Network/Ip/Validity.hs:5)
   0% (  0 /  4) in 'HaskellWorks.Data.Network.Ip.Word128'
  Missing documentation for:
    Module header
    Word128 (src/HaskellWorks/Data/Network/Ip/Word128.hs:16)
    integerToWord128 (src/HaskellWorks/Data/Network/Ip/Word128.hs:32)
    word128ToInteger (src/HaskellWorks/Data/Network/Ip/Word128.hs:39)
   0% (  0 /  4) in 'HaskellWorks.Data.Network.Ip.SafeEnum'
  Missing documentation for:
    Module header
    SafeEnum (src/HaskellWorks/Data/Network/Ip/SafeEnum.hs:15)
    boundedPred (src/HaskellWorks/Data/Network/Ip/SafeEnum.hs:79)
    boundedSucc (src/HaskellWorks/Data/Network/Ip/SafeEnum.hs:82)
Warning: 'left' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
Warning: 'right' is out of scope.
    If you qualify the identifier, haddock can try to link it anyway.
  17% (  1 /  6) in 'HaskellWorks.Data.Network.Ip.Range'
  Missing documentation for:
    Module header
    Range (src/HaskellWorks/Data/Network/Ip/Range.hs:15)
    parseRange (src/HaskellWorks/Data/Network/Ip/Range.hs:20)
    Contains (src/HaskellWorks/Data/Network/Ip/Range.hs:32)
    rangeToList (src/HaskellWorks/Data/Network/Ip/Range.hs:39)
  16% (  4 / 25) in 'HaskellWorks.Data.Network.Ip.Ipv4'
  Missing documentation for:
    Module header
    IpAddress (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:51)
    IpNetMask (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:62)
    Unaligned (src/HaskellWorks/Data/Network/Ip/Validity.hs:5)
    Canonical (src/HaskellWorks/Data/Network/Ip/Validity.hs:3)
    bitPower (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:98)
    splitBlock (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:105)
    parseIpAddress (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:154)
    parseIpAddressAsBlock (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:157)
    showIpAddress (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:124)
    showsIpAddress (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:117)
    tshowIpAddress (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:127)
    tshowIpBlock (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:136)
    wordsToIpAddress (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:139)
    ipAddressToWords (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:146)
    firstIpAddress (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:92)
    lastIpAddress (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:95)
    splitIpRange (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:172)
    rangeToBlocksDL (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:211)
    rangeToBlocks (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:218)
    blockToRange (src/HaskellWorks/Data/Network/Ip/Ipv4.hs:221)
   0% (  0 / 25) in 'HaskellWorks.Data.Network.Ip.Ipv6'
  Missing documentation for:
    Module header
    IpAddress (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:55)
    IpNetMask (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:73)
    IpBlock (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:89)
    Unaligned (src/HaskellWorks/Data/Network/Ip/Validity.hs:5)
    Canonical (src/HaskellWorks/Data/Network/Ip/Validity.hs:3)
    fromIpv4 (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:175)
    fromIpv4Block (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:170)
    isIpv4Block (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:178)
    toIpv4Block (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:181)
    fromV4 (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:167)
    parseIpBlock (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:115)
    masksIp (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:145)
    showIpAddress (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:130)
    showsIpAddress (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:127)
    tshowIpAddress (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:133)
    tshowIpBlock (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:142)
    firstIpAddress (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:200)
    lastIpAddress (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:203)
    rangeToBlocks (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:224)
    rangeToBlocksDL (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:217)
    blockToRange (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:227)
    isCanonical (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:161)
    canonicaliseIpBlock (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:190)
    splitIpRange (src/HaskellWorks/Data/Network/Ip/Ipv6.hs:206)
   9% (  1 / 11) in 'HaskellWorks.Data.Network.Ip.Ip'
  Missing documentation for:
    Module header
    IpBlock (src/HaskellWorks/Data/Network/Ip/Ip.hs:31)
    Unaligned (src/HaskellWorks/Data/Network/Ip/Validity.hs:5)
    Canonical (src/HaskellWorks/Data/Network/Ip/Validity.hs:3)
    IpAddress (src/HaskellWorks/Data/Network/Ip/Ip.hs:34)
    isCanonical (src/HaskellWorks/Data/Network/Ip/Ip.hs:71)
    canonicalise (src/HaskellWorks/Data/Network/Ip/Ip.hs:75)
    blockToRange (src/HaskellWorks/Data/Network/Ip/Ip.hs:84)
    firstIpAddress (src/HaskellWorks/Data/Network/Ip/Ip.hs:88)
    lastIpAddress (src/HaskellWorks/Data/Network/Ip/Ip.hs:92)
Documentation created:
.stack-work/dist/x86_64-osx/Cabal-3.0.1.0/doc/html/hw-ip/index.html,
.stack-work/dist/x86_64-osx/Cabal-3.0.1.0/doc/html/hw-ip/hw-ip.txt
Preprocessing library 'hw-ip-gen' for hw-ip-2.4.2.0..
Running Haddock on library 'hw-ip-gen' for hw-ip-2.4.2.0..
Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3: internal error when calculating
transitive package dependencies.
Debug info: []


--  While building package hw-ip-2.4.2.0 using:
      /Users/jky/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.0.1.0 haddock --html --hoogle --html-location=../$pkg-$version/ --haddock-option=--hyperlinked-source --haddock-option=--quickjump
    Process exited with code: ExitFailure 1
```

### Stack version

```
$ stack --version
Version 2.3.1, Git revision de2a7b694f07de7e6cf17f8c92338c16286b2878 (8103 commits) x86_64 hpack-0.33.0
```

### Method of installation

`brew install` then `stack upgrade`

**Comment by newhoggy** [comment] 2020-04-30 03:57
Verbose run attached.

[verbose.txt](https://github.com/commercialhaskell/stack/files/4556061/verbose.txt)

**Comment by madgen** [comment] 2020-05-08 18:54
It is probably related to haskell/cabal#1919.

**Comment by brandon-leapyear** [comment] 2020-08-11 18:18
dupe of https://github.com/commercialhaskell/stack/issues/4428?

**Comment by mpilgrem** [comment] 2024-03-10 23:47
I am closing as this appears to duplicate #4428.

**Closed by mpilgrem** 2024-03-10 23:47 UTC
