### ISSUE TITLE
Caching profiling/non-profiling dependencies independently

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#2684] opened 2016-10-06 19:27 UTC
Per. https://twitter.com/mwotton/status/784112209878069248

Quote:

> so, is there a sane workflow for having profiling switchable in stack projects? I don't want to have always build with profiles.

So far as I'm aware and have seen in my own projects, switching profiling on/off forces a rebuild which is kinda gnarly. Could this be lifted into how builds are cached?

**Comment by mgsloan** [comment] 2017-08-07 01:41
Things should be much better on master, now that implicit snapshots is merged.  This means that even if you have lots of extra-deps it'll still used cached builds of packages.

Where it won't help so much is avoiding rebuilds of local packages.  Something like https://github.com/commercialhaskell/stack/issues/1634 might help here.

**Comment by ntc2** [comment] 2018-05-04 17:05
Duplicate of #1132?

**Comment by snoyberg** [comment] 2019-03-25 08:26
Mostly addressed via implicit snapshots, the rest is tracked with #4032.

**Closed by snoyberg** 2019-03-25 08:26 UTC
Labels: type: enhancement, type: performance
