### ISSUE TITLE
incompatible implementation for Double-star (**) wildcards in <pkg>.cabal

### ISSUE THREAD

**Issue by complyue** [commercialhaskell/stack#5085] opened 2019-11-13 11:29 UTC
### General summary/comments (optional)

cabal format specification 2.4 introduced the `Double-star (**) wildcards`,
`cabal build` supports it while `stack build` currently failed to copy subdirs
w/ nested files.

the cabal format spec: [cabal-version: 2.4](https://www.haskell.org/cabal/users-guide/file-format-changelog.html#cabal-version-2-4)

### Steps to reproduce

for any stack project, add a deep tree of data files like:
```bash
web/a/b/c.html
```

 within its `<pkg>.cabal` add the `data-files` list like:

```yaml
data-files:
    web/**/*.html
```

run `stack build`

### Expected

no error reported and all files under `web/` get copied correctly.

### Actual

build failed with error like:
```bash
...
'cabal copy' failed.  Error message:

--  While building package xxx using:
      xxx/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 copy
    Process exited with code: ExitFailure 1
...
```

### Stack version

```
$ stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by complyue** [comment] 2019-11-13 11:32
a side note, when using `package.yaml` to generate `<pkg>.cabal' won't trigger this issue, as hpack will interpret the wildcards to list all files explicitly into generated `<pkg>.cabal`

**Comment by mpilgrem** [comment] 2024-05-01 20:11
I am going to close this issue because:

*   the Cabal User Guide documents:

    > (Caveat: Double-star wildcards in `data-files` directories, e.g. `data-files: data/**/*.csv`, are only supported correctly from Cabal 3.0.)
*   I can't reproduce the problem with GHC > 8.6 (Cabal > 2.4)

**Closed by mpilgrem** 2024-05-01 20:11 UTC
Labels: type: bug, resolution: upstream issue, component: build, component: Cabal library
