### ISSUE TITLE
MIN_VERSION_ macros aren't set when compiling Setup.hs

### ISSUE THREAD

**Issue by phadej** [commercialhaskell/stack#2976] opened 2017-02-03 17:08 UTC
### General summary/comments (optional)

`cabal` sets `MIN_VERSION_` macros, if it knows about `custom-setup`.
I think it's important to keep this connection. It makes possible to make
more compatible `Setup.hs`: if there is no macros, assume only packages bundled
with GHC available.

In my particular case, it's possible to workaround the issue, but some my
later rely on `MIN_VERSION_` macros actually available.

If you look into `distributive`'s Setup.hs, it doesn't use `directory` or `filepath` modules
if `MIN_VERSION_cabal_doctest` is defined.

### Steps to reproduce

- `cabal get distributive-0.5.2`
- `cd distributive-0.5.2`
- remove `filepath` and `directory` from `setup-depends`
- add stack.yaml:
```yaml
resolver: lts-6.30
extra-deps:
- cabal-doctest-1
```

### Expected

Successful build

### Actual

```
/home/ogre/mess/distributive-0.5.2/Setup.lhs:49:8:
    Could not find module ‘System.Directory’
    It is a member of the hidden package ‘directory-1.2.2.0@direc_0hFG6ZxK1nk4zsyOqbNHfm’.
    Use -v to see a list of the files searched for.

/home/ogre/mess/distributive-0.5.2/Setup.lhs:50:8:
    Could not find module ‘System.FilePath’
    It is a member of the hidden package ‘filepath-1.4.0.0@filep_Ey7a1in9roBAE8bUFJ5R9m’.
    Use -v to see a list of the files searched for.
```

### Stack version

```
$ stack --version
Version 1.3.3, Git revision dc42af7a394f52d141563893a186d7ce3ab7f843 (dirty) (4502 commits) x86_64 hpack-0.16.0
```

(dirtyness is cabal.project file in repo)

---

cc @RyanGlScott

**Comment by RyanGlScott** [comment] 2017-02-03 20:38
To be clear, do you need to remove both `filepath` _and_ `directory` from `setup-depends`? Or just `directory`? After all, [that code](https://github.com/ekmett/distributive/blob/8852a615219b1634a2ea1ef92f8a8b14aee42d90/Setup.lhs) seems to only use `MIN_VERSION_directory`, nor `MIN_VERSION_filepath`.

**Comment by phadej** [comment] 2017-02-03 20:45
either one. As `MIN_VERSION_cabal_doctest` isn't defined, it goes to `import System.Directory` + `import System.FilePath` path.

**Comment by RyanGlScott** [comment] 2017-02-03 20:54
Actually, I can't reproduce this issue in the first place, even after removing both `directory` and `filepath`. I tried with both:

* `Version 1.2.0 x86_64 hpack-0.14.0`
* `Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 (4395 commits) x86_64 hpack-0.15.0`

Does this require version 1.3.3 to reproduce?

**Comment by phadej** [comment] 2017-02-03 20:58
@RyanGlScott yes.

**Comment by RyanGlScott** [comment] 2017-02-03 23:37
Thanks @phadej. I confirmed that this is reproducible with the latest master (4a22eef1bb6e36cc8f9dc30d4cddd51f4bfcf535).

**Comment by mgsloan** [comment] 2017-02-03 23:44
I've added setup_macros.h generation to the custom-setup support, so this is now fixed.

**Closed by mgsloan** 2017-02-03 23:44 UTC

**Comment by phadej** [comment] 2017-02-04 09:02
@mgsloan thanks for prompt fix!
