### ISSUE TITLE
-Wunused-packages sometimes fails to warn

### ISSUE THREAD

**Issue by brandon-leapyear** [commercialhaskell/stack#5569] opened 2021-06-23 21:28 UTC
### General summary/comments (optional)

We build in CI + locally with `-Wunused-packages -Werror`, but sometimes things get through CI and then fail when building locally, e.g. if someone makes a PR adding a dependency to `package.yaml` that's never used.

Unfortunately, it's pretty flaky, and running `stack purge` or `find . -name .stack-work | xargs rm -rf` doesn't help (I would think that purging all local stack state would start GHC from an empty state and help it recognize a package is unused). Furthermore, when I had one repo clone working and another repo clone not working, I ran `ghc --show-iface` on all `.hi` files in both repos and ran a diff, which didn't show any non-trivial differences.

Why am I opening an issue on Stack and not GHC? Well Stack's main goal is build reproducibility, so I think it's worthwhile to at least have this issue tracked for Stack.

### Steps to reproduce

As mentioned above, this is flaky, so I haven't been able to figure out a reproducible build yet.

**Comment by mpilgrem** [comment] 2024-03-28 20:46
I am going to close this issue given the passage of time and because no other user of Stack has reported a similar experience of GHC's `-Wunused-packages` flag (introduced in GHC 8.10) not working as intended.

**Closed by mpilgrem** 2024-03-28 20:46 UTC

**Comment by brandonchinn178** [comment] 2024-03-28 20:54
FWIW Here's one comment of someone else noticing false negatives with this flag:
https://discourse.haskell.org/t/should-you-use-wunused-packages-to-keep-cabal-file-tidy/9169/4

It's definitely not just me, I'm sure you'll get a number of responses if you surveyed people about this issue specifically.

**Comment by mpilgrem** [comment] 2024-03-28 21:24
Noted. GHC documents that its flag interacts poorly with GHCi (https://downloads.haskell.org/~ghc/9.8.2/docs/users_guide/using-warnings.html#ghc-flag--Wunused-packages) and some (but not all) of that comment seems to relate to GHCi (a REPL environment).

**Comment by philderbeast** [comment] 2024-03-29 13:23
Sorry @mpilgrem, I don't have a reproduction at hand.
