### ISSUE TITLE
When license-file is missing, stack reports both license-file and "possibly" main-is as missing.

### ISSUE THREAD

**Issue by mhitza** [commercialhaskell/stack#5259] opened 2020-04-18 19:12 UTC
### General summary/comments (optional)

When license-file is missing, stack reports both license-file and "possibly" main-is as missing.

### Steps to reproduce

For example:

1. `stack new project simple`
2. `cd project && rm LICENSE`
3. `stack build`

```
Possible causes of this issue:
* No module named "Main". The 'main-is' source file should usually have a header indicating that it's a 'Main' module.
* A cabal file that refers to nonexistent other files (e.g. a license-file that doesn't exist). Running 'cabal check' may point out these issues.
```

### Expected

Only report that a license-file is missing

### Actual

Both license-file and main-is are reported as probably missing.

### Stack version

```
$ stack --version
Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mattaudesse** [comment] 2020-04-20 02:50
I'm guessing there was probably a conscious design decision to try and be helpful but not re-implement what the `cabal` subprocess is already doing here (based on the `ExitFailure 1`).

```bash
...

Warning: The 'license-file' field refers to the file 'LICENSE' which does not
exist.

...

LICENSE: copyFile: does not exist (No such file or directory)
'cabal copy' failed.  Error message:

--  While building package i5259-0.1.0.0 using:
      /usr/home/matt/.stack/setup-exe-cache/x86_64-freebsd-ino64/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3 --builddir=.stack-work/dist/x86_64-freebsd-ino64/Cabal-3.0.1.0 copy
    Process exited with code: ExitFailure 1

Possible causes of this issue:
* No module named "Main". The 'main-is' source file should usually
  have a header indicating that it's a 'Main' module.
* A cabal file that refers to nonexistent other files (e.g. a license-file
  that doesn't exist). Running 'cabal check' may point out these issues.
```

We'd probably be open to a PR to improve the output as long as it doesn't introduce too much scope creep or duplicate effort - @mhitza is that something you'd like to look into?

Thanks for reporting this.

**Comment by mhitza** [comment] 2020-04-21 16:28
@mattaudesse sure, I would be happy to try and make a contribution to stack. I'll try it out in the following days and see if there is an obvious way for me to make the change. If you have any pointers at this point let me know. Otherwise, I'll just pop back in here if I get blocked/confused :)

**Comment by mpilgrem** [comment] 2024-03-10 19:41
I am closing given the passage of time and I could not reproduce this with a current version of Stack and LTS 22.13: no error message was reported.

**Closed by mpilgrem** 2024-03-10 19:41 UTC
