### ISSUE TITLE
The coverage report for chapter3's test-suite "chapter3-test" did not consider any code.

### ISSUE THREAD

**Issue by rwobben** [commercialhaskell/stack#1541] opened 2015-12-19 16:34 UTC
Hello, 

I have this project :  http://github.com/rwobben/craft_stack
But as soon as I do stack test --coverage and I goto the html report I see this : 

Error: The coverage report for chapter3's test-suite "chapter3-test" did not consider any code. One possible cause of this is if your test-suite builds the library code (see stack issue #1008). It may also indicate a bug in stack or the hpc program. Please report this issue if you think your coverage report should have meaningful results.

**Comment by luigy** [comment] 2015-12-19 16:49
I can reproduce this on master with 
```sh
stack build
stack test --coverage
```
with a clean project it works, though
```sh
stack clean
stack test --coverage
```

**Comment by rwobben** [comment] 2015-12-19 16:53
I see it with stack clean, stack test --coverage.
Maybe the problem is that my code to test lives in a libarary lib,hs ?

**Comment by rwobben** [comment] 2015-12-19 18:34
and here the verbose output : 

    2015-12-19 18:33:24.699610: [info] Generating coverage report for chapter3's test-suite "chapter3-test" @(stack_0VvCbDQ2gfsBxzuxYlepyD:Stack.Coverage src/Stack/Coverage.hs:181:13)
2015-12-19 18:33:24.699784: [debug] Run process: hpc report /home/ubuntu/workspace/craft/chapter3/.stack-work/install/x86_64-linux/lts-3.18/7.10.2/hpc/chapter3/chapter3-test/chapter3-test.tix --srcdir /home/ubuntu/workspace/craft/chapter3 --hpcdir .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/hpc --reset-hpcdirs --include chapt_GLaTxaU1fWGIuRNEXeX0qG: @(stack_0VvCbDQ2gfsBxzuxYlepyD:System.Process.Read src/System/Process/Read.hs:273:3)
2015-12-19 18:33:24.733924: [error] Error: The coverage report for chapter3's test-suite "chapter3-test" did not consider any code. One possible cause of this is if your test-suite builds the library code (see stack issue #1008). It may also indicate a bug in stack or the hpc program. Please report this issue if you think your coverage report should have meaningful results. @(stack_0VvCbDQ2gfsBxzuxYlepyD:Stack.Coverage src/Stack/Coverage.hs:201:21)
2015-12-19 18:33:24.736096: [info] Only one tix file found in /home/ubuntu/workspace/craft/chapter3/.stack-work/install/x86_64-linux/lts-3.18/7.10.2/hpc/, so not generating a unified coverage report. @(stack_0VvCbDQ2gfsBxzuxYlepyD:Stack.Coverage src/Stack/Coverage.hs:289:14)
2015-12-19 18:33:24.737580: [info] 
An index of the generated HTML coverage reports is available at /home/ubuntu/workspace/craft/chapter3/.stack-work/install/x86_64-linux/lts-3.18/7.10.2/hpc/index.html @(stack_0VvCbDQ2gfsBxzuxYlepyD:Stack.Coverage src/Stack/Coverage.hs:385:9)

**Comment by rwobben** [comment] 2015-12-19 18:58
sorry, this one is still not solved

**Comment by rwobben** [comment] 2015-12-20 17:03
When I tried again today I see this output 

``` wissel:~/workspace/craft/chapter3 (master) $ stack clean
wissel:~/workspace/craft/chapter3 (master) $ stack test coverage
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      base: needed (>=4.7 && <4.8), 4.8.1.0 found (latest applicable is 4.7.0.2)
    needed for package: coverage-0.1.0.3 ```

**Comment by mgsloan** [comment] 2015-12-20 22:27
Dupe of #1411 .

For the most recent repro, the mistake is doing `stack test coverage` (`coverage` is a package) instead of `stack test --coverage`

**Closed by mgsloan** 2015-12-20 22:27 UTC

**Comment by rwobben** [comment] 2015-12-21 07:18
I reopen it again. 

When I do stack test --coverage I see this output ;

```
Generating coverage report for chapter3's test-suite "chapter3-test"
 81% expressions used (9/11)
100% boolean coverage (0/0)
     100% guards (0/0)
     100% 'if' conditions (0/0)
     100% qualifiers (0/0)
 75% alternatives used (6/8)
100% local declarations used (0/0)
 75% top-level declarations used (3/4)
The coverage report for chapter3's test-suite "chapter3-test" is available at /home/ubuntu/workspace/craft/chapter3/.stack-work/install/x86_64-linux/lts-3.18/7.10.2/hpc/chapter3/chapter3-test/hpc_index.html
Only one tix file found in /home/ubuntu/workspace/craft/chapter3/.stack-work/install/x86_64-linux/lts-3.18/7.10.2/hpc/, so not generating a unified coverage report.
```

but as soon as I open the html report of chapter3 I still see this output : 
```
HPC Report Generation Error

Error: The coverage report for chapter3's test-suite "chapter3-test" did not consider any code. One possible cause of this is if your test-suite builds the library code (see stack issue #1008). It may also indicate a bug in stack or the hpc program. Please report this issue if you think your coverage report should have meaningful results.
```
