### ISSUE TITLE
ghcjs: cannot find package/module

### ISSUE THREAD

**Issue by emmanueltouzery** [commercialhaskell/stack#2495] opened 2016-08-15 13:22 UTC
I am seeing an issue with a stack/ghcjs setup; google also turned up that issue which seems to be my exact problem:  
https://github.com/yamafaktory/reflex-starter/issues/1
[unresolved, the maintainer suggested to open a `stack` bug, which it seems wasn't done]

My stack version is `1.1.2, Git revision 0d143ff492819dd4e5b5b680b3e2ad4dc17957ff (3671 commits) x86_64 hpack-0.14.0`.

here is a trivial test project (depending on newer versions of reflex & reflex-dom):
https://www.dropbox.com/s/alfpf300q3a55nj/stest.tgz?dl=0
[basically it contains a single line App.hs, then a stack.yaml & a cabal file]

In a clean environment, run `stack setup` then `stack build`.

As in the bug I'm linking, at first I was getting `Cannot find package` with a random package (different one each time). Later I remamed my `~/.stack` and now I'm getting `Could not find module`, `Perhaps you haven't install the "js" libraries for...`.

**Comment by agrafix** [comment] 2016-08-19 11:05
I can confirm this, I have the exact same issue! `stack build` seems to be flakey - if you retry often enough it works.

I'm on `Version 1.1.2 x86_64 hpack-0.14.0` and my `stack.yaml` looks like this:

```
resolver: lts-6.12
packages:
  - pkgs/tramcloud-frontend
  - pkgs/tramcloud-api
  - pkgs/tramcloud-util
extra-deps:
  - react-flux-1.2.1
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3
```

**Comment by mgsloan** [comment] 2016-08-20 01:29
There are a variety of versions of node that can have this sort of effect - https://github.com/commercialhaskell/stack/issues/1632

I'm not sure, but you may also need to blow away the ghcjs install in `stack path --programs`, and also remove ~/.ghcjs .  Try not removing first.  The only reason removing would be needed is if the buggy node version caused corrupted things to get written.

**Comment by agrafix** [comment] 2016-08-20 09:01
I'm on `6.1.0`. I think it would be a good idea to document this more prominently on the GHCJS Stack documentation? I.e.: We suggest using node version `0.12.10` or `6.2.2`, other may have issues. See issue #1632 and ...?

**Comment by mgsloan** [comment] 2016-08-23 21:00
Yes, if we can decide on a blessed node version and document it, then that'd be great.  I haven't had time to figure out the ideal node version.

**Comment by tolysz** [comment] 2016-08-27 17:15
node 6.4 is blessed

**Comment by emmanueltouzery** [comment] 2016-08-29 22:30
hmm for my specific case, I'm still not making it. Made sure node was 6.4.0, actually wiped `.stack-work`, `~/.ghcjs` and `~/.stack`, now I get errors like:

    Configuring MemoTrie-0.6.4...
    setup-Simple-Cabal-1.22.8.0-ghcjs-0.2.0_ghc-7.10.3:
    .stack-work/dist/x86_64-linux/Cabal-1.22.8.0_ghcjs/: does not exist

**Comment by tolysz** [comment] 2016-08-29 23:16
Did you wiped **relevant** subdirectories of `~/.ghcjs/` and `~/.stack/`
Or just build a new `ghcjs` with a new name eg (sorry for suggesting my repack ;) )

    resolver: lts-6.13
    compiler: ghcjs-0.2.0.9006013_ghc-7.10.3
    compiler-check: match-exact
    setup-info:
      ghcjs:
        source:
          ghcjs-0.2.0.9006013_ghc-7.10.3:
             url: "https://tolysz.org/ghcjs/lts-6.13-9006013.tar.gz"
             sha1: "7ae7c6571e0fc7642701af3d8a63739369e0f6e8"

**Comment by emmanueltouzery** [comment] 2016-08-30 04:33
I wiped at first subfolders of eg ~/.stack as described by @mgsloan then everything. I left `/usr/bin/node` alone but put 6.4.0 in the path. Surely `/usr/bin` is not hardcoded!?
Ghcjs was booted for scratch again (twice, since I first tried partial, then full wipe).

**Comment by tolysz** [comment] 2016-08-30 07:03
It is for now...
https://github.com/commercialhaskell/stack/issues/1632
https://github.com/ghcjs/ghcjs/issues/491

**Comment by emmanueltouzery** [comment] 2016-08-30 07:28
crazy!!! I'll try again tonight by uninstalling my system's node and letting `n` overwrite /usr/bin, and I'll report.

**Comment by emmanueltouzery** [comment] 2016-08-30 15:57
Hmm sorry I've rebuilt all with /usr/bin/node being 6.4.0 and I still get that error, as previously:

    Configuring MemoTrie-0.6.4...
    setup-Simple-Cabal-1.22.8.0-ghcjs-0.2.0_ghc-7.10.3:
    .stack-work/dist/x86_64-linux/Cabal-1.22.8.0_ghcjs/: does not exist

I had wiped my ~/.stack, ~/.ghcjs, and the .stack-work...

**Comment by tolysz** [comment] 2016-08-30 17:04
The only question left is: how did you install `ghcjs`, as it looks like a direct install from ghcjs.luite.com?

    resolver: lts-6.14
    compiler: ghcjs-0.2.0.9006014_ghc-7.10.3
    compiler-check: match-exact
    setup-info:
      ghcjs:
        source:
          ghcjs-0.2.0.9006014_ghc-7.10.3:
             url: "http://tolysz.org/ghcjs/untested/lts-6.14-9006014.tar.gz"
             sha1: "8408f2a00654976feb374075c5f9adecf0cea4c8"

Could you post the relevant snippet of `stack.yaml` and say which version of `stack` do you use?

**Comment by emmanueltouzery** [comment] 2016-08-30 17:12
actually I opened the bug and in the first comment I give a link to a sample project reproducing the problem for me:
https://www.dropbox.com/s/alfpf300q3a55nj/stest.tgz?dl=0

I'm using the ghcjs recommended in the stack wiki. It worked for me just fine until now, now I tried upgrading my dependencies, and maybe my system (like node) changed in the meantime, so maybe even with my old dependencies I couldn't build it anymore.

Right now I'm trying this exact same setup, but with node 6.2.2 just in case...

**Comment by tolysz** [comment] 2016-08-30 17:50
You are using resolver `6.12` with some random versions of packages, `stack` is hardwired not to reinstall anything from `ghcjs` boot stage... could you please use one of my `repacks`? eg, the latest `lts-6.14` ?
I use `debian` and only changed `snipped` above in your `stack.yaml ` and it works...
I do not have any global ghc so I need to wrap my build in

    #!/usr/bin/env bash
    stack --stack-yaml stack-base.yaml setup
    PATH=`stack path --bin-path  --stack-yaml stack-base.yaml 2>/dev/null`:$PATH
    stack setup
    stack build

cat stack-base.yaml

    flags: {}
    packages: []
    system-ghc: false
    extra-deps: []
    resolver: lts-6.14

All together... I start it with `build.sh`
https://www.dropbox.com/s/80hf7rsv19lt6wa/stest-works.tar.xz?dl=0

**Comment by emmanueltouzery** [comment] 2016-08-30 17:59
well right now I tried with node 6.2.2 and it works! (at least it went through all the dependencies and is now failing to build my project, because `reflex` changed API)... Maybe my project is really not set up the way it should... but the fact is... with node 6.2.2 the dependencies get built properly and it goes far enough to build my code... With 6.4 it fails building the dependencies... So if we standardize on one version, with my limited knowledge currently I vote for 6.2.2 :wink:

**Comment by tolysz** [comment] 2016-08-30 18:05
Can I ask what OS do you have?
My plan is to make some matrix with different versions of node and test which one works for each build.

**Comment by emmanueltouzery** [comment] 2016-08-30 18:07
Of course, I have fedora 24 x64.

**Comment by tolysz** [comment] 2016-08-31 00:09
Just to say, I used the docker's `fedora:24` and followed my instructions and using `n` pointing to `/usr/bin/node` ... and successfully build your sample against `node-6.4.0` and `node-6.5.0` thus my guess there been some work done to improve `ghcjs` since your snapshot :)

**Comment by mgsloan** [comment] 2016-09-26 01:47
I haven't followed the full discussion here.  However, yes, some newer ghcjs tarballs include fixes that work around specific node problems.

**Comment by s9gf4ult** [comment] 2016-10-24 07:43
I had the same problem, this is weird, but installing `nodejs-5.11.0` solved the problem.

**Comment by dredozubov** [comment] 2016-12-08 16:16
i'm experiencing this issue with ghcjs configuration from this page https://github.com/commercialhaskell/stack/blob/master/doc/ghcjs.md

This is what i use:
```
resolver: lts-6.25
compiler: ghcjs-0.2.0.9006025_ghc-7.10.3
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006025_ghc-7.10.3:
         url: http://ghcjs.tolysz.org/lts-6.25-9006025.tar.gz
         sha1: 3c87228579b55c05e227a7876682c2a7d4c9c007
```

I'm getting the same issue with node 5.11 and 6.4.

**Comment by tolysz** [comment] 2016-12-08 22:38
@dredozubov Could you give more information when are you experiencing it? I try to run a quite recent version of node-6.9
Dou you have a simple project which fails?
I usually focus on the ghcjs8 branch, but if there is something in ghjs7 I could fix I will try.

**Comment by dredozubov** [comment] 2016-12-12 11:51
@tolysz I'm trying to upgrade a project that's quite big to the more recent stackage snapshot(moving from 5.14 to 6.24). Frankly, I don't have a clue how to make it reproducible on a small project.

**Comment by dredozubov** [comment] 2016-12-12 11:56
Update: I've tried it with lts-7.8 and ghc 8.0.1 and got the same result:
```
Progress: 4/85
--  While building package cookie-0.4.2.1 using:
      /Users/dr/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.22.8.0-ghcjs-0.2.0_ghc-7.10.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/dr/workspace/contractor/b2b/b2b-frontend/.stack-work/logs/cookie-0.4.2.1.log

    Configuring cookie-0.4.2.1...
    Building cookie-0.4.2.1...
    Preprocessing library cookie-0.4.2.1...

    /private/var/folders/f8/2_rc4tgd1gj9vbgv7q9gbk4c0000gn/T/stack69319/cookie-0.4.2.1/Web/Cookie.hs:40:8:
        Could not find module ‘Blaze.ByteString.Builder’
        Perhaps you haven't installed the "js" libraries for package ‘blaze-builder-0.4.0.2@blaze_8iiR3gHiZe7F3iKGFq4l3h’?
        Use -v to see a list of the files searched for.

    /private/var/folders/f8/2_rc4tgd1gj9vbgv7q9gbk4c0000gn/T/stack69319/cookie-0.4.2.1/Web/Cookie.hs:41:8:
        Could not find module ‘Blaze.ByteString.Builder.Char8’
        Perhaps you haven't installed the "js" libraries for package ‘blaze-builder-0.4.0.2@blaze_8iiR3gHiZe7F3iKGFq4l3h’?
        Use -v to see a list of the files searched for.


--  While building package blaze-markup-0.7.1.0 using:
      /Users/dr/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.22.8.0-ghcjs-0.2.0_ghc-7.10.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.8.0_ghcjs build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/dr/workspace/contractor/b2b/b2b-frontend/.stack-work/logs/blaze-markup-0.7.1.0.log

    Configuring blaze-markup-0.7.1.0...
    Building blaze-markup-0.7.1.0...
    Preprocessing library blaze-markup-0.7.1.0...

    /private/var/folders/f8/2_rc4tgd1gj9vbgv7q9gbk4c0000gn/T/stack69319/blaze-markup-0.7.1.0/src/Text/Blaze/Renderer/Utf8.hs:20:18:
        Could not find module ‘Blaze.ByteString.Builder’
        Perhaps you haven't installed the "js" libraries for package ‘blaze-builder-0.4.0.2@blaze_8iiR3gHiZe7F3iKGFq4l3h’?
        Use -v to see a list of the files searched for.

    /private/var/folders/f8/2_rc4tgd1gj9vbgv7q9gbk4c0000gn/T/stack69319/blaze-markup-0.7.1.0/src/Text/Blaze/Renderer/Utf8.hs:21:18:
        Could not find module ‘Blaze.ByteString.Builder.Html.Utf8’
        Perhaps you haven't installed the "js" libraries for package ‘blaze-builder-0.4.0.2@blaze_8iiR3gHiZe7F3iKGFq4l3h’?
        Use -v to see a list of the files searched for.
```

**Comment by tolysz** [comment] 2017-01-12 15:01
@dredozubov Could you simply post the `.cabal` with some dummy `main.hs`

**Comment by mgsloan** [comment] 2017-01-31 03:47
I can't reproduce the issue with the tarball project.  Since this conversation hasn't been updated in a while, closing.

**Closed by mgsloan** 2017-01-31 03:47 UTC
Labels: component: ghcjs
