### ISSUE TITLE
"invalid argument" error on windows

### ISSUE THREAD

**Issue by pbethke** [commercialhaskell/stack#1448] opened 2015-11-28 21:10 UTC
I had dependency problems building my project with global cabal, so i wanted to switch to stack. Whereas I am able to install new packages via cabal-install, stack always fails with the same error.

The system is Windows 8.1 x64 first with haskell platform and stack, later only stack. The error did not change.

**Steps to reproduce**
1. Download stack installer and install stack
2. Create new stack project with ```stack new```
3. ```cd``` into the new project directory
4. ```stack setup``` finishes successfully (both with haskell platform ghc and newly downloaded ghc)
5. Try ```stack install cabal-install``` (or any other package)

**Expected:**
6. successful build of cabal and other packages

**Actual:**
6. Get the following error structure:

```
PS D:\stacktest> stack build
Setting codepage to UTF-8 (65001) to ensure correct output from GHC
[1 of 1] Compiling Main             ( C:\Users\USER\AppData\Local\Temp\stack764\Setup.hs, C:\Users\USER\AppData\Lo
cal\Temp\stack764\Setup.o )
Linking C:\stack_root\setup-exe-cache\tmp-setup-Simple-Cabal-1.22.4.0-x86_64-windows-ghc-7.10.2.exe ...
stacktest-0.1.0.0: configure
Configuring stacktest-0.1.0.0...
setup-Simple-Cabal-1.22.4.0-x86_64-windows-ghc-7.10.2.exe: fd:4: invalid
argument
setup-Simple-Cabal-1.22.4.0-x86_64-windows-ghc-7.10.2.exe: fd:4: hGetContents: invalid argument (invalid byte sequence)

--  While building package stacktest-0.1.0.0 using:
      C:\stack_root\setup-exe-cache\setup-Simple-Cabal-1.22.4.0-x86_64-windows-ghc-7.10.2.exe --builddir=.stack-work\dis
t\d96ab9d9 configure --with-ghc=C:\Users\USER\AppData\Local\Programs\stack\x86_64-windows\ghc-7.10.2\bin\ghc.exe --wi
th-ghc-pkg=C:\Users\USER\AppData\Local\Programs\stack\x86_64-windows\ghc-7.10.2\bin\ghc-pkg.exe --user --package-db=c
lear --package-db=global --package-db=C:\stack_root\snapshots\cf5cf2bf\pkgdb --package-db=D:\stacktest\.stack-work\insta
ll\2bc429f2\pkgdb --libdir=D:\stacktest\.stack-work\install\2bc429f2\lib --bindir=D:\stacktest\.stack-work\install\2bc42
9f2\bin --datadir=D:\stacktest\.stack-work\install\2bc429f2\share --libexecdir=D:\stacktest\.stack-work\install\2bc429f2
\libexec --sysconfdir=D:\stacktest\.stack-work\install\2bc429f2\etc --docdir=D:\stacktest\.stack-work\install\2bc429f2\d
oc\stacktest-0.1.0.0 --htmldir=D:\stacktest\.stack-work\install\2bc429f2\doc\stacktest-0.1.0.0 --haddockdir=D:\stacktest
\.stack-work\install\2bc429f2\doc\stacktest-0.1.0.0 --dependency=base=base-4.8.1.0-5e8cb96faebe2db97f24c6e11c6070d6 --ex
tra-include-dirs=C:\Users\USER\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw32\include --extra-inc
lude-dirs=C:\Users\USER\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\include --extra-lib-dirs=C
:\Users\USER\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw32\lib --extra-lib-dirs=C:\Users\USER
\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\lib --enable-tests --enable-benchmarks
    Process exited with code: ExitFailure 1
PS D:\stacktest> stack build
Setting codepage to UTF-8 (65001) to ensure correct output from GHC
stacktest-0.1.0.0: configure
Configuring stacktest-0.1.0.0...
setup-Simple-Cabal-1.22.4.0-x86_64-windows-ghc-7.10.2.exe: fd:4: invalid
argument
setup-Simple-Cabal-1.22.4.0-x86_64-windows-ghc-7.10.2.exe: fd:4: hGetContents: invalid argument (invalid byte sequence)

--  While building package stacktest-0.1.0.0 using:
      C:\stack_root\setup-exe-cache\setup-Simple-Cabal-1.22.4.0-x86_64-windows-ghc-7.10.2.exe --builddir=.stack-work\dis
t\d96ab9d9 configure --with-ghc=C:\Users\USER\AppData\Local\Programs\stack\x86_64-windows\ghc-7.10.2\bin\ghc.exe --wi
th-ghc-pkg=C:\Users\USER\AppData\Local\Programs\stack\x86_64-windows\ghc-7.10.2\bin\ghc-pkg.exe --user --package-db=c
lear --package-db=global --package-db=C:\stack_root\snapshots\cf5cf2bf\pkgdb --package-db=D:\stacktest\.stack-work\insta
ll\2bc429f2\pkgdb --libdir=D:\stacktest\.stack-work\install\2bc429f2\lib --bindir=D:\stacktest\.stack-work\install\2bc42
9f2\bin --datadir=D:\stacktest\.stack-work\install\2bc429f2\share --libexecdir=D:\stacktest\.stack-work\install\2bc429f2
\libexec --sysconfdir=D:\stacktest\.stack-work\install\2bc429f2\etc --docdir=D:\stacktest\.stack-work\install\2bc429f2\d
oc\stacktest-0.1.0.0 --htmldir=D:\stacktest\.stack-work\install\2bc429f2\doc\stacktest-0.1.0.0 --haddockdir=D:\stacktest
\.stack-work\install\2bc429f2\doc\stacktest-0.1.0.0 --dependency=base=base-4.8.1.0-5e8cb96faebe2db97f24c6e11c6070d6 --ex
tra-include-dirs=C:\Users\USER\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw32\include --extra-inc
lude-dirs=C:\Users\USER\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\include --extra-lib-dirs=C
:\Users\USER\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw32\lib --extra-lib-dirs=C:\Users\USER
\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\lib --enable-tests --enable-benchmarks
    Process exited with code: ExitFailure 1
```

I have tried both powershell and cmd, uninstalling haskell platform, manually removing the stack root, ghc and cabal dirs in %APPDATA%. It doesn't change. Someone on the IRC suggested a unicode problem, but i have no idea how to check for that.

**Comment by pbethke** [comment] 2015-11-29 08:27
Oh, that lengthy command ```C:\stack_root\setup-exe-cache\setup-Simple-Cabal-1.22.4.0-x86_64-windows-ghc-7.10.2.exe`...``` doesn't fail if i call it manually. Is it related to that codepage setting?

**Comment by pbethke** [comment] 2015-11-29 08:38
OK, one more update:
Using the ```bash``` some ssh client brought onto my system, I am able to install and build packages again:
* ```stack build``` fails just as before
* ```LANG=C.utf-8 stack build``` works as intended.

**Comment by mgsloan** [comment] 2016-01-03 07:19
Did `LANG=C.utf-8` resolve the issue, then?  Feel free to re-open if not.

**Comment by CarstenKoenig** [comment] 2016-01-11 14:38
I have the same issue on windows with 

> Version 1.0.0, Git revision 3bc26237b5b3c387b8fd564459ea4dd88fd58b30 (2939 commits) x86_64

and while `LANG=C.utf-8 stack buid` solves the problem it (of course) only works if you are using some kind of **bash**

I think you can also add this to your environment variables in windows to work but all this feels like *workarounds* to me - so it would be great if you could look on it again

---

in case I am just using an outdated version (although I did grab the latest binary just now) - then please feel free to ignore or delete this comment/item

Thank you

**Comment by mgsloan** [comment] 2016-01-11 21:35
@borsboom @snoyberg I don't really grok this windows codepage stuff.  Is there something that can be done automatically here?

A couple relevant issues from the past, that led to the current codepage stuff: https://github.com/commercialhaskell/stack/issues/757 https://github.com/commercialhaskell/stack/issues/824

**Comment by user471** [comment] 2016-01-12 06:45
If cabal doesn't have such problem then what would be the main difference?

**Comment by borsboom** [comment] 2016-01-19 14:43
@CarstenKoenig Can you try stack-1.0.2 with GHC 7.10.3?  There have been a number of changes to the way GHC handles character encoding and so Stack no longer does any of the codepage/locale hacks if it detects that you're using ghc-7.10.3 or later.

**Comment by CarstenKoenig** [comment] 2016-01-19 15:00
I just tested it with 1.0.2 and indeed it seems to work (even with GHC 7.10.2).
I'm not 100% sure as I set `LANG` in my environments-variables in windows as a workaround and although I removed it in the prompt with `set LANG=` I sometimes doubt if it will not somehow reassign it ...

To make it short I removed the environment and will try again once I rebooted my machine tomorrow.

**Comment by CarstenKoenig** [comment] 2016-01-21 05:49
Update: it seems to work for me right now even on GHC 7.10.2 which seems strange (especially as it tells me

    Setting codepage to UTF-8 (65001) to ensure correct output from GHC

still)

**Comment by CarstenKoenig** [comment] 2016-02-03 13:20
Well sadly the issue is back: if I

     stack install transformers-base

I get

    .stack-work\dist\d96ab9d9\build\src\Control\Monad\Base.dump-hi: commitBuffer: invalid argument (invalid character)

this time no setting (tried `LANG`, `LANGUAGE`, `LC_ALL`) helps

**Comment by mgsloan** [comment] 2016-02-04 01:50
Interesting.  Is there anything unusual about your setup?  I'm just wondering why we aren't hearing similar things from other windows users.

**Comment by CarstenKoenig** [comment] 2016-02-04 06:46
well that is hard to tell:

- Windows 10 Enterprise (german)
-  `stack --version: Version 1.0.2, Git revision fa09a980d8bb3df88b2a9193cd9bf84cc6c419b3 (3084 commits) x86_64`
- `ghc --version: The Glorious Glasgow Haskell Compilation System, version 7.10.2`
- `cabal --version: cabal-install version 1.22.6.0 using version 1.22.4.0 of the Cabal library`
- `LANG=C.utf8` set in environment (but tried to remove it too)

The error happens in the middle of building a project using `yesod-hello-world` - at least 20 dependencies build without any problems.

And maybe this is why you don't hear that much - if it only happens with certain packages in the middle of a big pile of other packages(?)

**Comment by CarstenKoenig** [comment] 2016-03-14 10:17
it's still there with stack 1.0.4 (while building ghcjs) - I tried:

- set `LC_ALL`, LANGUAGE`, `LANG` to `C.utf8`, `de_DE.utf8` or `en_US.utf8`
- using stack inside git-bash
- setting the codepage with `chcp 65001`

nothing works at the moment

**Comment by mgsloan** [comment] 2016-03-14 22:38
I'm not familiar enough with this issue / windows to be much help, sorry!  One wild guess is to try temporarily switching the locale to english?  That would at least tell us if it's some sort of issue related to locale

**Comment by CarstenKoenig** [comment] 2016-04-04 05:33
I just tried again and yes @mgsloan was on the right track.

Thankfully you don't have to reset your complete system.

If you change the **Language for non-Unicode programs** settings in windows ([as described here](http://windows.microsoft.com/en-us/windows/change-system-locale#1TC=windows-7)) to en-us it will finally compile (to be honest it still is here but it managed to compile `transformers` already)

**Comment by borsboom** [comment] 2016-04-04 16:21
Does anything change if you use GHC 7.10.3 instead of 7.10.2?  They fixed some locale issues on Windows in that and Stack disables its workarounds (which were not entirely reliable) when using 7.10.3 or later.

**Comment by Lewerow** [comment] 2016-09-24 16:38
I have the exactly same problem, also during building GHCJS - `transformers` not compiling on 64-bit Windows 10 with error `commitBuffer: invalid argument (invalid character)`. Setting `LC_ALL` etc. didn't help.
I checked `stack` 1.1.2 and 1.2.0 (no differences - neither works) and GHC 7.10.3 and 7.10.2 (also neither works).
Changing *Language for non-Unicode programs* to *English (US)* helped (my usual locale is Polish).
If it's hard to fix and heavily configuration-dependent, it would be great if we at least had a hint in https://docs.haskellstack.org/en/stable/ghcjs/#ghcjs that such problems happen in Windows environments and the workaround is changing locale

**Comment by mgsloan** [comment] 2016-10-04 20:46
Since there is a documentation fix, closing this for now.  If there is something that stack can do better here, please open another issue about it!

**Closed by mgsloan** 2016-10-04 20:46 UTC
Labels: component: windows, type: enhancement
