### ISSUE TITLE
Stack clones external repositories multiple times

### ISSUE THREAD

**Issue by jonathanknowles** [commercialhaskell/stack#5453] opened 2020-12-08 07:42 UTC
### General summary

In certain situations, stack clones external dependencies **_multiple times_** instead of cloning a single time and caching the result.

In pathological cases, this causes stack to spend a great deal of time re-cloning the same repository, greatly increasing network data usage.

### Steps to reproduce

1. Clone either of the following repositories:
    - minimal test case:
      https://github.com/rvl/stack-git-package-subdirs-test
    - more complex test case:
      https://github.com/input-output-hk/cardano-wallet/
2. Build with `stack build --fast --test --no-run-tests --bench --no-run-benchmarks`
3. Observe the build output.

### Expected

Stack clones external repositories as needed, but does not clone each external repository more than once.

### Actual

Stack clones certain repositories multiple times:

![stack-repeated-repository-clones](https://user-images.githubusercontent.com/206319/101454244-9a6c3a00-396b-11eb-833d-99b65973bf82.png)

### Stack version

```
$ stack --version
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by KtorZ** [comment] 2020-12-08 08:47
duplicate of: https://github.com/commercialhaskell/stack/issues/5411 ?

**Comment by mpilgrem** [comment] 2024-03-10 17:41
I am closing this issue as it appears to me also to be a duplicate of #5411.

**Closed by mpilgrem** 2024-03-10 17:41 UTC
Labels: resolution: duplicate
