### ISSUE TITLE
`stack test --coverage` crashes

### ISSUE THREAD

**Issue by soenkehahn** [commercialhaskell/stack#1162] opened 2015-10-15 05:20 UTC
`stack test --coverage` crashes with the following message:
`/home/shahn/dead-code-detection/.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/package.conf.inplace/dead-code-detection-0.4-inplace.conf: openFile: does not exist (No such file or directory)`

`stack` revision: ddc45880bbf2688c7d3ece8c2ec0f432b35fe3b9 (recent master)

Running `stack test --coverage` in https://github.com/soenkehahn/dead-code-detection/tree/b405254521faf4cce78ee9fc819a323fbcdac983.

**Comment by mgsloan** [comment] 2015-10-15 05:49
Hey Soenke, thanks for reporting this!  I can indeed reproduce the issue, it's due to a change I made a few hours ago in an attempt to fix coverage results.  I've reverted the change.

The problem is that I need to get a package key (those things that look like `deadc_A7pNEgFOJJW9nvvA3ldIjb`) for a package that just got built.  ghc-pkg can tell me info about these packages, since they are installed locally even for `stack build` or `stack test`.  However, it seems to give me the wrong package keys sometimes...  I need to investigate this further.

**Comment by mgsloan** [comment] 2015-10-18 02:32
@soenkehahn I've reverted the commit that caused this, so this particular issue is now fixed.

The core issue is unfortunately unresolved: https://github.com/commercialhaskell/stack/issues/1181

It'll get fixed one way or another, though.

**Closed by mgsloan** 2015-10-18 02:32 UTC

**Comment by soenkehahn** [comment] 2015-10-20 17:16
I added a library section to the cabal file and let the test suite depend on it. Then everything works. It would be nice if that weren't necessary of course.

Btw, this is not at all urgent to me. It just would be great if `stack` supported this out of the box. Thanks for working on this!

**Comment by mgsloan** [comment] 2015-10-21 01:48
@soenkehahn Welcome!  I've added some more explanation of why it's done this way here: https://github.com/commercialhaskell/stack/issues/1008#issuecomment-149751891

Also, I've just added a `stack hpc report` command, which lets you create reports from tix files.  If you specify multiple tix files / package components, then the coverage info gets unioned together.
