### ISSUE TITLE
STACK_ROOT on a non-root partition fails (linux)

### ISSUE THREAD

**Issue by penteract** [commercialhaskell/stack#4884] opened 2019-06-19 00:15 UTC
### General summary/comments
When trying to force stack to use a non-root partition, it fails when installing GHC.

### Steps to reproduce

1. Make an NTFS partition mounted at `/shared` with a directory `/shared/stack/`
2. `ln -s /shared/stack ~/.stack`
3. `stack update`
4. `stack ghci` (or any other stack command that requires ghc)

### Expected

GHC gets downloaded and installed then a GHCi prompt appears.

### Actual

Stack downloads and extracts, but installation fails

Full log: https://gist.github.com/penteract/bbd263852553cb49f6563d6e24693c85

```
$ stack ghci --verbose --stack-root="/shared/stack"
...
2019-06-19 00:53:06.940360: [debug] Configuring ghc-prim-0.5.3...
2019-06-19 00:53:06.940690: [error] ghc-cabal: Cannot find the program 'ghc'. User-specified path
2019-06-19 00:53:06.940850: [error] '/builds/ghc/ghc/inplace/bin/ghc-stage1' does not refer to an executable and
2019-06-19 00:53:06.941005: [error] the program is not on the system path.
2019-06-19 00:53:06.941146: [error] 
2019-06-19 00:53:06.943328: [error] make[1]: *** [ghc.mk:990: install_packages] Error 1
2019-06-19 00:53:06.944531: [error] make: *** [Makefile:51: install] Error 2
2019-06-19 00:53:06.944980: [error] Received ExitFailure 2 when running
Raw command: /usr/bin/make install
Run from: /shared/stack/programs/x86_64-linux/ghc-tinfo6-8.6.5.temp/ghc-8.6.5/

2019-06-19 00:53:06.945261: [error] 
Error: Error encountered while installing GHC with
         make install
         run in /shared/stack/programs/x86_64-linux/ghc-tinfo6-8.6.5.temp/ghc-8.6.5/
       
       The following directories may now contain files, but won't be used by stack:
         - /shared/stack/programs/x86_64-linux/ghc-tinfo6-8.6.5.temp/
         - /shared/stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/
       
       For more information consider rerunning with --verbose flag
       
Installing GHC ...
```

### Stack version

```
$ stack --version
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

### Additional Comments

The issue also existed in stack 1.9.3.

I have tried both symlinks and --stack-root, but not any partition type other than NTFS (other than my primary ext4 partition that works). My home directory is on the same partition as my root directory.

**Comment by snoyberg** [comment] 2019-06-23 02:29
I'm guessing this is an upstream issue with GHC's scripts itself, where they are failing due to executable permissions issues. Can you try manually running `./configure && make install` inside an unpacked GHC directory on that NTFS volume?

**Comment by Treferwynd** [comment] 2019-08-07 10:56
I have the same problem, and I get:
```
$ make install
make --no-print-directory -f ghc.mk install BINDIST=YES NO_INCLUDE_DEPS=YES
/usr/bin/install -c -m 755 -d "/usr/local/bin"
"rm" -f                                         "/usr/local/bin/hp2ps"  
create () { touch "$1" && chmod 755 "$1" ; } && create                                           "/usr/local/bin/hp2ps"
touch: cannot touch '/usr/local/bin/hp2ps': Permission denied
make[1]: *** [utils/hp2ps/ghc.mk:46: install_utils/hp2ps_dist-install_wrapper] Error 1
make: *** [Makefile:51: install] Error 2```

**Comment by snoyberg** [comment] 2019-08-08 02:14
That looks like a file permissions issue more than anything else. Are you
sure you're able to write to the file in question? In any event, this looks
like it's out of school for Stack, since it's reproducible with GHC itself.

**Comment by Treferwynd** [comment] 2019-08-08 13:33
It's a bit weird: as in the OP, my home is on an ext4 partition and Stack works fine there, unless I symlink `.stack/` to a NTFS partition. 
While if I `make install` GHC directly from source it fails on both partitions with the same permission error as before (which is correct I guess, since the local user does not have write access to `/usr/local/bin/`).

The interesting bit is that when Stack works (i.e. `.stack/` on the ext4 partition) `/usr/local/bin/hp2ps` is *not* created, so I guess Stack tries to compile GHC with a different configuration (?no idea?).

**Comment by cdfa** [comment] 2020-06-03 23:04
I'm having the same issue, but I just set my `STACK_ROOT` to a path on a NTFS partition, no symlink.
Getting the exact same error messages. Could it be harmful to run as root?

**Comment by mpilgrem** [comment] 2024-04-01 19:49
I am closing this issue given the passage of time and because I understand that it has been identified as an issue with GHC itself.

**Closed by mpilgrem** 2024-04-01 19:49 UTC
Labels: resolution: upstream issue, component: setup, component: linux
