### ISSUE TITLE
Stack 2.1.1 failing to chekcout `extra-deps` due to `tar` problem

### ISSUE THREAD

**Issue by vertexcite** [commercialhaskell/stack#4890] opened 2019-06-20 04:15 UTC
### General summary/comments (optional)
Stack 1.9.x allows `extra-deps` from e.g. GitHub.  On Mac, stack 2.1.1 appears to fail due to using `--force-local` option of `tar` with the error message saying that option is not supported by `tar`.

Might be related to #4888

### Steps to reproduce
Run `stack build` where `stack.yaml` has a `git` item under `extra-deps`

See example below:
```
$ git clone https://github.com/vertexcite/Frames.git Frames
$ cd Frames
$ git checkout repair-self-contained-example
Branch 'repair-self-contained-example' set up to track remote branch 'repair-self-contained-example' from 'origin'.
Switched to a new branch 'repair-self-contained-example'
$ cd demo/framestack/
$ stack --version
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
$ stack build
Cloning 191de8964dfc71119c62087ae81d362726114677 from https://github.com/acowley/Frames.git
Received ExitFailure 128 when running
Raw command: /Users/myuser/.nix-profile/bin/git submodule foreach --recursive "git -c core.autocrlf=false archive --prefix=$displaypath/ -o bar.tar HEAD && if [ -f bar.tar ]; then tar --force-local -Af /private/var/folders/7h/r_6bn1t55wv0l4mz5v6v75f40000gn/T/with-repo-archive69570/foo.tar bar.tar ; fi"
Run from: /private/var/folders/7h/r_6bn1t55wv0l4mz5v6v75f40000gn/T/with-repo69570/cloned
Standard output:

Entering 'Vinyl'
Standard error:

tar: Option --force-local is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
fatal: run_command returned non-zero status for Vinyl
.
```

### Expected
Expected success, as with previous release of stack, as shown below:

```
$ stack upgrade --binary-version 1.9.3
Current Stack version: 2.1.1, available download version: 1.9.3
Forcing binary upgrade
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1

$ stack build
Cloning 191de8964dfc71119c62087ae81d362726114677 from https://github.com/acowley/Frames.git
Cloning into '/Users/myuser/Frames/demo/framestack/.stack-work/downloaded/P1Cd-L3lP1_n'...
remote: Enumerating objects: 1809, done.
remote: Total 1809 (delta 0), reused 0 (delta 0), pack-reused 1809
Receiving objects: 100% (1809/1809), 1.99 MiB | 124.00 KiB/s, done.
Resolving deltas: 100% (1064/1064), done.
Submodule 'Vinyl' (https://github.com/VinylRecords/Vinyl.git) registered for path 'Vinyl'
Cloning into '/Users/myuser/Frames/demo/framestack/.stack-work/downloaded/P1Cd-L3lP1_n/Vinyl'...
remote: Enumerating objects: 1757, done.
remote: Total 1757 (delta 0), reused 0 (delta 0), pack-reused 1757
Receiving objects: 100% (1757/1757), 760.86 KiB | 210.00 KiB/s, done.
Resolving deltas: 100% (940/940), done.
Submodule path 'Vinyl': checked out '18762466b0e78741eda1cb17cf8120cf9ecbdc12'
Cloning e16ba6461bb12aa942bfd2cd41604be76dfc9eb7 from https://github.com/VinylRecords/Vinyl.git
Cloning into '/Users/myuser/Frames/demo/framestack/.stack-work/downloaded/ykzKPHzxScoL'...
remote: Enumerating objects: 1757, done.
remote: Total 1757 (delta 0), reused 0 (delta 0), pack-reused 1757
Receiving objects: 100% (1757/1757), 760.86 KiB | 150.00 KiB/s, done.
Resolving deltas: 100% (940/940), done.
vinyl-0.10.0: configure (lib)
vinyl-0.10.0: build (lib)
vinyl-0.10.0: copy/register
Frames-0.5.0: configure (lib)
Frames-0.5.0: build (lib)
Frames-0.5.0: copy/register
Building all executables for `framestack' once. After a successful build of all of them, only specified executables will be rebuilt.
framestack-0.1.0.0: configure (exe)
Configuring framestack-0.1.0.0...
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
framestack-0.1.0.0: build (exe)
Preprocessing executable 'framestack-exe' for framestack-0.1.0.0..
Building executable 'framestack-exe' for framestack-0.1.0.0..
[1 of 2] Compiling Main             ( app/Main.hs, .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/framestack-exe/framestack-exe-tmp/Main.o )
[2 of 2] Compiling Paths_framestack ( .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/framestack-exe/autogen/Paths_framestack.hs, .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/framestack-exe/framestack-exe-tmp/Paths_framestack.o )
Linking .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/framestack-exe/framestack-exe ...
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
framestack-0.1.0.0: copy/register
Installing executable framestack-exe in /Users/myuser/Frames/demo/framestack/.stack-work/install/x86_64-osx/lts-12.7/8.4.3/bin
Completed 3 action(s).
```

### Actual
Failed, as shown in first transcript.

### Stack version

```
$ stack --version
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by psibi** [comment] 2019-06-20 08:14
Thanks for the report! This is the duplicate of https://github.com/commercialhaskell/stack/issues/4865

There are two workarounds right now:
* Change url to different format: https://github.com/commercialhaskell/stack/issues/4865#issuecomment-502169845
* (Or) Install gnu-tar and give preference to it in $PATH: https://github.com/commercialhaskell/stack/issues/4865#issuecomment-502609664

**Comment by snoyberg** [comment] 2019-06-23 02:01
@psibi From the comments in the codebase, it looks like this option is only needed on Windows, where we already have control of the `tar` executable and know it's GNU tar. What do you think about making the inclusion of that flag dependent on whether the build is running on Windows?

**Comment by psibi** [comment] 2019-06-23 02:13
@snoyberg I think that's what is done in this PR: https://github.com/commercialhaskell/stack/pull/4879

**Comment by snoyberg** [comment] 2019-06-23 02:19
Doh, that's what I get for reading my emails in a weird order... thanks @psibi :)

**Comment by snoyberg** [comment] 2019-06-23 02:43
PR merged, closing.

**Closed by snoyberg** 2019-06-23 02:43 UTC
