### ISSUE TITLE
Using a GHC version other than configured in stack.yaml sometimes doesn't give an error

### ISSUE THREAD

**Issue by bergmark** [commercialhaskell/stack#1091] opened 2015-10-02 18:21 UTC
Reproduction:

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.4

# Clean 7.8
$ stack --stack-yaml stack-7.8.yaml clean

# Switch to 7.10
$ ghc10
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.2

# Compile and test on 7.10
$ stack --stack-yaml stack-7.10.yaml test -j4
[snip]
 Test Cases   Total
 Passed  13           13
 Failed  0            0
 Total   13           13

# Switch back to 7.8
$ ghc8
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.4

# Run test with the wrong snapshot
$ stack --stack-yaml stack-7.10.yaml test -j4
feed-0.3.10.2: test (suite: tests)
Text.RSS:
[snip]
 Test Cases   Total
 Passed  13           13
 Failed  0            0
 Total   13           13

# Here I think the test suite passes on 7.8, whereas:

$ stack --stack-yaml stack-7.8.yaml test -j4
feed-0.3.10.2: configure
Configuring feed-0.3.10.2...
feed-0.3.10.2: build
[snip]
```

Expected: All commands run with a GHC version not matching the resolver should give an error message.

Actual: No error message if... the build target hasn't changed?

**Comment by snoyberg** [comment] 2015-10-04 06:17
If you have a Stack-installed version of GHC available, it will just use it and ignore the non-matching GHC on the PATH. That seems to be what's going on here.

**Comment by bergmark** [comment] 2015-10-04 14:22
I have no stack installed versions of GHC.

**Comment by snoyberg** [comment] 2015-10-06 02:25
I'm really not sure how to proceed on this one. Could you create some kind of reproduction inside a Docker image, perhaps? I've never been able to fool Stack about which GHC version it's using.

**Comment by snoyberg** [comment] 2015-10-15 08:05
Bumping for repro, as it stands there's no progress we can make on this issue

**Comment by bergmark** [comment] 2015-10-15 17:08
I'll try, currently I'm trying to figure out what the password to log in to the default image is.

**Comment by snoyberg** [comment] 2017-07-05 16:49
Closing, if this pops up again please comment/reopen.

**Closed by snoyberg** 2017-07-05 16:49 UTC
Labels: need repro
