### ISSUE TITLE
"stack build" (ghcjs) fails with "happy" which requires ghc compiler in path

### ISSUE THREAD

**Issue by luigy** [commercialhaskell/stack#1258] opened 2015-10-31 02:46 UTC
asked on irc:
is there a particular reason why not to have the ghc compiler in the path as well?

@mgsloan:

> The reason GHC isn't on the path is that it's a pain to have the code keep track of two different compiler versions.  For most things it works great to only have GHCJS, but that's a good point - this isn't the case for build tools

[build log](http://lpaste.net/3427500905707077632)

``` sh
> stack --version
Version 0.1.7.0, Git revision 193b285e0dc8fd705a7d2475e5a57bb15f4a9990 (2453 commits) x86_64
```

**Comment by mgsloan** [comment] 2016-03-11 20:26
Note that the cause is that the setup script for happy hardcodes GHC.  Other than a circumstance like that GHCJS builds should /not/ demand a GHC.  However, given that cases like this do

As my other comment suggests, it could also be that we want to default to using GHC for arbitrary build-tool dependencies.  I'm not sure if GHCJS could build a working `happy`.

**Comment by tolgap** [comment] 2016-06-27 14:15
@mgsloan So what actually is the workaround? I'm trying to setup GHCJS for some researching, but `stack build` fails when trying to build happy with the same error you described. How do I correctly set the path for GHC so happy can compile?

**Comment by dysinger** [comment] 2016-06-28 20:09
I've added a realy GHC to my PATH (at the end of the PATH).  It's a ugly hack but it seems to work.

```
export PATH=$PATH:$HOME/.stack/programs/x86_64-linux/ghc-7.10.3/bin
```

**Comment by dysinger** [comment] 2016-06-28 20:14
We should send patches to `happy` maintainers since this is a (not) happy bug

**Comment by tolysz** [comment] 2016-09-27 23:44
I use 
```bash
export OLDPATH=$PATH
alias stackjs='stack --stack-yaml stack-ghcjs.yaml'
alias stack7='stack --stack-yaml stack.yaml'

stack7 setup
stack7 install alex happy hscolour
PATH=`stack7 path --bin-path 2>/dev/null`:$OLDPATH

echo SETUP
stackjs setup
```
https://github.com/tolysz/spock-ghcjs-sample/blob/master/build-lts.sh

And it works fine on any global `ghc`'less systems

**Comment by snoyberg** [comment] 2020-02-04 12:29
The next version of Stack will no longer have GHCJS support, closing.

**Closed by snoyberg** 2020-02-04 12:29 UTC
Labels: component: ghcjs, type: enhancement
