### ISSUE TITLE
Profiling: getDirectoryContents: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by alexbiehl** [commercialhaskell/stack#371] opened 2015-06-22 08:58 UTC
Hi, 

I get the following error when I try profiling my application: 

```
$ stack build --executable-profiling --library-profiling
/opt/local/lib/ /usr/local/lib/: getDirectoryContents: does not exist (No such file or directory)
```

My stack.yaml (no fancy settings)
```
packages:
  - ./html-hunter
  - ./hunt-client
  - ./hunt-crawler
  - ./hunt-searchengine
  - ./hunt-server
  - ./hunt-server-cli
extra-deps:
  - data-r-tree-0.0.5.0
  - data-stringmap-1.0.1.1
  - murmur-hash-0.1.0.8
  - ekg-core-0.1.0.4
  - hxt-xpath-9.1.2.2
  - hxt-cache-9.1.0.1
  - docopt-0.7.0.2
resolver: lts-2.13
```

**Comment by chrisdone** [comment] 2015-06-22 09:27
Can you re-run with `-v` and paste the output?

**Comment by chrisdone** [comment] 2015-06-22 09:29
Also, I wonder whether one of your cabal files contains the string `/opt/local/lib/ /usr/local/lib/`, where it ought to be comma-separated (perhaps).

**Comment by snoyberg** [comment] 2015-06-22 09:31
I'm guessing it's the profiling cache. It would seem that the GHC package dump is mentioning a directory that doesn't exist for some reason. I have a theoretical fix for this, just testing before pushing.

**Comment by snoyberg** [comment] 2015-06-22 09:42
OK, I just pushed a commit which may resolve the issue. @alexbiehl Would you be able to pull the latest master and test?

**Comment by chrisdone** [comment] 2015-06-22 10:22
Wait… is this not a parsing issue instead?

```
/opt/local/lib/ /usr/local/lib/: getDirectoryContents: does not exist (No such file or directory)
```

That implies the path it's trying to read is literally `"/opt/local/lib/ /usr/local/lib/"`. I don't see another explanation for that error message; at some point two separate paths are being considered as one.

**Comment by alexbiehl** [comment] 2015-06-22 10:38
@snoyberg your fix seems to work. 

@chrisdone no, none of my cabal files contains such paths. 

Anyway, my `stack` verbose output (before switching to master):
```
Admins-MacBook-Air:hunt alexbiehl$ stack -v build  --executable-profiling --library-profiling
Version 0.0.3.1, Git revision ba1075a6452ca50b6c927864cf447335952cca7e
2015-06-22 10:17:37.806613: [debug] Checking for project config at: /Users/alexbiehl/git/hunt/stack.yaml @(stack-0.0.3.1:Stack.Config src/Stack/Config.hs:473:9)
2015-06-22 10:17:37.806998: [debug] Loading project config file stack.yaml @(stack-0.0.3.1:Stack.Config src/Stack/Config.hs:494:13)
2015-06-22 10:17:37.818841: [debug] Run process: ghc --info @(stack-0.0.3.1:System.Process.Read src/System/Process/Read.hs:253:3)
2015-06-22 10:17:37.884361: [debug] Run process: ghc --numeric-version @(stack-0.0.3.1:System.Process.Read src/System/Process/Read.hs:253:3)
2015-06-22 10:17:37.9219: [debug] Run process: ghc-pkg --no-user-package-db describe Cabal @(stack-0.0.3.1:System.Process.Read src/System/Process/Read.hs:253:3)
2015-06-22 10:17:37.953808: [debug] Run process: ghc-pkg --no-user-package-db list --global @(stack-0.0.3.1:System.Process.Read src/System/Process/Read.hs:253:3)
2015-06-22 10:17:37.989736: [debug] Checking resolver: lts-2.13 @(stack-0.0.3.1:Stack.Build.Source src/Stack/Build/Source.hs:75:13)
2015-06-22 10:17:38.435521: [debug] Run process: ghc-pkg --global --no-user-package-db dump --expand-pkgroot @(stack-0.0.3.1:System.Process.Read src/System/Process/Read.hs:253:3)
2015-06-22 10:17:38.505577: [debug] Run process: ghc-pkg --user --no-user-package-db --package-db /Users/alexbiehl/.stack/snapshots/x86_64-osx/lts-2.13/7.8.4/pkgdb/ dump --expand-pkgroot @(stack-0.0.3.1:System.Process.Read src/System/Process/Read.hs:253:3)
/opt/local/lib/ /usr/local/lib/: getDirectoryContents: does not exist (No such file or directory)
```

**Comment by chrisdone** [comment] 2015-06-22 10:42
Can you paste the output of this to https://gist.github.com/?

    ghc-pkg --user --no-user-package-db --package-db /Users/alexbiehl/.stack/snapshots/x86_64-osx/lts-2.13/7.8.4/pkgdb/ dump --expand-pkgroot

**Comment by snoyberg** [comment] 2015-06-22 10:42
@chrisdone you're right, my fix here is incorrect

**Comment by alexbiehl** [comment] 2015-06-22 10:44
https://gist.github.com/alexbiehl/9d7e49609f3e0aed3ef0

**Comment by chrisdone** [comment] 2015-06-22 10:46
@alexbiehl Thanks! I see the content has

```
library-dirs: /Users/alexbiehl/.stack/snapshots/x86_64-osx/lts-2.13/7.8.4/lib/x86_64-osx-ghc-7.8.4/hmatrix-0.16.1.5
              /opt/local/lib/ /usr/local/lib/
```

But the dump parser [splits with S8.words](https://github.com/commercialhaskell/stack/blob/master/src/Stack/PackageDump.hs#L310..L310) so I'm unsure where the issue is. But we can use this output to test out the parser.

**Comment by chrisdone** [comment] 2015-06-22 10:51
Ah, correction: `libDirs`. `eachPair` splits by lines, so I guess we just need a thing to split the paths on spaces. 

Presumably something that can handle speech marks in the case of paths with spaces in, like Windows.

**Comment by chrisdone** [comment] 2015-06-22 10:54
Yep, paths with spaces in are wrapped in speech marks: https://github.com/ghc/ghc/blob/master/testsuite/tests/cabal/ghcpkg01.stdout#L24..L24

**Comment by snoyberg** [comment] 2015-06-22 11:01
Good find @chrisdone

**Comment by chrisdone** [comment] 2015-06-22 11:31
@snoyberg  Done in 2a564ec, can you review? I re-used the args parsing I did elsewhere, which [has a test suite](https://github.com/commercialhaskell/stack/blob/master/src/test/Stack/ArgsSpec.hs#L1) already.

**Comment by snoyberg** [comment] 2015-06-22 11:37
Looks good, only change I made was adding the file to extra-source-files (which is necessary since Cabal's globbing is broken).

@alexbiehl Can you confirm that this fixes things on your system?

**Comment by alexbiehl** [comment] 2015-06-22 13:59
@snoyberg Looks good to me! Thank you!

**Comment by snoyberg** [comment] 2015-06-22 14:22
Thanks for checking Alex. And credit on this one goes to Chris, not me :)

**Closed by snoyberg** 2015-06-22 14:22 UTC
Labels: need-confirmation
