### ISSUE TITLE
`stack ghci` can't load package defined in `internal-libraries`

### ISSUE THREAD

**Issue by karamellpelle** [commercialhaskell/stack#6214] opened 2023-08-19 15:24 UTC
### General summary/comments (optional)
`stack ghci` fails when I create an internal library in _package.yaml_  (Hpack has a [top level field](https://github.com/sol/hpack#top-level-fields) `internal-libraries` which creates [internal libraries](https://cabal.readthedocs.io/en/latest/cabal-package.html#sublibs)). `stack build` goes fine, however.

### Steps to reproduce

1. `stack new test-internal`
2. Change _package.yaml_, from 
```yaml
library:
  source-dirs: src
```
into
```yaml
internal-libraries:
  myinternal:
    source-dirs: src
```
and updating the dependencies
```yaml
    dependencies:
    #- test-internal
    - myinternal
```

### Expected

I expected _ghci_ to load the project in the same way as it builds.

### Actual

`stack ghci` quits because: `<command line>: cannot satisfy -package z-test-internal-z-myinternal`. Verbose output is

~~~text
2023-08-19 17:08:26.878756: [debug] Run process within /Users/karamellpelle/Source/tmp/test-internal/: /Users/karamellpelle/.stack/programs/x86_64-osx/ghc-9.4.5/bin/ghc-9.4.5 --interactive -i -odir=/Users/karamellpelle/Source/tmp/test-internal/.stack-work/odir -hidir=/Users/karamellpelle/Source/tmp/test-internal/.stack-work/odir -hide-all-packages -XHaskell2010 -i/Users/karamellpelle/Source/tmp/test-internal/.stack-work/dist/x86_64-osx/Cabal-3.8.1.0/build/myinternal -i/Users/karamellpelle/Source/tmp/test-internal/src -i/Users/karamellpelle/Source/tmp/test-internal/.stack-work/dist/x86_64-osx/Cabal-3.8.1.0/build/myinternal/autogen -i/Users/karamellpelle/Source/tmp/test-internal/.stack-work/dist/x86_64-osx/Cabal-3.8.1.0/build/global-autogen -i/Users/karamellpelle/Source/tmp/test-internal/.stack-work/dist/x86_64-osx/Cabal-3.8.1.0/build/myinternal/myinternal-tmp -stubdir=/Users/karamellpelle/Source/tmp/test-internal/.stack-work/dist/x86_64-osx/Cabal-3.8.1.0/build -package=z-test-internal-z-myinternal -package-id=base-4.17.1.0 -i/Users/karamellpelle/Source/tmp/test-internal/.stack-work/dist/x86_64-osx/Cabal-3.8.1.0/build/test-internal-exe -i/Users/karamellpelle/Source/tmp/test-internal/app -i/Users/karamellpelle/Source/tmp/test-internal/.stack-work/dist/x86_64-osx/Cabal-3.8.1.0/build/test-internal-exe/autogen -i/Users/karamellpelle/Source/tmp/test-internal/.stack-work/dist/x86_64-osx/Cabal-3.8.1.0/build/test-internal-exe/test-internal-exe-tmp -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wmissing-export-lists -Wmissing-home-modules -Wpartial-fields -Wredundant-constraints -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wmissing-export-lists -Wmissing-home-modules -Wpartial-fields -Wredundant-constraints -rtsopts -with-rtsopts=-N -optP-include -optP/Users/karamellpelle/Source/tmp/test-internal/.stack-work/ghci/374157a2/cabal_macros.h -ghci-script=/Users/karamellpelle/.cache/stack/ghci-script/08631029/ghci-script
GHCi, version 9.4.5: https://www.haskell.org/ghc/  :? for help
<command line>: cannot satisfy -package z-test-internal-z-myinternal
    (use -v for more information)
~~~

### Stack version

~~~text
stack --version
Version 2.11.1, Git revision c1167a6abc3f4978ccded5ba0246a57387da0e2f x86_64 hpack-0.35.2
~~~

### Method of installation
Homebrew

### Platform

macOS Catalina 10.15.7

**Comment by mihaimaruseac** [comment] 2023-08-20 16:59
This is #4148 but it's not simple to solve sadly.

**Comment by karamellpelle** [comment] 2023-08-20 18:27
OK! I searched for an issue with `internal-libraries` but couldn't find one.

**Comment by mpilgrem** [comment] 2023-09-03 14:12
I am going to close this issue as the problem is covered by #4148 (stack ghci/repl with internal sublibraries only works after a build).

**Closed by mpilgrem** 2023-09-03 14:12 UTC
