### ISSUE TITLE
Multiple writes at the same time on windows machine causes permission denied error

### ISSUE THREAD

**Issue by hanjoosten** [commercialhaskell/stack#2617] opened 2016-09-21 07:01 UTC
On my windows 7 machine, I tried to build my project with LTS-7.0 This failed for some reason. Evantually, I removed ALL previously installed haskell / ghc / cabal / stack stuff from my machine, making sure I could do a totally clean installation. 

When I install my project, I get the following error message, when on of the many packages is being registered:

```
ghc-pkg.EXE: C:\sr\snapshots\480beed7\pkgdb\package.cache: you don't have permission to modify this file
```
### Diagnose

There are two things that catch my eye:
1. I wonder why anything is being written to a directory at C:\sr . In my case, I have admin rights on my machine, but in a lot of companies, this isn't by default.
2. When I resubmit the command `stack install`, the list of packages being built is growing. However, sometime further it can happen again. I guess that there are multiple processes trying to write to  `C:\sr\snapshots\480beed7\pkgdb\package.cache` at the same time. This results in a write error in the latter process. 
### Steps to reproduce
1. clone a [large haskell program like the one I have these problems](https://github.com/AmpersandTarski/Ampersand/commit/9641c96cfc37232507cb1bf832a7372c276d1316)
2. build it on a multicore windows machine, using stack:
   1. stack setup
   2. stack install
### Expected

I would expect the build to succeed by only calling `stack install` once.
### Actual

During installation, I ran into the following error message:

```
Progress: 30/126
--  While building package asn1-parse-0.9.4 using:
      C:\sr\setup-exe-cache\x86_64-windows\setup-Simple-Cabal-1.24.0.0-ghc-8.0.1.exe --builddir=.stack-work\dist\b7fec021 register
    Process exited with code: ExitFailure 1
    Logs have been written to: D:\data\hjo20125\Git\Ampersand\.stack-work\logs\asn1-parse-0.9.4.log

    Configuring asn1-parse-0.9.4...
    Building asn1-parse-0.9.4...
    Preprocessing library asn1-parse-0.9.4...
    [1 of 1] Compiling Data.ASN1.Parse  ( Data\ASN1\Parse.hs, .stack-work\dist\b7fec021\build\Data\ASN1\Parse.o )

    Data\ASN1\Parse.hs:30:1: warning: [-Wunused-imports]
        The import of `Control.Applicative' is redundant
          except perhaps to import instances from `Control.Applicative'
        To import instances alone, use: import Control.Applicative()
    Installing library in
    C:\sr\snapshots\480beed7\lib\x86_64-windows-ghc-8.0.1\asn1-parse-0.9.4-472aFk4Rjki87YeAg9g5Ph
    Registering asn1-parse-0.9.4...
    setup-Simple-Cabal-1.24.0.0-ghc-8.0.1.exe:
    'C:\Users\hjo20125\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE'
    exited with an error:
    asn1-parse-0.9.4: Warning: haddock-interfaces:
    C:\sr\snapshots\480beed7\doc\asn1-parse-0.9.4\asn1-parse.haddock doesn't exist
    or isn't a file
    ghc-pkg.EXE: C:\sr\snapshots\480beed7\pkgdb\package.cache: you don't have
    permission to modify this file

D:\data\hjo20125\Git\Ampersand>
```

Because of the fact that there seems to be a write conflict, I tried to re-run `stack install` each time that this error occurs. Every time, some more packages are registered, and eventually my application is build succesfully.
### Stack version

```
$ stack --version
Version 1.2.0, Git revision 123819b7d65df2ad7fe63fb5eb39a98536acb5f3 (4055 commits) x86_64 hpack-0.14.0
```
### Method of installation
- Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by hanjoosten** [comment] 2016-09-21 09:40
For what it is worth: The result can be [observed from Appveyor](https://ci.appveyor.com/project/hanjoosten/ampersand/build/build.404-feature%2fmeatgrinder) too.

**Comment by mgsloan** [comment] 2016-09-26 00:01
> I wonder why anything is being written to a directory at C:\sr . In my case, I have admin rights on my machine, but in a lot of companies, this isn't by default.

This is customizable via the STACK_ROOT environment variable.  This is described in [the docs](https://readthedocs.org/search/?q=STACK_ROOT&check_keywords=yes&area=default&project=stack&version=stable&type=file).

> When I resubmit the command stack install, the list of packages being built is growing. However, sometime further it can happen again. I guess that there are multiple processes trying to write to C:\sr\snapshots\480beed7\pkgdb\package.cache at the same time. This results in a write error in the latter process.

We have not seen such problems with concurrent writing of that.  Perhaps it is only an issue on windows?  Seems worth investigation.  At least multiple builds eventually succeed.

**Comment by hanjoosten** [comment] 2016-09-26 08:10
I had the variable STACK_ROOT defined before I did the fresh install. I assume that there is no existence check before it is set. Before it installed, it pointed to D:\stackroot\ After installation, it pointed to c:\sr

The Ampersand project uses 100+ packages (transitive). Other team members with Windows machines experienced the same problem. Fortunately the workaround is to just issue the command `stack install` a couple of times. Every time some progress is made. 

When I delete stackroot and start fresh, the issue persists indeed. Having to re-issue the command 2 to 3 times seems standard.

**Comment by hanjoosten** [comment] 2016-09-26 08:12
If there is anything I can do to help (testing?), just let me know.

**Comment by mgsloan** [comment] 2016-09-26 20:45
I've split off an issue for it.

We don't have other issues like this from windows users, so my theory is that your code base (or particular dependencies) do something unusual which is triggering this condition.

If you could construct a case that reproduces, that would be very helpful.  One approach might be to trim down your project to just a cabal file + stack file, rename it, and post it up.

**Comment by hanjoosten** [comment] 2016-09-27 06:56
Yesterday I installed ghc-mod, because I want to try [atom](atom.io) as an editor. So I issued the command `stack install ghc-mod` . There too, I ran into this same 'permission denied' problem. Therefor, I do not think that this is something particular to my code base. I do have an 8-core machine, with 32Gb of memory onboard. During compilation, I see quite a few ghc processes busy at the same time.

**Comment by mgsloan** [comment] 2016-09-27 08:41
Cool!  I will try next time I'm on a windows box.

**Comment by nightuser** [comment] 2016-10-09 15:50
I'm experiencing the same problem (any package with lots of dependencies, like `ghc-mod`).

**Comment by ezyang** [comment] 2016-10-18 22:57
https://github.com/haskell/cabal/issues/4005 might be related.

**Comment by simonmichael** [comment] 2016-10-22 14:55
I'm seeing this in most of my appveyor builds of hledger, since switching them to GHC 8 I think. Eg: https://ci.appveyor.com/project/simonmichael/hledger/build/master-85.

**Comment by TerrorJack** [comment] 2017-01-11 19:18
I'm experiencing the same issue on Windows x64. This occurs whenever you use `stack build` with a heavy build plan on a multi-core machine (`stack build` using global project also triggers it). And this bug hasn't been encountered in earlier versions of `ghc` before. Can also be observed on AppVeyor.

The temporary fix is to use `-j1` whenever possible on Windows.

**Comment by domenkozar** [comment] 2017-01-16 16:26
I looked a bit closer around haddock phase building, but couldn't find anything obvious.

**Comment by domenkozar** [comment] 2017-01-18 11:31
Is someone available to look into this issue (paid)? domen@enlambda.com

**Comment by ndmitchell** [comment] 2017-01-18 12:47
The root cause is likely to be that `ghc-pkg` can only be called with a single writer or multiple readers simultaneously - any other combination results in these errors. The GHC build system Hadrian (https://github.com/snowleopard/hadrian) uses locks to avoid that problem. Fixing `ghc-pkg` to properly use file locks would be the real solution.

**Comment by domenkozar** [comment] 2017-01-18 12:50
@ndmitchell so this is actually a stack issue, looking at `src/Stack/GhcPkg.hs`

**Comment by ndmitchell** [comment] 2017-01-18 12:52
@domenkozar perhaps, perhaps not. `cabal configure` and `cabal register` also call `ghc-pkg`, so you have to synchronise with them as well. I believe `ghc` also calls `ghc-pkg` so that needs dealing with too.

**Comment by ezyang** [comment] 2017-01-18 16:49
Oh, @ndmitchell, that's an interesting claim. Is a concurrent read-write really not possible on Windows? It will be hard for us to fix this, because when we shell out to GHC, GHC will read from the package database; we'd have to block ALL calls to GHC before running a ghc-pkg register.

**Comment by ndmitchell** [comment] 2017-01-18 16:55
It is possible on Windows, but the Haskell file handle functions deliberately chose to pass the flags explicitly requesting that you deny sharing. I reported this ~10 years ago to GHC, but can't find where I did so (the Linux functions pass different sharing flags).

**Comment by domenkozar** [comment] 2017-01-19 13:05
Relevant: https://ghc.haskell.org/trac/ghc/ticket/11394

**Comment by domenkozar** [comment] 2017-01-21 10:42
For future reference, until this is fixed: 

See workaround in https://github.com/input-output-hk/cardano-sl/commit/61470aa41b70428467543f5ac23118fa1fa5a2f6

**Comment by domenkozar** [comment] 2017-01-26 16:39
See https://github.com/haskell/cabal/issues/4005#issuecomment-275434975 for further development on this issue.

**Comment by arybczak** [comment] 2017-03-27 09:32
The proper fix went into ghc-pkg and will be available in GHC 8.2.1 (see https://phabricator.haskell.org/rGHC0d86aa5904e5a06c93632357122e57e4e118fd2a for more details).

However, this still needs to be fixed in stack for older GHC versions. As pointed out in https://github.com/haskell/cabal/issues/4005#issuecomment-275434975, we need to acquire global read/write lock while interacting with a specific package database, where configure/build phase is treated as a reader and install/register phase as a writer.

This will unfortunately limit overall build parallelism, so I presume it should be only done on Windows. The idea is to port GHC.IO.Handle.Lock from base-4.10.0.0 and acquire appropriate lock on a specific file within STACK_ROOT during each build phase.

I'll be providing PR that solves this. I'm not overly familiar with stack source code, so any pointers for what part of the code I should focus on would be welcome.

**Comment by ndmitchell** [comment] 2017-03-27 11:54
We've lived with this problem a really long time. It's great the fix is available upstream, but is it worth just waiting for GHC 8.2, rather than fixing stack?

**Comment by arybczak** [comment] 2017-03-29 09:30
@ndmitchell Well, it could be argued that people who won't/can't use 8.2 will not benefit from the fix. Although the problem can be worked around , it is pretty annoying.

**Comment by philipcraig** [comment] 2017-03-29 13:22
I will be happy to wait for ghc 8.2 to land for the fix, and happy for stack *not* to do anything about this

**Comment by varosi** [comment] 2017-05-04 17:01
As I see "need repro" label for that issue - it is easily reproducable - try to build Stack itself with stack build on clean caches.

**Comment by borsboom** [comment] 2017-10-27 13:34
Can anyone confirm whether 8.2 fixes this?

**Comment by TerrorJack** [comment] 2017-10-27 13:41
@borsboom It does.

**Comment by borsboom** [comment] 2017-10-27 13:43
Alright, closing this issue as resolved upstream.

**Closed by borsboom** 2017-10-27 13:43 UTC
Labels: component: windows, resolution: upstream issue

**Comment by robinp** [comment] 2018-05-23 06:06
Note: passing the `-j1` flag to stack (build/install) seems to mitigate.
