### ISSUE TITLE
Breakage on Ubuntu 18.04 LTS with GHC 8.4.2

### ISSUE THREAD

**Issue by parsonsmatt** [commercialhaskell/stack#4019] opened 2018-05-10 19:17 UTC
### General summary/comments (optional)

Quoth HVR:

> It should be rather easy to fix this on Stack's side by detecting system configurations which are known to be incompatible and avoid passing -g to GHC by default. (snip)

GHC Trac ticket: https://ghc.haskell.org/trac/ghc/ticket/15068

`sclv` says: [Apparently the problem is that stack turns on debug information by default, which most people don't realize, and also you can only turn it off by enable symbol stripping, which is a pain.](https://www.reddit.com/r/haskell/comments/8ic3c5/ghc_fatally_broken_on_ubuntu_1804_bionic_and/dyrn79x/)

I am opening this issue on behalf of [the author of this Reddit thread](https://www.reddit.com/r/haskell/comments/8ic3c5/ghc_fatally_broken_on_ubuntu_1804_bionic_and/). 

### Steps to reproduce

I am unable to reproduce this on my machine; I'm going to let the OP know that this issue exists and hopefully they can submit their reproduction steps.

### Expected

What you expected to see and happen.

### Actual

What actually happened.

If you suspect that a stack command misbehaved, please include the output of that command in `--verbose` mode.
If the output is larger than a page please paste the output in a [Gist](https://gist.github.com/).

```
$ stack <your command here> <args> --verbose
<output>
```

### Stack version

```
$ stack --version
Version 1.5.0, Git revision 63267f94d7c819cbecc2d59aa259d17240838e43 (4845 commits) x86_64 hpack-0.17.1
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository
* Via cabal-install
* An unofficial package repository (please specify which)
* Other (please specify)

**Comment by gbaz** [comment] 2018-05-10 19:56
to be clear, the information in that thread comes from this comment in particular from cocreature: https://www.reddit.com/r/haskell/comments/8ic3c5/ghc_fatally_broken_on_ubuntu_1804_bionic_and/dyrdmey/

which in turn points to this line: https://github.com/commercialhaskell/stack/blob/master/src/Stack/Build/Source.hs#L148

**Comment by ygale** [comment] 2018-05-13 10:46
1. Can someone please explain how to "turn it off by enabling symbol stripping", or whatever? Just looking for simple instructions how to work around this problem.

2. I still haven't heard whether the GHC fix will be backported, but I assume the chances are low. If not, a stack option to turn off default `-g` would be really nice, especially if it can be set in the global `stack.yaml`. Otherwise, we're going to have years of grief because of this to support our previous release versions.

**Comment by borsboom** [comment] 2018-05-13 11:44
From what I can tell, stripping is enabled by default and so `-g` is _not_ passed to GHC (confirmed by testing with `--verbose` on stack-1.7.1, although not on Ubuntu 18.04).  So for most people using the defaults, this shouldn't be an issue (you have to explicitly disable stripping using `--no-library-stripping` and/or `--no-executable-stripping` to experience this).

My best guess for people experiencing this problem by default is that they may have disabled stripping in their `~/.stack/config.yaml`?

Aside from that, there's the issue of tying `-g` with the stripping options which, in retrospect, may not have been a great idea.  That was introduced in https://github.com/commercialhaskell/stack/pull/2801, so I'd like to get @typedrat and @mgsloan's thoughts on a sensible approach for how we could change this.  Perhaps a separate `--debug` or `--dwarf` (as proposed in https://github.com/commercialhaskell/stack/issues/3365) that disables stripping and enables `-g` would be better, and leave the stripping options to _only_ control stripping.

**Comment by borsboom** [comment] 2018-05-13 12:04
I've now confirmed that things work by default on Ubuntu 18.04, and fail when stripping is disabled.

Setup commands:
```
$ docker run -ti --rm ubuntu:18.04
# apt-get update && apt-get dist-upgrade && apt-get install -y curl
# curl https://get.haskellstack.org|sh
# stack new stack4019
# cd stack4019
```
With defaults, build is successful:
```
# stack build
[…]
Installing library in /stack4019/.stack-work/install/x86_64-linux/lts-11.9/8.2.2/lib/x86_64-linux-ghc-8.2.2/stack4019-0.1.0.0-46PSLkK9utrAMFZL1iiFPo
Installing executable stack4019-exe in /stack4019/.stack-work/install/x86_64-linux/lts-11.9/8.2.2/bin
Registering library for stack4019-0.1.0.0..
```
With stripping disabled, build fails:
```
# stack clean
# stack build --no-library-stripping --no-executable-stripping
[…]
/stack4019//tmp/ghc5820_0/ghc_4.s:415:0: error:
     Error: invalid operands (.debug_frame and .note.GNU-stack sections) for `-'
    |
415 |         .uleb128 1f-.-1
    | ^
`gcc' failed in phase `Assembler'. (Exit code: 1)
[…]
```

**Comment by nh2** [comment] 2018-12-16 02:34
For reference, I am now also running into this issue when building DWARF-enabled GHCs in nixpkgs:

https://github.com/NixOS/nixpkgs/pull/52255#issuecomment-447610795

**Comment by snoyberg** [comment] 2019-03-26 16:24
From my reading, this is working as expected, closing

**Closed by snoyberg** 2019-03-26 16:24 UTC
