### ISSUE TITLE
Compiling large projects leads to ghc getting borked

### ISSUE THREAD

**Issue by jhance** [commercialhaskell/stack#2415] opened 2016-07-26 19:06 UTC
So, when I compile a large project (and I mean like, 3000 modules *in the same package* - its a lot of autogenerated code), the memory usage slowly but steadily increases. I have 16GB of RAM but after ~1000 modules I start to run OOM and I have to ctrl-c stack at around 90% usage to prevent myself from OOMing.

If I don't do this, and let stack continue as it would, the system OOMs and the ghc becomes *completely borked* (this might be specific to my machine and have something to do with harddisk corruption?). Stack then refuses to do anything, and since `stack setup` decides to run `--version`, it complains loudly when `--version` decides to segfault or something. It then refuses to install a new ghc over the borked one, instead of handling the case nicely and reinstalling for me. So I have to go into my stack cache and remove ghc-8.0.1.

I think there are two separate issues here:
1) No way to recover from the `--version` failing and treating that as "ghc is not installed"
2) [and this might be cabal's fault, not stack's] no way to deal with compiling a large amount of modules in a single batch.

My instinct is that GHC processes are being re-used somehow by Cabal, or something else is persisting, which causes the memory usage to slowly climb.

**Comment by phadej** [comment] 2016-07-26 21:23
At the end package is built by single GHC process. Could you check which process eats all the memory

**Comment by mgsloan** [comment] 2016-07-26 21:25
It seems very strange that it could bork ghc like that.

I'd be interested if anyone has any thoughts on whether it makes sense for stack to attempt to automatically manage memory usage.

If stack is also building other packages in parallel, you could force that to not happen by using `-jN`.

**Comment by Blaisorblade** [comment] 2016-08-02 18:34
@jhance Thanks for the report. Sorry for the stupid question, but can you confirm GHC is not being launched the `-j` option, just to be sure? I'll assume not.

# Memory exhaustion

> My instinct is that GHC processes are being re-used somehow by Cabal, or something else is persisting, which causes the memory usage to slowly climb

I understand `ghc --make` caches interfaces of compiled modules, and that might be your leak. I read this in some GHC bug I can't find, but it's mentioned here:

> http://blog.ezyang.com/2016/01/ghc-shake-reimplementing-ghc-make/

> ghc --make is a useful mode in GHC which automatically determines what modules need to be compiled and compiles them for you. Not only is it a convenient way of building Haskell projects, its single-threaded performance is good too, *by reusing the work of reading and deserializing external interface files.*

I assume this was never tested on packages with ~1000 modules, so I conjecture GHC does not manage its memory own memory. This part would arguably be a bug to report to GHC, at least to have a confirmation that this is a plausible diagnosis.

As a workaround, do you have a chance of splitting the generated code in multiple packages?

## GHC borked

What's your OS? How does the OS OOM killer bork GHC? Do you have a dynamically-sized swapfile in the same partition somehow? That part is surprising. Can you try making the GHC install readonly (with `chmod -R -r that-path/*` if on Unix) and reproducing the bug? Or figuring out which files changed?

## Handling failing --version

I agree that would be more robust, and could be implemented more easily than reproducing this bug.

**Comment by Blaisorblade** [comment] 2016-08-02 18:37
GHC's caching behavior is documented in GHC's docs since forever, though cache eviction is not discussed:

https://downloads.haskell.org/~ghc/8.0.1/docs/html/users_guide/using.html#using-ghc-make
https://downloads.haskell.org/~ghc/5.02/docs/set/make-mode.html

> GHC doesn't have to be restarted for each compilation, which means it can cache information between compilations. Compiling a muli-module program with ghc --make can be up to twice as fast as running ghc individually on each source file.

**Comment by jhance** [comment] 2016-08-02 19:40
No dynamically sized swapfile.

It was on ubuntu 16.04.

The GHC getting borked part makes absolutely no sense to me either, I could try making it read-only but I don't particularly want to OOM my system anymore heh. Also I've seen weird things on this laptop (had to reinstall packer a few weeks ago due to the binary segfaulting in the go runtime stuff) so I partially suspect that my laptop has disk corruption issues.

I believe the process that eats the memory was GHC

**Comment by Blaisorblade** [comment] 2016-08-03 08:25
I agree on `--version`. So I opened #2430 to focus on the actionable part.

Regarding your disk, I now wonder if your FS code could have bugs on OOM (it can happen), especially if btrfs, but that's not for me to investigate here.

I suppose we can close this issue then for now.

**Closed by Blaisorblade** 2016-08-03 08:25 UTC
Labels: further investigation required, help wanted, need repro

**Comment by jhance** [comment] 2016-08-03 18:26
SGTM, thanks!
