### ISSUE TITLE
Stack setup fails for ghcjs project on windows

### ISSUE THREAD

**Issue by martin-kolinek** [commercialhaskell/stack#1774] opened 2016-02-10 14:32 UTC
`stack setup` fails when executed in a project setup for ghcjs like this:

```
compiler: ghcjs-0.2.0.20151230.3_ghc-7.10.2
compiler-check: match-exact
setup-info:
 ghcjs:
  source:
   ghcjs-0.2.0.20151230.3_ghc-7.10.2:
    url: "https://github.com/nrolland/ghcjs/releases/download/v.0.2.0.20151230.3/ghcjs-0.2.0.20151230.3.tar.gz"
```

The error is `Expected a single directory within unpacked ...`, and happens on windows.

**Steps to reproduce**
1. Have a windows system without ghcjs installed
2. Create a project with stack.yaml such as [this one](https://github.com/commercialhaskell/stack/files/124868/stack.yaml.txt) (based on the guide)
3. Run `stack setup`

**Expected:**
Stack sets up ghcjs

**Actual**
Stack fails with `Expected a single directory within unpacked ...`

Whole output:

```
Preparing to install GHCJS to an isolated location.
This will not interfere with any system-level installation.
Preparing to download ghcjs-0.2.0.20151230.3_ghc-7.10.2 ...
No sha1 found in metadata, download hash won't be checked.
Preparing to download ghcjs-0.2.0.20151230.3_ghc-7.10.2 ...
Already downloaded.
Unpacking GHCJS into C:\Users\kot\AppData\Local\Programs\stack\x86_64-windows\ghcjs-0.2.0.20151230.3_ghc-7.10.2\src\ 
Preparing to download 7z.dll ...
Already downloaded.
Preparing to download 7z.exe ...Already downloaded.
Expected a single directory within unpacked C:\Users\kot\AppData\Local\Programs\stack\x86_64-windows\ghcjs-0.2.0.20151230.3_ghc-7.10.2.tar.gz
```

Output of `stack --version`:

```
Version 1.0.2, Git revision fa09a980d8bb3df88b2a9193cd9bf84cc6c419b3 (3084 commits) x86_64
```

I [attached](https://github.com/commercialhaskell/stack/files/124883/out.txt) the output of `stack setup --verbose`

**Comment by mgsloan** [comment] 2016-02-11 00:07
Doh!  Thanks for finding and fixing this :D

**Comment by RaoulSchaffranek** [comment] 2018-01-10 17:19
Unfortunately, the bug seems to have sneaked in again with version 1.6.3:

~~~
stack --version
Version 1.6.3, Git revision b27e629b8c4ce369e3b8273f04db193b060000db (5454 commits) x86_64 hpack-0.20.0
~~~

~~~yaml
# stack.yaml
resolver: lts-6.20
compiler: ghcjs-0.2.0.9006020_ghc-7.10.3
compiler-check: match-exact

packages:
 - '.'
extra-deps: []

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006020_ghc-7.10.3:
         url: http://ghcjs.tolysz.org/lts-6.20-9006020.tar.gz
         sha1: a6cea90cd8121eee3afb201183c6e9bd6bacd94a
~~~

The steps to reproduce are exactly the same as above, the whole error-message reads:

~~~
Control.Exception.Safe.throwString called with:

Expected a single directory within unpacked C:\Users\Raoul\AppData\Local\Programs\stack\x86_64-windows\ghcjs-0.2.0.9006030_ghc-7.10.3.tar.gz
Called from:
  throwString (src/Stack\Setup.hs:1416:14 in stack-1.6.3-F6YVX3qh2MsHZufmhdWM8J:Stack.Setup)
~~~

The exception is thrown from this line https://github.com/commercialhaskell/stack/blob/v1.6.3/src/Stack/Setup.hs#L1416

**Comment by mgsloan** [comment] 2018-01-11 04:23
@RaoulSchaffranek Huh, that's curious.  Perhaps it's an issue with that particular tarball.  Setup.hs hasn't changed much recently.  Only thing that's GHCJS related is https://github.com/commercialhaskell/stack/commit/bc9007a6d139dfbb06c02cf646249d902ec81249 and that's a change for booting which comes after installing from the tarball.

**Comment by RaoulSchaffranek** [comment] 2018-01-11 15:44
I tried several other tarballs and it remains the same story. After running `stack setup` i end up with a weird directory-structure in `C:\Users\Raoul\AppData\Local\Programs\stack\x86_64-windows`:

~~~
ghcjs-0.2.0.9006020_ghc-7.10.3
ghcjs-0.2.0.9006020_ghc-7.10.3.temp
ghcjs-0.2.0.9006020_ghc-7.10.3.tar.gz
7z.dll
7z.exe
~~~

Where the directories `ghcjs-0.2.0.9006020_ghc-7.10.3` and `ghcjs-0.2.0.9006020_ghc-7.10.3.temp` are both empty. However, I can unpack the tarball manually, so the archive seems to be working in general.

**Comment by mgsloan** [comment] 2018-01-12 07:16
Curious!  Things changed here - https://github.com/commercialhaskell/stack/pull/3212 - but I verified with a windows user that the change works.  Can you please try without that change to see if that's the culprit?  I don't currently have access to a windows setup.  Extra awesome bonus points would be to open a PR with a fix!

**Comment by dwaldhalm** [comment] 2018-01-18 19:39
I'm able to get it working on my fresh Windows 10 installation by easing the expectation for the single unpacked directory in `Setup.hs`.  `expectSingleUnpackedDir` fails when `contents` has to be `([dir], [] )`, but works when it can be `([dir], _)`. I think the `.tar` file is still in the directory.  

I can make a pull request if that suits you.

```haskell
expectSingleUnpackedDir :: (MonadIO m, MonadThrow m) => Path Abs File -> Path Abs Dir -> m (Path Abs Dir)
expectSingleUnpackedDir archiveFile destDir = do
    contents <- listDir destDir
    case contents of
        ([dir], _ ) -> return dir
        _ -> throwString $ "Expected a single directory within unpacked " ++ toFilePath archiveFile
```

**Comment by mgsloan** [comment] 2018-01-18 20:04
@dwaldhalm Sure, a PR would be appreciated, thanks!

**Comment by dwaldhalm** [comment] 2018-01-18 20:33
#3794

**Comment by Rizary** [comment] 2018-03-01 23:27
it also happened to me when using this ghcjs compiler
https://github.com/matchwood/ghcjs-stack-dist

can i just change to `([dir], _)` ?

**Comment by mgsloan** [comment] 2018-03-02 07:38
@Rizary I don't think @dwaldhalm 's fix has been included in a released version of stack yet.  You can do `stack upgrade --git` to build the development version of stack from source.

Closing this issue, hopefully it is solved by that fix.  If not, feel free to re-open or request it be reopened.

**Closed by mgsloan** 2018-03-02 07:38 UTC
Labels: component: ghcjs, type: bug

**Comment by ShadowManu** [comment] 2018-04-04 07:53
Happening to me, just installing Stack and trying to follow the instructions at https://docs.haskellstack.org/en/stable/ghcjs/. Any workaround I can do?
