### ISSUE TITLE
Stack not recognising user directory with special characters

### ISSUE THREAD

**Issue by ErikPrantare** [commercialhaskell/stack#2846] opened 2016-12-14 00:31 UTC
### General summary/comments

I'm trying to get stack to work. However, it seems like stack is trying to access a global config file that exists in my user directory. This causes problems, as my name has the special character 'ä' in it. This leads to stack being unable to find the file, and as a consequence it doesn't build the project.

The error message prints it as "├ñ", which would be the ascii interpretation of the UTF-8 character 'ä'. It also prints \228, which represents 'õ'. I tried to create new user directories with these characters in my name instead, but that does not solve the problem.

### Steps to reproduce

1. Have user directory with special character 'ä' in the name
2. cd to project directory
3. Run command `stack <project name>`.

### Expected

For stack to build the project

### Actual

Getting this error:

```
C:\code\leap>stack test -v
Version 1.1.2, Git revision c6dac65e3174dea79df54ce6d56f3e98bc060ecc (3647 commi
ts) x86_64 hpack-0.14.0
2016-12-14 01:08:36.679216: [debug] Checking for project config at: C:\code\leap
\stack.yaml @(stack_9kewhubnl5WIl89fhd1ea2:Stack.Config src/Stack\Config.hs:811:
9)
2016-12-14 01:08:36.757220: [debug] Loading project config file stack.yaml @(sta
ck_9kewhubnl5WIl89fhd1ea2:Stack.Config src/Stack\Config.hs:829:13)
Could not parse 'C:\Users\Erik Pr├ñntare\AppData\Roaming\stack\config.yaml':
InvalidYaml (Just (YamlException "Yaml file not found: C:\\Users\\Erik Pr\228nta
re\\AppData\\Roaming\\stack\\config.yaml"))
See http://docs.haskellstack.org/en/stable/yaml_configuration/.
```

### Stack version

```
C:\code\leap> stack --version
Version 1.1.2, Git revision c6dac65e3174dea79df54ce6d56f3e98bc060ecc (3647 commits) x86_64 
hpack-0.14.0h
```

### Method of installation

ghc platform

**Comment by lwm** [comment] 2016-12-30 01:01
Please see the same issue listed:

  - https://mail.haskell.org/pipermail/haskell-cafe/2016-December/125658.html

I think you just need a `stack upgrade --git`.

**Comment by ErikPrantare** [comment] 2016-12-30 13:18
I had some issues with the ghc itself too, so I filed a report there also.
Think I'll just have to wait for 8.2.1 to be released, hopefully it'll be
fixed by then.

**Comment by lwm** [comment] 2017-09-12 20:53
@ErikPrantare, can you link to the report you made upstream? Or this is solved?

**Comment by ErikPrantare** [comment] 2017-09-17 15:26
@lwm kind of solved, while unicode wont be supported(upstream issue), they got support for latin1 to work. 

https://ghc.haskell.org/trac/ghc/ticket/12971

**Comment by lwm** [comment] 2017-09-17 16:11
> This is as fixed as it's going to get with the current toolchain. 

Right, sounds like we're done here as well. Although, @ErikPrantare, I think we should leave some note in the documentation about this being a known limitation - I'd leave this open to track that, otherwise, shall we close it off?

**Comment by mgsloan** [comment] 2017-09-17 21:27
Wow, double upstream bug!  Seems like filepaths are an eternal source of pain (windows MAX_PATH)

Yes, I agree with the approach of documenting it in the FAQ or some variety of gotchas section.

**Comment by mpilgrem** [comment] 2024-03-18 21:13
I am going to close this issue given the passage of time and because I cannot reproduce it on Windows 11/Windows Terminal (on the assumption that Linux does not lag behind) with current versions of Stack. On Windows, I can set `STACK_ROOT=D:\tëst` and Stack works fine.

**Closed by mpilgrem** 2024-03-18 21:13 UTC
Labels: component: documentation
