### ISSUE TITLE
stack build --profile problem (Windows 10)

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#4709] opened 2019-04-06 18:30 UTC
On Windows 10, I am using `stack --version` `Version 1.10.0, Git revision aa0185f2498541a16ab52c30bb6fe8660a729932 (7286 commits) x86_64 hpack-0.31.1`.

A plain vanilla stack project (`stack new profileTest` ... `Selected resolver: lts-13.15`) builds as expected with GHC 8.6.4 but `stack build --profile` results in errors such as this:
~~~
>stack build --profile
profileTest-0.1.0.0: configure (lib + exe)
Configuring profileTest-0.1.0.0...
profileTest-0.1.0.0: build (lib + exe)
Preprocessing library for profileTest-0.1.0.0..
Building library for profileTest-0.1.0.0..
[2 of 2] Compiling Paths_profileTest ( .stack-work\dist\e626a42b\build\autogen\Paths_profileTest.hs, .stack-work\dist\e626a42b\build\Paths_profileTest.o )
[1 of 2] Compiling Lib              ( src\Lib.hs, .stack-work\dist\e626a42b\build\Lib.p_o )

src\Lib.hs:1:8: error:
    Could not find module `Prelude'
    Perhaps you haven't installed the profiling libraries for package `base-4.12.0.0'?
    Use -v to see a list of the files searched for.
  |
1 | module Lib
  |        ^^^


--  While building package profileTest-0.1.0.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.4.0.1_ghc-8.6.4.exe --builddir=.stack-work\dist\e626a42b build lib:profileTest exe:profileTest-exe --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
~~~

In case it is something to do with GHC and what comes with it, I believe I am using the GHC that `stack` provides:
~~~
>stack exec where -- ghc
C:\Users\mikep\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc.exe
~~~

**Comment by dbaynard** [comment] 2019-04-06 22:56
That's very odd. @qrilka, you may have some thoughts on what is happening, here?

Meanwhile, I've had a quick check, and there's no integration test with a name that tests this, so it _might_ be a regression.

**Comment by snoyberg** [comment] 2019-04-07 07:13
I believe the problem is that the Windows distribution of GHC 8.6.4 does not include the profiling libraries. If that's the case, this is an upstream issue that we cannot work around.

**Comment by mpilgrem** [comment] 2019-04-07 11:50
It does seem to be GHC 8.6.4-specific. I went back to GHC 8.6.3 and 8.4.4 and did not have the same problem.

**Comment by mpilgrem** [comment] 2019-04-07 12:11
I created an issue at: https://gitlab.haskell.org/ghc/ghc/issues/16552

**Comment by snoyberg** [comment] 2019-04-07 13:29
Awesome, thanks. I'm going to close this as an upstream issue

**Closed by snoyberg** 2019-04-07 13:29 UTC

**Comment by sgraf812** [comment] 2019-04-07 17:51
Leaving this thread here for reference: https://www.mail-archive.com/ghc-devs@haskell.org/msg17042.html

So, this is the unfortunate reality until someone steps up to backport Phyx's linker patch for a 8.6.5.
