### ISSUE TITLE
Needing to add things to other-modules is stymieing users

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#722] opened 2015-08-05 16:32 UTC
```
so confused... I am using 'stack test --rerun-tests' and no matter what I do to my
Spec file (including just deleting everything in it), stack test says that spec passed
my problem is deeper than i initially thought - stack build keeps building
successfully despite me intentionally breaking my code.

add stuff to other-modules
your modules that you're breaking

thanks! I'm impressed with how quickly you sussed out the problem.
```

I run into this, people in IRC run into this. It's annoying. Can this be dealt with somehow? `cabal build` never seemed to need it.

**Comment by snoyberg** [comment] 2015-08-05 16:34
Looks like a dupe of #32 and #481, with possibly #105.

**Closed by snoyberg** 2015-08-05 16:34 UTC
