### ISSUE TITLE
Stack fails to build `base` libraries for profiling in 9.2.1

### ISSUE THREAD

**Issue by brandonchinn178** [commercialhaskell/stack#5652] opened 2021-12-17 06:43 UTC
### Steps to reproduce

1. Write a hello world file as `Foo.hs`
2. `stack ghc --resolver=ghc-9.2.1 Foo.hs -- -prof`

### Expected

It should build. (It does with `ghc-9.0.1` as `--resolver`)

### Actual

```
Could not find module 'Prelude'
Perhaps you haven't installed the profiling libraries for package 'base-4.16.0.0'
```

Running with `-v` shows it trying to look at `~/.stack/programs/x86_64-osx/ghc-9.2.1/lib/ghc-9.2.1/lib/x86_64-osx-ghc-9.2.1/base-4.16.0.0/Prelude.p_hi`, which doesn't exist, while the 9.0.1 counterpart `~/.stack/programs/x86_64-osx/ghc-9.0.1/lib/ghc-9.0.1/base-4.15.0.0/Prelude.p_hi` does.

### Stack version

```
$ stack --version
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

### Method of installation

**Comment by hasufell** [comment] 2021-12-17 06:53
Related: https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/296

Could be an issue with the bindists.

@bgamari

**Comment by sjakobi** [comment] 2021-12-20 15:02
This may be related to https://gitlab.haskell.org/ghc/ghc/-/issues/20707.

**Comment by mpilgrem** [comment] 2023-05-12 22:14
Closing, as I cannot reproduce it with the current version of Stack and the latest in the GHC 9.2 series (GHC 9.2.7).

**Closed by mpilgrem** 2023-05-12 22:14 UTC
