### ISSUE TITLE
Possibility to control verbosity in stack

### ISSUE THREAD

**Issue by wdanilo** [commercialhaskell/stack#1657] opened 2016-01-15 10:08 UTC
Hello guys. I was looking (but didnt found) any possible option to control verbosity in stack (I was trying the `--cabal-verbose` flag but without any visible difference) . Namely, when I'm compiling a library I'm getting output like:
```
stack build --cabal-verbose
test-0.1: unregistering (local file changes: test/Main.hs)
test-0.1: build
test-0.1: install
```

I would love to see which file is being compiled at the moment and how long it took to compile it - is or would it be possible within stack?

**Comment by harendra-kumar** [comment] 2016-01-15 13:00
From stack help output: 
 `--verbosity VERBOSITY    Verbosity: silent, error, warn, info, debug`

The default is `info` which is quite verbose. More verbose than that is debug but it will be a lot of output and I am not sure if you will get what you want with that.

**Comment by wdanilo** [comment] 2016-01-15 13:04
Ok, so I think we should change the title of this topic. I'm using the default `info` verbosity level and dont get the info I need. I would like to see what fiel is currently being compiled (like cabal used to report) preferrably with its compilation time. Could we do it somehow? :)

**Comment by harendra-kumar** [comment] 2016-01-15 13:28
I am not commenting on your specific requirement but it might be relevant to this discussion. In general I have sometimes felt that default is too verbose in many cases and there is no next verbosity level for regular users (debug is for developers). We should perhaps have a user verbosity level and reduce the default verbosity.

**Comment by mgsloan** [comment] 2016-01-15 21:03
I think this is a dupe of https://github.com/commercialhaskell/stack/issues/426 , I definitely agree that there should be a way to do this.  Feel free to add comments to that issue / re-open this if it's not a dupe.

**Closed by mgsloan** 2016-01-15 21:03 UTC

**Comment by fweth** [comment] 2017-04-11 12:02
I tried to install Idris and found out that some of stack's processes were apparently shading the useful GHC output, my solution is to check the PID of the GHC process (the one most involved CPU and memory wise in the installation) and than put `tail -f /proc/<pid>/fd/1` in a new pane, this will now show me the output that for some reason doesn't appear in the pane with stack running...
