### ISSUE TITLE
stack ghci probably shouldn't change the code page

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#757] opened 2015-08-11 10:08 UTC
On Windows, if I run `stack ghci`, when I get errors I see:

    <interactive>:2:53:
        Not in scope: â€˜mainâ€™
        Perhaps you meant â€˜minâ€™ (imported from Prelude)

If `stack ghci` on Windows is changing the codepage to something the console very definitely doesn't support, and as a result, it looks terrible. Without `stack` in the way I get:

    <interactive>:2:1:
        Not in scope: `main'

I would be entirely happy without any smart quotes, but garbling the text nearby is a little unfortunate.

**Comment by snoyberg** [comment] 2015-08-11 12:06
Would you be able to take a crack at the codepage stuff? This is an area I have virtually no experience with, and I haven't been able to reproduce these problems since both consoles I've tried seem to support utf8 just fine

**Comment by ndmitchell** [comment] 2015-08-11 12:12
I don't have much time at the moment. I'm only taking such an active interest in `stack` all of a sudden because `cabal` decided to eat itself at a bad time :). This is a minor annoyance, and one I can ignore reasonably easily.

I'm just on the standard Windows 8.1 `cmd` prompt. You change the codepage to call GHC to dump some information? Do you have an example somewhere of which thing goes wrong without changing the code base.

**Comment by snoyberg** [comment] 2015-08-11 13:02
Using the standard `cmd` on Windows 10:

![untitled](https://cloud.githubusercontent.com/assets/49415/9198077/18920de8-4042-11e5-8dbf-87d41c277ef7.png)

It's theoretically possible that this is because I've installed Hebrew support, but I really have no idea why my cmd prompt works in this case and yours doesn't. Regarding reproducing problems: https://ghc.haskell.org/trac/ghc/ticket/10762 gives some solid repros for the bugs we were encountering. Note that -ddump-hi is necessary in stack in order to detect files missing from the .cabal file.

**Comment by ndmitchell** [comment] 2015-08-11 13:03
I'll be upgrading to Windows 10 when things calm down, so maybe its fixed there. If there is a Win 8.1 only bug it's a lot less important.

**Comment by ndmitchell** [comment] 2015-08-11 13:04
BTW, why not use `-M` to generate a Makefile for the project? That seems much faster and easier than dumping all the hi files and will give you the same information.

**Comment by snoyberg** [comment] 2015-08-11 13:07
It doesn't; the hi dump includes the TH dependencies, and is generated as part of the normal build process. I'd be surprised if generating the Makefile as a separate step is faster than that, plus we'd have to write a significantly more complicated parser.

**Comment by iharh** [comment] 2015-08-13 05:40
Michael, which font do you use at the screenshot from Win-10?

**Comment by snoyberg** [comment] 2015-08-13 05:41
Consolas

**Comment by iharh** [comment] 2015-08-13 06:11
Thanx. Probably I need to upgrade to Win-10 at some point. At my current Win-7 Consolas looks really ugly.
BTW, are you using ClearType or some additional effects?

**Comment by snoyberg** [comment] 2015-08-13 06:14
Shrug, no idea. I haven't tweaked things much.

**Comment by iharh** [comment] 2015-08-13 07:04
BTW, At my Win-8 laptop Consolas is also much nicer. A also haven't tweaked it at all :)

**Comment by 3noch** [comment] 2015-08-13 14:02
I've had hit-and-miss experiences with this code-page stuff. Windows 10 console seems to support it well enough, but `Console2` (a popular console replacement) doesn't like it at all. I wonder if it would be best to offer some sort of local (and even global) setting to disable this feature.

**Comment by ndmitchell** [comment] 2015-08-14 15:47
With Win10 I don't have any problems, the characters display properly, so my initial concern is no longer a problem.

**Comment by 3noch** [comment] 2015-08-14 16:06
I think Win10 will be a minority for a while still.

**Comment by ndmitchell** [comment] 2015-08-14 21:21
Trying it again after a `stack upgrade --git` shows it doesn't work, so I may have been using a stale stack on the path when I reported the codepage didn't break it. Now, with vanilla Windows 10, stack ghci shows garbage characters.

**Comment by snoyberg** [comment] 2015-08-16 13:01
I've just pushed a commit to master which does the following:

* Code page changing only applies to the build command
* Adds a command line parameter for controlling what happens with the code page

**Comment by ndmitchell** [comment] 2015-08-16 18:22
Confirmed that fixes my issue with ghci.

**Comment by snoyberg** [comment] 2015-08-16 18:56
Cool, closing.

**Closed by snoyberg** 2015-08-16 18:56 UTC
Labels: need-confirmation

**Comment by lukexi** [comment] 2015-10-03 11:23
Using Cmder (http://cmder.net/) and MSYS2, I seem to need to pass the `--no-modify-code-page` option to get correct output. Is this something I can put in my global config.yaml?

**Comment by borsboom** [comment] 2015-10-03 12:36
@lukexi Not currently.  You might want to comment in #846 where we are planning to generally add many command-line arguments to the config file.

**Comment by lukexi** [comment] 2015-10-04 04:59
Thanks Emanuel!
