### ISSUE TITLE
Stack temporary ghci-scripts created with group write permissions doesn't work ghci-ng

### ISSUE THREAD

**Issue by phenguin** [commercialhaskell/stack#1480] opened 2015-12-09 06:01 UTC
Hey there,

I'm trying to get stack to play nicely with ghci-ng and I'm having issues with the permissions on the temporary ghci-script files stack is creating when running "stack ghci --with-ghc=ghci-ng".  ghci-ng complains when trying to execute any ghci script that has group or other write permissions, and from running an strace on the stack ghci command above, I saw that stack was creating these temp scripts with 0666 permissions.  This causes me to get a message like "WARNING: /tmp/username/ghci-script234234/ghci-script is writable by someone else.  IGNORING!" when running the command.  In addition, the project modules are not loaded either (because the script isn't run).  Is there a workaround for this issue? Also, is there a reason why these temp file couldn't be created with more restricted permissions, say 0644?

Thanks

**Comment by mgsloan** [comment] 2015-12-09 06:49
@phenguin Good point!  I don't get these warnings, but I've added some code to set the permissions.  Please reopen if the issue isn't fixed in the latest development version.

**Closed by mgsloan** 2015-12-09 06:49 UTC
Labels: component: ghci, type: enhancement
