### ISSUE TITLE
Cannot build using nightly with --profile and --pedantic

### ISSUE THREAD

**Issue by davidspies** [commercialhaskell/stack#3408] opened 2017-09-02 15:45 UTC
### General summary/comments (optional)
Cannot build using nightly with --profile and --pedantic

### Steps to reproduce
Build a project (https://github.com/davidspies/regret-solver)  with --profile and --pedantic using --resolver nightly-09-02

### Expected

The project builds

### Actual

Got an error relating to deprecated flags:

```
$ stack build --pedantic --profile --resolver nightly-2017-09-02 regret
regret-0.1.0.0: configure (lib)
Configuring regret-0.1.0.0...

<no location info>: error: 
Failing due to -Werror.

on the commandline: warning:
    -auto-all is deprecated: Use -fprof-auto instead

on the commandline: warning:
    -caf-all is deprecated: Use -fprof-cafs instead

--  While building package regret-0.1.0.0 using:
      /home/ubuntu/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.0.0.2_ghc-8.2.1 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.0.0.2 configure --with-ghc=/home/ubuntu/.stack/programs/x86_64-linux/ghc-8.2.1/bin/ghc --with-ghc-pkg=/home/ubuntu/.stack/programs/x86_64-linux/ghc-8.2.1/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/ubuntu/.stack/snapshots/x86_64-linux/nightly-2017-09-02/8.2.1/pkgdb --package-db=/home/ubuntu/regret-solver/.stack-work/install/x86_64-linux/nightly-2017-09-02/8.2.1/pkgdb --libdir=/home/ubuntu/regret-solver/.stack-work/install/x86_64-linux/nightly-2017-09-02/8.2.1/lib --bindir=/home/ubuntu/regret-solver/.stack-work/install/x86_64-linux/nightly-2017-09-02/8.2.1/bin --datadir=/home/ubuntu/regret-solver/.stack-work/install/x86_64-linux/nightly-2017-09-02/8.2.1/share --libexecdir=/home/ubuntu/regret-solver/.stack-work/install/x86_64-linux/nightly-2017-09-02/8.2.1/libexec --sysconfdir=/home/ubuntu/regret-solver/.stack-work/install/x86_64-linux/nightly-2017-09-02/8.2.1/etc --docdir=/home/ubuntu/regret-solver/.stack-work/install/x86_64-linux/nightly-2017-09-02/8.2.1/doc/regret-0.1.0.0 --htmldir=/home/ubuntu/regret-solver/.stack-work/install/x86_64-linux/nightly-2017-09-02/8.2.1/doc/regret-0.1.0.0 --haddockdir=/home/ubuntu/regret-solver/.stack-work/install/x86_64-linux/nightly-2017-09-02/8.2.1/doc/regret-0.1.0.0 --dependency=MemoTrie=MemoTrie-0.6.8-28T9mWsnNHB5tLT8wccnUV --dependency=base=base-4.10.0.0 --dependency=containers=containers-0.5.10.2 --dependency=hashable=hashable-1.2.6.1-4gQhquVO6wC1mCYLgdW6xs --dependency=hashtables=hashtables-1.2.1.1-Azf7sm0uAPm9EGn4ekGsXN --dependency=monad-loops=monad-loops-0.4.3-3JzKh7o2wug6uWMJY7Us25 --dependency=mtl=mtl-2.2.1-19EL8AGBsN3DnnOhrC9xY3 --dependency=optparse-applicative=optparse-applicative-0.14.0.0-2l9G2LPERxcCn7bBVqnFZE --dependency=pcg-random=pcg-random-0.1.3.4-HynIB2eiNpgLlUTl7nI7E9 --dependency=strict=strict-0.3.2-LQzaAbF4ftM86zqzue6gYC --dependency=vector=vector-0.12.0.1-CnPH69pDwM4A5esizlXfXi --enable-library-profiling --enable-profiling --ghc-options -auto-all --ghc-options -caf-all --ghc-options -Wall --ghc-options -Werror --enable-tests --enable-benchmarks
    Process exited with code: ExitFailure 1
```

### Stack version

```
$ stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1
```

### Method of installation

* Official binary, using `curl -sSL https://get.haskellstack.org/ | sh`

**Comment by kadoban** [comment] 2017-09-04 00:05
Thanks for the report. This looks like a duplicate of #3360 though, which has been fixed on master (not in a release yet).

**Closed by kadoban** 2017-09-04 00:05 UTC
