### ISSUE TITLE
Confusing progress report.

### ISSUE THREAD

**Issue by qnikst** [commercialhaskell/stack#1497] opened 2015-12-11 13:01 UTC
Currently stack progress report in units of work, but it doesn't increment value for units that were already done. As a result usually it's possible to see
```
stack test --no-run-tests
Progress 7/10
```
When I see that I may thought that 3 out of ten jobs were not complete, and assume some failure during execution. However in reality 3 jobs were done before and everything was done.
Is there some way to improve situation here?

**Comment by mgsloan** [comment] 2015-12-12 03:44
Hi!  Thanks for opening this issue, it inspired me to resolve the similar issue #1302 .  Do my fixes also solve this case for you?  (use `stack upgrade --git` to update to the dev version)  Otherwise, I'm going to need a way to reliably reproduce this.

**Comment by mgsloan** [comment] 2016-01-04 02:55
Closing as dupe of / covered by https://github.com/commercialhaskell/stack/issues/1302

**Closed by mgsloan** 2016-01-04 02:55 UTC
Labels: need repro, type: bug
