### ISSUE TITLE
Yaml file not found when Windows username contains non-ASCII characters

### ISSUE THREAD

**Issue by Forkest** [commercialhaskell/stack#2491] opened 2016-08-14 12:19 UTC
I'm encountering the same issue as described [here](https://stackoverflow.com/questions/34905113/how-to-change-the-default-location-of-stack-yaml-on-windows).

Almost any stack command (except of `stack --version`) results in an output like this (user René here):
```
Could not parse 'C:\Users\Ren├®\AppData\Roaming\stack\config.yaml':
InvalidYaml (Just (YamlException "Yaml file not found: C:\\Users\\Ren\233\\AppData\\Roaming\\stack\\config.yaml"))
See http://docs.haskellstack.org/en/stable/yaml_configuration.html.
```

The file is recreated successfully when I delete it, so in theory it should be possible to read it too.

**Comment by Blaisorblade** [comment] 2016-08-14 13:48
First, thanks for the report! Can you run a failing command with `-v` and post the complete log?

Then, have you tried the final tip on STACK_ROOT, as a workaround?
https://stackoverflow.com/questions/34905113/how-to-change-the-default-location-of-stack-yaml-on-windows#comment57558955_34905113

**Comment by Blaisorblade** [comment] 2016-08-14 14:07
Already minimized to a bug in the Yaml library.

`René/foo.yaml`
```
true
...
```

`testYaml.hs`:
```
import qualified Data.Yaml as Yaml

loadYaml :: FilePath -> IO (Either Yaml.ParseException Bool)
loadYaml = Yaml.decodeFileEither

main :: IO ()
main = do
  print =<< loadYaml "René\\foo.yaml"
  return ()
```

```
$ stack runhaskell testYaml.hs
Left (InvalidYaml (Just (YamlException "Yaml file not found: Ren\233\\foo.yaml")))
```

What I've shown is on a fresh Win10 VM, inside`Git Bash` coming from Git for Windows.

**Comment by Blaisorblade** [comment] 2016-08-14 14:46
Oh dear. `Data.Yaml` is a wrapper over a C library, but the issue is probably in its FFI code. I've filed an analysis over there. It doesn't appear fixed in later versions, but I haven't tried.

I think the easiest workaround doable inside stack is to read the file in Haskell into a bytestring and call — even if this changes the space complexity, `stack.yaml` files are probably usually small enough that this doesn't matter.

**Comment by Blaisorblade** [comment] 2016-08-14 15:00
Re workaround: since Snoyberg is in vacation, I guess we shouldn't expect a quickfix upstream. https://twitter.com/snoyberg/status/764514619822051328

**Comment by Blaisorblade** [comment] 2016-08-14 21:07
It turns out I got two fixes:
- https://github.com/snoyberg/yaml/pull/91, under review externally (even though Snoyberg is on vacation he reacted to my bug report).
- a workaround through https://github.com/commercialhaskell/stack/pull/2492 (that somehow is failing on Windows though, I didn't check because I was working on the other fix, investigating now O_O).

**Comment by Blaisorblade** [comment] 2016-08-17 12:31
@Forkest #2492 is merged so this should be fixed on `master`. Hence closing.

**Closed by Blaisorblade** 2016-08-17 12:31 UTC
Labels: in progress
