### ISSUE TITLE
Some project templates don't expand properly with stack-1.9.1

### ISSUE THREAD

**Issue by astynax** [commercialhaskell/stack#4395] opened 2018-11-13 06:13 UTC
### General summary

Recently I tried to create a project from `simple` template:
```
$ stack new foo simple
Downloading template "simple" to create project "foo" in foo/ ...
...
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- foo/

cabal file path /tmp/foo/{{name}}.cabal does not match the package name it defines.
Please rename the file to: foo.cabal
...
```
and got this
```
$ tree foo
foo
├── LICENSE
├── {{name}}.cabal
├── README.md
├── Setup.hs
└── src
    └── Main.hs
```
Other templates with file name generation (I tried the `servant`) produce similar results. Templates that doesn't touch the file names (`simple-hpack`, for example) works fine.

### Stack version

```
$ stack --version
stack --version
Version 1.9.1, Git revision f9d0042c141660e1d38f797e1d426be4a99b2a3c (6168 commits) x86_64 hpack-0.31.0
```

**Comment by andrevdm** [comment] 2018-11-13 11:42
The problem seems to be that mustache templates are only expanded in the file body and not in the file names. So `{-# START_FILE {{name}}.cabal #-}` is never expanded like it used to be.

**Comment by andrevdm** [comment] 2018-11-13 13:01
FWIW doing something like this in `New.hs` works for generating the .cabal files and I expect this is the 99% case

`let files = M.mapKeys (\k -> T.unpack $ T.replace "{{name}}" (T.pack $ packageNameString project) (T.pack k)) files'`

**Comment by andrevdm** [comment] 2018-11-14 12:53
Looks like this is a duplicate of: https://github.com/commercialhaskell/stack/issues/4344

**Closed** 2018-11-14 15:43 UTC
Labels: resolution: duplicate
