### ISSUE TITLE
Why is AppData\Local\Programs\stack\x86_64-windows using so much space?

### ISSUE THREAD

**Issue by Raluulu** [commercialhaskell/stack#5904] opened 2022-10-15 23:13 UTC
I recently started working in Haskell and I downloaded Stack. I have had my laptop for a few months and it has 450GB of memory in C. 

However, a few days ago it showed that it is full. I couldn't understand why but then I used **TreeSize** to investigate what was using so much space and I was shocked. In the **Users** folder in **C**, the hidden folder **AppData** was using almost 400GB of memory.  There is a huge amount of this **type of folder msys2**.  What are they? can I delete them?

How and why I don't understand.
I am not even sure if it's even related to Haskell anymore, I am very confused. What should I do to **free up the space**? 

Please look at the screenshot below.
![image](https://user-images.githubusercontent.com/82377282/196010834-23b22c3e-b58f-4a4f-b43a-b3430d755a9c.png)

**Comment by mpilgrem** [comment] 2022-10-16 00:04
@Raluulu, I don't know how the directory got into that state, but you can safely delete everything in that `x86_64-windows` directory that is not:

* a `ghc-x.y.z` folder
* a `msys2-yyyymmdd` folder
* `7z.dll`
* `7z.exe`
* a corresponding `ghc-x.y.z.installed` file
* a corresponding `msys2-yyyymmdd.installed` file

(In fact, you can safely delete the whole directory, in the sense that Stack will rebuild what it needs the next time you use it.)

**Comment by mpilgrem** [comment] 2022-10-16 00:12
As to what that directory is, it is Stack's 'programs' directory on Windows. It is the directory in which Stack puts Stack-supplied tools (that is, versions of GHC and a version of MSYS2). See `stack path --help` and `stack path --programs`.

**Comment by mpilgrem** [comment] 2022-10-16 00:18
Another directory that can get quite large is the `snapshots` directory in the Stack root (see `stack path --stack-root` - the Stack root is usually `C:\sr`). You can safely delete that directory too, but it does mean that Stack will need to start rebuilding snapshots again as it build things.

**Comment by Raluulu** [comment] 2022-10-16 17:33
Thank you, but all of the folders are of the types that you mentioned in the list. I deleted one and nothing happened, so I hope its okay. For reference, this is what they all conntain:
![image](https://user-images.githubusercontent.com/82377282/196049580-cb8bef5c-b5ca-4453-8028-0a7b26442294.png)
![image](https://user-images.githubusercontent.com/82377282/196049592-8fb9c626-8770-4ad6-b8e6-206d8d83aca1.png)


Do you think its safe to delete them without any damage to my laptop? Or do you know how to prevent this happening with stack in the future?

Thank you!

**Comment by mpilgrem** [comment] 2022-10-16 17:48
@Raluulu, sorry if I was not clear. You can keep a directory named `msys2-20220503` (full stop) and you can delete all the others that start `msys2-202220503-tmp-`.

**Comment by mpilgrem** [comment] 2022-10-16 17:56
For example, on my PC, that directory contains only:
~~~text
    Directory: C:\Users\mike\AppData\Local\Programs\stack\x86_64-windows

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          19/08/2021    10:07                ghc-8.10.7
d----          20/03/2022    15:42                ghc-9.0.2
d----          04/08/2022    20:37                ghc-9.2.4
d----          22/08/2022    20:35                ghc-9.4.2
d----          25/08/2022    10:24                ghc-int-native-9.4.2
d----          02/07/2022    13:26                msys2-20210604
-a---          10/09/2022    19:38        1814016 7z.dll
-a---          10/09/2022    19:38         545280 7z.exe
-a---          10/09/2022    19:39              9 ghc-8.10.7.installed
-a---          20/03/2022    15:42              9 ghc-9.0.2.installed
-a---          04/08/2022    20:37              9 ghc-9.2.4.installed
-a---          22/08/2022    20:35              9 ghc-9.4.2.installed
-a---          25/08/2022    10:24              9 ghc-int-native-9.4.2.installed
-a---          24/04/2022    18:50              9 msys2-20210604.installed
~~~
my MSYS2 directory is named `msys2-20210604` because I installed Stack a while ago.

**Comment by Raluulu** [comment] 2022-10-16 18:03
Hmm.. I see. I seem to not have the msys2.. .installed folder. Maybe that is the problem. Anyway, I have deleted all the tmp files except one and now I finally have my storage back. Thank you for all the help!
![image](https://user-images.githubusercontent.com/82377282/196050783-f8972fa2-f349-4ec3-9d2f-d414f89946a8.png)

**Comment by mpilgrem** [comment] 2022-10-16 18:08
OK, this is what is supposed to happen: Stack fetches the MSYS2 tar, unpacks it to a directory named `msys2-yyyymmdd-tmp-<something>`, renames that directory `msys2-yyymmdd`, and then creates `msys2-yyyymmdd.installed` to flag MSYS2 as installed.

It looks like something has prevented the renaming of the `tmp` directories and the marking of MSYS2 as installed. So, Stack has tried again and again and you have ended up with a lot of the `...tmp-<something>` directories, each containing a copy of MSYS2.

**Comment by mpilgrem** [comment] 2022-10-16 18:34
Why that has happened to you with MSYS2 is a puzzle. Stack does much the same thing with versions of GHC. You can the `ghc-9.0.2.tar.xz` it fetched, the `ghc-9.0.2` directory it ended up with, and the `ghc-9.0.2.installed` it created when all was done. So, Stack did not stumble when it came to GHC.

If you delete _everything_ named MSYS2 in that directory, it will be interesting to see what happens when Stack does something that needs MSYS2 - for example, if you simply command `stack path`. What should happen is that Stack fetches MSYS2 and installs it.

**Comment by mpilgrem** [comment] 2022-10-16 18:40
I've just tried it on my own PC and it failed with:
~~~
Downloaded msys2-20220503.
Already downloaded.
Already downloaded.
Decompressing msys2-20220503.tar.xz...

7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:
1 file, 93835868 bytes (90 MiB)

Extracting archive: C:\Users\mike\AppData\Local\Programs\stack\x86_64-windows\msys2-20220503.tar.xz
--
Path = C:\Users\mike\AppData\Local\Programs\stack\x86_64-windows\msys2-20220503.tar.xz
Type = xz
Physical Size = 93835868
Method = LZMA2:23 CRC64
Streams = 1
Blocks = 1

Everything is Ok

Size:       366448640
Compressed: 93835868
Extracting msys2-20220503.tar...
Extracted 15 filesERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\mike\AppData\Local\Programs\stack\x86_64-windows\msys2-20220503-tmp-2cac8832b30e5ece\\msys64\dev\fd
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\mike\AppData\Local\Programs\stack\x86_64-windows\msys2-20220503-tmp-2cac8832b30e5ece\\msys64\dev\stderr
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\mike\AppData\Local\Programs\stack\x86_64-windows\msys2-20220503-tmp-2cac8832b30e5ece\\msys64\dev\stdin
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\mike\AppData\Local\Programs\stack\x86_64-windows\msys2-20220503-tmp-2cac8832b30e5ece\\msys64\dev\stdout
ERROR: Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\mike\AppData\Local\Programs\stack\x86_64-windows\msys2-20220503-tmp-2cac8832b30e5ece\\msys64\etc\mtab
Extracted total of 21 files from msys2-20220503.tar
Problem while decompressing C:\Users\mike\AppData\Local\Programs\stack\x86_64-windows\msys2-20220503-tmp-2cac8832b30e5ece\msys2-20220503.tar
~~~

That is the underlying problem. Something is going wrong with the decompression of the tar archive.

**Comment by mpilgrem** [comment] 2022-10-16 18:58
@Raluulu, I think this is a work around while I am investigating further: I am using Windows Terminal as my terminal. If I run Windows Terminal 'as Administrator' (ie with elevated rights), I do not get the `ERROR: Cannot create symbolic link : A required privilege is not held by the client.` errors and MSYS2 installs as intended.

**Comment by mpilgrem** [comment] 2022-10-16 19:57
@Raluulu, I think I have now fixed the problem and, in the process, updated to msys2-20220904.

Please can you delete everything named `msys2- ...` in your `x86_64-windows` directory, and then try the `stack path` command. That should trigger a download and install of `msys2-20220904`. I am hoping that no errors will occur in the unpacking of the archive. I've tried it on my own PC but it would be good to know that it works for you too.

**Comment by mpilgrem** [comment] 2022-10-20 20:12
@Raluulu, has this addressed your issue?

**Comment by mpilgrem** [comment] 2022-11-03 18:33
As it has been a couple of weeks, I will close this issue.

**Closed by mpilgrem** 2022-11-03 18:33 UTC
