### ISSUE TITLE
Invalid option `--bash-completion-script`

### ISSUE THREAD

**Issue by anihm136** [commercialhaskell/stack#5663] opened 2022-01-03 18:09 UTC
### General summary/comments (optional)
Following the guide at https://docs.haskellstack.org/en/v2.7.3/shell_autocompletion/ to enable shell autocompletion fails with the following message - `invalid option '--bash-completion-script'

### Steps to reproduce
Try running `stack --bash-completion-script'

### Expected

Completion script for stack, which can be sourced

### Actual

Fails with above message

### Stack version

```
$ stack --version
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

### Method of installation

* Via asdf-haskell, which uses a [modified version](https://github.com/asdf-community/asdf-haskell/blob/master/bin/get_haskell_stack) of the official installation script

**Comment by mpilgrem** [comment] 2022-04-19 22:21
@anihm136, is this still an issue for you with `stack` version 2.7.5? For me (on Windows 11), `stack --bash-completion-script stack` yields:
~~~
_stack.exe()
{
    local CMDLINE
    local IFS=$'\n'
    CMDLINE=(--bash-completion-index $COMP_CWORD)

    for arg in ${COMP_WORDS[@]}; do
        CMDLINE=(${CMDLINE[@]} --bash-completion-word $arg)
    done

    COMPREPLY=( $(stack "${CMDLINE[@]}") )
}

complete -o filenames -F _stack.exe stack.exe
~~~

**Comment by mpilgrem** [comment] 2022-05-30 19:36
I am going to close this issue as I could not reproduce it with a modern version of `stack`.

**Closed by mpilgrem** 2022-05-30 19:36 UTC

**Comment by anihm136** [comment] 2022-05-31 03:13
Sorry, I seem to have missed some messages in this thread. I can confirm that I'm no longer facing this issue with the latest version of stack. Thanks!
