### ISSUE TITLE
stack does not allow using an external package from ghci

### ISSUE THREAD

**Issue by feuerbach** [commercialhaskell/stack#1557] opened 2015-12-22 13:38 UTC
I have a library that I want to debug. For that, I need a package that's not among the library's dependencies (`base16-bytestring`). But stack ghci would not allow me to do that, even if I pass `--package`:

```
% stack ghci --package base16-bytestring presta-lib:lib 
The following GHC options are incompatible with GHCi and have not been passed to it: -O0
Configuring GHCi with the following packages: presta-lib
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
...
Ok, modules loaded: ...
> :m +Data.ByteString.Base16 Data.SafeCopy Data.Serialize

<no location info>:
    Could not find module ‘Data.ByteString.Base16’
    It is a member of the hidden package ‘base16-bytestring-0.1.1.6@base1_LGFgY5jaffY4IePNqJx55U’.

% stack --version
Version 0.1.11.0, Git revision 189d677ca6d63012ebe56083c9bee49f635bcc0d (dirty) (2919 commits) x86_64
```

**Comment by feuerbach** [comment] 2015-12-22 13:42
I just discovered `--no-package-hiding`, but it doesn't quite work either. I guess I'll open a separate issue for that.

**Comment by feuerbach** [comment] 2015-12-22 13:44
Ok, so one problem with `--no-package-hiding` isn't really a bug, just unfortunate expected behaviour:

```
    Ambiguous module name ‘Crypto.MAC.HMAC’:
      it was found in multiple packages:
      cryptonite-0.6@crypt_1A87AV0e5C8BaBsLLV3mNF cryptohash-0.11.6@crypt_5epyAhdyCoGIBkp2icUC24
```

**Comment by mgsloan** [comment] 2015-12-23 01:12
Good point, looks like a bug.

**Comment by luigy** [comment] 2015-12-23 22:35
In the meantime I think you can get around it by:
```
stack ghci --ghci-options "-package base16-bytestring" --package base16-bytestring presta-lib:lib
```

@mgsloan I wonder if it should be the default to pass a formatted `ghciAdditionalPackages` to ghci 
Are there any edge cases to consider, though?

**Comment by mgsloan** [comment] 2015-12-29 00:18
@luigy I don't think there are any funky edge cases.  I've pushed a couple commits resolving this.

Feel free to re-open if the problem is still around after these changes.

**Closed by mgsloan** 2015-12-29 00:18 UTC
Labels: component: ghci, type: bug
