### ISSUE TITLE
Make GHC minor and bug fix releases available as default in Stack

### ISSUE THREAD

**Issue by conradwt** [commercialhaskell/stack#5163] opened 2020-02-05 09:23 UTC
There appears to be a huge gap between GHC version and the default version which Stack installs when creating a new project.  For example, the current stable version of GHC is 8.8.2 and the default stack version is GHC 8.6.5.  Thus, I would like to see GHC minor and bug fix releases become the default in Stack.  However, I don't know and/or understand the technical limitations of this for the current Stack architecture.

**Comment by openingnow** [comment] 2020-02-06 17:56
You can change your resolver to recent nightly. See https://docs.haskellstack.org/en/stable/yaml_configuration

**Comment by mattaudesse** [comment] 2020-02-07 00:22
@conradwt this is actually more of a [`stackage`](https://github.com/commercialhaskell/stackage) thing than `stack`.

As I write this, if you were to run:
```bash
$ stack ls snapshots --lts remote
```
you'd see the latest LTS as of two days ago is pinned to GHC 8.6.5 (and the latest [LTS](https://github.com/commercialhaskell/lts-haskell) is what we use when scaffolding new projects).

Why do the LTS snapshots trail behind the latest and greatest version of GHC? You'll find multiple answers if you dig around, but the main consideration is ensuring stability. Like @openingnow mentions you can always switch to a `--nightly` snapshot if you're brave :-)

```bash
stack ls snapshots --nightly remote

...
a day ago

Resolver name: nightly-2020-02-06
Stackage Nightly 2020-02-06 (ghc-8.8.2)
```


I'm going to go ahead and close this.

**Closed by mattaudesse** 2020-02-07 00:22 UTC

**Comment by conradwt** [comment] 2020-02-07 05:14
@mattaudesse How does automatically set this up where I can get the latest when creating a project?  For example, `stack new project-name` will just simply use the latest snapshot/nightly instead of having to constantly go and edit configuration file(s).

**Comment by mattaudesse** [comment] 2020-02-08 21:25
@conradwt sorry it's taken me awhile to respond - we had a pretty bad internet outage in my neck of the woods yesterday.

It should be possible to knock together the functionality you're asking for via the template system if you're motivated:
https://github.com/commercialhaskell/stack-templates/search?q=resolver&unscoped_q=resolver

```bash
$ stack new --help
Usage: stack new PACKAGE_NAME [--bare] [TEMPLATE_NAME] [-p|--param KEY:VALUE]
                 [DIR] [--omit-packages] [--force] [--ignore-subdirs] [--help]
  Create a new project from a template. Run `stack templates' to see available
  templates. Note: you can also specify a local file or a remote URL as a
  template.

Available options:
  PACKAGE_NAME             A valid package name.
  --bare                   Do not create a subdirectory for the project
  TEMPLATE_NAME            Name of a template - can take the form
                           [[service:]username/]template with optional service
                           name (github, gitlab, or bitbucket) and username for
                           the service; or, a local filename such as foo.hsfiles
                           or ~/foo; or, a full URL such as
                           https://example.com/foo.hsfiles.
  -p,--param KEY:VALUE     Parameter for the template in the format key:value
  DIR                      Directories to include, default is current directory.
  --omit-packages          Exclude conflicting or incompatible user packages
  --force                  Force overwriting an existing stack.yaml
  --ignore-subdirs         Do not search for .cabal files in sub directories
  --help                   Show this help text

Run 'stack --help' for global options that apply to all subcommands.

```

There are a few reasons why people don't care to do that in practice though (and why `stack` doesn't offer it out of the box):

- Non-throwaway projects will periodically need to bump their resolver field to remain current, which means you have to make the occasional, quick config edit anyway

- For the majority of `stack` users, LTS snapshots' stability and deterministic builds wind up being more valuable than tracking GHC's bleeding edge

- Most mainstream Haskell library authors leave plenty of time for consuming code to catch up with new GHC releases' language features, so unless someone's doing something really novel (at which point, again, they'll likely need to exercise greater control over their config anyway) they probably won't be affected

**Comment by conradwt** [comment] 2020-02-09 02:24
@mattaudesse 

Option 1

- set the resolver to `resolver: nightly` in the global `stack.yaml` but this gives me `lts-14.23` instead of `nightly-2020-02-08` in the resulting project

Note: It doesn't appear to be implemented and working at this time.

Option 2

If the `new-template.hsfiles` is the default when someone does `stack new project-name`, I believe that I can add `stack.yml` section which has the following:

-- use the most recent nightly
resolver: nightly

Note:  This option still has this issue of Option (1).

**Comment by mattaudesse** [comment] 2020-02-09 19:36
@conradwt  I think I understand what you've tried but we're still a bit out of sync, so here's what I'd recommend you do next:

Revisit the [link](https://github.com/commercialhaskell/stack-templates/search?q=resolver&unscoped_q=resolver) I pasted above and check out this template:
![image](https://user-images.githubusercontent.com/3409214/74106838-0c030e00-4b38-11ea-812a-0f4c0ab19400.png)

This instructs `stack new PACKAGE_NAME tasty-discover` to dump a `stack.yaml` file into your new project with the `resolver` set to `lts-5.3`. 

When you create your own template you can replace the `resolver` and drop the `location` field from `packages`, leaving just:

```yaml
{-# START_FILE stack.yaml #-}
resolver: nightly # <-- this is ultimately what you're trying to achieve
packages:
- '.'
```


**`stack new`, by design, isn't supposed to track `nightly` by default, so instead of modifying `new-template.hsfiles` you'll create an entirely new template that's tweaked to your liking and explicitly specify it when running `stack new` from now on (i.e. `stack new PACKAGE_NAME conradwt-yolo-nightly` :-) ).**


Looking at the help output I pasted above you can see it's possible to target a different template on your local filesystem or even a remote GitHub/GitLab/BitBucket repo:

```bash
$ stack new --help
Usage: stack new PACKAGE_NAME [--bare] [TEMPLATE_NAME] [-p|--param KEY:VALUE]

...

  TEMPLATE_NAME            Name of a template - can take the form
                           [[service:]username/]template with optional service
                           name (github, gitlab, or bitbucket) and username for
                           the service; or, a local filename such as foo.hsfiles
                           or ~/foo; or, a full URL such as
                           https://example.com/foo.hsfiles.

...
```

So it's up to you where you'd like to put your new template, but if it was me I'd just host it locally until I nailed down my workflow.

If you build a template you're happy with and want to share you can submit it in a PR to https://github.com/commercialhaskell/stack-templates.

Regarding option 1 above, I'd recommend re-reading this bit of the docs (this is another case of intended behavior):
![image](https://user-images.githubusercontent.com/3409214/74107225-ccd6bc00-4b3b-11ea-9232-abd210cee1c2.png)

The note at the bottom explains why your resolver wasn't overridden.

**Comment by conradwt** [comment] 2020-02-09 23:00
@mattaudesse I'm invoking `stack` outside of the project (i.e. $HOME).  From the note above, it should invoke `~/.stack/global-project/stack.yaml`.  Is this correct or am I missing something here?

**Comment by mattaudesse** [comment] 2020-02-10 01:25
> For now, I'll simply generate a project and change the resolver because I want to better understand how a stack generated project deals with the development, test, and production dependencies.

👍 I think this is your best bet even if it feels counter-intuitive or more effortful right now (and I could've done a better job qualifying that above - hacking templates right out of the gate is pretty hardcore). Running through the motions a few times will probably be more self-explanatory.


> @mattaudesse I'm invoking stack outside of the project (i.e. $HOME). From the note above, it should invoke ~/.stack/global-project/stack.yaml. Is this correct or am I missing something here?

I can see how that'd be confusing. Maybe the best way to think about it is to distinguish between _project_ commands (e.g. `stack build`, `stack repl`, `stack test`, etc) and _"utility"_ commands (e.g. `stack upgrade`, `stack ls ...`, `stack new`, etc).

Even though `stack new` _creates_ a project, it's not directly operating upon one in a way that involves project configuration (such as referring to a resolver snapshot in order to stage a dependency). The `stack` binary itself is just performing some basic file prep, situating a new project for you based on templated rules.

Once you run `stack build` or another "project" command then the `resolver` field becomes one of the most important factors in determining GHC's output because the version of every dependency you include will depend upon it. We can use [`aeson`](https://www.stackage.org/lts-11.22/package/aeson-1.2.4.0) as an example:

![image](https://user-images.githubusercontent.com/3409214/74113492-733db400-4b72-11ea-99f9-75dcc18e7df3.png)

I chose `lts-11.22` just to emphasize how GHC and dependency versions are pinned for all time. When selecting an LTS (and periodically updating it to stay current) you get reliable builds and make it easier for other packages to depend on you in turn. That's why this is the default behavior. 

Alternatively, if you choose to track `nightly`, you're essentially saying you don't mind manually coaxing broken inter-dependencies before things stabilize into an LTS, and you're cool with `stack build` meaning something different today than it will next week/month/year.

> Finally, I want to take some time to understand the current state of Haskell's package dependency manager.

I think that'll be enlightening too, but beware it's potentially another confusing rabbit hole :-) Good luck!
