### ISSUE TITLE
`Could not find module` for `yesod-simple` with lts-3.14 with docker enabled

### ISSUE THREAD

**Issue by MaxDaten** [commercialhaskell/stack#1377] opened 2015-11-19 17:16 UTC
Hi,

It's not `yesod-simple` specific, I experienced this problem in my own projects but with `yesod-simple` it is  easy to reproduce.

```
stack --version                                                                                                                                
Version 0.1.6.0, Git revision e22271f5ce9afa2cb5be3bad9cafa392c623f85c (2313 commits) x86_64
```

docker is installed via the [docker-toolbox](https://github.com/docker/toolbox/releases/tag/v1.9.0)
```
docker version                                                                                                                                 
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

## Steps to Reproduce

```sh
stack new myProject yesod-simple
cd myProject
cat >> stack.yaml <<EOL
docker: 
  enable: true
EOL
stack docker pull
stack build
```

Results with multiple `Could not find module` errors:

For example:

```
Configuring aeson-extra-0.2.2.0...
Building aeson-extra-0.2.2.0...
Preprocessing library aeson-extra-0.2.2.0...

src/Data/Aeson/Compat.hs:55:18:
    Could not find module ‘Control.Monad.Catch’
    There are files missing in the ‘exceptions-0.8.0.2@excep_8GsEeHgaIks3pVGk6GaELJ’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.

src/Data/Aeson/Compat.hs:59:18:
    Could not find module ‘Data.HashMap.Strict’
    There are files missing in the ‘unordered-containers-0.2.5.1@unord_7E41cj9RvqSJeZ4jSnbs1a’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.

src/Data/Aeson/Compat.hs:60:18:
    Could not find module ‘Data.Text’
    There are files missing in the ‘text-1.2.1.3@text_1l1AN4I48k37RaQ6fm6CEh’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.

src/Data/Aeson/Extra.hs:58:18:
    Could not find module ‘Data.Hashable’
    There are files missing in the ‘hashable-1.2.3.3@hasha_2GTZqecVp8NJZrNuKzGxfy’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.

src/Data/Aeson/Extra.hs:61:18:
    Could not find module ‘Data.Text.Lazy’
    There are files missing in the ‘text-1.2.1.3@text_1l1AN4I48k37RaQ6fm6CEh’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.

```

complete Log: [stack-build.log](https://github.com/commercialhaskell/stack/files/39215/stack-build.txt)

With lts-3.13 in `stack.yaml` it's possible to build the project without problems. Without docker enabled, I don't have any problems, even with lts-3.14.

I'm using OSX and I'm aware of the limited OSX support currently, but since I can build with 3.13 but not with 3.14, I think it's worth an issue.

**Comment by MaxDaten** [comment] 2015-11-22 02:17
Updated to `0.1.8.0` with the same problem.

**Comment by borsboom** [comment] 2015-11-22 17:33
I haven't been able to reproduce this locally (also using Stack's Docker integration from Mac OS X).  If you move your `~/.stack/snapshots` out of the way temporarily, does the problem still occur?  I'm thinking if this might be related to #911.

**Comment by MaxDaten** [comment] 2015-11-23 10:15
Thanks, moving `~/.stack/snapshots` out of the way did it for me.

**Comment by borsboom** [comment] 2015-11-23 12:34
Ok, I'll close this assuming the cause was #911.

**Closed by borsboom** 2015-11-23 12:34 UTC
Labels: component: docker, need repro, type: bug
