### ISSUE TITLE
acme-missiles hang on

### ISSUE THREAD

**Issue by MurakamiKennzo** [commercialhaskell/stack#4925] opened 2019-06-30 17:31 UTC
### Stack version

```
$ stack --version
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
```

### Method of installation

Official binary, downloaded from stackage.org or fpcomplete's package repository

```
curl -sSL https://get.haskellstack.org/ | sh
```

### Problem

Im search so hard but can't get any solution.

I followed the user guide and add acme-missiles packages, but here's the output:

```
Mac:my-random murakami$ stack build
Cabal file info not found for acme-missiles-0.3, updating
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
Downloading snapshot
Downloading mirrors
Cannot update index (no local copy)
Downloading index
```

It's hang on.

what's problem here?

I remembered that some day ago it happened again, but I'm not cared.

currently, I wanna install [random](https://www.stackage.org/package/random), It's hang on, so I test acme-missiles, also so.

### expect

Install package.

I'm new in Haskell and Stack, can anyone help me?

**Comment by MurakamiKennzo** [comment] 2019-06-30 17:34
# stack.yaml
 resolver: lts-13.26
packages:
- .
extra-deps:
- acme-missiles-0.3

**Comment by qrilka** [comment] 2019-06-30 18:58
Duplicate of #2240 or #4064 ?

**Comment by MurakamiKennzo** [comment] 2019-07-01 00:59
No, not really, It just some packages look like this, I try ghc and text package in the user guide all ok.

**Comment by MurakamiKennzo** [comment] 2019-07-01 02:34
strangely, It works on my company network well, any magic? I'll close it if tonight it works well on my home computer.

**Closed** 2019-07-01 22:15 UTC
