### ISSUE TITLE
stack bench truncates final output on a slow terminal

### ISSUE THREAD

**Issue by simonmichael** [commercialhaskell/stack#413] opened 2015-06-25 14:50 UTC
If a benchmark executable prints much output, in a slow terminal (such as an emacs shell buffer) "stack bench" truncates it.

**Comment by snoyberg** [comment] 2015-06-25 18:26
Do you have a repo for this? `stack bench` just calls `runghc Setup.hs bench` under the surface, which I thought sent all of the output to a log file.

**Comment by simonmichael** [comment] 2015-06-25 23:19
Hey Michael, https://github.com/simonmichael/hledger/ master should show the problem now if you uncomment hledger/bench/bench.hs line 30 or 31 and run `stack bench hledger` in an emacs shell buffer (`M-x shell` in emacs). You can see the full non-truncated output eg with:
```
(cd hledger; stack exec -- ghc -ibench bench/bench && stack exec -- bench/bench --simplebench)`

**Comment by snoyberg** [comment] 2015-06-26 04:57
I didn't realize that Cabal's bench output went to the terminal, interesting.

**Comment by snoyberg** [comment] 2015-06-26 05:11
Since we're just reusing Cabal's run code here, can you tell me if the same problem appears when you would run `cabal bench`?

**Comment by simonmichael** [comment] 2015-06-26 05:27
I don't see the problem when running `caval bench` myself.

**Comment by snoyberg** [comment] 2015-06-26 07:19
@chrisdone Do you have any thoughts on this?

**Comment by snoyberg** [comment] 2015-06-26 08:04
I just merged a PR that changes the buffering of stdout, I'm not sure if that will have any impact. For the record, I've been unable to repro so far.

**Comment by simonmichael** [comment] 2015-06-26 19:04
Today's stack (revision 2cac22d2a26dab6faa00c6f03edf5798affb7840) has the same problem here, FWIW.

I think maybe Stack.Build.Execute.printBuildOutput should hold on to the printing thread's id, so that the main thread can wait for it to finish before exiting ?

**Comment by simonmichael** [comment] 2015-06-26 19:09
PS awkward that you can't reproduce. To be more specific, I see this in a shell buffer in GNU Emacs 25.0.50.1 running in the normal GUI mode on OSX Yosemite on a 2013 macbook air.

**Comment by radix** [comment] 2015-06-26 19:22
Emacs for OS X has really slow buffer drawing compared to Linux, so it may be difficult to repro on Linux vs Mac.

**Comment by snoyberg** [comment] 2015-08-23 13:46
Can you think of any other way to reproduce this problem? As it stands right now, I don't think anyone else can attempt to fix this.

**Comment by simonmichael** [comment] 2015-08-23 18:16
Have you tried it in an emacs shell on a mac ?

**Comment by snoyberg** [comment] 2015-08-23 18:21
No, I don't have access to a Mac.

**Comment by borsboom** [comment] 2015-08-23 19:24
I was able to reproduce this on my Mac:

![screen shot 2015-08-23 at 12 20 33 pm](https://cloud.githubusercontent.com/assets/2164261/9429790/8ed59fee-4991-11e5-9230-4a4f2596a43f.png)

(a bunch more output appears when I run the same commend in a regular terminal)

I'm also running into something possibly related on Windows, where GHC's output is cut off.  I'm on Windows 10 in a VirtualBox VM and running stack in the "Git Bash" shell (from msysgit), which has incredibly slow output (seriously, it's almost like being on a dial-up modem).

**Comment by borsboom** [comment] 2015-08-24 23:33
I've pushed a change that fixes this for my case and also the similar problem I saw in Windows.  @simonmichael, please re-open if this doesn't work for you (your suggestion of waiting for the `printBuildOutput` threads to finish was indeed the fix).

**Closed by borsboom** 2015-08-24 23:33 UTC
Labels: need repro

**Comment by simonmichael** [comment] 2015-08-25 00:22
Hurrah! Thank you.
