### ISSUE TITLE
Local version of package is not rebuild / removed

### ISSUE THREAD

**Issue by blitzcode** [commercialhaskell/stack#2147] opened 2016-05-16 19:01 UTC
I have a dependencies on a package that's not in Stackage. I specify an `extra-deps`. Works as expected. If I now remove it from the `extra-deps`, download the source from GitHub and add it in `packages`, it is rebuild and the local, modified version is used. So far so good. But:
- If I modify the local package and then rebuild my project, the changes are not rebuild, not picked up
- If I delete the local package, remove it from `packages`, put the Hackage version back in `extra-deps`, nothing changes either
- Even if I do a `stack clean` it still seems to link to whatever binary of the local package it had

Only deleting `.stack-work` makes it pick up on the changes and rebuild & link the Hackage version again. This is with stack v1.1.0 on OS X 10.10.

**Comment by mgsloan** [comment] 2016-05-16 22:31
> If I modify the local package and then rebuild my project, the changes are not rebuild, not picked up

Is the file you've modified mentioned in `exposed-modules` or `other-modules` in your cabal file?  When you do build the package are there warnings about unlisted modules?

> If I delete the local package, remove it from packages, put the Hackage version back in extra-deps, nothing changes either

That's extremely mysterious.

I've done a similar workflow many many times, so there must be something weird.  While I realize that you've described some general steps to reproduce, can you please put together a list of specific steps? (preferably using packages that don't require 3rd party deps)

**Comment by blitzcode** [comment] 2016-05-16 22:55
I'll see if I can make a smaller repo case, but the concrete example is here:

https://github.com/blitzcode/hue-dashboard/blob/v1.1/stack.yaml

I have a single package that's not in Stackage as a dependency. I just had the problem again where I tried with a modified local version of the package, and then removed it from `packages` and put the `extra-deps` one back, trying to go back to using the officil release. Didn't get a rebuild, did a `stack clean`, still had the local modified version. Only after deleting `.stack-work` did I get a build/configure step for `threepenny` and the release version again.

**Comment by mgsloan** [comment] 2016-05-16 23:11
Thanks!  Giving it a try.

**Comment by blitzcode** [comment] 2016-05-16 23:15
What made me pause was that I actually do get a configure/build step for `threepenny` after clearing everything. It should just be in the cache like all the other dependencies, but it seems the local version overwrites it somehow, requiring an actual rebuild?

**Comment by mgsloan** [comment] 2016-05-16 23:20
```
hue-dashboard-0.1.0.0: build
Preprocessing executable 'hue-dashboard' for hue-dashboard-0.1.0.0...
[ 1 of 18] Compiling ProcFS           ( ProcFS.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/ProcFS.o )
[ 2 of 18] Compiling CmdLineOptions   ( CmdLineOptions.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/CmdLineOptions.o )
[ 3 of 18] Compiling Trace            ( Trace.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/Trace.o )
[ 4 of 18] Compiling Util             ( Util.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/Util.o )
[ 5 of 18] Compiling HueJSON          ( HueJSON.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/HueJSON.o )
[ 6 of 18] Compiling PersistConfig    ( PersistConfig.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/PersistConfig.o )
[ 7 of 18] Compiling AppDefs          ( AppDefs.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/AppDefs.o )
[ 8 of 18] Compiling LightColor       ( LightColor.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/LightColor.o )
[ 9 of 18] Compiling HueREST          ( HueREST.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/HueREST.o )
[10 of 18] Compiling WebUIREST        ( WebUIREST.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/WebUIREST.o )
[11 of 18] Compiling BackgroundProcessing ( BackgroundProcessing.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/BackgroundProcessing.o )
[12 of 18] Compiling WebUIHelpers     ( WebUIHelpers.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/WebUIHelpers.o )
[13 of 18] Compiling WebUITileBuilding ( WebUITileBuilding.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/WebUITileBuilding.o )
[14 of 18] Compiling WebUITileBuildingScenes ( WebUITileBuildingScenes.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/WebUITileBuildingScenes.o )
[15 of 18] Compiling WebUITileBuildingSchedules ( WebUITileBuildingSchedules.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/WebUITileBuildingSchedules.o )
[16 of 18] Compiling WebUI            ( WebUI.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/WebUI.o )
[17 of 18] Compiling App              ( App.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/App.o )
[18 of 18] Compiling Main             ( Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/hue-dashboard/hue-dashboard ...
Warning: modules not listed in hue-dashboard.cabal for 'hue-dashboard' component (add to other-modules):
    App
    AppDefs
    BackgroundProcessing
    CmdLineOptions
    HueJSON
    HueREST
    LightColor
    PersistConfig
    ProcFS
    Trace
    Util
    WebUI
    WebUIHelpers
    WebUIREST
    WebUITileBuilding
    WebUITileBuildingScenes
    WebUITileBuildingSchedules
hue-dashboard-0.1.0.0: copy/register
```

Here's what I get.  I believe you've encountered the issue before - https://github.com/commercialhaskell/stack/issues/1705

That said, the dirtiness checker should pay attention to modules even if they are unlisted.

**Comment by blitzcode** [comment] 2016-05-16 23:27
I don't understand, this is just building the project? That's working just fine!

The problem isn't happening with the executable project, it's with the dependency. The application builds/rebuilds etc., the problem only shows if I add `threepenny` as a local package. The application continues to rebuild, but changes in `threepenny` are not picked up. Then, if I remove the local version of `threepenny` and add the hackage dependency on `threepenny` again, nothing is picked up either. Even if I `stack clean` and rebuild the entire project, I still get the old local version of `threepenny`. Only deleting `.stack-work` makes it go back to using the version downloaded from hackage, which is then rebuild instead of take from the cache.

**Comment by mgsloan** [comment] 2016-05-16 23:28
Yeah, sorry, I was going a little quick with the repro.  I do indeed see the issue, and have updated my comment.  Thanks for reporting the problem and providing a repro!

**Comment by mgsloan** [comment] 2016-05-16 23:35
Ok, so far I cannot reproduce the issue with dirty modules in threepenny not causing build.  Are you sure about that part?  It could be that this is fixed in HEAD, I recently fixed a bug with missing files in the dirtiness checker.

I can reproduce the issue where switching from local package to extra-dep with matching version doesn't cause a build.

**Comment by mgsloan** [comment] 2016-05-16 23:39
I think this may be solved as a consequence of https://github.com/commercialhaskell/stack/issues/1265

Since that's coming soon-ish, I'll come back to this issue after.

**Comment by blitzcode** [comment] 2016-05-17 09:26
I tried with v1.1.0 installed from brew, but I also didn't try too hard to pin down the rebuild issue. I was mostly concerned with not being able to easily go back to the hackage dependency. I'll add some more detail when I try to work with the external package next, soon-ish.

**Comment by mgsloan** [comment] 2017-04-20 06:05
Finally fixed!  Wish I'd seen that the fix was so straightforward.

**Closed by mgsloan** 2017-04-20 06:05 UTC
Labels: blocked, type: bug

**Comment by nh2** [comment] 2017-04-23 23:07
Second part of fix for stack not noticing switches between `packages` and `location extra-deps`: https://github.com/commercialhaskell/stack/commit/417996785a659a1eb872e0d6536f5a82759940f4
