### ISSUE TITLE
stack ghci not loading module

### ISSUE THREAD

**Issue by bergmark** [commercialhaskell/stack#394] opened 2015-06-24 08:51 UTC
I'm not sure if this is me not understanding how to use `stack ghci` or if it's a bug. Here's my session where I'd expect to be able to import `Rest.Gen` from the `rest-gen` package (this is in [a clean checkout](https://github.com/silkapp/rest)):

```
V~/s/r/rest master> stack install

rest-core-0.36.0.4-fa8874bcacc78287e03ee55e0faa2143: unregistering
rest-example-0.2.0.2-314aa08691cea0f68e43acc2d3d33ae1: unregistering
rest-gen-0.17.0.6-01a0aca11dad589b7fe1705a08cc5b7d: unregistering
rest-happstack-0.2.10.8-bf090e9c3fa7463909b046b8339f07e3: unregistering
rest-snap-0.1.17.18-1d196ca1a2619ebe3f115ee187c9ec60: unregistering
rest-wai-0.1.0.8-fdf6cde89b3edd3a736334489cc27e8a: unregistering
restexample-client-0.1.1.1-0639ca38538510132b65464834ac230a: unregistering
rest-core-0.36.0.4: build
rest-core-0.36.0.4: install
rest-wai-0.1.0.8: build
rest-snap-0.1.17.18: build
rest-gen-0.17.0.6: build
rest-snap-0.1.17.18: install
rest-wai-0.1.0.8: install
rest-gen-0.17.0.6: install
rest-happstack-0.2.10.8: configure
rest-example-0.2.0.2: configure
rest-happstack-0.2.10.8: build
rest-example-0.2.0.2: build
rest-happstack-0.2.10.8: install
rest-example-0.2.0.2: install
restexample-client-0.1.1.1: build
restexample-client-0.1.1.1: install
Completed all 7 actions.
Installation path /Users/adam/.local/bin/ not found in PATH environment variable
Copying from /Users/adam/silk/repos/rest/.stack-work/install/x86_64-osx/nightly-2015-06-23/7.10.1/bin/rest-example-gen to /Users/adam/.local/bin/rest-example-gen

Installed executables to /Users/adam/.local/bin/:
- rest-example-gen

V~/s/r/rest master> stack ghci
Configuring GHCi with the following packages: code-builder, rest-client, rest-core, rest-example, restexample-client, rest-gen, rest-happstack, rest-snap, rest-stringmap, rest-types, rest-wai
mGHCi, version 7.10.1: http://www.haskell.org/ghc/  :? for help

λ> import Rest.Gen

Top level:
    attempting to use module ‘Rest.Gen’ (/Users/adam/silk/repos/rest/rest-gen/src/Rest/Gen.hs) which is not loaded
```

**Comment by bergmark** [comment] 2015-06-24 08:53
Here's the output from `stack -v ghci`

```
V~/s/r/rest master> stack -v ghci
Version 0.1.0.0
2015-06-24 08:52:31.347025: [debug] Checking for project config at: /Users/adam/silk/repos/rest/stack.yaml @(stack-0.1.0.0:Stack.Config src/Stack/Config.hs:473:9)
2015-06-24 08:52:31.347356: [debug] Loading project config file stack.yaml @(stack-0.1.0.0:Stack.Config src/Stack/Config.hs:494:13)
2015-06-24 08:52:31.356773: [debug] Run process: ghc --info @(stack-0.1.0.0:System.Process.Read src/System/Process/Read.hs:253:3)
2015-06-24 08:52:31.411337: [debug] Run process: ghc --numeric-version @(stack-0.1.0.0:System.Process.Read src/System/Process/Read.hs:253:3)
2015-06-24 08:52:31.440493: [debug] Run process: ghc-pkg --no-user-package-db field --simple-output Cabal id @(stack-0.1.0.0:System.Process.Read src/System/Process/Read.hs:253:3)
2015-06-24 08:52:31.466873: [debug] Run process: ghc-pkg --no-user-package-db list --global @(stack-0.1.0.0:System.Process.Read src/System/Process/Read.hs:253:3)
2015-06-24 08:52:31.513492: [info] Configuring GHCi with the following packages: code-builder, rest-client, rest-core, rest-example, restexample-client, rest-gen, rest-happstack, rest-snap, rest-stringmap, rest-types, rest-wai @(stack-0.1.0.0:Stack.Repl src/Stack/Repl.hs:63:5)
2015-06-24 08:52:31.513756: [debug] Run process: /Users/adam/.ghc-7.10.1/bin/ghc --interactive -Wall -i/Users/adam/silk/repos/rest/code-builder/ -i/Users/adam/silk/repos/rest/code-builder/src/ -i/Users/adam/silk/repos/rest/code-builder/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/ -optP-include -optP/Users/adam/silk/repos/rest/code-builder/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/cabal_macros.h -Wall -i/Users/adam/silk/repos/rest/rest-client/ -i/Users/adam/silk/repos/rest/rest-client/src/ -i/Users/adam/silk/repos/rest/rest-client/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/ -optP-include -optP/Users/adam/silk/repos/rest/rest-client/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/cabal_macros.h -Wall -i/Users/adam/silk/repos/rest/rest-core/ -i/Users/adam/silk/repos/rest/rest-core/src/ -i/Users/adam/silk/repos/rest/rest-core/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/ -optP-include -optP/Users/adam/silk/repos/rest/rest-core/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/cabal_macros.h -i/Users/adam/silk/repos/rest/rest-core/tests/ -Wall -i/Users/adam/silk/repos/rest/rest-example/ -i/Users/adam/silk/repos/rest/rest-example/example-api/ -i/Users/adam/silk/repos/rest/rest-example/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/ -optP-include -optP/Users/adam/silk/repos/rest/rest-example/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/cabal_macros.h -i/Users/adam/silk/repos/rest/rest-example/happstack/ -i/Users/adam/silk/repos/rest/rest-example/wai/ -i/Users/adam/silk/repos/rest/rest-example/snap/ -i/Users/adam/silk/repos/rest/rest-example/generate/ -i/Users/adam/silk/repos/rest/rest-example/client/ -i/Users/adam/silk/repos/rest/rest-example/client/src/ -i/Users/adam/silk/repos/rest/rest-example/client/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/ -optP-include -optP/Users/adam/silk/repos/rest/rest-example/client/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/cabal_macros.h -Wall -i/Users/adam/silk/repos/rest/rest-gen/ -i/Users/adam/silk/repos/rest/rest-gen/src/ -i/Users/adam/silk/repos/rest/rest-gen/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/ -optP-include -optP/Users/adam/silk/repos/rest/rest-gen/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/cabal_macros.h -i/Users/adam/silk/repos/rest/rest-gen/tests/ -Wall -i/Users/adam/silk/repos/rest/rest-happstack/ -i/Users/adam/silk/repos/rest/rest-happstack/src/ -i/Users/adam/silk/repos/rest/rest-happstack/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/ -optP-include -optP/Users/adam/silk/repos/rest/rest-happstack/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/cabal_macros.h -Wall -i/Users/adam/silk/repos/rest/rest-snap/ -i/Users/adam/silk/repos/rest/rest-snap/src/ -i/Users/adam/silk/repos/rest/rest-snap/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/ -optP-include -optP/Users/adam/silk/repos/rest/rest-snap/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/cabal_macros.h -Wall -i/Users/adam/silk/repos/rest/rest-stringmap/ -i/Users/adam/silk/repos/rest/rest-stringmap/src/ -i/Users/adam/silk/repos/rest/rest-stringmap/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/ -optP-include -optP/Users/adam/silk/repos/rest/rest-stringmap/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/cabal_macros.h -Wall -i/Users/adam/silk/repos/rest/rest-types/ -i/Users/adam/silk/repos/rest/rest-types/src/ -i/Users/adam/silk/repos/rest/rest-types/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/ -optP-include -optP/Users/adam/silk/repos/rest/rest-types/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/cabal_macros.h -Wall -i/Users/adam/silk/repos/rest/rest-wai/ -i/Users/adam/silk/repos/rest/rest-wai/src/ -i/Users/adam/silk/repos/rest/rest-wai/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/ -optP-include -optP/Users/adam/silk/repos/rest/rest-wai/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/cabal_macros.h @(stack-0.1.0.0:Stack.Exec src/Stack/Exec.hs:41:5)
GHCi, version 7.10.1: http://www.haskell.org/ghc/  :? for help
λ> import Rest.Gen

Top level:
    attempting to use module ‘Rest.Gen’ (/Users/adam/silk/repos/rest/rest-gen/src/Rest/Gen.hs) which is not loaded
```

**Comment by chrisdone** [comment] 2015-06-24 09:04
Dupe of #347 and #355. I'm going to put this on higher priority otherwise we'll be getting this reported all the time.

**Comment by bergmark** [comment] 2015-06-24 09:43
Thanks!

**Comment by chrisdone** [comment] 2015-06-24 10:27
Okay, please retry! Some info:

* `stack ghci` should load everything by default.
* It will create object files in the usual place that ghci does. So if you enable `-fobject-code` (either in your `./.ghci`, `~/.ghci` or via `--ghc-options=-fobject-code`), it will not reload anything it doesn't need to. With the usual caveats of object code in GHCi, of course.
* It will only load "modules". It won't load Main modules for the executable or bench marks or test suites, because they conflict. So for that you should load the filename manually with `:load src/main/Main.hs` or whatnot.

**Comment by rvion** [comment] 2015-06-24 10:47
Random questions:

 1. Can we load the first executable Main module (non test, non bench) by default ? or with a --load-main option
 2. Could we specify which package to load the main from with a --load-main=xxx
 3. would a --no-main flag make sense in that situation ?
 4. Would loading Main only when there is just one main in the project make sense ? 
 5. More generic: when several modules conflicts, a message could say: modules package1/path/XXX and package2/path/XXX conflict, so XXX is skipped

**Comment by bergmark** [comment] 2015-06-24 10:56
`stack ghci` now gives me errors of the form
```
<built-in>:27:10:
     fatal error: 'dist/build/autogen/cabal_macros.h' file not found
#include "dist/build/autogen/cabal_macros.h"
         ^
```

`stack ghci rest-gen/src/Rest/Gen.hs` works, but I need to `import Rest.Gen` explicitly after ghci launches, I assumed that would be automatic.

**Comment by chrisdone** [comment] 2015-06-24 10:58
@bergmark I expect the fatal error prevented any loading from happening. Do you have some code in your project or .ghci file that refers to cabal_macros.h?

There is [code in stack ghci](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Package.hs#L272..L278) that adds this, but it would be `.stack-work/dist/etc` and only if the file exists.

**Comment by bergmark** [comment] 2015-06-24 11:36
The culprit was `:set -optP-include` in my `~/.ghci`. `stack ghci` works now, thanks! :beers:

**Comment by chrisdone** [comment] 2015-06-24 11:37
Yay!

**Closed** 2015-06-27 20:04 UTC
Labels: need-confirmation
