### ISSUE TITLE
Stack install GHC took too much time on FreeBSD

### ISSUE THREAD

**Issue by yzgyyang** [commercialhaskell/stack#4206] opened 2018-08-05 07:01 UTC
### Steps to reproduce
```
curl -fsSL -o haskellstack.sh https://get.haskellstack.org/
chmod +x haskellstack.sh
./haskellstack.sh
stack setup --resolver ghc-8.4.2
```

### Expected

GHC 8.4.2 being installed.

### Actual

`stack setup` never stops. From SIGINFO, it seems to be stuck at:

```
load: 0.98  cmd: strip 2147 [runnable] 178.39r 177.83u 0.17s 100% 33516k
```

Specifically:

```
strip --strip-unneeded /root/.stack/programs/x86_64-freebsd/ghc-8.4.2/lib/ghc-8.4.2/Cabal-2.2.0.1/libHSCabal-2.2.0.1_p.a
```
forever.

### Stack version

```
root@gitlab:/ # stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
root@gitlab:/ # uname -a
FreeBSD gitlab 11.2-RELEASE FreeBSD 11.2-RELEASE #0 r335510: Fri Jun 22 04:32:14 UTC 2018     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

I am also running this as CI service. Example log: https://gitlab.com/yzgyyang/package_manager/-/jobs/86887810

**Comment by arrowd** [comment] 2018-08-14 14:08
I'm maintaining GHC port for FreeBSD and also noticed that stripping Haskell-compiled binaries takes very long time. However, it doesn't hang. How much did you wait?

**Comment by yzgyyang** [comment] 2018-08-14 22:15
> I'm maintaining GHC port for FreeBSD

I should probably just try that ;)

> stripping Haskell-compiled binaries takes very long time. However, it doesn't hang. How much did you wait?

I run this on my shabby CI server, and there's a 1-hour limit for jobs. I will try it again and post the result here.

**Comment by dbaynard** [comment] 2018-08-22 16:59
Does it always fail with a linker error?

**Comment by mattaudesse** [comment] 2018-10-10 18:07
Not sure if it's helpful at all, but just to echo what @arrowd says above: an install I ran a moment ago took quite awhile to complete, and it was almost entirely in the `strip` phase, but it eventually did succeed.

This is on my own hardware, so obviously no build-time constraints or anything. I'm running FreeBSD 11.2-RELEASE-p4.

**Comment by yzgyyang** [comment] 2018-10-11 01:02
I tested it again with my VM running on a Ryzen desktop, and it took 17 minutes to finish. And as @mattaudesse said,

> it was almost entirely in the strip phase, but it eventually did succeed

I am running FreeBSD 12-ALPHA8.

**Comment by dbaynard** [comment] 2018-11-07 16:34
I believe ABIs have changed between FreeBSD 11 and 12; is it possible that this is related?

**Comment by jessekempf** [comment] 2018-11-21 00:59
I'm finding the same issue on FreeBSD 11.2-RELEASE-p4 on a t2.micro running in us-west-2a.

**Comment by arrowd** [comment] 2019-06-02 10:39
This is being worked upstream, tracking bug is https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=234949

I think, we can close this, because the problem isn't within Stack in any way.

**Closed** 2019-06-02 15:33 UTC
Labels: component: openbsd, further investigation required, need confirmation
