### ISSUE TITLE
Don't build executables with `stack bench`

### ISSUE THREAD

**Issue by crockeea** [commercialhaskell/stack#2799] opened 2016-11-22 00:25 UTC
When I run `stack test` or `stack bench` for a project which also has an executable, stack first prints `build (lib + exe + test)` or `build (lib + exe + bench)` (respectively). However, I do _not_ want to have to build the executables to run the test/benchmark. `stack test` should _only_ try to build `(lib + test)`, without building the executables.

An example cabal file which triggers the issue is:

```
name:                foo
version:             0.1.1.0
stability:           experimental
build-type:          Simple
cabal-version:       >= 1.10

library
  default-language: Haskell2010
  exposed-modules:  Foo
  build-depends:    base
test-suite testfoo
  type:             exitcode-stdio-1.0
  default-language: Haskell2010
  main-is:          Main.hs
  build-depends:    base
Benchmark benchfoo
  type:             exitcode-stdio-1.0
  default-language: Haskell2010
  main-is:          Main.hs
  build-depends:    base

executable exfoo
  default-language: Haskell2010
  main-is:          Main.hs
  build-depends:    base
```

With stack-1.2.0.

**Comment by mgsloan** [comment] 2016-11-22 00:35
Known issue, unfortunately - duplicate of https://github.com/commercialhaskell/stack/issues/1406

**Closed by mgsloan** 2016-11-22 00:35 UTC
