### ISSUE TITLE
Publish Dockerfiles for fpco/stack-build etc, or deprecate them

### ISSUE THREAD

**Issue by robinp** [commercialhaskell/stack#2137] opened 2016-05-14 08:34 UTC
It is somewhat frustrating that the official stack docker documentation is referring to images that don't have the Dockerfiles avaliable, so customization is not possible.

I would propose either publishing them, or updating the doc to point to public ones, or at least guidelines on how to build custom ones (what to include, any special arrangement needed, etc).

I also see a stack-base dockerfile in this repo - is that in any way related?

Thank you!

**Comment by aaronc** [comment] 2016-05-26 18:38
`stack-build` and `stack-run` are great, but I just ran into issues with `stack-run:lts-6` (still works on `stack-run:lts-5` even though it's built against lts-6). There's really no way the community can help debugging such issues when the Dockerfile's are closed source...

**Comment by borsboom** [comment] 2016-05-26 19:02
I'm closing as a duplicate of #624.

We do want to open the scripts, but unfortunately right now it's bunch of Propellor code with conditionals throughout to enable/disable various proprietary client-specific features, so it's not a trivial thing to do.  The scripts have to be refactored so we can make the proprietary parts external.

@aaronc: chances are the difference you're seeing is that the lts-6 images are based on Ubuntu 16.04 xenial (lts-5 images are based on 14.04 trusty).

**Closed** 2016-05-26 19:50 UTC
Labels: component: documentation, type: enhancement
