### ISSUE TITLE
Build against recent persistent fails

### ISSUE THREAD

**Issue by arrowd** [commercialhaskell/stack#5753] opened 2022-05-15 20:08 UTC
I'm building Stack using GHC 9.2.2 against `persistent-2.14.0.0`. This is the error I'm getting:

```
src/Stack/Storage/Util.hs:39:9: error:
    * Could not deduce (Database.Persist.Class.PersistEntity.SafeToInsert
                          record)
        arising from a use of `insertMany_'
      from the context: (PersistEntityBackend record
                         ~ BaseBackend backend,
                         PersistField parentid, PersistField value, Ord value,
                         PersistEntity record, MonadIO m, PersistQueryWrite backend)
        bound by the type signature for:
                   updateSet :: forall record backend parentid value (m :: * -> *).
                                (PersistEntityBackend record ~ BaseBackend backend,
                                 PersistField parentid, PersistField value, Ord value,
                                 PersistEntity record, MonadIO m, PersistQueryWrite backend) =>
                                (parentid -> value -> record)
                                -> EntityField record parentid
                                -> parentid
                                -> EntityField record value
                                -> Set value
                                -> Set value
                                -> ReaderT backend m ()
        at src/Stack/Storage/Util.hs:(17,1)-(32,27)
      Possible fix:
        add (Database.Persist.Class.PersistEntity.SafeToInsert
               record) to the context of
          the type signature for:
            updateSet :: forall record backend parentid value (m :: * -> *).
                         (PersistEntityBackend record ~ BaseBackend backend,
                          PersistField parentid, PersistField value, Ord value,
                          PersistEntity record, MonadIO m, PersistQueryWrite backend) =>
                         (parentid -> value -> record)
                         -> EntityField record parentid
                         -> parentid
                         -> EntityField record value
                         -> Set value
                         -> Set value
                         -> ReaderT backend m ()
    * In the first argument of `($)', namely `insertMany_'
      In a stmt of a 'do' block:
        insertMany_
          $ map (recordCons parentId) $ Set.toList (Set.difference new old)
      In the second argument of `($)', namely
        `do deleteWhere
              [parentFieldCons ==. parentId,
               valueFieldCons <-. Set.toList (Set.difference old new)]
            insertMany_
              $ map (recordCons parentId) $ Set.toList (Set.difference new old)'
   |
39 |         insertMany_ $
   |         ^^^^^^^^^^^
```

**Comment by andreasabel** [comment] 2022-05-16 07:17
Why are you reporting this here, @arrowd, and not at https://github.com/yesodweb/persistent/issues ?

I cannot reproduce the problem you report, the following succeeds:
```
stack build --resolver nightly persistent-2.14.0.0
...
Installing library in /Users/abel/.stack/snapshots/x86_64-osx/4955e4ff638671c1e22f0640246941d88e76d0fc5d24ef9e3e98d50a5ee3b258/9.2.2/lib/x86_64-osx-ghc-9.2.2/persistent-2.14.0.0-7UWtCAgaraWDN4FLNcR7EK
```

**Comment by arrowd** [comment] 2022-05-16 07:23
> Why are you reporting this here, @arrowd, and not at https://github.com/yesodweb/persistent/issues ?

Well, it is the Stack code that fails to compile.

> I cannot reproduce the problem you report

Sorry, I should have mentioned that I'm building 2.7.5 release, not the master branch.

**Comment by stackptr** [comment] 2022-06-12 02:22
I also experience this failure when building via homebrew on an ARM system

**Comment by mpilgrem** [comment] 2022-07-24 15:59
The above is noted. Very recently an upper bound for `persistent` has been added to Stack's `package.yaml`. See https://github.com/commercialhaskell/stack/pull/5791.

Each version of Stack is intended to be built against a specific set of dependencies (https://github.com/commercialhaskell/stack/blob/master/CONTRIBUTING.md#backwards-compatability). There are current attempts to move Stack to GHC 9.0.2 (currently `lts-19.16`) or, more likely, GHC 9.2.3 (currently `nightly-2022-07-23`) but both are blocked by what seems to be an upstream bug in `process` on macOS only. However, in any event, the version of `persistent` on Stackage is currently `2.13.3.5@rev:1`.

I am going to close this issue, as I anticipate it will be addressed when Stack eventually moves to a resolver that includes `persistent` >= 2.14.

**Closed by mpilgrem** 2022-07-24 15:59 UTC
