### ISSUE TITLE
Setup.hs cannot use local snapshot dependencies WAS stack failing to resolve local dependencies of multiple package project

### ISSUE THREAD

**Issue by mitchellwrosen** [commercialhaskell/stack#897] opened 2015-09-02 04:51 UTC
Hi, I can't seem to reproduce this with a smaller example repo so I'll just point to the one that's failing: https://github.com/mitchellwrosen/cabal-macosx/tree/b6e5f714fbf451a72c8b7e70577ce7d9e342f8d0

I'm trying to stackify this three year old repo, and the example projects, which depend on the `cabal-macosx`, fail to build:

```
--  While building package gtkHello-0.1.0 using:
      /Users/mrosen/.stack/programs/x86_64-osx/ghc-7.10.2/bin/runhaskell -package=Cabal-1.22.4.0 -clear-package-db -global-package-db -package-db=/Users/mrosen/.stack/snapshots/x86_64-osx/lts-3.3/7.10.2/pkgdb/ /Users/mrosen/haskell/cabal-macosx/examples/gtkHello/Setup.hs --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ configure --user --package-db=clear --package-db=global --package-db=/Users/mrosen/.stack/snapshots/x86_64-osx/lts-3.3/7.10.2/pkgdb/ --package-db=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/pkgdb/ --dependency=base=base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f --dependency=cabal-macosx=cabal-macosx-0.2.2-2b48f42cc1cff87ee217afa95d34d3ed --dependency=gtk=gtk-0.13.9-37993e343fdd10dc6c30b07beea3d344 --libdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/lib --bindir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/bin --datadir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/share --docdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/gtkHello-0.1.0 --htmldir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/gtkHello-0.1.0 --haddockdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/gtkHello-0.1.0
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/mrosen/haskell/cabal-macosx/.stack-work/logs/gtkHello-0.1.0.log


    /Users/mrosen/haskell/cabal-macosx/examples/gtkHello/Setup.hs:3:8:
        Could not find module ‘Distribution.MacOSX’
        Perhaps you meant
          Distribution.Make (from Cabal-1.22.4.0@Cabal_96aI7pZyaxU3dsgngOxbdK)
          Distribution.GetOpt
          Distribution.Package (from Cabal-1.22.4.0@Cabal_96aI7pZyaxU3dsgngOxbdK)
        Use -v to see a list of the files searched for.
```

I'm not really sure why; `stack exec ghc-pkg list` shows `cabal-macosx-0.2.2` in `.stack-work/install/x86_64-osx/lts-3.3/7.10.2/pkgdb`, and `stack exec ghc-pkg describe cabal-macosx` lists `Distribution.MacOSX` as an exposed module. And as I said, I couldn't replicate this with a simpler multiple-package example.

Here's the entire `stack -v build` in case any of it is relevant:

```
Version 0.1.3.1
2015-09-02 04:53:55.87362: [debug] Checking for project config at: /Users/mrosen/haskell/cabal-macosx/stack.yaml @(stack-0.1.3.1:Stack.Config src/Stack/Config.hs:459:9)
2015-09-02 04:53:55.873842: [debug] Loading project config file stack.yaml @(stack-0.1.3.1:Stack.Config src/Stack/Config.hs:482:13)
2015-09-02 04:53:55.883887: [debug] Run process: ghc --info @(stack-0.1.3.1:System.Process.Read src/System/Process/Read.hs:255:3)
2015-09-02 04:53:55.937986: [debug] Run process: ghc --numeric-version @(stack-0.1.3.1:System.Process.Read src/System/Process/Read.hs:255:3)
2015-09-02 04:53:55.965839: [debug] Run process: ghc-pkg --no-user-package-db field --simple-output Cabal id @(stack-0.1.3.1:System.Process.Read src/System/Process/Read.hs:255:3)
2015-09-02 04:53:55.986855: [debug] Run process: ghc-pkg --no-user-package-db list --global @(stack-0.1.3.1:System.Process.Read src/System/Process/Read.hs:255:3)
2015-09-02 04:53:56.009977: [debug] Checking resolver: lts-3.3 @(stack-0.1.3.1:Stack.Build.Source src/Stack/Build/Source.hs:76:13)
2015-09-02 04:53:56.215766: [warn] Warning: modules not listed in cabal-macosx.cabal for 'macosx-app' component (add to other-modules):
    Distribution.MacOSX
    Distribution.MacOSX.AppBuildInfo
    Distribution.MacOSX.Common
    Distribution.MacOSX.DG
    Distribution.MacOSX.Dependencies @(stack-0.1.3.1:Stack.Package src/Stack/Package.hs:647:11)
2015-09-02 04:53:56.21763: [debug] Run process: ghc-pkg --global --no-user-package-db dump --expand-pkgroot @(stack-0.1.3.1:System.Process.Read src/System/Process/Read.hs:255:3)
2015-09-02 04:53:56.248176: [debug] Run process: ghc-pkg --user --no-user-package-db --package-db /Users/mrosen/.stack/snapshots/x86_64-osx/lts-3.3/7.10.2/pkgdb/ dump --expand-pkgroot @(stack-0.1.3.1:System.Process.Read src/System/Process/Read.hs:255:3)
2015-09-02 04:53:56.360577: [debug] Run process: ghc-pkg --user --no-user-package-db --package-db /Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/pkgdb/ dump --expand-pkgroot @(stack-0.1.3.1:System.Process.Read src/System/Process/Read.hs:255:3)
2015-09-02 04:53:56.73411: [debug] All installs are local; releasing snapshot lock early. @(stack-0.1.3.1:Stack.Build src/Stack/Build.hs:92:28)
2015-09-02 04:53:56.734519: [debug] Run process: ghc-pkg --no-user-package-db list --global @(stack-0.1.3.1:System.Process.Read src/System/Process/Read.hs:255:3)
2015-09-02 04:53:56.757883: [info] gtkHello-0.1.0: configure @(stack-0.1.3.1:Stack.Build.Execute src/Stack/Build/Execute.hs:505:18)
2015-09-02 04:53:56.758061: [debug] Run process: /Users/mrosen/.stack/programs/x86_64-osx/ghc-7.10.2/bin/runhaskell -package=Cabal-1.22.4.0 -clear-package-db -global-package-db -package-db=/Users/mrosen/.stack/snapshots/x86_64-osx/lts-3.3/7.10.2/pkgdb/ /Users/mrosen/haskell/cabal-macosx/examples/gtkHello/Setup.hs --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ configure --user --package-db=clear --package-db=global --package-db=/Users/mrosen/.stack/snapshots/x86_64-osx/lts-3.3/7.10.2/pkgdb/ --package-db=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/pkgdb/ --dependency=base=base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f --dependency=cabal-macosx=cabal-macosx-0.2.2-2b48f42cc1cff87ee217afa95d34d3ed --dependency=gtk=gtk-0.13.9-37993e343fdd10dc6c30b07beea3d344 --libdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/lib --bindir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/bin --datadir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/share --docdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/gtkHello-0.1.0 --htmldir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/gtkHello-0.1.0 --haddockdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/gtkHello-0.1.0 @(stack-0.1.3.1:Stack.Build.Execute src/Stack/Build/Execute.hs:611:13)
2015-09-02 04:53:56.94405: [info] wxHello-0.1.0: configure @(stack-0.1.3.1:Stack.Build.Execute src/Stack/Build/Execute.hs:505:18)
2015-09-02 04:53:56.944259: [debug] Run process: /Users/mrosen/.stack/programs/x86_64-osx/ghc-7.10.2/bin/runhaskell -package=Cabal-1.22.4.0 -clear-package-db -global-package-db -package-db=/Users/mrosen/.stack/snapshots/x86_64-osx/lts-3.3/7.10.2/pkgdb/ /Users/mrosen/haskell/cabal-macosx/examples/wxHello/Setup.hs --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ configure --user --package-db=clear --package-db=global --package-db=/Users/mrosen/.stack/snapshots/x86_64-osx/lts-3.3/7.10.2/pkgdb/ --package-db=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/pkgdb/ --dependency=base=base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f --dependency=cabal-macosx=cabal-macosx-0.2.2-2b48f42cc1cff87ee217afa95d34d3ed --dependency=wx=wx-0.92.0.0-4fb8738e2e82f261b6019b277a7473cf --libdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/lib --bindir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/bin --datadir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/share --docdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/wxHello-0.1.0 --htmldir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/wxHello-0.1.0 --haddockdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/wxHello-0.1.0 @(stack-0.1.3.1:Stack.Build.Execute src/Stack/Build/Execute.hs:611:13)
Completed all 2 actions.

--  While building package wxHello-0.1.0 using:
      /Users/mrosen/.stack/programs/x86_64-osx/ghc-7.10.2/bin/runhaskell -package=Cabal-1.22.4.0 -clear-package-db -global-package-db -package-db=/Users/mrosen/.stack/snapshots/x86_64-osx/lts-3.3/7.10.2/pkgdb/ /Users/mrosen/haskell/cabal-macosx/examples/wxHello/Setup.hs --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ configure --user --package-db=clear --package-db=global --package-db=/Users/mrosen/.stack/snapshots/x86_64-osx/lts-3.3/7.10.2/pkgdb/ --package-db=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/pkgdb/ --dependency=base=base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f --dependency=cabal-macosx=cabal-macosx-0.2.2-2b48f42cc1cff87ee217afa95d34d3ed --dependency=wx=wx-0.92.0.0-4fb8738e2e82f261b6019b277a7473cf --libdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/lib --bindir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/bin --datadir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/share --docdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/wxHello-0.1.0 --htmldir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/wxHello-0.1.0 --haddockdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/wxHello-0.1.0
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/mrosen/haskell/cabal-macosx/.stack-work/logs/wxHello-0.1.0.log


    /Users/mrosen/haskell/cabal-macosx/examples/wxHello/Setup.hs:3:8:
        Could not find module ‘Distribution.MacOSX’
        Perhaps you meant
          Distribution.Make (from Cabal-1.22.4.0@Cabal_96aI7pZyaxU3dsgngOxbdK)
          Distribution.GetOpt
          Distribution.Package (from Cabal-1.22.4.0@Cabal_96aI7pZyaxU3dsgngOxbdK)
        Use -v to see a list of the files searched for.


--  While building package gtkHello-0.1.0 using:
      /Users/mrosen/.stack/programs/x86_64-osx/ghc-7.10.2/bin/runhaskell -package=Cabal-1.22.4.0 -clear-package-db -global-package-db -package-db=/Users/mrosen/.stack/snapshots/x86_64-osx/lts-3.3/7.10.2/pkgdb/ /Users/mrosen/haskell/cabal-macosx/examples/gtkHello/Setup.hs --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ configure --user --package-db=clear --package-db=global --package-db=/Users/mrosen/.stack/snapshots/x86_64-osx/lts-3.3/7.10.2/pkgdb/ --package-db=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/pkgdb/ --dependency=base=base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f --dependency=cabal-macosx=cabal-macosx-0.2.2-2b48f42cc1cff87ee217afa95d34d3ed --dependency=gtk=gtk-0.13.9-37993e343fdd10dc6c30b07beea3d344 --libdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/lib --bindir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/bin --datadir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/share --docdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/gtkHello-0.1.0 --htmldir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/gtkHello-0.1.0 --haddockdir=/Users/mrosen/haskell/cabal-macosx/.stack-work/install/x86_64-osx/lts-3.3/7.10.2/doc/gtkHello-0.1.0
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/mrosen/haskell/cabal-macosx/.stack-work/logs/gtkHello-0.1.0.log


    /Users/mrosen/haskell/cabal-macosx/examples/gtkHello/Setup.hs:3:8:
        Could not find module ‘Distribution.MacOSX’
        Perhaps you meant
          Distribution.Make (from Cabal-1.22.4.0@Cabal_96aI7pZyaxU3dsgngOxbdK)
          Distribution.GetOpt
          Distribution.Package (from Cabal-1.22.4.0@Cabal_96aI7pZyaxU3dsgngOxbdK)
        Use -v to see a list of the files searched for.
```

**Comment by snoyberg** [comment] 2015-09-02 05:04
The reason this is happening is that, currently, we only allow the Setup.hs file to use global and snapshot packages, not local packages. The reason is reproducible builds: relying on something in the local database means that a build today may fail later if the local database is in a different state.

I'm open to relaxing this. There's even a comment about all of this in the codebase at: https://github.com/commercialhaskell/stack/blob/master/src/Stack/Build/Execute.hs#L678.

I think the best course of action here is to add `bcoLocalDB` when compiling a local package. You interested in taking a stab at making that change and see if it solves your problem?

**Comment by mitchellwrosen** [comment] 2015-09-02 05:10
I'm not sure I understand. This repo has two packages, the second of which depends on the first in its Setup.hs, and it builds successfully: https://github.com/mitchellwrosen/stack-897-example

**Comment by snoyberg** [comment] 2015-09-02 05:14
That's because you've set `build-type: Simple` at https://github.com/mitchellwrosen/stack-897-example/blob/master/child/child.cabal#L12, which means "ignore the Setup.hs file and just use a simple build plan." Changing that to `build-type: Custom` should demonstrate the problem.

**Comment by mitchellwrosen** [comment] 2015-09-02 05:20
I see. Sure, I can attempt that change but it might take a bit =)

**Comment by snoyberg** [comment] 2015-09-02 05:21
If you get stuck, let me know. Initial version would just be adding `"-package-db=" ++ toFilePath (bcoLocalDB eeBaseConfigOpts)` and confirming that it fixes your problem.

**Comment by mitchellwrosen** [comment] 2015-09-02 05:44
Well, that was simple enough, and it did fix the problem. So, bigger picture, I don't really have a strong opinion about which package databases Setup.hs has. The comment in the source code about `-hide-all-packages` and explicitly listing packages seems reasonable.

**Comment by snoyberg** [comment] 2015-09-02 05:48
You interested in taking a crack at implementing that? I don't foresee any obstacles, especially since the list of available dependencies is already populated at this point in the build process.

**Comment by mitchellwrosen** [comment] 2015-09-02 05:51
Sure. Where is the list of available dependencies? =)

**Comment by snoyberg** [comment] 2015-09-02 06:00
Just walked out of the house so I can't show you the exact code. Look in
the getConfigCache. You should be able to refactor to have access to the
ConfigCache

**Comment by mitchellwrosen** [comment] 2015-09-02 07:06
Ok, here's a first attempt: https://github.com/commercialhaskell/stack/pull/899

**Comment by mgsloan** [comment] 2015-09-03 19:20
Yesterday, Duncan mentioned that cabal plans to have build dependencies for Setup.hs, like this: https://github.com/haskell/cabal/issues/948

It does seem like a reasonable idea to use the same set of packages as the package itself + Cabal.

**Comment by snoyberg** [comment] 2015-09-07 09:58
This resulted in a regression (#941), but let's follow up on that in the other issue. I'm going to close this as resolved due to #897.

**Closed by snoyberg** 2015-09-07 09:58 UTC
Labels: awaiting-pr

**Comment by asr** [comment] 2016-09-19 16:39
> I'm going to close this as resolved due to #897.

I guess you meant #899.

**Comment by snoyberg** [comment] 2016-09-19 16:44
So it would seem. Blast from the past :)

**Comment by asr** [comment] 2016-09-19 17:02
The present for me :-)
See [Error installing the suffle library with stack](http://stackoverflow.com/questions/39564607/error-installing-the-suffle-library-with-stack).

**Comment by snoyberg** [comment] 2016-09-19 17:21
What happens if you manually install the dependencies with `stack build
uuagc-cabal ...` first?

**Comment by asr** [comment] 2016-09-19 17:33
After installing `uuagc-cabal` in the shuffle directory I got the same error.

**Comment by snoyberg** [comment] 2016-09-19 19:11
I've added an answer at: http://stackoverflow.com/a/39579714/369198

**Comment by asr** [comment] 2016-09-19 20:09
Your answer above fixed the problem. Thanks!
