### ISSUE TITLE
stack's command-line argument parser is too picky

### ISSUE THREAD

**Issue by pharpend** [commercialhaskell/stack#718] opened 2015-08-05 05:13 UTC
```
$ stack --version
Version 0.1.2.7, Git revision 7befa5caad720cb8859a04efda3b304e13cbf8c9
```

Ideally, all of the following would produce the same result:

* `stack build -j 5 -fdev`
* `stack -j 5 build -fdev`
* `stack -fdev build -j 5`
* `stack build -j 5 --flag learnyou:dev`
* `stack build --flag learnyou:dev -j 5`

Stack's argument parser only accepts the last one. The order really shouldn't matter.

**Comment by snoyberg** [comment] 2015-08-05 06:14
I believe this is a dupe of #519.

**Closed** 2015-08-08 20:11 UTC
