### ISSUE TITLE
Missing reconfigure can lead to shadowed dependency bug

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#4768] opened 2019-04-23 16:30 UTC
I'm guessing this may be related to #4741, but I haven't investigated yet. Instead of giving a thorough description here, I'm going to push a commit including an integration test that triggers this bug. Opening the issue first so I can name it with the correct issue number.

**Comment by qrilka** [comment] 2019-05-15 12:59
@snoyberg it's not quite related to #4741 because the problem in 44d721 happens when you have a local module change, rebuild a package and then you try to build a package having a dependency depending on that rebuild package. In that case their is no missing dependency as the package was already rebuild. The problem is that we have the same package registered in the package database and also we have (or rather could have) the same config cache for that package. With updates in 370cd701 I was able to reproduce this problem with 1.9.3 so it's not a regression in Stack `master`.

**Comment by snoyberg** [comment] 2019-05-15 13:16
Since it's not a regression, I'm going to move this from the Stack 2 milestone over to P0.

**Comment by mpilgrem** [comment] 2024-04-01 18:41
I am closing this issue given the passage of time and because, looking at https://github.com/commercialhaskell/stack/commit/44d721e9d55855d36574ff1806351eccc408801f (which does not belong to any branch in the repository), I could not reproduce any error with Stack 2.15.5:
* `stack build a` rebuilds, because the source file has changed;
* `stack build c` rebuilds `b` and `c`, because `LibA` has changed and, then, `LibB` has changed.

**Closed by mpilgrem** 2024-04-01 18:41 UTC
