### ISSUE TITLE
build output could indicate more clearly where each package is coming from

### ISSUE THREAD

**Issue by simonmichael** [commercialhaskell/stack#2401] opened 2016-07-22 00:32 UTC
Moved from https://github.com/fpco/stackage-server/issues/185.

When stack build is asked to install a package that's not local or in a stackage snapshot, it can fetch it from upstream (Hackage). Even after reading docs and using stack for a while, I have found this [non-obvious/easy to forget](https://github.com/fpco/stackage-server/issues/184). The output of the build command could make this clearer.

Steps to reproduce:

`$ cd; stack install tabular`

(any package not already downloaded)

Actual:
```
Run from outside a project, using implicit global project config
Using resolver: lts-6.0 from implicit global project's config file: /Users/simon/.stack/global/stack.yaml
tabular-0.2.2.7: download
tabular-0.2.2.7: configure
tabular-0.2.2.7: build
tabular-0.2.2.7: copy/register
```

Expected:

I assumed this output meant the package was being fetched from the lts-6.0 snapshot. It would have been helpful to see eg 
```
...
tabular-0.2.2.7: download (from Hackage)
...
```

stack --version:
```
Version 1.1.2 x86_64 hpack-0.14.0
```

**Comment by mgsloan** [comment] 2016-07-26 03:14
Yup, this should definitely be addressed.  The output side is covered by this ticket - https://github.com/commercialhaskell/stack/issues/2155 .  Closing as a dupe of that, make sense?

**Closed by mgsloan** 2016-07-26 03:14 UTC
