### ISSUE TITLE
Stack doesn't correctly pass extra libraries to subcommands

### ISSUE THREAD

**Issue by martijnbastiaan** [commercialhaskell/stack#5662] opened 2021-12-31 12:11 UTC
### General summary/comments
Stack doesn't seem to pass extra libraries to subcommands correctly. I.e., the following cabal file includes a public library and a private one (`extra`):

```
cabal-version:       >=1.10
name:                import-issues
version:             0.1.0.0
author:              Martijn Bastiaan
maintainer:          martijn@hmbastiaan.nl
build-type:          Simple

library
  exposed-modules:     Library
  hs-source-dirs:      src
  build-depends:       base
  default-language:    Haskell2010

library extra
  exposed-modules:     LibraryExtra
  hs-source-dirs:      src
  build-depends:       base
  default-language:    Haskell2010
```

Both libraries are completely empty, their content isn't important. Additionally, I defined an executable:

```
executable import-issues
  main-is:             Main.hs
  hs-source-dirs:      src
  build-depends:       base, process, import-issues, extra
  default-language:    Haskell2010
```

which does:

```haskell
module Main where

import System.Process
import System.IO

main :: IO ()
main = do
  (Just stdin, _, _, ph) <- createProcess ((proc "ghci" []){std_in = CreatePipe})
  hPutStrLn stdin "import Library"
  hFlush stdin
  hPutStrLn stdin "import LibraryExtra"
  hFlush stdin
  hPutStrLn stdin ":q"
  hFlush stdin
  waitForProcess ph
  pure ()
```

I.e., it starts `ghci` and tries to do `import LibraryExtra`. This works with Cabal, but fails with Stack. Note that `import Library` succeeds for both.

### Steps to reproduce

```
git clone https://github.com/martijnbastiaan/import-issues.git
cd import-issues
stack run
```

### Expected

I expected a similar output to Cabal:

```
$ cabal run --write-ghc-environment-files=always
Up to date
GHCi, version 8.10.3: https://www.haskell.org/ghc/  :? for help
Loaded package environment from /home/martijn/Code/import-issues/.ghc.environment.x86_64-linux-8.10.3
Prelude> Prelude Library> Prelude Library LibraryExtra> Leaving GHCi.
```

### Actual

GHCi fails to load the extra module:

```
$ stack run
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
Prelude> Prelude Library> 
<no location info>: error:
    Could not load module ‘LibraryExtra’
    It is a member of the hidden package ‘import-issues-0.1.0.0’.
    You can run ‘:set -package import-issues’ to expose it.
    (Note: this unloads all the modules in the current scope.)
Prelude Library> Leaving GHCi.
```

Note that the hint, adding `:set -package import-issues`, does not work (nor should it).

### Stack version

```
$ stack --version
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

### Method of installation
GHCup

**Comment by philderbeast** [comment] 2022-08-03 00:45
If I change the cabal file to use the scoped sublibrary dependency syntax then stack complains:

```
> stack build
SubLibrary dependency is not supported, this will almost certainly fail
```

```diff
- cabal-version:       >=1.10
+ cabal-version:       3.0
  executable import-issues
   main-is:             Main.hs
   hs-source-dirs:      src
-  build-depends:       base, process, import-issues, extra
+  build-depends:       base, process, import-issues, import-issues:extra
   default-language:    Haskell2010
```

With this change `cabal build` works but `cabal repl` has trouble:

```
> cabal --version
cabal-install version 3.8.0.20220526
compiled using version 3.8.0.20220526 of the Cabal library
```

```
> cabal repl
Error: cabal: Cannot open a repl for multiple components at once. The target
'' refers to the package import-issues-0.1.0.0 which includes the libraries
extra and import-issues.

The reason for this limitation is that current versions of ghci do not support
loading multiple components as source. Load just one component and when you
make changes to a dependent component then quit and reload.
```

I can load either library in the `cabal repl` but not both at the same time.

```
> cabal repl import-issues
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - import-issues-0.1.0.0 (lib) (ephemeral targets)
Preprocessing library for import-issues-0.1.0.0..
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /Users/pdejoux/.ghci
[1 of 1] Compiling Library          ( src/Library.hs, interpreted )
Ok, one module loaded.
*Library> import LibraryExtra

<no location info>: error:
    Could not load module ‘LibraryExtra’
    It is a member of the hidden package ‘import-issues-0.1.0.0’.
    Perhaps you need to add ‘import-issues’ to the build-depends in your .cabal file.
```

```
> cabal repl extra
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - import-issues-0.1.0.0 (lib:extra) (ephemeral targets)
Preprocessing library 'extra' for import-issues-0.1.0.0..
...
[1 of 1] Compiling LibraryExtra     ( src/LibraryExtra.hs, interpreted )
Ok, one module loaded.
*LibraryExtra> import Library

<no location info>: error:
    Could not load module ‘Library’
    It is a member of the hidden package ‘import-issues-0.1.0.0’.
    Perhaps you need to add ‘import-issues’ to the build-depends in your .cabal file.
```

Trying `PackageImports`:

```
> cabal repl import-issues
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - import-issues-0.1.0.0 (lib) (ephemeral targets)
Preprocessing library for import-issues-0.1.0.0..
...
[1 of 1] Compiling Library          ( src/Library.hs, interpreted )
Ok, one module loaded.
*Library> :set -XPackageImports
*Library> import "import-issues:extra" LibraryExtra

<interactive>:1:8: error:
    Parse error: ‘import-issues:extra’
    Version number or non-alphanumeric character in package name
```

**Comment by mpilgrem** [comment] 2024-04-02 22:51
I am closing this issue given the passage of time and because I can not reproduce the problem with Stack 2.15.5.

**Closed by mpilgrem** 2024-04-02 22:51 UTC
