### ISSUE TITLE
AesonException: Invalid flag name

### ISSUE THREAD

**Issue by mrkkrp** [commercialhaskell/stack#3634] opened 2017-12-09 15:48 UTC
I wanted to try `brittany`, but stack said "no":

```
~/.stack $ stack install brittany-0.9.0.0 --resolver=nightly-2017-12-09
Downloaded nightly-2017-12-09 build plan.
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
~/.stack $ stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1
```

P.S. I'm forced to use 1.5.1, because 1.6.1 is not fully functional #3630.

**Comment by tfausak** [comment] 2017-12-09 17:34
https://github.com/hvr/cassava/pull/155 strikes again!

**Comment by lwm** [comment] 2017-12-09 17:48
Sorry you got hit by this @mrkkrp. As you seem to know, this has been fixed in 1.6.1 and an upgrade is the answer to this problem. Hopefully #3630 can be resolved soon (I left a comment!). I'm not sure we get an value from leaving this issue open and I'm inclined to close it.

**Comment by kadoban** [comment] 2017-12-09 19:31
Yeah, this is an unfortunate situation, but this particular bug has already been reported, found, fixed and released, so I don't think leaving this open is useful. Let's hope your other issue can be resolved quickly.

**Closed by kadoban** 2017-12-09 19:31 UTC

**Comment by giuliods** [comment] 2018-02-23 09:37
I've got the same problem this days with the 1.6.5 stack version. I lurked for other solution but are too old or not resolved. Considering i can't upgrade stack what i need to do:

    % stack exec -- yesod devel
    Downloading lts-10.6 build plan ...
    Downloaded lts-10.6 build plan.
    AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
    Type help for available commands. Press enter to force a rebuild.
    quit
    Yesod devel server. Enter 'quit' or hit Ctrl-C to quit.
    Application can be accessed at:
    http://localhost:3000
    https://localhost:3443
    If you wish to test https capabilities, you should set the following variable:
      export APPROOT=https://localhost:3443

    % stack --version
    Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0

**Comment by tfausak** [comment] 2018-02-23 12:16
Oh no, it's back! 

I was not able to reproduce this problem with Stack 1.6.5 and LTS 10.6. I am not very familiar with `yesod devel`, but I'm guessing it shells out to `stack`. It's possible that the path is pointing to a different, older version of Stack. A quick peek at [the code](https://github.com/yesodweb/yesod/blob/a3f130233bbf4e6bfebdb7bfd3d926c689b53fd7/yesod-bin/Devel.hs#L327) doesn't reveal anything obviously broken.

What does `stack exec -- stack --version` output?

**Comment by giuliods** [comment] 2018-02-23 14:14
Nevermind, I resolved removing and reinstalling stack, removing .stack folder. Sorry for any concerns

**Comment by mgsloan** [comment] 2018-02-23 20:25
:herb: :bug: strikes again!

**Comment by mgsloan** [comment] 2018-02-23 20:29
Glad the workaround was effective for you!

:herb: :bug:

**Comment by JamesMcMahon** [comment] 2018-10-03 01:53
Ubuntu 18.04 is using `1.5.1-1`, which may have been affected by this bug.
