### ISSUE TITLE
"stack --resolver nightly build pandoc" failed since hslua not in current Stackage Nightly yet

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/stack#2256] opened 2016-06-08 03:20 UTC
The summary is just an example.  I imagine the current behaviour is by design but...
Would it be possible to add an option to stack to make it try to find missing dependencies not in Stackage in Hackage?

**Comment by mgsloan** [comment] 2016-06-08 22:19
Agreed, this would be a good thing to support.  For now, just initialize a project and use `stack solver`.

Dupe of https://github.com/commercialhaskell/stack/issues/1693

**Closed by mgsloan** 2016-06-08 22:19 UTC

**Comment by juhp** [comment] 2016-06-12 12:05
Okay thanks, but I would prefer to avoid needing a project.

**Comment by mgsloan** [comment] 2016-06-12 23:35
Agreed, PRs for #1693 appreciated!  It should be pretty straightforward.
