### ISSUE TITLE
To use stack to compile and run _only_ the tests

### ISSUE THREAD

**Issue by tallen-imvu** [commercialhaskell/stack#2710] opened 2016-10-14 16:38 UTC
### I would like to be able to run something similar to `stack test --test-only`

When I run a `stack test` or a `stack test <package>:<test-suite>` then the output looks something like:

    package: configure (lib + exe + test)
    package: build (lib + exe + test)
    package: copy/register
    package: test (suite: tests)

And it ends up basically compiling all my changes twice: once for the exe or lib and a second time for the test.

What I would like is a command like `stack test --test-only` that would produce something like:

    package: configure (test)
    package: build (test)
    package: copy/register
    package: test (suite: tests)

**Comment by epsilonhalbe** [comment] 2016-10-14 22:06
maybe relevant for this issue

1. https://github.com/epsilonhalbe/stack-tests--tests-only-example I created a small repo to reproduce this problem
2. to answer [this](https://stackoverflow.com/questions/40028933/) question on stackoverflow

**Comment by mgsloan** [comment] 2016-10-16 01:57
Unfortunately, we currently have to build executables - https://github.com/commercialhaskell/stack/issues/1406 .  Marking this as a duplicate of that issue.

To reduce redundant compilation, have a library component for most of the source code.  Then the executables can be very lightweight to compile.

**Closed by mgsloan** 2016-10-16 01:57 UTC
Labels: resolution: duplicate
