### ISSUE TITLE
Stack build (Haskell) cannot find any module in the src directory.

### ISSUE THREAD

**Issue by KeesBleijenberg** [commercialhaskell/stack#4553] opened 2019-01-31 14:33 UTC
If I import module XX  in Main.hs from the src directory, I always get: Could not find module XX
I've purged .stack-work, but no luck. In Main.hs I import ProgSettings and I get the error message.
I tried to add build-depends in packages.yaml, but it didn't work. I always get: Ignoring unrecognized field $.library.build-depends.?
I'am using stack 1.9.3 on Ubuntu. Ghc version: 8.2.2 What can I do?

Kees

The directory structure:

```
-- app
      Main.hs
-- src
      ProgSettings.hs
      ... and more modules
```

packages.yaml:

```yaml
dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies :
    - text
    - megaparsec
    ....

executables:
  freeDB:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:  
    - text
    - async
    ....
    
tests:
  ---    
```

**Comment by mgsloan** [comment] 2019-01-31 22:57
The fix for this is probably to add `- my-library-name` to the `dependencies:` list of the executable.

Note that `source-dirs` is just `app` for the executable, and so imports will only resolve to modules in the `app` folder or modules from dependencies.

**Comment by KeesBleijenberg** [comment] 2019-02-01 08:12
Thank you for your reply.

I've tried your suggestion and I get:
Error: While constructing the build plan, the following exceptions were
encountered:

In the dependencies for freeDB-0.1.0.0:
    ProgSettings needed, but the stack configuration has no specified
                 version (no package with that name found, perhaps there is a
                 typo in a package's build-depends or an omission from the
                 stack.yaml packages list?)
needed since freeDB is a build target.

Some different approaches to resolving this:

  * Consider trying 'stack solver', which uses the cabal-install solver to
    attempt to find some working build configuration. This can be convenient
    when dealing with many complicated constraint errors, but results may be
    unpredictable.
    
I tried stack solver and my computer runs out of memory and locks up.

If I create a fresh freeDB2 stack project the package.yaml looks like this
...
library:
  source-dirs: src

executables:
  freeDB2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - freeDB2
.....
There is no Lib in dependencies of the executable and still this project compiles and the compiler finds Lib.hs

I added Lib2.hs to the scr directory and imported Lib2 in Main.hs. Now it compiles fine. Strange!
I've noticed this same behaviour on Windows. Sometimes stack can't find the modules in src and I can't figure out why.

**Comment by ketzacoatl** [comment] 2019-02-28 19:17
@mattaudesse can you reproduce the same behavior starting with one of the [stack project templates](https://github.com/commercialhaskell/stack-templates), such as `stack new my-test simple`? That would probably help identify the bug in stack as reproducible (as well as how to reproduce) and/or help you find the errors in your code.

**Comment by mattaudesse** [comment] 2019-03-01 23:56
@ketzacoatl I'm guessing you meant to at-mention @KeesBleijenberg instead of me but I haven't been able to reproduce this either.

**Comment by snoyberg** [comment] 2019-03-26 04:34
Closing due to lack of reproduction. There is insufficient information provided here to debug the problem, due to lack of complete `package.yaml` files.

**Closed by snoyberg** 2019-03-26 04:34 UTC
Labels: further investigation required, type: question
