### ISSUE TITLE
`stack ghci` fails to open a test target without first build

### ISSUE THREAD

**Issue by parsonsmatt** [commercialhaskell/stack#3943] opened 2018-03-24 17:55 UTC
### General summary/comments (optional)

`stack ghci` fails to open a test target if you haven't built the test target before.

### Steps to reproduce

I have created a repro repo with a `README.sh` that demonstrates the issue: https://github.com/parsonsmatt/stack-test-bug

### Expected

I expect that

```
$ stack ghci stack-test-bug:test:test
```

should recognize what needs to be built, build it, and work correctly.

### Actual

```bash
λ stack ghci stack-test-bug:test:test
stack-test-bug-0.0.0: configure (lib)
Configuring stack-test-bug-0.0.0...
stack-test-bug-0.0.0: initial-build-steps (lib)
Configuring GHCi with the following packages: stack-test-bug
Using main module: 1. Package `stack-test-bug' component test:test with main-is file: /home/matt/
Projects/stack-test-bug/test/Test.hs
GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help
<command line>: cannot satisfy -package stack-test-bug-0.0.0
    (use -v for more information)
```

### Stack version

```bash
λ stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mgsloan** [comment] 2018-03-28 07:17
Thanks for the report!  It's a duplicate of https://github.com/commercialhaskell/stack/issues/2790 , which is indeed a crappy bug.  Trickier than one might think to resolve, but certainly possible.  PR would be appreciated!

**Closed by mgsloan** 2018-03-28 07:17 UTC
