### ISSUE TITLE
Using "--flag *:someflagname" messes with dependencies' flags

### ISSUE THREAD

**Issue by brandon-leapyear** [commercialhaskell/stack#5410] opened 2020-10-06 21:01 UTC
### Steps to reproduce

Create the following files:
```yaml
# stack.yaml
resolver: lts-16.2
```
```yaml
# package.yaml
name: foo
version: 0.1
dependencies: [cassava]
library: {}
```
Running `stack build --only-dependencies` works as normal, but running `stack build --flag '*:somerandomflagname' --only-dependencies` will first show a warning
```
WARNING: Ignoring cassava's bounds on bytestring (>=0.9.2 && <0.10.4); using bytestring-0.10.10.0.
Reason: trusting snapshot over cabal file dependency information.
```
and then fail with the `cassava` build error that occurs due to bad dependency versions ([ref1](https://github.com/haskell-hvr/cassava/blob/master/src/Data/Csv/Conversion.hs#L25-L27), [ref2](https://github.com/haskell-hvr/cassava/blob/master/cassava.cabal#L111-L116))
```
cassava             > /private/var/folders/y2/_vwl0z8x7zn35z0c5663nfvm0000gn/T/stack-ab0bd21ee080725a/cassava-0.5.2.0/src/Data/Csv/Conversion.hs:26:3: error:
cassava             >      error: **INVARIANT BROKEN** Detected invalid combination of `text-short` and `bytestring` versions. Please verify the `pre-bytestring-0.10-4` flag-logic in the .cabal file wasn't elided.
cassava             >    |
cassava             > 26 | # error **INVARIANT BROKEN** Detected invalid combination of `text-short` and `bytestring` versions. Please verify the `pre-bytestring-0.10-4` flag-logic in the .cabal file wasn't elided.
cassava             >    |   ^
cassava             > # error **INVARIANT BROKEN** Detected invalid combination of `text-short` and `bytestring` versions. Please verify the `pre-bytestring-0.10-4` flag-logic in the .cabal file wasn't elided.
cassava             >   ^
```

### Expected

Using `--flag '*:asdf'` for a flag that doesn't exist in a package should not affect how that package is built.

### Actual

Running with `--verbose` showed that the flags passed to `cassava` are `-fasdfasdf -fbytestring--lt-0_10_4`, as opposed to `-fasdfasdf -f-bytestring--lt-0_10_4` when not passing `--flag '*:asdfasdf'`. I find it very unexpected that setting a flag would change how the `bytestring--lt-0_10_4` flag was passed.

### Stack version

```
$ stack --version
Version 2.3.3, Git revision cb44d51bed48b723a5deb08c3348c0b3ccfc437e x86_64 hpack-0.33.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository
* Via cabal-install
* An unofficial package repository (please specify which)
* Other (please specify)

**Comment by mpilgrem** [comment] 2024-05-05 19:33
I am going to close this issue because:

* what `flag *:[-]<flag_name>` does is now documented better https://github.com/commercialhaskell/stack/issues/6564
* (very soon) `flag *:[-]<flag_name>` will no longer be applied to packages that do not define `<flag_name>` https://github.com/commercialhaskell/stack/issues/6570 (essentially, a duplicate of this issue)

**Closed by mpilgrem** 2024-05-05 19:33 UTC
Labels: resolution: duplicate, type: enhancement, component: build
