### ISSUE TITLE
stack: out of memory (requested 2097152 bytes) on Alpine Linux

### ISSUE THREAD

**Issue by sumyuga** [commercialhaskell/stack#688] opened 2015-07-28 18:19 UTC
I've downloaded the binary file of stack and unzip on docker alpine image with glibc. I've installed all needed (perl make automake gcc gmp) and while I executable file is out of memory. ldd test is ok, but strace falls:
```
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=0, ptr=0}} ---
rt_sigreturn()                          = 0
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=0, ptr=0}} ---
rt_sigreturn()                          = 139938731157504
write(2, "stack: ", 7stack: )                  = 7
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=0, ptr=0}} ---
rt_sigreturn()                          = 139938741142048
write(2, "out of memory (requested 2097152"..., 39out of memory (requested 2097152 bytes)) = 39
write(2, "\n", 1
)                       = 1
exit_group(1)                           = ?
+++ exited with 1 +++
```
On debian:wheezy docker image it works fine

**Comment by manny-fp** [comment] 2015-07-30 06:20
Can you provide some more details on how to reproduce?  In particular, a precise list of commands you're running (including any `docker run` commands, custom Dockerfiles, etc.) and output of `stack --verbose` for your stack run would be helpful.  See [CONTRIBUTING.md](https://github.com/commercialhaskell/stack/blob/master/CONTRIBUTING.md) for general information about reporting bugs.

**Comment by sumyuga** [comment] 2015-07-30 06:52
Here is my Dockerfile with all needed packages:
```
FROM alpine:latest
MAINTAINER Sum Yuga <sumyuga@gmail.com>

ENV ALPINE_GLIBC_URL="https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/6/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/" \
    GLIBC_PKG="glibc-2.21-r2.apk" \
    GLIBC_BIN_PKG="glibc-bin-2.21-r2.apk" \
    STACK_VERSION=0.1.2.0

RUN \
    apk add --update -t deps ca-certificates \
    && apk add perl make automake gcc gmp-dev \
# Glibc
    && cd /tmp \
    && wget ${ALPINE_GLIBC_URL}${GLIBC_PKG} ${ALPINE_GLIBC_URL}${GLIBC_BIN_PKG} \
    && apk add --allow-untrusted ${GLIBC_PKG} ${GLIBC_BIN_PKG} \
    && /usr/glibc/usr/bin/ldconfig /lib /usr/glibc/usr/lib \
    && echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf \
# Stack
    && wget -O - https://github.com/commercialhaskell/stack/releases/download/v${STACK_VERSION}/stack-${STACK_VERSION}-x86_64-linux.gz | gunzip -c > /usr/local/bin/stack \
    && chmod +x /usr/local/bin/stack \
    && apk del --purge deps \
    && rm /tmp/* /var/cache/apk/*
```
I've also tried to install without glibc and result is the same.
I build this dockerfile with this command:
```
docker build -t alpine-stack -f ~/.dockerfile/alpine-stack ~/.dockerfile
```
After building this dockerfile I run:
```
docker run --rm -ti alpine-stack /bin/sh
```
The fact is I can't run any option with running stack command – it always falls with "out of memory"

**Comment by manny-fp** [comment] 2015-07-30 13:31
@dysinger: I think you've done some work with minimal Docker images; do you recall running into anything like this?

**Comment by sumyuga** [comment] 2015-07-30 13:39
This minimal image is fully working Linux and I can recall anything I install and run.
You can build it and make sure yourself.
Alpine is very popular minimal Linux image on docker hub.

**Comment by phadej** [comment] 2015-07-30 17:08
Wild guess: probably related to `musl libc`.

**Comment by sumyuga** [comment] 2015-07-30 17:14
@phadej If you look at my dockerfile above you notice that I have preinstalled glibc just in case

**Comment by dysinger** [comment] 2015-07-31 00:37
@manny-fp I've only ever seen problems when my host was running out of memory

**Comment by snoyberg** [comment] 2015-07-31 04:59
@sumyuga Please try building the stack executable from the source with Alpine and see if that changes the behavior.

**Comment by snoyberg** [comment] 2015-08-09 02:40
Closing due to lack of input from reporter. However, I'm fairly certain this is a GHC bug I already filed, and which has already been fixed:

https://ghc.haskell.org/trac/ghc/ticket/10298

If that's the case:

* You can fix the problem short term by adding the missing shared libraries (and can determine what they are by `strace`ing the executable)
* Once stack is built with a new enough version of GHC, this problem will disappear

**Closed by snoyberg** 2015-08-09 02:40 UTC

**Comment by sumyuga** [comment] 2015-08-10 20:36
@snoyberg I have not missing shared libs at all. Strace shows all libs are ok. I couldn't build the stack because I have not any ghc installed to make build. I just want to wget the archive, unzip and run.

**Comment by snoyberg** [comment] 2015-08-11 02:33
Can you include the full strace output (as a Gist)?

**Comment by ketzacoatl** [comment] 2015-12-24 16:39
I copy/pasted @sumyuga's original list of steps to reproduce, but using the most recent release of stack, and I found the same OOM results:

```
# docker run --rm -ti stack-test sh
/ # stack --version
stack: out of memory (requested 1048576 bytes)
```

I believe the reasons for this are related to alpine's use of a micro libc, which is otherwise not _exactly_ the same as glibc.. but there may be a set of reasons similar to this. Fortunately, @mitchty has already slayed many of the dragons down here - the result of which is here: https://github.com/mitchty/alpine-linux-ghc-bootstrap.

This even includes the latest version of stack, and works out of the box: 

```
# docker run --rm -i -t mitchty/alpine-ghc:latest
bash-4.3# stack --version
Version 0.1.10.1, Git revision 13925b3651ff86ea00c3864814eb83e0fb0862b3 (dirty) x86_64
```

Also, if we look closely at @mitchty's build process, we'll find that the stack release binary is used directly: https://github.com/mitchty/alpine-linux-ghc-bootstrap/blob/master/stack/APKBUILD

Thus.. this confirms for us, Stack works fine on Alpine when the right build process is used (for the Alpine environment, not Stack).

It probably does no use to re-open this ticket, but it probably makes sense to review @mitchty's work a little closer, and figure out how to better support Stack on alpine. If Stack wishes to keep pace with the eb and flow of the ops world, solid support for Alpine is a good bet to hedge on.

**Comment by mitchty** [comment] 2015-12-24 18:35
So I'd not expect stack when compiled against glibc to do a whole lot on alpine linux. Running things like the jvm get to be a fun proposition there. Or anything linked via/to the glibc dynamic linker really.

But building a version of stack on musl libc shouldn't be too hard, I did a test building stack as a fully static binary and it seemed to work fine on any os/libc thereafter. Did this back in the 1.3.N ish times so not sure it still applies or not. In any case I ran the binary on ubuntu to install ghc and didn't hit any hiccoughs. Couldn't think of a linux distribution that had uclibc as its libc or I'd have tested there as well.

A side note, supporting alpine linux would probably also mean sorting out a ghc that will work there as well. None of the ghc bindists will technically run on alpine linux. I also gave up porting the 7.8 series due to weird bugs I found but could be convinced with enough beer to try again.

Should be able to just also use the docker image that uses the apk build @ketzacoatl noted to generate a bindist. Ping me if you've any issues and good luck!
https://hub.docker.com/r/mitchty/alpine-ghc/

**Comment by ketzacoatl** [comment] 2015-12-24 18:59
Thanks for all your hard work on this @mitchty! I will sync up with @snoyberg and others to see how the group would like to support Alpine, and what this would look like. I'll CC you on any new issues created, if you are interested in tracking that development.

**Comment by mitchty** [comment] 2015-12-26 12:14
Sounds good. Just to note, there are some huge gotchas to supporting alpine linux relating to things like pic/pie related assembly. It is a bit of a mess but not insurmountable. Took me a while to get ghc ported so figure I can offer up any advice to prevent others from the timesink.

**Comment by ketzacoatl** [comment] 2016-02-06 13:46
> Incidentay, we have hired Natanael Copa, the awesome creator of Alpine Linux and are in the process of switching the Docker official image library from ubuntu to Alpine. You can help us with pull requests to https://github.com/docker-library if you want :)

This is Solomon (from docker), from https://news.ycombinator.com/item?id=11000827.

**Comment by borsboom** [comment] 2016-02-06 23:13
That's excellent news.  They're going to have fun with the official Haskell images!
