### ISSUE TITLE
Ignoring Cabal's bounds on containers (>=0.4.2.1 && <0.6); using containers-0.6.0.1.

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/stack#5046] opened 2019-10-01 08:06 UTC
### General summary/comments (optional)
In a system I have trouble building for lts-12.

### Steps to reproduce
`stack --resolver lts-12 build` for most packages (using my F31 instance/container).

### Expected
Builds to work

### Actual
```
stack --resolver lts-12 --stack-yaml stack-lts12.yaml build
Selected resolver: lts-12.26
WARNING: Ignoring Cabal's bounds on containers (>=0.4.2.1 && <0.6); using containers-0.6.0.1.
Reason: trusting snapshot over cabal file dependency information.
WARNING: Ignoring stm's bounds on base (>=4.3 && <4.12); using base-4.12.0.0.
Reason: trusting snapshot over cabal file dependency information.
Cabal            > configure
Cabal            > Configuring Cabal-2.2.0.1...
Cabal            > build
aeson            > configure
Cabal            > Preprocessing library for Cabal-2.2.0.1..
Cabal            > Building library for Cabal-2.2.0.1..
Cabal            > [  1 of 221] Compiling Distribution.Compat.Binary
aeson            > Configuring aeson-1.3.1.1...
Cabal            > [  2 of 221] Compiling Distribution.Compat.Directory
Cabal            > [  3 of 221] Compiling Distribution.Compat.Exception
Cabal            > [  4 of 221] Compiling Distribution.Compat.Internal.TempFile
aeson            > build
stm              > configure
aeson            > Preprocessing library for aeson-1.3.1.1..
aeson            > Building library for aeson-1.3.1.1..
Cabal            > [  5 of 221] Compiling Distribution.Compat.Map.Strict
:
```
Note the warnings/issue are most likely not reproducible: in another instance (container) using Fedora 30 it runs okay (even with the same home dir mounted!!).
(I think this problem didn't happen with stack-1.9.)

Verbose output in this [Gist](https://gist.github.com/juhp/63755abf649eb6ce006126c781d7cccf).

### Stack version

```
Version 2.1.3.1 x86_64
Compiled with:
- Cabal-2.4.1.0
```

See the [Gist](https://gist.github.com/juhp/63755abf649eb6ce006126c781d7cccf) for full output

### Method of installation
* Via cabal-install
* An unofficial package repository: https://copr.fedorainfracloud.org/coprs/petersen/stack2/

### Summary
- Why is stack behaving in this way: ie why does it chose to rebuild Cabal?
- Is there an easy way I can clean my lts-12 caches?  Without wiping all the rest? ie just for lts-12.

**Comment by qrilka** [comment] 2019-10-01 08:35
@juhp the log you show is very suspicious - lts-12.26 doesn't contain `containers-0.6.0.1` and `base-4.12.0.0` comes with GHC-8.6.x i.e. LTS-13
Could it be that your `stack-lts12.yaml` uses system GHC for example? Could share the contents of that file?
BTW what is the point of `--resolver lts-12` if you use lts-specific Stack file?
Regarding not building Cabal there is trick of using `drop-packages` so Cabal shipped with GHC will get used and not the one from a snapshot.
As for the reason for Cabal rebuild - two main reasons for that are: 1) custom-setup 2) dependency package depending on Cabal

**Comment by juhp** [comment] 2019-10-01 10:04
Thanks, Kirill

> @juhp the log you show is very suspicious - lts-12.26 doesn't contain `containers-0.6.0.1` and `base-4.12.0.0` comes with GHC-8.6.x i.e. LTS-13

I agree completely

> Could it be that your `stack-lts12.yaml` uses system GHC for example? Could share the contents of that file?

This is `stack-lts12.yaml`:
```
resolver: lts-12.26
packages:
- .
- simple-cabal
extra-deps:
- simple-cmd-0.2.0.1
- simple-cmd-args-0.1.3
```

> BTW what is the point of `--resolver lts-12` if you use lts-specific Stack file?

Not so much - but for some other LTS versions I share the yaml file.
Anyway I don't think this affects my problem.

> Regarding not building Cabal there is trick of using `drop-packages` so Cabal shipped with GHC will get used and not the one from a snapshot.

Yeah but in this case it is the same Cabal version.

> As for the reason for Cabal rebuild - two main reasons for that are: 1) custom-setup 2) dependency package depending on Cabal

It feels like something (config) is broken locally... however:

The only significant difference between the two containers and stack builds is the version of ghc (8.6.5 vs 8.4.4): maybe I should post `stack --version` for both.

**Comment by qrilka** [comment] 2019-10-01 10:12
Could you explain the last sentence? How do you use 8.6.5 with LTS-12?
BTW regarding Cabal versions - there is a difference between "global" packages (in terms of Stack, in GHC they seem to be boot package) and snapshot packages, disregarding package versions - Stack doesn't recompile packages shipped with GHC as it even couldn't - e.g. Hackage doesn't contain all of those and sometimes GHC ships with some intermediate package version.

**Comment by juhp** [comment] 2019-10-01 10:27
> Could you explain the last sentence? How do you use 8.6.5 with LTS-12?

One container has system ghc 8.6.5 and stack built with 8.6.5, and the other container with 8.4.4. 
Maybe the significant thing is the version of ghc that stack was built with?

**Comment by qrilka** [comment] 2019-10-01 12:08
GHC version that Stack was built with shouldn't influence the build at all, i.e. GHC that you use should be determined by your `stack.yaml` and/or `~/.stack/config.yaml` and CLI flags if you choose some. The log looks like somehow you use system GHC and not 8.4.4 from the LTS-12 snapshot. The only reason I see for that is `system-ghc: true` in `~/.stack/config.yaml`.
Is it possible to create e.g. a Docker image so I could reproduce your problem locally?

**Comment by mpilgrem** [comment] 2024-03-11 23:04
I am closing this issue given the passage of time.

**Closed by mpilgrem** 2024-03-11 23:04 UTC
