### ISSUE TITLE
stack ghci error after building ekmett's algebra package

### ISSUE THREAD

**Issue by danielbarter** [commercialhaskell/stack#1282] opened 2015-11-04 02:48 UTC
I cloned https://github.com/ekmett/algebra, ran stack init, stack setup and stack build with no problems. When I try and run stack ghci, i get the following error:

```
<command-line>:9:0: 
fatal error: dist/build/autogen/cabal_macros.h: No such file or directory 
compilation terminated. 
phase `C pre-processor' failed (exitcode = 1)
```
I have searched through some of the pervious issues and have noticed people with similar looking issues, but I was not able to convert any of the responses into a solution.

**Comment by mgsloan** [comment] 2015-11-04 05:33
Hmm, I can't reproduce.  What resolved did `stack init` decide on?  It used `lts-2.22` for me, and `stack ghci` worked fine.

A number of fixes to ghci support have landed since the last release.  Does `stack upgrade --git` to use the development version fix this?

**Comment by danielbarter** [comment] 2015-11-04 22:11
Thank you for the feedback! I did not try updating stack, so i suspect what you are describing should work. My computer is being annoying right now, so I can't test what you have said, but I should be able to test it tonight

**Comment by danielbarter** [comment] 2015-11-06 04:05
OK i retried everything again in a fresh folder after a stack upgrade --git and I am still getting the same error. Sorry it took so long for me to reply.

**Comment by danielbarter** [comment] 2015-11-06 23:27
I made a docker container inside which the bug can be reproduced:
https://github.com/danielbarter/haskelldocker.git
after you are inside, just stack init, setup and build. then run stack ghci.

**Comment by mgsloan** [comment] 2015-11-17 06:42
Thanks for the repro, it does indeed reproduce for me.

Are you 100% sure it's using the upgraded stack version after doing `stack upgrade --git`?  Maybe `.local/bin` isn't on your PATH?  I'd try, but I no longer have the setup docker container, and it takes a long time to get it all setup..

**Comment by danielbarter** [comment] 2015-11-17 22:52
.local/bin was not on PATH but I added it and the error still happens.

**Comment by mgsloan** [comment] 2015-11-17 23:50
Hmm, and `stack --version` says the right thing (0.1.7)?

**Comment by danielbarter** [comment] 2015-11-18 00:09
`stack --version` says 

```
Version 0.1.6.0, Git revision e22271f5ce9afa2cb5be3bad9cafa392c623f85c (2313 commits) x86_64
```

after running `stack upgrade --git`

**Comment by mgsloan** [comment] 2015-11-18 02:47
Ah, well then that's the problem!  Maybe you need to add `~/.local/bin` to your path?  Sorry for not being more precise before.  Where does it install stack when upgrading?

I've opened up an issue about making the warnings clearer here: https://github.com/commercialhaskell/stack/issues/1362

**Comment by danielbarter** [comment] 2015-11-18 12:57
~/.local/bin is on my path. 

Maybe the problem is that stack upgrade is being run as a user instead of root? I'll test.

**Comment by danielbarter** [comment] 2015-11-18 13:38
OK, the problem is that after a stack upgrade, the upgraded version is not being used. 

which stack returns `/usr/bin/stack`
the upgraded version is located at `/root/.local/bin`

**Comment by danielbarter** [comment] 2015-11-19 23:36
the bug still happens with Version 0.1.7.0 of stack. 

Sorry about the confusion above. I was not used to things being installed in ~/.local/bin

**Comment by mgsloan** [comment] 2015-11-20 00:19
That's really strange, I have no idea what could cause this behavior difference.

**Comment by mgsloan** [comment] 2015-12-03 04:44
How about with latest development stack?  I changed how the `cabal_macros.h` stuff works.  Not something that I'd expect to really make a difference here, but perhaps!

**Comment by danielbarter** [comment] 2015-12-03 13:48
something still goes wrong, but in 0.1.9.0 there is more error!
```
<no location info>:
    Could not find module ‘Numeric.Additive.Class’
    It is a member of the hidden package ‘algebra-4.2’.
```

**Comment by mgsloan** [comment] 2016-05-15 01:55
`stack init` + `stack ghci` works fine for me on the algebra package, with current stack.  Closing as need repro.

**Closed by mgsloan** 2016-05-15 01:55 UTC
Labels: component: ghci, type: bug
