### ISSUE TITLE
stack build (on the stack project itself) cache invalidated after a stack install

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/stack#2353] opened 2016-07-08 10:09 UTC
Pinging @mgsloan. @snoyberg suspects this may be due to the `store` serialization we added recently. It seems like perhaps the git hash for the stack binary is causing such invalidation.

**Steps to reproduce**

```
bash-3.2$ stack build
bash-3.2$ stack install
Copying from /Users/chris/Work/stack/.stack-work/install/x86_64-osx/lts-6.0/7.10.3/bin/stack to /Users/chris/.local/bin/stack

Copied executables to /Users/chris/.local/bin:
- stack
bash-3.2$ stack build
Populated index cache.
Did not find .cabal file for kansas-comet-0.4 with Git SHA of be4690cfa4a780f71d05182fe5c69bb4ae635bf7
Did not find .cabal file for blank-canvas-0.6 with Git SHA of 1ab8537279ad2dd4cf25f76527633d47e5b16a94
stack-1.1.3: unregistering (missing dependencies: store)
store-0.1.0.1: unregistering (missing dependencies: th-lift-instances, th-orphans, th-utilities)
th-lift-instances-0.1.7: unregistering (old configure information not found)
th-orphans-0.13.1: unregistering (missing dependencies: th-lift-instances)
th-utilities-0.1.1.0: unregistering (missing dependencies: th-orphans)
th-lift-instances-0.1.7: configure
Progress: 0/5  c cuser interrupt
```

**Comment by sjakobi** [comment] 2016-07-08 16:53
Yes I hope this gets fixed soon.

Closing as a duplicate of https://github.com/commercialhaskell/stack/issues/2296.

**Closed** 2016-07-08 16:54 UTC
Labels: type: bug
