### ISSUE TITLE
Update Copyright year in LICENSE

### ISSUE THREAD

**Issue by daniel-j-h** [commercialhaskell/stack#1730] opened 2016-02-03 00:56 UTC
It seems like a new project's `LICENSE` file still contains the year 2015:

    $ stack new myproj
    $ grep Copyright LICENSE
    Copyright My Name (c) 2015

Here's the version information, running on Ubuntu 15.04, latest in repository:

    $ stack --version
    Version 1.0.2, Git revision fa09a980d8bb3df88b2a9193cd9bf84cc6c419b3 (3084 commits) x86_64

**Comment by lwm** [comment] 2016-02-03 07:25
That is because the [new-template](https://github.com/commercialhaskell/stack-templates/blob/336d2fce25e904b61b21f8960f0955aef7aab55f/new-template.hsfiles#L69) file over at [stack-templates](https://github.com/commercialhaskell/stack-templates/tree/336d2fce25e904b61b21f8960f0955aef7aab55f) hasn't been updated. Not related to stack repo, so probably best to close here and make a PR over at the other repo, or open an issue.

**Comment by mgsloan** [comment] 2016-02-03 07:32
Good point, but this is a dupe of https://github.com/commercialhaskell/stack-templates/issues/28

**Closed by mgsloan** 2016-02-03 07:32 UTC
