### ISSUE TITLE
Using --haddock and --coverage together fails with “Failed to find package key for <package>”

### ISSUE THREAD

**Issue by wleslie** [commercialhaskell/stack#4838] opened 2019-05-25 18:46 UTC
### Summary

With `stack build --haddock --test --coverage`, the tests are executed, but the coverage information is never printed. Instead, the error message is “Failed to find package key for template-0.1.0.0”. The generated HTML coverage report contains only this error message.

However, `stack build --test --coverage` correctly prints coverage information and produces the HTML report.

### Steps to reproduce

* A complete repro is included in https://gist.github.com/wleslie/bf60da3153b992c061a99cf219062b2d#file-package-yaml
  * stack.yaml contains only `resolver: lts-13.23`.
  * The test package consists of a library and a test suite. The test suite depends on the library. The only other dependency is `base`.
* Started with a clean build: `rm -rf .stack-work`
* Run `stack -v build --haddock --test --coverage`.

### Expected

* The command output should include coverage information: X% expressions used, etc.
* The HTML coverage report contains the same coverage information.

Note: You get the expected behavior if repeat the repro steps, omitting the `--haddock` flag.

### Actual

* Instead of coverage information, the command prints “Failed to find package key for template-0.1.0.0”
* The HTML coverage report consists solely of the same error message.

https://gist.github.com/wleslie/bf60da3153b992c061a99cf219062b2d#file-build-diff contains a diff of the build output with/without `--haddock`. (The build output was post-processed to remove timestamps and other irrelevant differences.)

### Workaround

Run haddock and coverage as separate commands: `stack build --haddock && stack build --test --coverage`. (The order of commands doesn’t seem to matter.)

### Stack version

```
$ stack --version | head
1.9.3 x86_64
Compiled with:
- Cabal-2.4.0.1
- Glob-0.9.3
- HUnit-1.6.0.0
- QuickCheck-2.11.3
- StateVar-1.1.1.1
- aeson-1.3.1.1
- aeson-compat-0.3.9
- annotated-wl-pprint-0.7.0
```

### Method of installation

Homebrew on macOS 10.12.6.
```
haskell-stack: stable 1.9.3 (bottled), HEAD
The Haskell Tool Stack
https://haskellstack.org/
/usr/local/Cellar/haskell-stack/1.9.3 (6 files, 38.5MB) *
  Poured from bottle on 2018-12-31 at 10:14:16
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/haskell-stack.rb
```

**Comment by dogonthehorizon** [comment] 2019-08-10 16:01
I can confirm the same behavior with the following information:
- **Stack Version:** `Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1`
- **Stackage Version:** `lts-13.26`
- **Operating System:** Arch-Linux
- **Repository:** [repo](https://github.com/dogonthehorizon/togglemon)

One difference between OP and myself is the project I am building contains multiple modules. I observe this behavior whether I am building all project modules or a single module.

The stated workarounds _do_ work for me, though it's not compatible with `--file-watch` unless I remove either haddock or coverage.

**Comment by mpilgrem** [comment] 2024-04-01 19:36
I am going to close this issue given the passage of time and because, using Stack's own repository as a test, `stack build --haddock --test --coverage` works as expected - generating Haddock documentation, running the test suite and generating a coverage report.

**Closed by mpilgrem** 2024-04-01 19:36 UTC
