### ISSUE TITLE
Failure to build filepath library

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#5025] opened 2019-09-05 00:22 UTC
Using stack-2.1.3 x86_64 on Windows.

### Steps to reproduce

1. Checkout filepath `git clone https://github.com/haskell/filepath.git`
2. Run `stack init --resolver=nightly-2019-04-24 --ignore-subdirs --force` to create a simple `stack.yaml` file.
3. Run `stack test`

### Expected

I expected it to run successfully, and indeed it did 4 months ago, using an older stack but the same resolver. See the trace at https://ci.appveyor.com/project/ndmitchell/filepath/builds/24067399.

### Actual

```
C:\Neil\filepath>stack test

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for random-1.1:
    time needed, but the stack configuration has no specified version  (latest matching version is 1.9.3)
needed due to filepath-1.4.2.1 -> random-1.1

In the dependencies for tf-random-0.5:
    time needed, but the stack configuration has no specified version  (latest matching version is 1.9.3)
needed due to filepath-1.4.2.1 -> tf-random-0.5

Some different approaches to resolving this:

  * Recommended action: try adding the following to your extra-deps in C:\Neil\filepath\stack.yaml:

- time-1.9.3@sha256:8f1b5448722a12a952248b356c9eb366e351226543d9086a2da71270522d5f45,5679

Plan construction failed.
```

Note that adding the time extra-deps does work, as does adding the `time` that is in the stackage snapshot. The problem only occurs when `filepath` is the package name, so I guess that is messing with its dependencies some way?

### Stack version

```
$ stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
```

Installed via `stack upgrade`.

Tracked at https://github.com/haskell/filepath/issues/72 as well.

**Comment by qrilka** [comment] 2019-09-16 20:52
@ndmitchell I think this problem could be related to GHC boot packages pruning added in #4547. Unfortunately I'm not sure if I will have time to have a close look into the details of it soon.

**Comment by qrilka** [comment] 2019-09-17 21:23
I couldn't reproduce it using Linux unfortunately and that raises some doubts in my hypothesis above

**Comment by qrilka** [comment] 2019-09-20 06:19
@ndmitchell could you run this with verbose logging?

**Comment by ndmitchell** [comment] 2019-09-20 09:44
@qrilka - the output of `stack test --verbose --color=never` is at https://gist.github.com/ndmitchell/3b0ac88c49ac1233efb7d94bfb1527c6

**Comment by qrilka** [comment] 2019-09-30 21:00
Sorry for being late with a reply. It looks like the main problem here comes from a dependency cycle through the `Win32` package and probably new Stack is theoretically more correct here but as we still don't have component-based builds in Stack we get this failure here. But that's just a rough understanding, I need to find some more time to analyze this (and without Windows at hand it's a bit more complicated)

**Comment by mpilgrem** [comment] 2024-03-17 19:26
I am closing given the passage of time and because I can build the current version of `filepath` (1.5.2.0) with the current version of Stack and snapshot:
~~~yaml
snapshot: lts-22.13
extra-deps:
- directory-1.3.8.2
- process-1.6.18.0
- time-1.12.2
- Win32-2.14.0.0
flags:
 Win32:
   os-string: true
 directory:
   os-string: true
~~~

**Closed by mpilgrem** 2024-03-17 19:26 UTC
