### ISSUE TITLE
Documentation in PDF format is outdated

### ISSUE THREAD

**Issue by helderman** [commercialhaskell/stack#4279] opened 2018-09-02 11:29 UTC
### General summary/comments

Documentation appears to be not available in PDF format. Normally, Read the Docs automatically generate a complete PDF document when building. The navigation bar in the documentation links to the PDF. This is explained here:
https://stackoverflow.com/questions/50425740/how-to-find-the-pdf-version-of-a-read-the-docs-project

On readthedocs.org, there is a project named 'stack' where PDFs can be found (just click button 'downloads'):
https://readthedocs.org/projects/stack/

However, the 'stable' PDF seems outdated (timestamp 2015; changelog stops at 0.1.8.0), and the 'latest' PDF is as good as empty.

Is there a way to have this fixed? If not, is it possible for people to pull stack and generate the PDF themselves? If so, how?

Disclaimer: I am submitting this issue in an attempt to answer this stackoverflow question:
https://stackoverflow.com/questions/52130181/how-to-download-the-docs-as-pdf

### Steps to reproduce

1. Navigate to https://docs.haskellstack.org/
2. At the bottom left of the page, there is a label 'Read the Docs'. Notice the version indicator is missing.
3. Click the label 'Read the Docs'.

### Expected

A panel should open, showing available versions and hyperlinks to possible downloads (e.g. PDF, HTML, ePub). Versioning should be shown, both when the panel is collapsed (just a small indicator) and when the panel is expanded.

For screenshots of a regular RtD instance, see:
https://stackoverflow.com/questions/50425740/how-to-find-the-pdf-version-of-a-read-the-docs-project

### Actual

No PDF document. I tried crafting the URL in an attempt to find the PDF, but it seems it is just not there.

No version info. Panel seems to be opening ('Read the Docs' label is moving up a bit), but it is blank. This is not a problem, but it may be related to the missing PDF, that's why I am mentioning it.

### Stack version

This involves stack's own website, so this is beyond my control. Version info is not shown, as explained above. Was versioning completely abandoned on docs.haskellstack.org? Is that a configuration setting, or has the RtD software been modded specifically for stack?

### Method of installation

Irrelevant; this is about RtD, not stack.

**Comment by dbaynard** [comment] 2018-09-02 13:09
Duplicate of #4276

**Closed by dbaynard** 2018-09-02 13:09 UTC
