### ISSUE TITLE
stack build - The same package name is used in multiple local packages

### ISSUE THREAD

**Issue by razvan-panda** [commercialhaskell/stack#5009] opened 2019-08-18 20:07 UTC
### Steps to reproduce

For example:
* git clone https://github.com/razvan-panda/postgresql-simple-migration-patches.git
* checkout commit: a6d59b4ba4d9c737f84b57659f23318b682d394b
* run `stack build --verbose`

### Expected

Build to succeed.

### Actual

```
[neo@nixos:~/Forks/postgresql-simple-migration-patches]$ stack build --verbose
2.1.3.1 x86_64 hpack-0.31.2
2019-08-18 21:05:51.281381: [debug] Checking for project config at: /home/neo/Forks/postgresql-simple-migration-patches/stack.yaml
2019-08-18 21:05:51.281704: [debug] Loading project config file stack.yaml
2019-08-18 21:05:51.327256: [debug] SELECT COUNT(*) FROM "last_performed" WHERE ("action"=?) AND ("timestamp">=?); [PersistInt64 1,PersistUTCTime 2019-08-17 20:05:51.327002653 UTC]
2019-08-18 21:05:51.331103: [debug] Using package location completions from a lock file
2019-08-18 21:05:51.759491: [error] The same package name is used in multiple local packages

postgresql-simple-migration used in:
- PLImmutable (PLIRepo Git repo at https://github.com/razvan-panda/postgresql-simple-migration.git, commit 9cd59706b5a9c382d010c479725d0f67f6e574c1 (PackageMetadata {pmIdent = PackageIdentifier {pkgName = PackageName "postgresql-simple-migration", pkgVersion = mkVersion [0,1,14,0]}, pmTreeKey = TreeKey d9a9e1b7099dce2d829f3ee09f0e9d0cca510509ce02d0c52055e7b0ba4abf83,959, pmCabal = f24784ea62a2a147de860f3a45412842a72f0ec4914f7ab18c14b2bf4ac1aa75,3877}))
- PLMutable (ResolvedPath {resolvedRelative = RelFilePath ".", resolvedAbsolute = "/home/neo/Forks/postgresql-simple-migration-patches/"})

```

### Stack version

```
$ stack --version
2.1.3.1 x86_64 hpack-0.31.2
```

### Method of installation

Installed via Nix

**Comment by mattaudesse** [comment] 2019-08-18 21:27
Unless I'm missing something this is the expected behavior (due to [this commit](https://github.com/razvan-panda/postgresql-simple-migration-patches/commit/a6d59b4ba4d9c737f84b57659f23318b682d394b#diff-fafd0cdcd559a7b124cc61c29413fb54R5)).

```diff
+ extra-deps:
+  - git: https://github.com/razvan-panda/postgresql-simple-migration.git
+    commit: 9cd59706b5a9c382d010c479725d0f67f6e574c1
```

Since both repos' package definitions share a name I'd expect to see the collision you're reporting.

Removing that `extra-deps` stanza from your `stack.yaml` should help, but you probably put it there for some reason I'm just not seeing... :-)

Was that intentional?

**Comment by razvan-panda** [comment] 2019-08-18 21:44
@mattaudesse Ah yea. I think I tried fixing another issue and made that change, which put me into this situation. Removing it gives the issue described in this ticket: https://github.com/commercialhaskell/stack/issues/5008

**Comment by mattaudesse** [comment] 2019-08-18 23:36
Cool! I'm going to go ahead and close this issue then - hopefully we can whittle down the rest soon.

Thanks @razvan-panda.

**Closed by mattaudesse** 2019-08-18 23:36 UTC
