### ISSUE TITLE
no-run-tests in stack.yaml does nothing

### ISSUE THREAD

**Issue by pacak** [commercialhaskell/stack#4044] opened 2018-05-28 06:15 UTC
https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md suggests that it's possible to disable running tests after building them however 

having
```
build:
  test-arguments:
    no-run-tests: true
```
or 

```
build:
  test-arguments:
    no-run-tests: false
```

inside stack.yaml does nothing: `stack build foo:test` results in compiling test executable (expected) and running it (unexpected).

**Comment by mattaudesse** [comment] 2018-05-28 19:15
I've experimented with this a bit using the `stack` repo itself as a test subject and I agree it seems like the expected behavior is ignored right now.

I'll see if I can pin down what's (not) happening and why.

Thanks for the bug report @pacak.

**Comment by snoyberg** [comment] 2019-04-02 03:16
This appears to be working on `master` and 1.9.3, I cannot reproduce. I'm adding an integration test to ensure this continues to work and closing. If you have a repro against Stack master or 1.9.3, please comment.

**Closed** 2019-04-02 03:16 UTC
Labels: component: build, component: documentation, type: bug
