### ISSUE TITLE
Linker error when compiling with --trace/--profile

### ISSUE THREAD

**Issue by cocreature** [commercialhaskell/stack#2422] opened 2016-08-01 07:37 UTC
## Steps to reproduce:
1. `git clone git@github.com:cocreature/postgres-tmp.git -b stack-bug`
2. `stack build --trace

I strongly suspect that the state of the snapshot is also important but I don’t want to nuke it away just yet since I might be able to provide helpful information from it.
## Expected:

A clean build
## Actual:

```
Linking .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/hasql-bug/hasql-bug ...
/home/moritz/.stack/snapshots/x86_64-linux/nightly-2016-07-17/8.0.1/lib/x86_64-linux-ghc-8.0.1/uuid-types-1.0.3-1qmdgBeDGlbCUibOmxVGqx/libHSuuid-types-1.0.3-1qmdgBeDGlbCUibOmxVGqx_p.a(Internal.p_o):(.text+0x3aa60): undefined reference to `textzm1zi2zi2zi1zm5QpmrLQApEZZ4Ly9nMHWY0s_DataziTextziInternalziFusion_unstreamzsresizze_dFTV_cc'
/home/moritz/.stack/snapshots/x86_64-linux/nightly-2016-07-17/8.0.1/lib/x86_64-linux-ghc-8.0.1/uuid-types-1.0.3-1qmdgBeDGlbCUibOmxVGqx/libHSuuid-types-1.0.3-1qmdgBeDGlbCUibOmxVGqx_p.a(Internal.p_o):(.text+0x3ad63): undefined reference to `textzm1zi2zi2zi1zm5QpmrLQApEZZ4Ly9nMHWY0s_DataziTextziArray_maBA_Cd18_cc'
/home/moritz/.stack/snapshots/x86_64-linux/nightly-2016-07-17/8.0.1/lib/x86_64-linux-ghc-8.0.1/uuid-types-1.0.3-1qmdgBeDGlbCUibOmxVGqx/libHSuuid-types-1.0.3-1qmdgBeDGlbCUibOmxVGqx_p.a(Internal.p_o):(.text+0x3b03a): undefined reference to `textzm1zi2zi2zi1zm5QpmrLQApEZZ4Ly9nMHWY0s_DataziTextziArray_maBA_Cd18_cc'
collect2: error: ld returned 1 exit status
```
## Comments

Sometimes I am able to fix it by some combination of stack clean/nuking .stack-`work` and unregistering the corresponding packages (in this case uuid-types) but that doesn’t seem to help in all cases.  

So far I’ve solved this by nuking the snapshot and `.stack-work` but for the sake of finally fixing it I haven’t done this this time so that I can provide any other information that might be necessary.

**Comment by sjakobi** [comment] 2016-08-09 12:20
Thanks,  but I can't reproduce this with either v1.1.2 or the current HEAD.

I suspect it's related to https://github.com/commercialhaskell/stack/issues/1691.

**Comment by nh2** [comment] 2019-02-04 18:41
There's also some chance that this is due to an interrupted build: https://github.com/lehins/exec-kill-loop

**Comment by snoyberg** [comment] 2019-03-25 07:33
Since we don't have a clear repro, and this may be caused by an upstream issue, closing.

**Closed by snoyberg** 2019-03-25 07:33 UTC
Labels: help wanted, needs reproduction
