### ISSUE TITLE
Links in project documentation don't link outside the project

### ISSUE THREAD

**Issue by YPares** [commercialhaskell/stack#1215] opened 2015-10-22 07:29 UTC
When building with either stack 0.1.5.0 or 0.1.6.0 with
` stack haddock `
the files in `.stack-work/install/x86_64-linux/lts-3.7/7.10.2/doc/` contain broken links to function and types defined elsewhere.
I'm using GHC 7.10.2 as per lts-3.7, installed with `stack setup`.

## Steps to reproduce

`$ stack new doclink`
Edit src/Lib.hs:
```haskell
module Lib
   where

import Control.Applicative

-- | Recoding the traverse fn for lists
myListTraverse :: (Applicative f) => (a -> f b) -> [a] -> f [b]
myListTraverse f = foldr (liftA2 (:) . f)  (pure [])
```
Then
`$ stack haddock`

## Expected

`.stack-work/install/x86_64-linux/lts-3.7/7.10.2/doc/doclink-0.1.0.0/Lib.html` containing a valid link to some Control-Applicative.html in `base`.

## Actual

The generated documentation for myListTraverse contains a link for Applicative, but it points to
`.stack-work/install/x86_64-linux/lts-3.7/7.10.2/doc/base-4.8.1.0/Control-Applicative.html` which doesn't exist.

Output of `stack haddock --verbose`:
```
Version 0.1.6.0, Git revision e22271f5ce9afa2cb5be3bad9cafa392c623f85c (2313 commits) x86_64
2015-10-22 07:27:54.071754: [debug] Checking for project config at: /home/ywen/doclink/stack.yaml @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Config src/Stack/Config.hs:546:9)
2015-10-22 07:27:54.072161: [debug] Loading project config file stack.yaml @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Config src/Stack/Config.hs:569:13)
2015-10-22 07:27:54.073736: [debug] Run process: ldd /usr/bin/stack @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:54.096007: [debug] Trying to decode /home/ywen/.stack/build-plan-cache/x86_64-linux/lts-3.7.cache @(stack_AExdckAgYVa6TDUNGi5WTl:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:53:5)
2015-10-22 07:27:54.110986: [debug] Success decoding /home/ywen/.stack/build-plan-cache/x86_64-linux/lts-3.7.cache @(stack_AExdckAgYVa6TDUNGi5WTl:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:62:13)
2015-10-22 07:27:54.113053: [debug] Run process: ghc --info @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:54.122704: [debug] Run process: ghc --numeric-version @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:54.159537: [debug] Run process: ghc-pkg --no-user-package-db field --simple-output Cabal version @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:54.183146: [debug] Run process: ghc-pkg init /home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb/ @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:54.19808: [debug] Run process: ghc-pkg --no-user-package-db list --global @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:54.220367: [debug] Checking resolver: lts-3.7 @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Source src/Stack/Build/Source.hs:162:17)
2015-10-22 07:27:54.220513: [debug] Trying to decode /home/ywen/.stack/build-plan-cache/x86_64-linux/lts-3.7.cache @(stack_AExdckAgYVa6TDUNGi5WTl:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:53:5)
2015-10-22 07:27:54.226535: [debug] Success decoding /home/ywen/.stack/build-plan-cache/x86_64-linux/lts-3.7.cache @(stack_AExdckAgYVa6TDUNGi5WTl:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:62:13)
2015-10-22 07:27:54.231443: [debug] Trying to decode /home/ywen/.stack/indices/Hackage/00-index.cache @(stack_AExdckAgYVa6TDUNGi5WTl:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:53:5)
2015-10-22 07:27:54.449274: [debug] Success decoding /home/ywen/.stack/indices/Hackage/00-index.cache @(stack_AExdckAgYVa6TDUNGi5WTl:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:62:13)
2015-10-22 07:27:54.450972: [debug] Trying to decode /home/ywen/doclink/.stack-work/installed-cache.bin @(stack_AExdckAgYVa6TDUNGi5WTl:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:53:5)
2015-10-22 07:27:54.451223: [debug] Failure decoding /home/ywen/doclink/.stack-work/installed-cache.bin @(stack_AExdckAgYVa6TDUNGi5WTl:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:57:13)
2015-10-22 07:27:54.451545: [debug] Run process: ghc-pkg --global --no-user-package-db dump --expand-pkgroot @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:54.501913: [debug] Run process: ghc-pkg --user --no-user-package-db --package-db /home/ywen/.stack/snapshots/x86_64-linux/lts-3.7/7.10.2/pkgdb/ dump --expand-pkgroot @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:54.63117: [debug] Run process: ghc-pkg --user --no-user-package-db --package-db /home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb/ dump --expand-pkgroot @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:54.67592: [debug] Trying to decode /home/ywen/.stack/indices/Hackage/00-index.cache @(stack_AExdckAgYVa6TDUNGi5WTl:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:53:5)
2015-10-22 07:27:54.877104: [debug] Success decoding /home/ywen/.stack/indices/Hackage/00-index.cache @(stack_AExdckAgYVa6TDUNGi5WTl:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:62:13)
2015-10-22 07:27:54.877269: [debug] Trying to decode /home/ywen/.stack/indices/Hackage/00-index.cache @(stack_AExdckAgYVa6TDUNGi5WTl:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:53:5)
2015-10-22 07:27:55.074956: [debug] Success decoding /home/ywen/.stack/indices/Hackage/00-index.cache @(stack_AExdckAgYVa6TDUNGi5WTl:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:62:13)
2015-10-22 07:27:55.149216: [debug] Run process: ghc-pkg --no-user-package-db list --global @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:55.188591: [info] doclink-0.1.0.0: configure @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:621:23)
2015-10-22 07:27:55.189012: [debug] Run process: /home/ywen/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-linux-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/ configure --with-ghc=/home/ywen/.stack/programs/x86_64-linux/ghc-7.10.2/bin/ghc --user --package-db=clear --package-db=global --package-db=/home/ywen/.stack/snapshots/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --libdir=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/lib --bindir=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/bin --datadir=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/share --libexecdir=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/libexec --sysconfdir=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/etc --docdir=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/doc/doclink-0.1.0.0 --htmldir=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/doc/doclink-0.1.0.0 --haddockdir=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/doc/doclink-0.1.0.0 --dependency=base=base-4.8.1.0-4f7206fd964c629946bb89db72c80011 --enable-tests --enable-benchmarks @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:755:21)
2015-10-22 07:27:56.013654: [info] Configuring doclink-0.1.0.0... @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:56.237752: [info] doclink-0.1.0.0: build @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:621:23)
2015-10-22 07:27:56.238075: [debug] Run process: /home/ywen/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-linux-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/ build lib:doclink --ghc-options " -ddump-hi -ddump-to-file" @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:755:21)
2015-10-22 07:27:56.302452: [info] Preprocessing library doclink-0.1.0.0... @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:56.395009: [info] [1 of 1] Compiling Lib              ( src/Lib.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Lib.o ) @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:56.930434: [info] In-place registering doclink-0.1.0.0... @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:56.93283: [info] doclink-0.1.0.0: haddock @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:621:23)
2015-10-22 07:27:56.932957: [debug] Run process: haddock --hyperlinked-source @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:56.973328: [debug] Run process: /home/ywen/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-linux-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/ haddock --html --hoogle --html-location=../$pkg-$version/ --hyperlink-source @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:755:21)
2015-10-22 07:27:57.041752: [info] Running Haddock for doclink-0.1.0.0... @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:57.042197: [info] Running hscolour for doclink-0.1.0.0... @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:57.042414: [info] Preprocessing library doclink-0.1.0.0... @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:57.117875: [info] Preprocessing library doclink-0.1.0.0... @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:57.423983: [info] Haddock coverage: @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:57.42411: [info]   50% (  1 /  2) in 'Lib' @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:57.424233: [info]   Missing documentation for: @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:57.424293: [info]     Module header @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:57.440447: [info] Documentation created: @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:57.440621: [info] .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/doc/html/doclink/index.html, @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:57.440706: [info] .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/doc/html/doclink/doclink.txt @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:57.440949: [info] doclink-0.1.0.0: install @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:621:23)
2015-10-22 07:27:57.441036: [debug] Run process: /home/ywen/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-linux-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/ install @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:755:21)
2015-10-22 07:27:57.452249: [info] Installing library in @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:57.452398: [info] /home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/lib/x86_64-linux-ghc-7.10.2/doclink-0.1.0.0-AzYAFnqQIQgKyAKUwOpFtP @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:57.569338: [info] Registering doclink-0.1.0.0... @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Execute src/Stack/Build/Execute.hs:1287:35)
2015-10-22 07:27:57.5699: [debug] Run process: ghc-pkg --no-user-package-db --package-db=/home/ywen/.stack/snapshots/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb/ field --simple-output doclink id @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:57.628342: [debug] Run process: ghc-pkg --no-user-package-db --package-db=/home/ywen/.stack/snapshots/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/.stack/programs/x86_64-linux/ghc-7.10.2/lib/ghc-7.10.2/package.conf.d/ field --simple-output doclink-0.1.0.0 haddock-html @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:57.708245: [debug] Run process: ghc-pkg --no-user-package-db --package-db=/home/ywen/.stack/snapshots/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/.stack/programs/x86_64-linux/ghc-7.10.2/lib/ghc-7.10.2/package.conf.d/ field --simple-output doclink-0.1.0.0 id @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:57.760224: [debug] Run process: ghc-pkg --no-user-package-db --package-db=/home/ywen/.stack/snapshots/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/.stack/programs/x86_64-linux/ghc-7.10.2/lib/ghc-7.10.2/package.conf.d/ field --simple-output doclink-0.1.0.0 version @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:57.81105: [info] Updating Haddock index for local packages in
/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/doc/index.html @(stack_AExdckAgYVa6TDUNGi5WTl:Stack.Build.Haddock src/Stack/Build/Haddock.hs:199:20)
2015-10-22 07:27:57.811316: [debug] Run process: haddock --gen-contents --gen-index -i ./doclink-0.1.0.0,./doclink-0.1.0.0/doclink.haddock @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:57.897063: [debug] Run process: ghc-pkg --no-user-package-db --package-db=/home/ywen/.stack/snapshots/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb/ field --simple-output doclink-0.1.0.0 depends @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:57.95933: [debug] Run process: ghc-pkg --no-user-package-db --package-db=/home/ywen/.stack/snapshots/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb/ field --simple-output base-4.8.1.0-4f7206fd964c629946bb89db72c80011 name @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:58.042639: [debug] Run process: ghc-pkg --no-user-package-db --package-db=/home/ywen/.stack/snapshots/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb/ field --simple-output base-4.8.1.0-4f7206fd964c629946bb89db72c80011 name @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:58.112966: [debug] Run process: ghc-pkg --no-user-package-db --package-db=/home/ywen/.stack/snapshots/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb/ field --simple-output base-4.8.1.0-4f7206fd964c629946bb89db72c80011 version @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:58.166146: [debug] Run process: ghc-pkg --no-user-package-db --package-db=/home/ywen/.stack/snapshots/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb/ field --simple-output base-4.8.1.0-4f7206fd964c629946bb89db72c80011 version @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:58.213676: [debug] Run process: ghc-pkg --no-user-package-db --package-db=/home/ywen/.stack/snapshots/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb/ field --simple-output base-4.8.1.0-4f7206fd964c629946bb89db72c80011 depends @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:58.306932: [debug] Run process: ghc-pkg --no-user-package-db --package-db=/home/ywen/.stack/snapshots/x86_64-linux/lts-3.7/7.10.2/pkgdb/ --package-db=/home/ywen/doclink/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/pkgdb/ field --simple-output base-4.8.1.0-4f7206fd964c629946bb89db72c80011 depends @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
2015-10-22 07:27:58.394865: [debug] Run process: ghc-pkg --no-user-package-db --package-db=/home/ywen/.stack/programs/x86_64-linux/ghc-7.10.2/lib/ghc-7.10.2/package.conf.d/ --package-db=/home/ywen/.stack/snapshots/x86_64-linux/lts-3.7/7.10.2/pkgdb/ list --simple-output @(stack_AExdckAgYVa6TDUNGi5WTl:System.Process.Read src/System/Process/Read.hs:272:3)
```

**Comment by borsboom** [comment] 2015-10-22 14:04
Duplicate of #1105

**Closed by borsboom** 2015-10-22 14:04 UTC
