### ISSUE TITLE
Stack exec should prefer the bin-path over local-bin

### ISSUE THREAD

**Issue by bergus** [commercialhaskell/stack#3914] opened 2018-03-12 14:33 UTC
I kinda expected `stack exec` to run my executable from the last build - but it didn't.
I had encountered a bug, and it took me quite some time to figure out that there was no problem with my project code, or my local dependency that I was also editing, but that I was actually running an old version of my executable.
How it happened? I'm using `local-bin-path: .` in my project's `stack.yaml`, so that I could run my executable right in the project directory (it's a Hakyll website).

In the past I remember using `stack exec website -- -v build` to run the newest build, but now that gets me the latest `stack install`ed version, i.e. `./website`. Did this behaviour change or did I just never notice?

Tell me if you want some example code to reproduce or whether it's clear what happened.

---
The docs at https://docs.haskellstack.org/en/stable/GUIDE/#exec say

> In particular: `stack exec` looks for executables on stack's bin paths

but apparently this means that it *just* adds them to the `PATH` environment variable, and then runs the command as-is? If that's what is happening, I guess changing the behaviour is out of question, but a clarification of the documentation would help. Also it would be super-useful if `stack exec` could check whether the chosen executable name appears in multiple directories in the PATH as well as in the local working directory, and outputs a warning if they are different executables.

### My stack version

```
stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

**Comment by snoyberg** [comment] 2019-04-05 05:17
I agree, this looks like a regression.

**Comment by snoyberg** [comment] 2019-04-05 05:26
I tried adding an integration test to reproduce, but I wasn't able to get it to trigger this bug, even with Stack 1.6.5. I've pushed this commit to a separate branch (3914-path-ordering):

762dea907514c687a1f757fd9054fa6f79bba0eb

Can you provide some more details?

**Comment by snoyberg** [comment] 2019-04-12 15:15
Closing, if you have a repro, please add a comment and I'l reopen.

**Closed by snoyberg** 2019-04-12 15:15 UTC
