### ISSUE TITLE
pkg-config + external msys2 = package not found

### ISSUE THREAD

**Issue by YellowOnion** [commercialhaskell/stack#2169] opened 2016-05-20 23:37 UTC
This part of stack seems to be very poorly documented

```
$ pacman -Ss mingw-w64-x86_64-SDL2
mingw64/mingw-w64-x86_64-SDL2 2.0.4-1 [installed]
    A library for portable low-level access to a video framebuffer, audio
    output, mouse, and keyboard (Version 2) (mingw-w64)

```

```
$ stack install sdl2
<snip>
    Configuring sdl2-2.1.1...
    setup-Simple-Cabal-1.22.5.0-ghc-7.10.3.exe: The pkg-config package 'sdl2'
    version >=2.0.3 is required but it could not be found.
```

trying with `--no-msys`

```
$ stack --skip-msys install sdl2
<snip>
    Configuring sdl2-2.1.1...
    setup-Simple-Cabal-1.22.5.0-ghc-7.10.3.exe: The pkg-config package 'sdl2'
    version >=2.0.3 is required but it could not be found.
```

How would I proceed installing sdl2 bindings?

**Comment by mgsloan** [comment] 2016-05-21 00:33
Yes, things like this are still frustrating on windows.  Dupe of https://github.com/commercialhaskell/stack/issues/1714

**Closed by mgsloan** 2016-05-21 00:33 UTC

**Comment by YellowOnion** [comment] 2016-06-04 01:15
@mgsloan Sorry for late reply, but I cannot for the life of me figure out using the solution in the other thread to work around the issue in my case, is there a work around to getting my project to build sdl2?

**Comment by mgsloan** [comment] 2016-06-04 01:24
Not sure, sorry :/  Windows isn't my specialty.
