### ISSUE TITLE
stack Doesn't Work (that's what picture tell)

### ISSUE THREAD

**Issue by Heather** [commercialhaskell/stack#2106] opened 2016-05-05 17:47 UTC
![1](https://cloud.githubusercontent.com/assets/2656965/15051613/96fde134-130a-11e6-8f11-08fa1be1c921.JPG)

```
win 10 x64
C:\Users\Rainbow>stack --version
Version 1.1.0, Git revision 0e9430aad55841b5ff2c6c2851f0548c16bce7cf (3540 commits) x86_64 hpack-0.13.0
```

Access Violation

**Comment by mgsloan** [comment] 2016-05-05 21:01
Wow, that's a rare thing indeed, I wonder what could cause it.

**Comment by Heather** [comment] 2016-05-06 04:34
@mgsloan try set stack to spin (resolve many deps packages) like crazy on windows, e.g. run some stress tests, maybe it's not that hard to reproduce and people just don't pay much attention to it, e.g. it works if I just run same second time so it's a glitch

**Comment by mgsloan** [comment] 2016-05-06 20:35
Seems like it's happened before:  https://github.com/commercialhaskell/stack/issues/898

I'm guessing it's something specific to your setup as otherwise I think we'd hear about it more.

**Comment by Heather** [comment] 2016-05-09 10:13
I really doubt if it's related to setup, there was nothing specific. What do you think about my stress test suggestion in case this issue was already known/reported

**Comment by mgsloan** [comment] 2016-05-09 19:48
Was stack installed via the binary installer?  If installed via cabal-install, one possibility is that it picked a dependency version that has a bug which causes segfaults.

I would appreciate an automated repro based on stress testing in some reproducible environment (container / vm image).

**Comment by Heather** [comment] 2016-05-09 20:01
@mgsloan stack was installed via the binary installer but sure maybe still one possibility is that binary stack is using some dependency version that has a bug which causes segfaults, sure

**Comment by mgsloan** [comment] 2016-05-09 20:27
Right, I'm just trying to figure out why only 2 windows users are reporting this.

**Comment by mgsloan** [comment] 2016-05-13 00:11
I am closing this as need repro, as it seems to be a rare thing, and I cannot investigate without a repro.

Opening https://github.com/commercialhaskell/stack/issues/2134 about stress testing

**Closed by mgsloan** 2016-05-13 00:11 UTC
Labels: component: windows, need repro, type: bug

**Comment by mgsloan** [comment] 2016-05-20 02:41
This may be caused by http://www.echonolan.net/posts/2016-05-10-a-debugging-horror-story.html

See also https://github.com/commercialhaskell/stack/issues/1689
