### ISSUE TITLE
stack exec should propagate +RTS-options better

### ISSUE THREAD

**Issue by michaxm** [commercialhaskell/stack#1655] opened 2016-01-14 17:39 UTC
```
stack new example
cd example
stack build --profile --executable-profiling --library-profiling
stack exec  example +RTS  -p
```

... fails with: the flag -p requires the program to be built with -prof

```
.stack-work/install/.../example +RTS -p
```

works. 

It would be nice to use exec for this use case as well, as it is time consuming to discover you can't. I would consider this a feature request, cabal-install seems to have the same issue: http://stackoverflow.com/questions/22942194/profiling-an-executable-with-cabal

Could not find a documented "won't work / won't fix" anywhere for stack, so a decision documentation here would be nice.

**Comment by mgsloan** [comment] 2016-01-14 23:21
The issue is that `+RTS -p` is getting interpreted by the stack executable.  Use a `--` to separate out the inner invocation - `stack exec -- example +RTS -p`.  See [the docs on this](http://docs.haskellstack.org/en/stable/GUIDE.html#exec)

**Comment by michaxm** [comment] 2016-01-15 09:09
A part of the instructions I have overlooked so far, thanks a lot.

**Comment by ndmitchell** [comment] 2016-11-10 11:52
This issue still persists. In particular the `+RTS -p` option after `--` doesn't get passed through on Windows. As a concrete example:

```
stack new example
cd example
stack build
stack exec  -- example-exe +RTS  -?
```

This does not print out the help for `example-exe`, and examining process explorer the `+RTS -?` argument is not passed onwards.

**Comment by mgsloan** [comment] 2016-11-11 22:24
@ndmitchell Curious, that works just fine for me on linux.

This reminded me of this comment - https://github.com/commercialhaskell/stack/issues/2022#issuecomment-245600170 .  Perhaps `stack exec --RTS -- example-exe +RTS -?` will work?  Or perhaps `stack exec example-exe --RTS -- +RTS -?`?

**Comment by ndmitchell** [comment] 2016-11-14 06:55
@mgsloan I confirm both those things work. Do you do anything special to get the other one working? Is this a GHC issue? Should there be a `--rts=...` flag to stack to make this easier and consistent?

**Comment by varosi** [comment] 2017-01-24 10:04
Will "--RTS" be automatically included in stack? 
Currently it's not logical stack invocation to not work without --RTS:
```
myapp +RTS -s
stack exec -- myapp -- +RTS -s
```
It's logical both to be identical, but they aren't even on the latest stack-1.3.2 on Windows.

**Comment by mgsloan** [comment] 2017-01-31 23:36
I think it'd be reasonable to add a `--rts` flag as @ndmitchell suggests.  Does someone want to write a patch for this?

**Comment by AndreasPK** [comment] 2017-10-21 18:57
Can this be closed via https://github.com/commercialhaskell/stack/pull/3012 ?

**Comment by ndmitchell** [comment] 2017-10-22 06:10
This answers my need, and covers what was discussed, so closing.

**Closed by ndmitchell** 2017-10-22 06:10 UTC
Labels: component: windows
