### ISSUE TITLE
Stack should install gotta-go-fast in a single command

### ISSUE THREAD

**Issue by alexanderkjeldaas** [commercialhaskell/stack#3308] opened 2017-08-02 09:30 UTC
See https://github.com/hot-leaf-juice/gotta-go-fast

Bad:

```
$ git clone https://github.com/hot-leaf-juice/gotta-go-fast
$ cd gotta-go-fast
$ stack install
```

Good, cool and hip:

```
stack install https://github.com/hot-leaf-juice/gotta-go-fast
```

**Comment by tfausak** [comment] 2017-08-02 12:25
This would be great! Original discussion on Reddit: https://www.reddit.com/r/haskell/comments/6qzdx6/a_typing_practice_app_written_with_brick/dl1wi20/

It's worth noting that [`gotta-go-fast`](https://hackage.haskell.org/package/gotta-go-fast) is on Hackage, so you could just do `stack install gotta-go-fast`. But building/installing packages from Git/web sources would be awesome. You can already do it from `stack.yaml` or custom snapshots, so it would be nice to do it from the command line too.

**Comment by lwm** [comment] 2017-08-06 17:06
> You can already do it from stack.yaml

Should this new way of installing update your `stack.yaml` pointing to the Git source as per usual? Probably a good idea no? Would be easier to know after, which version was installed from source.

**Comment by tfausak** [comment] 2017-08-06 18:04
I don't know. When you `stack install some-package-1.2.3`, I don't think it modifies your `stack.yaml`.

**Comment by kadoban** [comment] 2017-08-11 05:25
This is a duplicate of issue #1278

**Closed by kadoban** 2017-08-11 05:25 UTC
Labels: type: enhancement
