### ISSUE TITLE
Bug: stack build of project using wreq hangs indefinitely on lts-13.3 on Windows 10

### ISSUE THREAD

**Issue by fegu** [commercialhaskell/stack#4523] opened 2019-01-21 13:10 UTC
Attached is a minimal project using wreq which builds on lts-12.26 but hangs on lts-13.3 while installing wreq on Windows 10. The wreq version is identical on these two resolvers (wreq-0.5.3.1) so something else is probably the issue. The GHC process must be stopped manually to recover, but no workaround has been found.

[wreq-stack-hang.zip](https://github.com/commercialhaskell/stack/files/2778990/wreq-stack-hang.zip)

**Comment by dbaynard** [comment] 2019-01-24 12:02
Quick note: the snapshots use different compiler versions: lts-13.3 uses GHC 8.6.3, lts-12.26 uses GHC 8.4.4.

**Comment by DuckOfDoom** [comment] 2019-02-20 09:34
I can confirm that too.

**Comment by dbaynard** [comment] 2019-02-20 13:42
Right, that resolver also uses 8.6. It looks like it might be a ghc bug.

I suggest you try building with cabal; if that works then it's a stack problem, if it doesn't then it's a ghc problem.

**Comment by snoyberg** [comment] 2019-03-19 20:52
I believe there was an infinite loop bug on GHC 8.6.3 on Windows. The latest LTS 13 snapshots using GHC 8.6.4. Can you try using the latest LTS 13 (currently lts-13.13) and see if it works?

**Comment by snoyberg** [comment] 2019-03-26 04:40
Closing as upstream issue.

**Closed by snoyberg** 2019-03-26 04:40 UTC
Labels: component: build, component: windows, further investigation required
