### ISSUE TITLE
InvalidAbsDir "./stack-setupXXXXX" from Path.IO.listDirectory

### ISSUE THREAD

**Issue by robstewart57** [commercialhaskell/stack#1017] opened 2015-09-20 10:04 UTC
When I execute `stack setup` I'm getting this error:

    $ stack setup
    InvalidAbsDir "./stack-setup31658"

This is thrown by Path.parseAbsDir in the path package (see [line 79](https://github.com/chrisdone/path/blob/09996f160573edba61166293c27438ea1d342050/src/Path.hs#L79)). I've modified Path.IO.listDirectory to print the filepath it is calling `parseAbsDir` on, so that the file path is printed each time and also so that I can get the stack trace up to that point.

This is the printed file paths and the stack trace:

```
"/home/rob/.stack/programs/i386-linux/ghc-7.10.2.tar.xz"
"/home/rob/.stack/programs/i386-linux/.."
*** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace:
  Path.CAF
  --> evaluated by: Path.IO.listDirectory.\,
  called from Path.IO.listDirectory,
  called from Stack.Setup.listInstalled,
  called from Stack.Setup.ensureGHC,
  called from Stack.Types.StackT.>>=,
  called from Main.setupCmd.\,
  called from Main.withUserFileLock.\,
  called from Main.withUserFileLock,
  called from Main.setupCmd,
  called from Main.main.\,
  called from Data.Attoparsec.Args.withInterpreterArgs,
  called from Main.main
```

I've raised this question with @chrisdone who believes that stack should canonicalize paths before calling  `parseAbsDir`.

**Comment by mgsloan** [comment] 2015-09-20 10:25
configLocalPrograms seems to be well canonicalized, [here](https://github.com/commercialhaskell/stack/blob/c774f9905b3b112f58fc3789dfb9c26389d33b24/src/Stack/Config.hs#L167), so it must not be the input to `listDirectory` that's the issue.

It's very surprising that there'd be a bug in `listDirectory`, though (you'd think it'd always happen, and be caught quickly).

Lets test out chris's thought - does this fix it?

```diff
diff --git a/src/Path/IO.hs b/src/Path/IO.hs
index ca1bed9..79e6d39 100644
--- a/src/Path/IO.hs
+++ b/src/Path/IO.hs
@@ -170,8 +170,9 @@ listDirectory dir =
   do entriesFP <- liftIO (D.getDirectoryContents dirFP)
      maybeEntries <-
        forM (map (dirFP ++) entriesFP)
-            (\entryFP ->
-               do isDir <- liftIO (D.doesDirectoryExist entryFP)
+            (\entryFP' ->
+               do entryFP <- liftIO (D.canonicalizePath entryFP')
+                  isDir <- liftIO (D.doesDirectoryExist entryFP)
                   if isDir
                      then case parseAbsDir entryFP of
                             Nothing -> return Nothing
```

**Comment by chrisdone** [comment] 2015-09-20 10:44
The calls to `parseAbsDir` inside `listDirectory` are in the Maybe monad so I don't see why an exception would be thrown from within `listDirectory`.

**Comment by chrisdone** [comment] 2015-09-20 10:56
@robstewart57 Can you offer some extra details so that we can reproduce this?

**Comment by robstewart57** [comment] 2015-09-20 17:08
In fact, I wasn't reading the stack trace in the right way. It turns out that the issue was with Stack.Setup whenever `withSystemTempDirectory` is used, e.g.

```haskell
withSystemTempDirectory "stack-setup" $ \root' -> do
root <- parseAbsDir root'
```

At least for me, the withSystemTempDirectory was not returning a canonicalised path, which is why `parseAbsDir` from the path library was throwing the error.

I propose a PR that applies a fix to stack setup, sanityCheck and stack upgrade
in Stack.Setup : https://github.com/commercialhaskell/stack/pull/1019 .

**Comment by robstewart57** [comment] 2015-09-20 17:32
Hang off accepting this PR actually, this same problem is causing a problem elsewhere. More anon...

**Comment by robstewart57** [comment] 2015-09-20 18:07
OK, that second commit ( f912e2f8adb04511a5dae8cc6724204403eda23e ) does appear to fix the `InvalidAbsDir` error I was getting. This PR is ready for review.

**Comment by snoyberg** [comment] 2015-09-21 02:19
Closing so that we follow up on the PR (#1019).

**Closed by snoyberg** 2015-09-21 02:19 UTC
