### ISSUE TITLE
Certificate Issues behind Corporate Proxy?

### ISSUE THREAD

**Issue by laurencer** [commercialhaskell/stack#907] opened 2015-09-03 06:49 UTC
When stack is pulling new packages - I'm getting the following error:

    TlsException (HandshakeFailed (Error_Protocol ("certificate rejected: [SelfSigned]",True,CertificateUnknown)))

I'm assuming this is because I'm behind a corporate MITM proxy. Anyway to get it to accept my systems custom root CA?

**Comment by snoyberg** [comment] 2015-09-03 08:26
In general stack (and the underlying tls library for Haskell) do respect system certificates. There are debugging instructions available for this at:

https://github.com/vincenthz/hs-tls/#common-issues

I have personal experience using stack in this use case, so (perhaps surprisingly) it is actually tested.

**Comment by laurencer** [comment] 2015-09-05 03:38
Okay thanks - I'll have a look on Monday and see if I can get it working

**Comment by laurencer** [comment] 2015-09-06 23:27
I seem to be running in to [this issue here](https://github.com/vincenthz/hs-certificate/issues/49). It's fixed in the latest version of `hs-certificate` but I'm guessing that's not used by Stack yet. It only happens on recent versions of Mac OS X due to a way the Keychains have been changed.

The temporary fix was to add the certificate to the `SystemRootCertificates` Keychain (aka `sudo security add-trusted-cert -d -r trustRoot -k /System/Library/Keychains/SystemRootCertificates.keychain ~/my_fancy_cert.pem`), but it'd be nice in future if we didn't have to.

Any idea how to bump the version appropriately?

**Comment by snoyberg** [comment] 2015-09-07 05:29
The certificate package is marked as deprecated in favor of x509.

@vincenthz Can you let us know which version of which package we need to upgrade to in order to get this change?

**Comment by vincenthz** [comment] 2015-09-07 08:59
@snoyberg Since x509-system-1.6.0, the SystemRootCertificates *and* the `/Library/Keychains/System.keychain` are automatically processed as the Trusted CA Store.

@laurencer Do you know which keychains your certificate is in ?

**Comment by snoyberg** [comment] 2015-09-07 09:02
I can confirm that stack is currently using x509-system-1.6.0: https://www.stackage.org/lts-3.0/package/x509-system-1.6.0. Thanks @vincenthz

**Comment by laurencer** [comment] 2015-09-11 05:22
@vincenthz - I believe the certificate was in `/Library/Keychains/System.keychain` (before I added it to the `SystemRootCertificates` manually). I'll have to check when I'm next at work...

**Comment by snoyberg** [comment] 2015-09-21 03:28
Have you had a chance to check this?

**Comment by laurencer** [comment] 2015-09-21 04:21
Yeah I'm fairly confident it was in `/Library/Keychains/System.keychain`. I would have to remove it from `SystemRootCertificates` to be sure though (to verify the bug)...

**Comment by thsutton** [comment] 2015-09-24 23:11
I've just done this too and can confirm @laurencer's last comment: the cert was in `System` and adding it to `SystemRootCertificates` fixes the problem.

**Comment by snoyberg** [comment] 2015-09-30 11:06
Is this an issue that should be moved to the tls package, or is there something that Stack can do about this?

**Comment by vincenthz** [comment] 2015-09-30 11:29
I don't think there's anything Stack can do, short of supplying an extra list of CA maybe. I need to find time to see what's going on with the System keychain, unless someone beat me to it.

**Comment by snoyberg** [comment] 2015-09-30 11:30
OK, thanks Vincent. Closing as an upstream issue.

**Closed by snoyberg** 2015-09-30 11:30 UTC

**Comment by vincenthz** [comment] 2015-09-30 11:45
I'm adding a tracking ticket for this: https://github.com/vincenthz/hs-certificate/issues/68

**Comment by dmvianna** [comment] 2016-03-17 04:37
Any chance this will be fixed for non-root users? Other languages allow users to point to `.pem` certificates through configuration files. In Python one can use `~/.pip/pip.conf`:

    [global]

    cert = /home/<user>/.pip/<cert>.pem
    proxy = http://<proxy-address>:<port>/

**Comment by kyrias** [comment] 2016-05-06 11:38
Looking at the code, it should be possible by setting the `SYSTEM_CERTIFICATE_PATH` environment variable?

**Comment by sjakobi** [comment] 2016-07-14 16:04
> Looking at the code, it should be possible by setting the SYSTEM_CERTIFICATE_PATH environment variable?

I think that should work.
