### ISSUE TITLE
`stack upgrade` fails to use binary on Linux

### ISSUE THREAD

**Issue by Vlix** [commercialhaskell/stack#5882] opened 2022-09-25 09:36 UTC
### General summary

`stack upgrade` on Linux results in the following message:

```
Warning: Exception occured when trying to perform binary upgrade:
         InvalidUrlException "/upgrade/linux-x86_64.tar.gz" "Invalid URL" 
         Falling back to source upgrade
```
Because `curl -X HEAD "https://get.haskellstack.org/upgrade/linux-x86_64-static.tar.gz"` ([see source](https://github.com/commercialhaskell/stack/blob/b846eae85d9f30d28d7a4fa33fea139e7d1420c7/src/Stack/Setup.hs#L1884)) gets a path in the `Location` header, instead of a URL with protocol + domain + path.

### Steps to reproduce

1. Use Ubuntu
2. Run command `stack upgrade`

### Expected

For it to download the readily available binary

### Actual

Fails to add the domain back in front of the received path, so `parseRequest` throws an exception.

### Stack version

~~~text
stack --version
Version 2.7.5, Git revision ba147e6f59b2da75b1beb98b1888cce97f7032b1 x86_64 hpack-0.34.4
~~~

**Comment by mpilgrem** [comment] 2022-09-25 12:39
@Vlix, thanks for reporting.

@borsboom, has this been introduced by the update of https://get.haskellstack.org for the move to Stack 2.9.1?

**Comment by Vlix** [comment] 2022-09-25 13:08
Made a PR: #5884

**Comment by mpilgrem** [comment] 2022-09-25 21:22
Thanks. I'm hoping a simpler fix involves fixing some mis-wiring of https://get.haskellstack.org - in part because `stack upgrade` works as intended on Windows and this is 'old' code. I'd like to give Emanuel a chance to look into that.

**Comment by Vlix** [comment] 2022-09-26 18:31
I mean, you can also make it work for everyone if anyone could change the Location header in the redirect from `get.haskellstack.org` to an absolute URL instead of just the path 🤷

**Comment by hasufell** [comment] 2022-09-27 01:19
You can use ghcup to install stack. It should work.

**Comment by snoyberg** [comment] 2022-09-27 16:34
@Vlix I've done just that. This is introduced by moving over to Cloudflare Pages for the redirects, which will make it easier for general community members to do the update. I don't know why, but they changed the absolute redirect to a relative one. This should hopefully be fixed in https://github.com/commercialhaskell/get-haskellstack-org/commit/1423520ceeca357cc9fb3779cfc1c63f4b7f0a08. Can you give it a shot to confirm?

**Comment by mpilgrem** [comment] 2022-09-27 22:12
Thanks! @snoyberg. Tested on Ubuntu 22.04 (on WSL). All good.

**Closed by mpilgrem** 2022-09-27 22:12 UTC
Labels: type: bug, component: installer, component: linux

**Comment by Vlix** [comment] 2022-09-28 14:48
@snoyberg indeed works again
