### ISSUE TITLE
stack build aeson-1.0.0.0 ExitFailure (-11)

### ISSUE THREAD

**Issue by jiakai0419** [commercialhaskell/stack#2575] opened 2016-09-10 09:46 UTC
### General summary/comments (optional)
stack build aeson-1.0.0.0 failed
display Process exited with code: ExitFailure (-11) and some warning, none error.
It is strange that add
```
flags:
  aeson:
    fast: true
```
to stack.yaml will be build success.

the machine cpu 1 core, memory 1G.

### Steps to reproduce
1. git clone https://github.com/jiakai0419/snowflake.git
2. stack build

stack.yaml
```
flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.0.0.0
- binary-0.7.6.1
- snowflake-0.1.0.0
- time-1.5.0.1
- time-exts-2.1.0
- timezone-olson-0.1.7
- timezone-series-0.1.5.1
resolver: nightly-2016-08-13
```

### Actual
```
[jiakai@iZ25uyotqyoZ snowflake]$ stack build --verbose
Version 1.1.2, Git revision cebe10e845fed4420b6224d97dcabf20477bbd4b (3646 commits) x86_64 hpack-0.14.0
2016-09-10 17:41:25.602974: [debug] Checking for project config at: /home/jiakai/temp/snowflake/stack.yaml @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Config src/Stack/Config.hs:811:9)
2016-09-10 17:41:25.625941: [debug] Loading project config file stack.yaml @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Config src/Stack/Config.hs:829:13)
2016-09-10 17:41:25.638195: [debug] Checking whether stack was built with libgmp4 @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Config src/Stack/Config.hs:326:5)
2016-09-10 17:41:25.638399: [debug] Run process: ldd /usr/bin/stack @(stack_IZ6kIIshaMC0uV4dtbkAts:System.Process.Read src/System/Process/Read.hs:283:3)
2016-09-10 17:41:25.650125: [debug] Stack was not built with libgmp4 @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Config src/Stack/Config.hs:330:14)
2016-09-10 17:41:25.650273: [debug] Trying to decode /home/jiakai/.stack/build-plan-cache/x86_64-linux/nightly-2016-08-13.cache @(stack_IZ6kIIshaMC0uV4dtbkAts:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:55:5)
2016-09-10 17:41:25.676074: [debug] Success decoding /home/jiakai/.stack/build-plan-cache/x86_64-linux/nightly-2016-08-13.cache @(stack_IZ6kIIshaMC0uV4dtbkAts:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:64:13)
2016-09-10 17:41:25.677723: [debug] Getting system compiler version @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Setup src/Stack/Setup.hs:341:17)
2016-09-10 17:41:25.686858: [debug] Asking GHC for its version @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Setup.Installed src/Stack/Setup/Installed.hs:94:13)
2016-09-10 17:41:25.687057: [debug] Run process: ghc --numeric-version @(stack_IZ6kIIshaMC0uV4dtbkAts:System.Process.Read src/System/Process/Read.hs:283:3)
2016-09-10 17:41:28.019954: [debug] Getting Cabal package version @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.GhcPkg src/Stack/GhcPkg.hs:165:5)
2016-09-10 17:41:28.020194: [debug] Run process: ghc-pkg --no-user-package-db field --simple-output Cabal version @(stack_IZ6kIIshaMC0uV4dtbkAts:System.Process.Read src/System/Process/Read.hs:283:3)
2016-09-10 17:41:28.199293: [debug] Resolving package entries @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Setup src/Stack/Setup.hs:221:5)
2016-09-10 17:41:28.208299: [debug] Getting global package database location @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.GhcPkg src/Stack/GhcPkg.hs:48:5)
2016-09-10 17:41:28.208527: [debug] Run process: ghc-pkg --no-user-package-db list --global @(stack_IZ6kIIshaMC0uV4dtbkAts:System.Process.Read src/System/Process/Read.hs:283:3)
2016-09-10 17:41:28.241271: [debug] Run process: ghc-pkg --global --no-user-package-db dump --expand-pkgroot @(stack_IZ6kIIshaMC0uV4dtbkAts:System.Process.Read src/System/Process/Read.hs:283:3)
2016-09-10 17:41:28.298642: [debug] Ignoring package ghci due to wrong location: (Nothing,Local) @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.Installed src/Stack/Build/Installed.hs:189:5)
2016-09-10 17:41:28.299012: [debug] Ignoring package haskeline due to wrong location: (Nothing,Local) @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.Installed src/Stack/Build/Installed.hs:189:5)
2016-09-10 17:41:28.299221: [debug] Ignoring package ghc-boot due to wrong location: (Nothing,Local) @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.Installed src/Stack/Build/Installed.hs:189:5)
2016-09-10 17:41:28.299398: [debug] Ignoring package Cabal due to wrong location: (Nothing,Local) @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.Installed src/Stack/Build/Installed.hs:189:5)
2016-09-10 17:41:28.299572: [debug] Ignoring package binary due to wrong location: (Nothing,Local) @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.Installed src/Stack/Build/Installed.hs:189:5)
2016-09-10 17:41:28.299717: [debug] Ignoring package hpc due to wrong location: (Nothing,Local) @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.Installed src/Stack/Build/Installed.hs:189:5)
2016-09-10 17:41:28.299850: [debug] Ignoring package process due to wrong location: (Nothing,Local) @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.Installed src/Stack/Build/Installed.hs:189:5)
2016-09-10 17:41:28.299983: [debug] Ignoring package directory due to wrong location: (Nothing,Local) @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.Installed src/Stack/Build/Installed.hs:189:5)
2016-09-10 17:41:28.300291: [debug] Ignoring package unix due to wrong location: (Nothing,Local) @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.Installed src/Stack/Build/Installed.hs:189:5)
2016-09-10 17:41:28.300425: [debug] Ignoring package time due to wrong location: (Nothing,Local) @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.Installed src/Stack/Build/Installed.hs:189:5)
2016-09-10 17:41:28.300672: [debug] Run process: ghc-pkg --user --no-user-package-db --package-db /home/jiakai/.stack/snapshots/x86_64-linux/nightly-2016-08-13/8.0.1/pkgdb dump --expand-pkgroot @(stack_IZ6kIIshaMC0uV4dtbkAts:System.Process.Read src/System/Process/Read.hs:283:3)
2016-09-10 17:41:28.347943: [debug] Run process: ghc-pkg --user --no-user-package-db --package-db /home/jiakai/temp/snowflake/.stack-work/install/x86_64-linux/nightly-2016-08-13/8.0.1/pkgdb dump --expand-pkgroot @(stack_IZ6kIIshaMC0uV4dtbkAts:System.Process.Read src/System/Process/Read.hs:283:3)
2016-09-10 17:41:28.391668: [debug] Trying to decode /home/jiakai/.stack/indices/Hackage/00-index.cache @(stack_IZ6kIIshaMC0uV4dtbkAts:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:55:5)
2016-09-10 17:41:28.887885: [debug] Success decoding /home/jiakai/.stack/indices/Hackage/00-index.cache @(stack_IZ6kIIshaMC0uV4dtbkAts:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:64:13)
2016-09-10 17:41:29.107147: [warn] No packages found in snapshot which provide a "hsc2hs" executable, which is a build-tool dependency of "time-exts" @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.ConstructPlan src/Stack/Build/ConstructPlan.hs:147:11)
2016-09-10 17:41:29.107556: [warn] No packages found in snapshot which provide a "hsc2hs" executable, which is a build-tool dependency of "time-exts" @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.ConstructPlan src/Stack/Build/ConstructPlan.hs:147:11)
2016-09-10 17:41:29.107726: [warn] Missing build-tools may be caused by dependencies of the build-tool being overridden by extra-deps.
This should be fixed soon - see this issue https://github.com/commercialhaskell/stack/issues/595
 @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.ConstructPlan src/Stack/Build/ConstructPlan.hs:147:11)
2016-09-10 17:41:29.108774: [debug] Getting global package database location @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.GhcPkg src/Stack/GhcPkg.hs:48:5)
2016-09-10 17:41:29.108925: [debug] Run process: ghc-pkg --no-user-package-db list --global @(stack_IZ6kIIshaMC0uV4dtbkAts:System.Process.Read src/System/Process/Read.hs:283:3)
2016-09-10 17:41:29.182965: [info] aeson-1.0.0.0: configure @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.Execute src/Stack/Build/Execute.hs:731:23)
2016-09-10 17:41:29.187278: [debug] Run process: /home/jiakai/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 configure --with-ghc=/home/jiakai/.stack/programs/x86_64-linux/ghc-8.0.1/bin/ghc --with-ghc-pkg=/home/jiakai/.stack/programs/x86_64-linux/ghc-8.0.1/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/jiakai/.stack/snapshots/x86_64-linux/nightly-2016-08-13/8.0.1/pkgdb --package-db=/home/jiakai/temp/snowflake/.stack-work/install/x86_64-linux/nightly-2016-08-13/8.0.1/pkgdb --libdir=/home/jiakai/temp/snowflake/.stack-work/install/x86_64-linux/nightly-2016-08-13/8.0.1/lib --bindir=/home/jiakai/temp/snowflake/.stack-work/install/x86_64-linux/nightly-2016-08-13/8.0.1/bin --datadir=/home/jiakai/temp/snowflake/.stack-work/install/x86_64-linux/nightly-2016-08-13/8.0.1/share --libexecdir=/home/jiakai/temp/snowflake/.stack-work/install/x86_64-linux/nightly-2016-08-13/8.0.1/libexec --sysconfdir=/home/jiakai/temp/snowflake/.stack-work/install/x86_64-linux/nightly-2016-08-13/8.0.1/etc --docdir=/home/jiakai/temp/snowflake/.stack-work/install/x86_64-linux/nightly-2016-08-13/8.0.1/doc/aeson-1.0.0.0 --htmldir=/home/jiakai/temp/snowflake/.stack-work/install/x86_64-linux/nightly-2016-08-13/8.0.1/doc/aeson-1.0.0.0 --haddockdir=/home/jiakai/temp/snowflake/.stack-work/install/x86_64-linux/nightly-2016-08-13/8.0.1/doc/aeson-1.0.0.0 --dependency=attoparsec=attoparsec-0.13.0.2-HqM3fpGNp3Y9pstB2ohuIW --dependency=base=base-4.9.0.0 --dependency=base-compat=base-compat-0.9.1-7UjALQfeqODGdHbUgdNjDN --dependency=bytestring=bytestring-0.10.8.1 --dependency=containers=containers-0.5.7.1 --dependency=deepseq=deepseq-1.4.2.0 --dependency=dlist=dlist-0.8.0.1-8vOZASaQM8T5SLbodsdvHz --dependency=ghc-prim=ghc-prim-0.5.0.0 --dependency=hashable=hashable-1.2.4.0-H8WcftPh5eO8VmeTo4yOJ2 --dependency=scientific=scientific-0.3.4.9-HIPsjEW903zHfnOjdOgUhr --dependency=tagged=tagged-0.8.5-CtgV6EcN0do8F92i1S6iYx --dependency=template-haskell=template-haskell-2.11.0.0 --dependency=text=text-1.2.2.1-Emg4ZpWb6MuI6i7uLM9Qwl --dependency=time=time-1.5.0.1-7YRD6A110U85GkCfV2HErU --dependency=time-locale-compat=time-locale-compat-0.1.1.3-JjN36HJaDhPBjhEj5N0aVG --dependency=unordered-containers=unordered-containers-0.2.7.1-IJx0dRCqS3f9bHwMjJCS9Y --dependency=vector=vector-0.11.0.0-BEDZb5o2QOhGbIm6ky7rl6 @(stack_IZ6kIIshaMC0uV4dtbkAts:System.Process.Read src/System/Process/Read.hs:301:3)
2016-09-10 17:41:30.895694: [info] aeson-1.0.0.0: build @(stack_IZ6kIIshaMC0uV4dtbkAts:Stack.Build.Execute src/Stack/Build/Execute.hs:731:23)
2016-09-10 17:41:30.896119: [debug] Run process: /home/jiakai/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 build --ghc-options " -ddump-hi -ddump-to-file" @(stack_IZ6kIIshaMC0uV4dtbkAts:System.Process.Read src/System/Process/Read.hs:301:3)
Progress: 1/3
--  While building package aeson-1.0.0.0 using:
      /home/jiakai/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure (-11)
    Logs have been written to: /home/jiakai/temp/snowflake/.stack-work/logs/aeson-1.0.0.0.log

    Configuring aeson-1.0.0.0...
    Building aeson-1.0.0.0...
    Preprocessing library aeson-1.0.0.0...
    [ 1 of 19] Compiling Data.Aeson.Types.Generic ( Data/Aeson/Types/Generic.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Data/Aeson/Types/Generic.o )

    /tmp/stack14862/aeson-1.0.0.0/Data/Aeson/Types/Generic.hs:51:10: warning: [-Wredundant-constraints]
        • Redundant constraint: IsRecord f isRecord
        • In the instance declaration for ‘IsRecord (f :*: g) isRecord’

    /tmp/stack14862/aeson-1.0.0.0/Data/Aeson/Types/Generic.hs:58:10: warning: [-Wredundant-constraints]
        • Redundant constraint: IsRecord f isRecord
        • In the instance declaration for ‘IsRecord (M1 S c f) isRecord’

    /tmp/stack14862/aeson-1.0.0.0/Data/Aeson/Types/Generic.hs:70:10: warning: [-Wredundant-constraints]
        • Redundant constraints: (AllNullary a allNullaryL,
                                  AllNullary b allNullaryR,
                                  And allNullaryL allNullaryR allNullary)
        • In the instance declaration for ‘AllNullary (a :+: b) allNullary’

    /tmp/stack14862/aeson-1.0.0.0/Data/Aeson/Types/Generic.hs:74:10: warning: [-Wredundant-constraints]
        • Redundant constraint: AllNullary a allNullary
        • In the instance declaration for
            ‘AllNullary (M1 i c a) allNullary’
    [ 2 of 19] Compiling Data.Aeson.Internal.Functions ( Data/Aeson/Internal/Functions.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Data/Aeson/Internal/Functions.o )
    [ 3 of 19] Compiling Data.Aeson.Internal.Time ( Data/Aeson/Internal/Time.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Data/Aeson/Internal/Time.o )
    [ 4 of 19] Compiling Data.Aeson.Types.Internal ( Data/Aeson/Types/Internal.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Data/Aeson/Types/Internal.o )
    [ 5 of 19] Compiling Data.Aeson.Encoding.Builder ( Data/Aeson/Encoding/Builder.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Data/Aeson/Encoding/Builder.o )
    [ 6 of 19] Compiling Data.Aeson.Encoding.Internal ( Data/Aeson/Encoding/Internal.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Data/Aeson/Encoding/Internal.o )
    [ 7 of 19] Compiling Data.Aeson.Parser.Time ( Data/Aeson/Parser/Time.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Data/Aeson/Parser/Time.o )
    [ 8 of 19] Compiling Data.Aeson.Parser.Internal ( Data/Aeson/Parser/Internal.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Data/Aeson/Parser/Internal.o )
    [ 9 of 19] Compiling Data.Aeson.Parser ( Data/Aeson/Parser.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Data/Aeson/Parser.o )
    [10 of 19] Compiling Data.Aeson.Encoding ( Data/Aeson/Encoding.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Data/Aeson/Encoding.o )
    [11 of 19] Compiling Data.Aeson.Types.ToJSON ( Data/Aeson/Types/ToJSON.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Data/Aeson/Types/ToJSON.o )

    /tmp/stack14862/aeson-1.0.0.0/Data/Aeson/Types/ToJSON.hs:671:10: warning: [-Wredundant-constraints]
        • Redundant constraint: AllNullary (a :+: b) allNullary
        • In the instance declaration for ‘GToJSON arity (a :+: b)’

    /tmp/stack14862/aeson-1.0.0.0/Data/Aeson/Types/ToJSON.hs:726:10: warning: [-Wredundant-constraints]
        • Redundant constraint: AllNullary (a :+: b) allNullary
        • In the instance declaration for ‘GToEncoding arity (a :+: b)’

    /tmp/stack14862/aeson-1.0.0.0/Data/Aeson/Types/ToJSON.hs:1193:5: warning: [-Wredundant-constraints]
        • Redundant constraint: GToJSON arity a
        • In the instance declaration for ‘UntaggedValueObj arity (C1 c a)’

    /tmp/stack14862/aeson-1.0.0.0/Data/Aeson/Types/ToJSON.hs:1219:5: warning: [-Wredundant-constraints]
        • Redundant constraint: GToEncoding arity a
        • In the instance declaration for ‘UntaggedValueEnc arity (C1 c a)’

    /tmp/stack14862/aeson-1.0.0.0/Data/Aeson/Types/ToJSON.hs:1381:10: warning: [-Wredundant-constraints]
        • Redundant constraint: Integral a
        • In the instance declaration for ‘ToJSON (Ratio a)’

    /tmp/stack14862/aeson-1.0.0.0/Data/Aeson/Types/ToJSON.hs:1662:10: warning: [-Wredundant-constraints]
        • Redundant constraint: ToJSON a
        • In the instance declaration for ‘ToJSONKey (Identity a)’
```

### Stack version

```
[jiakai@iZ25uyotqyoZ ~]$ stack --version
Version 1.1.2, Git revision cebe10e845fed4420b6224d97dcabf20477bbd4b (3646 commits) x86_64 hpack-0.14.0
```

### Method of installation
https://docs.haskellstack.org/en/stable/install_and_upgrade/#centos

**Comment by Blaisorblade** [comment] 2016-09-20 00:58
@jiakai0419 `fast: true` disables optimization... 

Since your machine has only 1G, maybe it's running out of memory? Building with optimizations consumes more memory. ExitFailure (-11) should describe a segmentation fault, but if some native code has bugs, allocates memory and doesn't check the allocation succeeded, it will produce this kind of failure if the memory allocation fails. How much swap do you have? Can you check if memory is being exhausted? Which is your OS?

In general, there's the possibility is a compiler bug that only happens with optimizations. But this is not really enough evidence to suggest this.

But your log doesn't get up to the failure, so it's hard to tell what's happening right before the failure—or is that everything up to `Process exited with code: ExitFailure (-11)`.

**Comment by jiakai0419** [comment] 2016-09-20 03:30
Thanks

> How much swap do you have?

Swap has 0B

> Can you check if memory is being exhausted?

follow is the free status:

[jiakai@iZ25uyotqyoZ snowflake]$ /bin/sh loop_free.sh
              total        used        free      shared  buff/cache   available
Mem:           991M         50M        628M         37M        311M        776M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M         50M        628M         37M        311M        776M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M         50M        628M         37M        311M        776M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M         50M        628M         37M        311M        776M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        171M        507M         37M        312M        656M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        205M        472M         37M        313M        622M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        264M        413M         37M        313M        563M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        377M        295M         37M        318M        450M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        387M        282M         37M        322M        440M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        387M        281M         37M        322M        440M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        422M        246M         37M        322M        404M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        469M        199M         37M        322M        357M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        469M        198M         37M        323M        357M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        469M        196M         37M        325M        357M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        469M        196M         37M        324M        357M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        469M        196M         37M        324M        357M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        469M        196M         37M        324M        357M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        530M        135M         37M        325M        296M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        531M        134M         37M        325M        296M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        537M        128M         37M        325M        290M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        536M        127M         37M        327M        290M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        536M        127M         37M        327M        290M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        537M        126M         37M        327M        290M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        536M        125M         37M        329M        290M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        537M        125M         37M        329M        290M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        536M        125M         37M        329M        290M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        536M        125M         37M        329M        290M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        536M        125M         37M        329M        290M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        562M         98M         37M        330M        265M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        561M         99M         37M        330M        265M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        562M         95M         37M        334M        265M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        562M         95M         37M        334M        265M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        562M         95M         37M        334M        265M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        641M         59M         37M        290M        186M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        657M         75M         37M        258M        170M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        657M         75M         37M        258M        170M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        657M         75M         37M        258M        170M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        657M         75M         37M        258M        170M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        657M         75M         37M        258M        170M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        657M         75M         37M        258M        170M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        657M         75M         37M        258M        170M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        657M         75M         37M        258M        170M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        782M         71M         37M        138M         60M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        782M         70M         37M        138M         60M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        782M         70M         37M        139M         60M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        782M         70M         37M        139M         60M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        782M         69M         37M        139M         60M
Swap:            0B          0B          0B
              total        used        free      shared  buff/cache   available
Mem:           991M        782M         69M         37M        139M         60M
Swap:            0B          0B          0B


> Which is your OS?

[jiakai@iZ25uyotqyoZ snowflake]$ cat /proc/version
Linux version 3.10.0-327.28.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Wed Aug 3 11:11:39 UTC 2016

**Comment by Blaisorblade** [comment] 2016-09-20 03:42
1GB and no swap means builds are unlikely to complete, depending on
details; GHC easily uses up to 2GB. Is this a VM?
To actually fix your problem, options are to increase RAM size or add swap.
BTW Linux devs recommend to always have swap available (twice the size of
RAM).

It would still be good to not segfault, but if we're exhausting memory the
best we could do is to fail more properly, assuming I can reproduce this.
I'll see if I can confirm my explanation; by default, IIRC, malloc never
fails on Linux but I want to check details.

**Comment by jiakai0419** [comment] 2016-09-20 04:05
> Is this a VM?

Yes, it's Aliyun VM.

Fix my problem is not important. This is bug in my point.

**Comment by Blaisorblade** [comment] 2016-09-20 04:12
Agreed, thanks for caring and reporting it, I should have said this earlier!

**Comment by mgsloan** [comment] 2016-10-10 07:20
This is likely a segmentation fault from GHC or Cabal.  (-7) indicates running out of memory, whereas (-11) is segmentation fault.

@jiakai0419 Perhaps you are using a broken GHC installation?  It may be valuable to put `system-ghc: false` in your global `config.yaml`.  This will help ensure that your GHC is setup properly.

You may also want to run a memory check, it could be that your RAM has corruption.

**Comment by Blaisorblade** [comment] 2016-10-10 09:13
> This is likely a segmentation fault from GHC or Cabal. (-7) indicates running out of memory, whereas (-11) is segmentation fault.

Agreed on -11, confused on -7 — on x86 Linux that's SIGBUS, but the OOM seems to send SIGKILL.

But you can (in theory) easily get a segfault out of low-memory conditions and buggy programs, if there's a `malloc` whose return value is not checked and it fails:
```c
ptr = (struct foo*) malloc(size); //Can fail and return NULL
ptr->bar = 1; //segfault
```

Debugging this by code review is hard, but it would be easy _if given a core dump_ and with enough debug info.

Conditions under which malloc fails, on Linux, depend on overcommit accounting, but you need to be very short on memory without OOMing, so I have never seen this in practice. If I tried to reproduce this bug I'd start with /proc/sys/vm/overcommit_memory set to 2, but that might not be necessary.
https://www.kernel.org/doc/Documentation/vm/overcommit-accounting
http://www.win.tue.nl/~aeb/linux/lk/lk-9.html

**Comment by jiakai0419** [comment] 2016-10-11 15:26
@mgsloan 

> @jiakai0419 Perhaps you are using a broken GHC installation? It may be valuable to put system-ghc: false in your global config.yaml. This will help ensure that your GHC is setup properly.

follow is my global config.yaml content
```
[jiakai@iZ25uyotqyoZ .stack]$ pwd
/home/jiakai/.stack
[jiakai@iZ25uyotqyoZ .stack]$ cat config.yaml
# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
{}
```

**Comment by jiakai0419** [comment] 2016-10-11 15:31
@Blaisorblade what can do for you?

**Comment by jiakai0419** [comment] 2016-10-11 15:36
@Blaisorblade What can i do to help you solve this problem.

**Comment by Blaisorblade** [comment] 2016-10-11 15:41
@jiakai0419
> follow is my global config.yaml content

@mgsloan is suggesting to replace `{}` by `system-ghc: false`. Can you do that and check if the problem still appears?

**Comment by jiakai0419** [comment] 2016-10-11 16:03
The problem still appears.

**Comment by jiakai0419** [comment] 2016-10-11 16:04
```
[jiakai@iZ25uyotqyoZ .stack]$ pwd
/home/jiakai/.stack
[jiakai@iZ25uyotqyoZ .stack]$ cat config.yaml
# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#

system-ghc: false
```

**Comment by jiakai0419** [comment] 2016-10-11 16:08
i will give you the username and passwd, you enable to login in.

**Comment by jiakai0419** [comment] 2016-10-11 16:08
leave you mail for me

**Comment by jiakai0419** [comment] 2016-10-11 16:10
The problem still appears.
```
[jiakai@iZ25uyotqyoZ .stack]$ pwd
/home/jiakai/.stack
[jiakai@iZ25uyotqyoZ .stack]$ cat config.yaml
# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#

system-ghc: false
```

I will give you the username and passwd, you enable to login in.
please, leave you mail for me.

**Comment by Blaisorblade** [comment] 2016-10-11 16:12
I've just mailed you from p (dot) giarrusso (at) gmail (dot) com 😉 . FTR I think this is a GHC bug, but I'm curious to try and confirm this anyway.

**Comment by Blaisorblade** [comment] 2016-10-11 17:04
I think I figured this out, and it's indeed a trickier variant of the bug I described is in GHC's runtime system, not some random library.

**Comment by Blaisorblade** [comment] 2016-10-11 17:47
I've reported the bug in GHC runtime system as https://ghc.haskell.org/trac/ghc/ticket/12690. Since this is not a Stack issue I'm closing this issue—but please @jiakai0419 feel free to ask clarifications here.

I hope I won't need further access to your machine but I'd wait for the bug to be acknowledged by GHC devs to be sure.

**Comment by Blaisorblade** [comment] 2016-10-11 17:48
And BTW thanks again @jiakai0419 for pinging us on this, I'd probably not have diagnosed the bug otherwise!

**Closed** 2016-10-11 17:47 UTC
Labels: need repro

**Comment by jiakai0419** [comment] 2016-10-12 01:20
The contribution of small.
