### ISSUE TITLE
Make libcurl4-gnutls-dev dependency more obvious

### ISSUE THREAD

**Issue by jezen** [commercialhaskell/stack#2813] opened 2016-11-28 10:52 UTC
I am using a Haskell library — namely, Scalpel — which depends on `curl`. I had already installed `curl` on my system, or rather, it comes pre-installed on Ubuntu 16.04.

When trying to build my project with `stack build`, I am told `curl` is not installed on the system.

```
ubuntu@ubuntu-xenial:/vagrant/metascraper$ stack build
curl-1.3.8: configure
Progress: 1/3
--  While building package curl-1.3.8 using:
      /tmp/stack3917/curl-1.3.8/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.5.0 configure --with-ghc=/home/ubuntu/.stack/programs/x86_64-linux/ghc-7.10.3/bin/ghc --with-ghc-pkg=/home/ubuntu/.stack/programs/x86_64-linux/ghc-7.10.3/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/ubuntu/.stack/snapshots/x86_64-linux/lts-6.26/7.10.3/pkgdb --libdir=/home/ubuntu/.stack/snapshots/x86_64-linux/lts-6.26/7.10.3/lib --bindir=/home/ubuntu/.stack/snapshots/x86_64-linux/lts-6.26/7.10.3/bin --datadir=/home/ubuntu/.stack/snapshots/x86_64-linux/lts-6.26/7.10.3/share --libexecdir=/home/ubuntu/.stack/snapshots/x86_64-linux/lts-6.26/7.10.3/libexec --sysconfdir=/home/ubuntu/.stack/snapshots/x86_64-linux/lts-6.26/7.10.3/etc --docdir=/home/ubuntu/.stack/snapshots/x86_64-linux/lts-6.26/7.10.3/doc/curl-1.3.8 --htmldir=/home/ubuntu/.stack/snapshots/x86_64-linux/lts-6.26/7.10.3/doc/curl-1.3.8 --haddockdir=/home/ubuntu/.stack/snapshots/x86_64-linux/lts-6.26/7.10.3/doc/curl-1.3.8 --dependency=base=base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d --dependency=bytestring=bytestring-0.10.6.0-9a873bcf33d6ce2fd2698ce69e2c1c66 --dependency=containers=containers-0.5.6.2-59326c33e30ec8f6afd574cbac625bbb -fnew-base
    Process exited with code: ExitFailure 1
    Logs have been written to: /vagrant/metascraper/.stack-work/logs/curl-1.3.8.log

    [1 of 1] Compiling Main             ( /tmp/stack3917/curl-1.3.8/Setup.hs, /tmp/stack3917/curl-1.3.8/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/setup/Main.o )
    Linking /tmp/stack3917/curl-1.3.8/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/setup/setup ...
    Configuring curl-1.3.8...
    setup: Missing dependency on a foreign library:
    * Missing C library: curl
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
```

After some digging, I found this SO answer: http://stackoverflow.com/a/25098250/704015

As it turns out, running `sudo apt-get install libcurl4-gnutls-dev` makes Stack understand how to use `curl`, but this is not obvious to a newcomer to the Haskell ecosystem.

How can we make this more obvious? I would expect Elm-style hand-holding if possible.

**Comment by mgsloan** [comment] 2016-11-29 04:01
Unfortunately, it is not straightforward to do this.  Why?

1) We'd need to parse out the error message from Cabal
2) We'd need to have knowledge of how the C library dependency can be provided via the user's package manager (not necessarily ubuntu)

So, closing this as wontfix.

**Closed by mgsloan** 2016-11-29 04:01 UTC

**Comment by lwm** [comment] 2018-02-25 11:32
Got bitten by this - any way at all to make this less painful? At least the issue is here :)

**Comment by mgsloan** [comment] 2018-02-25 22:03
@lwm Not sure.  It's also tracked by https://github.com/commercialhaskell/stack/issues/2448 .  There is some further discussion in https://github.com/commercialhaskell/stack/issues/1384
