### ISSUE TITLE
stack build distributive fails on Windows

### ISSUE THREAD

**Issue by Evthestrike** [commercialhaskell/stack#5432] opened 2020-11-15 05:54 UTC
Steps to reproduce:
1. use windows
2. run 'stack build distributive'

Error:
```
distributive> configure
distributive> [1 of 2] Compiling Main             ( C:\\Users\evthe\AppData\Local\Temp\stack-5e582187bf0ba66a\distributive-0.6.2\Setup.lhs, C:\\Users\evthe\AppData\Local\Temp\stack-5e582187bf0ba66a\distributive-0.6.2\.stack-work\dist\a3a5fe88\setup\Main.o )
distributive> [2 of 2] Compiling StackSetupShim   ( C:\\sr\setup-exe-src\setup-shim-Z6RU0evB.hs, C:\\Users\evthe\AppData\Local\Temp\stack-5e582187bf0ba66a\distributive-0.6.2\.stack-work\dist\a3a5fe88\setup\StackSetupShim.o )
distributive> Linking C:\\Users\\evthe\\AppData\\Local\\Temp\\stack-5e582187bf0ba66a\\distributive-0.6.2\\.stack-work\\dist\\a3a5fe88\\setup\\setup.exe ...
distributive> Configuring distributive-0.6.2...
distributive> build
distributive> Preprocessing library for distributive-0.6.2..
distributive> Building library for distributive-0.6.2..
distributive> [1 of 2] Compiling Data.Distributive
distributive> [2 of 2] Compiling Data.Distributive.Generic
distributive> copy/register
distributive> copyFile: permission denied (The process cannot access the file because it is being used by another process.)

--  While building package distributive-0.6.2 (scroll up to its section to see the error) using:
      C:\Users\evthe\AppData\Local\Temp\stack-5e582187bf0ba66a\distributive-0.6.2\.stack-work\dist\a3a5fe88\setup\setup --builddir=.stack-work\dist\a3a5fe88 copy
    Process exited with code: ExitFailure 1

Possible causes of this issue:
* No module named "Main". The 'main-is' source file should usually have a header indicating that it's a 'Main' module.
* A cabal file that refers to nonexistent other files (e.g. a license-file that doesn't exist). Running 'cabal check' may point out these issues.
* The Setup.hs file is changing the installation target dir.
```

stack version 2.5.1

installed using windows executable

**Comment by Evthestrike** [comment] 2020-11-15 08:23
About 1/2 of the libraries I try to install use distributive and they all fail at the copy/register command.

**Comment by Evthestrike** [comment] 2020-11-18 19:31
I found  [this thread](https://github.com/commercialhaskell/stack/issues/5115) with the same issue, but it is on a different OS. Could it be a problem with my operating system? I'm running Windows 10

**Comment by mpilgrem** [comment] 2024-03-10 18:25
I am closing this given the passage of time and because I can't reproduce this on Windows 11 with the current version of Stack and LTS 22.13:
~~~text
stack build distributive
~~~

works as expected.

**Closed by mpilgrem** 2024-03-10 18:25 UTC
Labels: component: windows, further investigation required
