### ISSUE TITLE
Problem installing attoparsec package

### ISSUE THREAD

**Issue by kdavy** [commercialhaskell/stack#951] opened 2015-09-08 15:16 UTC
I am a haskell/stack noob so I may have done something stupid.

I am running stack 1.4.1 and I'm trying to install the attoparsec package and I keep getting the error below.   In this example I am running outside of any particular project, but I am having the same issue when try it inside a project.  I also have the same problem when I have attoparsec as a build-dependency in my .cabal file and I run stack install.  

I have haskell platform installed as well and I don't know if that might be contributing to the problem.  

 Thanks!

Here is what's happening....

stack install attoparsec
Run from outside a project, using implicit global config
Using resolver: lts-3.2 from global config file: /Users/kdavy/.stack/global/stack.yaml
attoparsec-0.12.1.6: configure
attoparsec-0.12.1.6: build

--  While building package attoparsec-0.12.1.6 using:
      /Users/kdavy/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ build --ghc-options -hpcdir .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/hpc/.hpc/ -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/kdavy/.stack/global/.stack-work/logs/attoparsec-0.12.1.6.log

    Configuring attoparsec-0.12.1.6...
    Warning: This package indirectly depends on multiple versions of the same
    package. This is highly likely to cause a compile failure.
    package hashable-1.2.3.3 requires text-1.2.1.3
    package scientific-0.3.3.8 requires text-1.2.1.3
    package attoparsec-0.12.1.6 requires text-1.2.1.3
    Building attoparsec-0.12.1.6...
    Preprocessing library attoparsec-0.12.1.6...
    <command line>: cannot satisfy -package-id scientific-0.3.3.8-40684b56dd431830e064742a22d331e4: 
        scientific-0.3.3.8-40684b56dd431830e064742a22d331e4 is unusable due to missing or recursive dependencies:
          hashable-1.2.3.3-09c4177c49dd46a63f7036317bb17114
        (use -v for more information)

**Comment by snoyberg** [comment] 2015-09-08 15:20
This is the second Haskell Platform related problem I've seen around hashable in the past 24 hours. Can you try running the following to bypass the HP-installed GHC and packages?

    stack --no-system-ghc --install-ghc build attoparsec

It will take some time to download GHC, but hopefully will succeed. If you can confirm this, I'd recommend:

1. Deleting the Haskell Platform from your system
2. Sending a bug report to the HP team. The other bug report is at http://stackoverflow.com/questions/32444762/cabal-repl-wont-run-cant-load-so-dll-for/32448268, but I have not yet seen confirmation there that that's the cause

**Comment by snoyberg** [comment] 2015-09-08 15:26
This may actually be a distinct issue from the other one. If you could also provide a paste/Gist of the `stack build attoparsec --verbose` output, that would be useful.

**Comment by kdavy** [comment] 2015-09-08 15:52
Here's the result of running with --verbose:

```
stack build attoparsec --verbose
Version 0.1.4.1 (UNKNOWN commits) X86_64
2015-09-08 15:51:20.144019: [debug] Checking for project config at: /Users/kdavy/playing/stack.yaml @(stack_FhlmuwqZDji0WhaDijVRMV:Stack.Config src/Stack/Config.hs:466:9)
2015-09-08 15:51:20.144174: [debug] Checking for project config at: /Users/kdavy/stack.yaml @(stack_FhlmuwqZDji0WhaDijVRMV:Stack.Config src/Stack/Config.hs:466:9)
2015-09-08 15:51:20.144272: [debug] Checking for project config at: /Users/stack.yaml @(stack_FhlmuwqZDji0WhaDijVRMV:Stack.Config src/Stack/Config.hs:466:9)
2015-09-08 15:51:20.14433: [debug] Checking for project config at: /stack.yaml @(stack_FhlmuwqZDji0WhaDijVRMV:Stack.Config src/Stack/Config.hs:466:9)
2015-09-08 15:51:20.144382: [debug] No project config file found, using defaults. @(stack_FhlmuwqZDji0WhaDijVRMV:Stack.Config src/Stack/Config.hs:493:13)
2015-09-08 15:51:20.172308: [info] Run from outside a project, using implicit global config @(stack_FhlmuwqZDji0WhaDijVRMV:Stack.Config src/Stack/Config.hs:242:13)
2015-09-08 15:51:20.172973: [info] Using resolver: lts-3.2 from global config file: /Users/kdavy/.stack/global/stack.yaml @(stack_FhlmuwqZDji0WhaDijVRMV:Stack.Config src/Stack/Config.hs:256:32)
2015-09-08 15:51:20.202686: [debug] Trying to decode /Users/kdavy/.stack/build-plan-cache/x86_64-osx/lts-3.2.cache @(stack_FhlmuwqZDji0WhaDijVRMV:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:77:5)
2015-09-08 15:51:20.21361: [debug] Success decoding /Users/kdavy/.stack/build-plan-cache/x86_64-osx/lts-3.2.cache @(stack_FhlmuwqZDji0WhaDijVRMV:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:86:13)
2015-09-08 15:51:20.239577: [debug] Run process: ghc --info @(stack_FhlmuwqZDji0WhaDijVRMV:System.Process.Read src/System/Process/Read.hs:260:3)
2015-09-08 15:51:20.297733: [debug] Run process: ghc --numeric-version @(stack_FhlmuwqZDji0WhaDijVRMV:System.Process.Read src/System/Process/Read.hs:260:3)
2015-09-08 15:51:20.327233: [debug] Run process: ghc-pkg --no-user-package-db field --simple-output Cabal id @(stack_FhlmuwqZDji0WhaDijVRMV:System.Process.Read src/System/Process/Read.hs:260:3)
2015-09-08 15:51:20.362182: [debug] Run process: ghc-pkg --no-user-package-db list --global @(stack_FhlmuwqZDji0WhaDijVRMV:System.Process.Read src/System/Process/Read.hs:260:3)
2015-09-08 15:51:20.396239: [debug] Checking resolver: lts-3.2 @(stack_FhlmuwqZDji0WhaDijVRMV:Stack.Build.Source src/Stack/Build/Source.hs:162:17)
2015-09-08 15:51:20.396345: [debug] Trying to decode /Users/kdavy/.stack/build-plan-cache/x86_64-osx/lts-3.2.cache @(stack_FhlmuwqZDji0WhaDijVRMV:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:77:5)
2015-09-08 15:51:20.419268: [debug] Success decoding /Users/kdavy/.stack/build-plan-cache/x86_64-osx/lts-3.2.cache @(stack_FhlmuwqZDji0WhaDijVRMV:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:86:13)
2015-09-08 15:51:20.419984: [debug] Trying to decode /Users/kdavy/.stack/indices/Hackage/00-index.cache @(stack_FhlmuwqZDji0WhaDijVRMV:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:77:5)
2015-09-08 15:51:20.656544: [debug] Success decoding /Users/kdavy/.stack/indices/Hackage/00-index.cache @(stack_FhlmuwqZDji0WhaDijVRMV:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:86:13)
2015-09-08 15:51:20.656703: [debug] Run process: ghc-pkg --global --no-user-package-db dump --expand-pkgroot @(stack_FhlmuwqZDji0WhaDijVRMV:System.Process.Read src/System/Process/Read.hs:260:3)
2015-09-08 15:51:20.716648: [debug] Run process: ghc-pkg --user --no-user-package-db --package-db /Users/kdavy/.stack/snapshots/x86_64-osx/lts-3.2/7.10.2/pkgdb/ dump --expand-pkgroot @(stack_FhlmuwqZDji0WhaDijVRMV:System.Process.Read src/System/Process/Read.hs:260:3)
2015-09-08 15:51:20.832763: [debug] Run process: ghc-pkg --user --no-user-package-db --package-db /Users/kdavy/.stack/global/.stack-work/install/x86_64-osx/lts-3.2/7.10.2/pkgdb/ dump --expand-pkgroot @(stack_FhlmuwqZDji0WhaDijVRMV:System.Process.Read src/System/Process/Read.hs:260:3)
2015-09-08 15:51:20.866437: [debug] Trying to decode /Users/kdavy/.stack/indices/Hackage/00-index.cache @(stack_FhlmuwqZDji0WhaDijVRMV:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:77:5)
2015-09-08 15:51:21.054607: [debug] Success decoding /Users/kdavy/.stack/indices/Hackage/00-index.cache @(stack_FhlmuwqZDji0WhaDijVRMV:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:86:13)
2015-09-08 15:51:21.054741: [debug] Trying to decode /Users/kdavy/.stack/indices/Hackage/00-index.cache @(stack_FhlmuwqZDji0WhaDijVRMV:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:77:5)
2015-09-08 15:51:21.248183: [debug] Success decoding /Users/kdavy/.stack/indices/Hackage/00-index.cache @(stack_FhlmuwqZDji0WhaDijVRMV:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:86:13)
2015-09-08 15:51:21.324778: [debug] Run process: ghc-pkg --no-user-package-db list --global @(stack_FhlmuwqZDji0WhaDijVRMV:System.Process.Read src/System/Process/Read.hs:260:3)
2015-09-08 15:51:21.359566: [debug] Trying to decode /Users/kdavy/.stack/indices/Hackage/00-index.cache @(stack_FhlmuwqZDji0WhaDijVRMV:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:77:5)
2015-09-08 15:51:21.527672: [debug] Success decoding /Users/kdavy/.stack/indices/Hackage/00-index.cache @(stack_FhlmuwqZDji0WhaDijVRMV:Data.Binary.VersionTagged src/Data/Binary/VersionTagged.hs:86:13)
2015-09-08 15:51:21.760303: [info] attoparsec-0.12.1.6: configure @(stack_FhlmuwqZDji0WhaDijVRMV:Stack.Build.Execute src/Stack/Build/Execute.hs:587:23)
2015-09-08 15:51:21.76041: [debug] Run process: /Users/kdavy/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ configure --user --package-db=clear --package-db=global --package-db=/Users/kdavy/.stack/snapshots/x86_64-osx/lts-3.2/7.10.2/pkgdb/ --libdir=/Users/kdavy/.stack/snapshots/x86_64-osx/lts-3.2/7.10.2/lib --bindir=/Users/kdavy/.stack/snapshots/x86_64-osx/lts-3.2/7.10.2/bin --datadir=/Users/kdavy/.stack/snapshots/x86_64-osx/lts-3.2/7.10.2/share --libexecdir=/Users/kdavy/.stack/snapshots/x86_64-osx/lts-3.2/7.10.2/libexec --sysconfdir=/Users/kdavy/.stack/snapshots/x86_64-osx/lts-3.2/7.10.2/etc --docdir=/Users/kdavy/.stack/snapshots/x86_64-osx/lts-3.2/7.10.2/doc/attoparsec-0.12.1.6 --htmldir=/Users/kdavy/.stack/snapshots/x86_64-osx/lts-3.2/7.10.2/doc/attoparsec-0.12.1.6 --haddockdir=/Users/kdavy/.stack/snapshots/x86_64-osx/lts-3.2/7.10.2/doc/attoparsec-0.12.1.6 --dependency=array=array-0.5.1.0-d4206b835b96b5079d918fa1eab1a9a8 --dependency=base=base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f --dependency=bytestring=bytestring-0.10.6.0-6e8453cb70b477776f26900f41a5e17a --dependency=containers=containers-0.5.6.2-2b49cce16f8a2908df8454387e550b93 --dependency=deepseq=deepseq-1.4.1.1-5de90d6c626db2476788444fb08c1eb3 --dependency=scientific=scientific-0.3.3.8-40684b56dd431830e064742a22d331e4 --dependency=text=text-1.2.1.3-3718968f98d5614ccdc45c27d4e8b0a1 @(stack_FhlmuwqZDji0WhaDijVRMV:Stack.Build.Execute src/Stack/Build/Execute.hs:696:21)
2015-09-08 15:51:23.11327: [info] attoparsec-0.12.1.6: build @(stack_FhlmuwqZDji0WhaDijVRMV:Stack.Build.Execute src/Stack/Build/Execute.hs:587:23)
2015-09-08 15:51:23.113408: [debug] Run process: /Users/kdavy/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ build --ghc-options "-hpcdir .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/hpc/.hpc/ -ddump-hi -ddump-to-file" @(stack_FhlmuwqZDji0WhaDijVRMV:Stack.Build.Execute src/Stack/Build/Execute.hs:696:21)

--  While building package attoparsec-0.12.1.6 using:
      /Users/kdavy/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ build --ghc-options -hpcdir .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/hpc/.hpc/ -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/kdavy/.stack/global/.stack-work/logs/attoparsec-0.12.1.6.log

    Configuring attoparsec-0.12.1.6...
    Warning: This package indirectly depends on multiple versions of the same
    package. This is highly likely to cause a compile failure.
    package hashable-1.2.3.3 requires text-1.2.1.3
    package scientific-0.3.3.8 requires text-1.2.1.3
    package attoparsec-0.12.1.6 requires text-1.2.1.3
    Building attoparsec-0.12.1.6...
    Preprocessing library attoparsec-0.12.1.6...
    <command line>: cannot satisfy -package-id scientific-0.3.3.8-40684b56dd431830e064742a22d331e4: 
        scientific-0.3.3.8-40684b56dd431830e064742a22d331e4 is unusable due to missing or recursive dependencies:
          hashable-1.2.3.3-09c4177c49dd46a63f7036317bb17114
        (use -v for more information)
```

**Comment by snoyberg** [comment] 2015-09-08 15:57
The next output will be quite large, so please capture to a file and upload separately:

    stack exec -- ghc-pkg dump

**Comment by kdavy** [comment] 2015-09-08 15:58
When I enter
```
 stack --no-system-ghc --install-ghc build attoparsec
```

nothing happens.  There is no output and it almost immediatly gives me a new prompt.

**Comment by snoyberg** [comment] 2015-09-08 15:59
Huh. Sounds like you're alternatively using a stack-installed GHC and the Haskell Platform-installed GHC, which have different sets of installed packages in the global database, leading to this confusion. If you remove the HP-installed GHC from your PATH, or use the `--no-system-ghc` argument or set `system-ghc: false` in your stack.yaml file, things should work. Though it would be good if stack was able to detect this situation better.

**Comment by kdavy** [comment] 2015-09-08 17:13
That seems to have solved my problem.  Thanks for the help with this!

**Comment by snoyberg** [comment] 2015-09-09 05:38
No problem, closing.

**Closed by snoyberg** 2015-09-09 05:38 UTC
