### ISSUE TITLE
stack setup 7.8.4 fails sanity check on Windows

### ISSUE THREAD

**Issue by ygale** [commercialhaskell/stack#3213] opened 2017-06-12 14:03 UTC
### General summary/comments (optional)

`stack setup 7.8.4` on Windows fails with the following error message (sanitized by replacing the actual `AppData` path with `%AppData%`):

    The GHC located at %AppData%\Local\Programs\stack\x86_64-windows\ghc-7.8.4\bin\ghc.EXE failed to compile a sanity check. Please see:
    
        http://docs.haskellstack.org/en/stable/install_and_upgrade/
    
    for more information. Exception was:
    Running %AppData%\Local\Programs\stack\x86_64-windows\ghc-7.8.4\bin\ghc.EXE %AppData%\Local\Temp\stack-sanity-check4848\Main.hs -no-user-package-db in directory %AppData%\Local\Temp\stack-sanity-check4848\ exited with ExitFailure 1
    
    [1 of 1] Compiling Main             ( %AppData%\Local\Temp\stack-sanity-check4848\Main.hs, %AppData%\Local\Temp\stack-sanity-check4848\Main.o )
    
    
    <no location info>:
        Warning: Couldn't figure out linker information!
                 Make sure you're using GNU gcc, or clang
    Unable to start %AppData%\Local\Programs\stack\x86_64-windows\ghc-7.8.4\mingw\bin/realgcc.exe (error code: 2

**Workaround:** Copy the file

    %APPDATA%\Local\Programs\stack\x86_64-windows\ghc-7.8.4\mingw\bin\x86_64-w64-mingw32-gcc.exe

to `realgcc.exe` in the same folder.

### Steps to reproduce

    stack setup 7.8.4

### Expected

Successful installation of GHC version 7.8.4.

### Actual

The error message above. After performing the above workaround, GHC version 7.8.4 then works fine.

### Stack version

    Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd x86_64 hpack-0.17.0

### Method of installation

* Official Windows 64-bit MSI, downloaded from stackage.org

**Comment by mgsloan** [comment] 2017-08-07 01:49
Likely related to https://github.com/commercialhaskell/stack/issues/3189 / https://github.com/commercialhaskell/stack/issues/2998 .  Thanks for the report and workaround, but I don't think there's anything to be done here within stack.  Would probably require backporting a fix to ghc 7.8

**Comment by Rufflewind** [comment] 2017-09-15 21:41
I'm not sure this is actually related to either of those other issues.

If we look at the official https://downloads.haskell.org/~ghc/7.8.4/ghc-7.8.4-x86_64-unknown-mingw32.tar.xz we find that it is indeed missing `realgcc`.  However, `ghc` and `gcc` run just fine.

This is not true for Stack's GHC distribution.  I did a diff between the two GHC trees and the *only* difference is that Stack's `gcc` is different.  It is in fact much smaller, which suggests it is a thin wrapper to another executable.

Therefore, it looks to me that somewhere down the line the official GHC tarball was patched to replace `gcc` without the necessary `realgcc`, and that is the cause of the error we're seeing.

**Comment by mgsloan** [comment] 2017-09-15 23:26
Hmm, that's weird that the two tarballs are different, not sure which should be preferred, or why there is a different.  Pinging @borsboom

**Comment by behaghel** [comment] 2019-07-20 17:19
I encountered the same issue today with 7.10.2 installed via Haskell Platform 8.6.5 on Windows 10. The workaround worked.

**Comment by mpilgrem** [comment] 2024-03-17 20:13
I am closing the issue given the passage of time.

**Closed by mpilgrem** 2024-03-17 20:13 UTC
Labels: component: Windows
