### ISSUE TITLE
`commitBuffer: invalid argument` after `stack upgrade`

### ISSUE THREAD

**Issue by srutownik** [commercialhaskell/stack#1870] opened 2016-03-03 10:28 UTC
Recently, I have run command `stack upgrade`. Now `stack --versions` says:

```
Version 1.0.4, Git revision cf18703b1392a96a5a4896a560309e501af63260 (3220 commits) x86_64
```

After that, building my project fails while building `transformers-base`. `stack build transformers-base` does not work either.
I have cleaned every place mentioned by `stack --path`, but didn't help.
I still can build transformers-base using stack Version 0.1.7.0.

Related build log:

```
stack build transformers-base-0.4.4
Setting codepage to UTF-8 (65001) to ensure correct output from GHC
transformers-base-0.4.4: configure
transformers-base-0.4.4: build

--  While building package transformers-base-0.4.4 using:
      C:\Users\marek\AppData\Roaming\stack\setup-exe-cache\x86_64-windows\setup-Simple-Cabal-1.22.4.0-ghc-7.8.4.exe --builddir=.stack-work\dist\d96ab9d9 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\dev\stack-repro\r\repro\.stack-work\logs\transformers-base-0.4.4.log

    Configuring transformers-base-0.4.4...
    Building transformers-base-0.4.4...
    Preprocessing library transformers-base-0.4.4...
    [1 of 1] Compiling Control.Monad.Base ( src\Control\Monad\Base.hs, .stack-work\dist\d96ab9d9\build\Control\Monad\Base.o )
    .stack-work\dist\d96ab9d9\build\src\Control\Monad\Base.dump-hi: commitBuffer: invalid argument (invalid character)
```

**Comment by mgsloan** [comment] 2016-03-03 22:29
See this issue for more info: https://github.com/commercialhaskell/stack/issues/793

Seems like for some reason

> Setting codepage to UTF-8 (65001) to ensure correct output from GHC

Isn't enough for your circumstance.

**Comment by pmlodawski** [comment] 2016-03-17 20:39
I had recently the same problem and to fix this I need to downgrade `stack`. Seems like stack having regression.

**Comment by schernichkin** [comment] 2016-04-08 17:05
Having same problem on windows. [Here](https://github.com/commercialhaskell/stack/blob/51492566184b4f98106de0e8199c8962dace567e/src/Stack/Build.hs#L283) we had a hack for Windows but it will not be applied for 7.10.3. Well, it seems we still need it on 7.10.3.

**Comment by atc-** [comment] 2016-05-19 20:14
I'm trying to build a project with stack on Windows 10 that depends on the following:

```
library
  hs-source-dirs:      src
  exposed-modules:     Lib
  build-depends:       base >= 4.7 && < 5
                     , aeson
                     , servant-server
                     , wai
                     , warp
                     , postgresql-simple
                     , servant-ede
  default-language:    Haskell2010

```

which fails with the invalid character error:

```
    Configuring transformers-base-0.4.4...
    Building transformers-base-0.4.4...
    Preprocessing library transformers-base-0.4.4...
    [1 of 1] Compiling Control.Monad.Base ( src\Control\Monad\Base.hs, .stack-work\dist\d96ab9d9\build\Control\Monad\Base.o )

    C:\Users\atc\AppData\Local\Temp\stack13748\transformers-base-0.4.4\src\Control\Monad\Base.hs:22:1: Warning:
        The import of `Data.Monoid' is redundant
          except perhaps to import instances from `Data.Monoid'
        To import instances alone, use: import Data.Monoid()

    C:\Users\atc\AppData\Local\Temp\stack13748\transformers-base-0.4.4\src\Control\Monad\Base.hs:24:1: Warning:
        The import of `Control.Applicative' is redundant
          except perhaps to import instances from `Control.Applicative'
        To import instances alone, use: import Control.Applicative()
    .stack-work\dist\d96ab9d9\build\src\Control\Monad\Base.dump-hi: commitBuffer: invalid argument (invalid character)

C:\Users\atc\src\project>work\dist\d96ab9d9\build\src\Control\Monad\Base.dump-hi: commitBuffer: invalid argument (invalid character)
The system cannot find the path specified.

```
Version info:

`stack --version
Version 1.0.4, Git revision cf18703b1392a96a5a4896a560309e501af63260 (3220 commits) x86_64`

```
extra-deps:
- servant-ede-0.5.1
resolver: lts-3.4

```

**Comment by mgsloan** [comment] 2016-05-19 21:05
This is a ghc issue, resolved in 7.10.3: https://ghc.haskell.org/trac/ghc/ticket/6037 https://ghc.haskell.org/trac/ghc/ticket/9752

So, use a resolver that uses 7.10.3.  For existing stack configs from 3rd parties you may even be able to get away with doing `stack build --compiler ghc-7.10.3`

**Comment by atc-** [comment] 2016-05-20 08:41
Thanks, I wasn't aware this was a GHC issue and found this issue via Google so thought I'd post any relevant information here.

For anyone else that arrives here needing to fix this problem, according [these instructions](https://www.stackage.org/lts-5.17) one can use lts-5.17 in my stack.yml to resolve GHC 7.10.3:

> 
> Edit your stack.yaml and set the following:
> 
> resolver: lts-5.17
> 
> You can also use --resolver lts-5.17 on the command line

**Comment by schernichkin** [comment] 2016-05-20 15:01
Guys, guys, guys I'd like to emphasize what I have this problem on GHC-7.10.3 even with lts-5.17, so switching to GHC-7.10.3 does **not** fix it. In particular criterion benchmarks will fail because criterion attempts to output 'μ' to console. I had not this problem with stack 1.0.

**Comment by mgsloan** [comment] 2016-05-20 19:18
Ok, reopening.  Thanks for the specific repro which I can try.

**Comment by schernichkin** [comment] 2016-05-20 21:43
Just to make sure it's fully reproducible.

Here the small repository: https://github.com/PROTEINE-INSAIDERS/win-unicode-failure-demo If you'll run `stack test` on it, it will crash writing something like:

    win-unicode-failure-demo-0.1.0.0: test (suite: win-unicode-failure-demo-test)

    KABOOM!win-unicode-failure-demo-test.exe: <stdout>: commitBuffer: invalid argument (invalid character)

    Test suite failure for package win-unicode-failure-demo-0.1.0.0
        win-unicode-failure-demo-test:  exited with: ExitFailure 1
    Logs printed to console

Or you may reproduce it from scratch in few steps:
1. `stack new my-project`
2. Edit Spec.hs to output some non-ASCII.
3. `stack test`

Reason: 
- GHC prohibits your from printing any characters not supported by your system. Err.. Not supported from the GHC's point of view, I'm using mingw tty and unicode supported there just fine.

Why ~~does this cause pain in the ass~~ it would be nice to keep unicode workaround?
- Because of lot Haskell tools actually use unicode. The most common example is probably "criterion", but not limited to. And from the mathematical point of view it would be correct to delegate this problem to authors of GHC. Because this is not really Stack problem. But as for me, I'm using Stack because it just works. Yep, The Working Solution is the Stack's buisness value. So, I don't see any harm in the extending Stack's unicode workaround beyond the GHC 7.10.3

**Comment by rbasso** [comment] 2016-06-03 13:27
Bug reproduced with `stack test` in the supplied repository. Tested with **stack 1.1.2**, **ghc-7.10.3** AND **ghc-8.0.1**, in NixOS Unstable.

My benchmark suites written with *criterion* have the same behavior, failing with `commitBuffer: invalid argument`, but they work perfectly if run with `cabal bench`.

**Comment by rbasso** [comment] 2016-06-03 14:59
Bug reproduced with `stack test` in the supplied repository. Tested with **stack 1.1.2**, **ghc-7.10.3** AND **ghc-8.0.1**, in NixOS Unstable.

My benchmark suites written with *criterion* have the same behavior, failing with `commitBuffer: invalid argument`, but they work perfectly with `cabal bench`.

**Comment by fosskers** [comment] 2016-06-20 00:38
Just had this happen after a system update this morning. My criterion benchmarks no longer work.

**Comment by sjakobi** [comment] 2016-07-14 14:36
I can't reproduce this with ghc-7.10.3 or ghc-8.0.1 on Ubuntu 14.04.

@mgsloan: What's the reason for the low priority and removing the `bug` label?

**Comment by rbasso** [comment] 2016-07-14 16:45
@fosskers, could you explain what was wrong with you locale? This may help me understand why this happens here in Nixos with `stack test` but not with `cabal test --log=/dev/stdout`.
I also cannot reproduce it in Debian jessie (stable), @sjakobi.

**Comment by rbasso** [comment] 2016-07-14 17:00
@fosskers, could you explain what was wrong with you locale? This may help me understand why this happens here in Nixos with `stack test` but not with `cabal test --log=/dev/stdout`.
I also cannot reproduce it in Debian jessie (stable), @sjakobi.

**Comment by sjakobi** [comment] 2016-07-14 17:03
@rbasso: It might be a long shot but maybe this issue is related to https://github.com/commercialhaskell/stack/issues/2358?!

**Comment by rbasso** [comment] 2016-07-14 19:58
Congratulations, @sjakobi. You found it! Thanks!

The problem seems to be that when stack is run with nix `--pure`, it unsets the locale variables.

`stack test --no-nix-pure` works normally here!

@srutownik, are you using stack with nix too?

**Comment by fosskers** [comment] 2016-07-21 23:48
@rbasso between my system config (`/etc/...`), my login config, and my shell settings, I was having a hell of a time getting my locale settings set to `en_US.UTF-8` in a persistant way. I ended up putting the following in my fish config:

```
 set -x LANG 'en_US.UTF-8'
 set -x LC_ALL 'en_US.UTF-8'
```

**Comment by francesquini** [comment] 2017-02-14 14:40
I had the same issue on Windows 10 (pt-BR). Setting the "Language for non-Unicode Programs" to "English (US)" solved the problem....

**Comment by jgrosso** [comment] 2017-05-06 17:20
I had the "Language for non-Unicode Programs" set to "English (US)" and was still seeing the problem (Windows 10 Creators Update), but running `chcp.com 65001` (as per http://stackoverflow.com/a/27622364/2391244) fixed the issue for me.

**Comment by snoyberg** [comment] 2019-04-07 09:06
Is anyone still seeing this with recent versions of Stack (>= 1.9) and GHC (>= 8.4)?

**Comment by snoyberg** [comment] 2019-04-12 15:14
Closing, if someone has a more recent repro, please ping here or open a new issue.

**Closed by snoyberg** 2019-04-12 15:14 UTC
Labels: awaiting pull request, type: enhancement
