### ISSUE TITLE
Add "stack upload --test", to build and test the sdist before uploading

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1350] opened 2015-11-16 08:46 UTC
In addition to the cabal metadata check described in #1183, to me it makes a whole lot of sense to also support unpacking + building + testing the tarball.  I'm thinking that this would look like having a `--test` or `--check` flag.  It might also be sensible to just make this a default and have a `--no-test` flag.

In order to support build options, we'd need to add all of the build flags to the sdist command.  This was recently done with ghci.  It seems ugly to have all of those flags in `--help` when they are only relevant when `--test` is passed, though..

One possible alternative would be to have `--test-with "--pedantic"`, which takes a list of build flags.

**Comment by mgsloan** [comment] 2015-11-16 08:56
Implementation-wise, I think here's what this'll look like:

* Unpack the tarball
* Load the stack.yaml config
* Remove the target package from the packages list, and add in the tarball unpack directory
* Build and test the target package
* Continue with upload if successful

**Comment by sjakobi** [comment] 2016-07-13 20:40
Closing as a duplicate of #717 and #888, moving the ideas here to #717.

**Closed by sjakobi** 2016-07-13 20:40 UTC
Labels: awaiting pr, type: enhancement
