### ISSUE TITLE
`stack test` with multiple packages where the test suite of one package depends on another fails to build.

### ISSUE THREAD

**Issue by barrucadu** [commercialhaskell/stack#1122] opened 2015-10-07 18:33 UTC
This is a little awkward to explain as it involves multiple packages and a test suite, so here's a minimal failing example:

### stack.yaml

````
resolver: lts-3.0
packages:
- b/
- a/
extra-deps: []
flags: {}
````

### a/a.cabal

````
name:                a
version:             0.1.0.0
author:              Michael Walker
maintainer:          mike@barrucadu.co.uk
build-type:          Simple
cabal-version:       >=1.10

library
  exposed-modules:     A
  build-depends:       base
  default-language:    Haskell2010

test-suite tests
  type:                exitcode-stdio-1.0
  main-is:             Test.hs
  build-depends:       base, a, b
  default-language:    Haskell2010
````

### a/A.hs

````
module A where

data ABool = ATrue | AFalse deriving Eq
````

### a/Test.hs

````
module Main where

import A
import B

main = print $ bval == ATrue
````

### a/Setup.hs

As generated by cabal init.

### b/b.cabal

````
name:                b
version:             0.1.0.0
author:              Michael Walker
maintainer:          mike@barrucadu.co.uk
build-type:          Simple
cabal-version:       >=1.10

library
  exposed-modules:     B
  build-depends:       base, a
  default-language:    Haskell2010
````

### b/B.hs

````
module B where

import A

bval :: ABool
bval = ATrue
````

### b/Setup.hs

As generated by cabal init.

## Expected result

`stack test a` to build and run the test suite for a.

## Actual result

`stack test` appears to build a twice, and then fails to build the test suite due to this conflicting state:

````
 >>>  stack test a
a-0.1.0.0: build (test)
Preprocessing library a-0.1.0.0...
In-place registering a-0.1.0.0...
Preprocessing test suite 'tests' for a-0.1.0.0...
[2 of 2] Compiling Main             ( Test.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/tests/tests-tmp/Main.o )

Test.hs:6:24:
    Couldn't match expected type ‘a-0.1.0.0@a_Jmp0dBbBHj39AejfZCXGpl:A.ABool’
                with actual type ‘ABool’
    NB: ‘a-0.1.0.0@a_Jmp0dBbBHj39AejfZCXGpl:A.ABool’
          is defined in ‘A’ in package ‘a-0.1.0.0@a_Jmp0dBbBHj39AejfZCXGpl’
        ‘ABool’ is defined in ‘A’
    In the second argument of ‘(==)’, namely ‘ATrue’
    In the second argument of ‘($)’, namely ‘bval == ATrue’

--  While building package a-0.1.0.0 using:
      /usr/userfs/m/msw504/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-linux-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/ build test:tests --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
````

This has just bit me, as I have a repository containing two packages: a library, and one integrating it with hunit. I tried to port the test suite for the library to use hunit, but this triggers this issue. So I either have to stick with my own hand-rolled testing code, or duplicate all the hunit integration.

**Comment by snoyberg** [comment] 2015-10-12 06:38
I'm not sure that there's any way to get this to work with the current state of the Cabal library's interface. Improvement to this would come via #834. For now, I'd recommend putting the test suite in a separate package.

**Comment by mgsloan** [comment] 2015-11-05 08:29
This is caused by [a cabal bug which is fixed in the development version](https://github.com/haskell/cabal/issues/2870).  I don't think there's any way to work around it.

**Closed by mgsloan** 2015-11-05 08:29 UTC
