### ISSUE TITLE
/bin/bash

### ISSUE THREAD

**Issue by Pitometsu** [commercialhaskell/stack#1117] opened 2015-10-06 23:51 UTC
stack setup on NixOS error:
```shell
netsu@hackbook> stack setup
Warning: https://raw.githubusercontent.com/fpco/stackage-content/master/stack/stack-setup-2.yaml: Unrecognized field in SetupInfo: ghcjs
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-7.8.4.                                     
Configuring GHC ...Running /tmp/stack-setup16393/ghc-7.8.4/configure --prefix=/home/netsu/.stack/programs/x86_64-linux/ghc-7.8.4/ exited with ExitFailure 1
checking for path to top of build tree... /tmp/stack-setup16393/ghc-7.8.4/configure: utils/ghc-pwd/dist-install/build/tmp/ghc-pwd-bindist: /bin/bash: bad interpreter: No such file or directory
configure: error: cannot determine current directory
```

Should use `/bin/sh` or `/usr/bin/env bash`

**Comment by snoyberg** [comment] 2015-10-07 15:53
Dupe of #826

**Closed by snoyberg** 2015-10-07 15:53 UTC
