### ISSUE TITLE
OVERLAP pragmas are not updated between compiles

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [commercialhaskell/stack#5126] opened 2019-12-19 22:46 UTC
### General summary/comments (optional)

This error has been stumping me for a while and makes working with overlapping instances near impossible until I realized that stack was not updating the compiled objects when only the overlap pragmas were changed. I suspect that is because it is a comment and there is no change to the code structure.

### Steps to reproduce

run `stack new overlap-bug`

Put the following in *src/Lib.hs*
```haskell
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE FlexibleInstances #-}

module Lib where

class Over a where over :: a -> String

instance Show a => Over a where over _ = "Show a"
instance Over Int where over _ = "Int"
```

Put the following in *app/Main.hs*. This is key because the overlapping instances must occur in a separate file from the instance declarations.
```haskell
module Main where

import Lib

main :: IO ()
main = putStrLn $ over (1 :: Int)
```

run `stack build`. You should get an **Overlapping instances** error.

change *src/Lib.hs* to
```haskell
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE FlexibleInstances #-}

module Lib where

class Over a where over :: a -> String

instance Show a => Over a where over _ = "Show a"
instance {-# OVERLAPS #-} Over Int where over _ = "Int" -- notice the added OVERLAPS
```

run `stack build` again. Notice that the **Overlapping instances** error has not been resolved.

remove all of `.stack-work` with `rm -rf .stack-work/`. The **Overlapping instances** error has disappeared.

### Expected

I expected the **Overlapping instances** error to have been resolved with the addition of `{-# OVERLAPS #-}`.

### Actual

The **Overlapping instances** error was not resolved until I removed all of *.stack-work/* and recompiled.

### Stack version

```
> stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
```

**Comment by mpilgrem** [comment] 2024-04-02 22:07
I am closing this issue given the passage of time and because I could not reproduce the problem with Stack 2.15.5 and GHC 9.6.4 on Windows. I am wondering if this was some GHC bug that has been fixed, recalling that GHC's recompilation checker has had bugs in the past (https://discourse.haskell.org/t/problem-with-ghcs-recompilation-checker/7079).

**Closed by mpilgrem** 2024-04-02 22:07 UTC
