### ISSUE TITLE
`stack test` failed to build tests

### ISSUE THREAD

**Issue by YoEight** [commercialhaskell/stack#1455] opened 2015-12-01 14:31 UTC
Greetings,

considering this `.cabal`

```
name:              corecursion-net
version:           0.0.0
cabal-version:     >= 1.10
build-type:        Simple

Flag dev
    Description:   Turn on development settings, like auto-reload templates.
    Default:       False

Flag library-only
    Description:   Build for use with "yesod devel"
    Default:       False

library
    hs-source-dirs: ., app
    exposed-modules: Application
                     Foundation
                     Import
                     Import.NoFoundation
                     Model
                     Repository
                     Settings
                     Settings.StaticFiles
                     Store
                     Handler.Admin
                     Handler.Common
                     Handler.Home
                     Handler.Post

    if flag(dev) || flag(library-only)
        cpp-options:   -DDEVELOPMENT
        ghc-options:   -Wall -fwarn-tabs -O0
    else
        ghc-options:   -Wall -fwarn-tabs -O2

    default-extensions: TemplateHaskell
                        QuasiQuotes
                        OverloadedStrings
                        NoImplicitPrelude
                        CPP
                        MultiParamTypeClasses
                        TypeFamilies
                        GADTs
                        GeneralizedNewtypeDeriving
                        FlexibleContexts
                        EmptyDataDecls
                        NoMonomorphismRestriction
                        DeriveDataTypeable
                        ViewPatterns
                        TupleSections
                        RecordWildCards

    build-depends: base                          >= 4          && < 5
                 , yesod
                 , yesod-core
                 , yesod-auth
                 , yesod-static
                 , yesod-form
                 , classy-prelude
                 , classy-prelude-conduit
                 , classy-prelude-yesod
                 , bytestring
                 , text
                 , persistent
                 , persistent-template
                 , template-haskell
                 , shakespeare
                 , hjsmin
                 , monad-control
                 , wai-extra
                 , yaml
                 , http-conduit
                 , directory
                 , warp
                 , data-default
                 , aeson
                 , conduit
                 , monad-logger
                 , fast-logger
                 , wai-logger
                 , file-embed
                 , safe
                 , unordered-containers
                 , containers
                 , vector
                 , time
                 , eventstore >= 0.9
                 , uuid
                 , stm
                 , pandoc
                 , containers
                 , highlighting-kate
                 , mtl
                 , attoparsec
                 , blaze-html
                 , pwstore-fast

    default-language: Haskell2010

executable         corecursion-net
    if flag(library-only)
        Buildable: False

    main-is:           main.hs
    hs-source-dirs:    app
    build-depends:     base, corecursion-net

    ghc-options:       -threaded -O2 -rtsopts -with-rtsopts=-N
    default-language:  Haskell2010

Test-Suite bootstrap
  Type:             exitcode-stdio-1.0
  hs-source-dirs:   bootstrap
  Main-Is:          main.hs
  default-language: Haskell2010

  Build-Depends:    base,
                    eventstore,
                    aeson,
                    text,
                    time,
                    pwstore-fast,
                    bytestring
```

It's a yesod app.

When entering `stack test`, this is what I got:

```
yoeight@haestrom corecursion-net [master] $ stack test
Test suite bootstrap executable not found for corecursion-net
Test suite failure for package corecursion-net-0.0.0
    bootstrap:  executable not found
Logs printed to console
```

Note that I'm able to `stack exec yesod devel` and working on my webapp. So, I presume it isn't related to `yesod-bin`.

stack: Version 0.1.8.0, Git revision e33dd995e292efcf8ee42e1e4c649b96232abf2e (2603 commits) x86_64

ghc: 7.10.2

yesod-bin: 1.4.14

Thanks for your time.

**Comment by YoEight** [comment] 2015-12-01 16:26
@mboes found out a workaround, I add `Buildable: True` in the test-suite section, it works.

Note that I don't need to do this if my project is a library.

**Comment by mboes** [comment] 2015-12-01 16:32
Confirmed, insofar as it's possible to confirm that the below is exhibiting the same bug as @YoEight's (since no source code for that one). Here's a smaller example:

```
$ stack new foo
$ cd foo
$ stack build
$ stack test
Test suite foo-test executable not found for foo
Test suite failure for package foo-0.1.0.0
    foo-test:  executable not found
Logs printed to console
$ echo $?
1
```

Contrast this with

```
$ stack clean
$ stack test
...
$ echo $?
0
```

This bug breaks basically a number of CI script out there that build the project in a separate step to testing packages.

**Comment by luigy** [comment] 2015-12-01 16:40
looks like a duplicate of #1399 
this was fixed on https://github.com/commercialhaskell/stack/commit/ac57440c8554ecfd9f3fda708400ebd731eafbd0

**Comment by mboes** [comment] 2015-12-01 17:15
Ah right. Would be good to have a bugfix release including this change, as @mgsloan proposed in #1399. Sounds like multiple people have been running into this independently and investigating it.

**Comment by mgsloan** [comment] 2015-12-02 00:34
Agreed!  I think the plan is to just put out another release this week.

**Closed by mgsloan** 2015-12-02 00:34 UTC
