### ISSUE TITLE
Local templates

### ISSUE THREAD

**Issue by beojan** [commercialhaskell/stack#1033] opened 2015-09-23 11:42 UTC
Would it be possible to add local (customized) templates for `stack new`?

**Comment by mwm** [comment] 2015-09-23 16:36
Sure looks like it ought to be possible via the templates field in ~/.stack/stack.yaml, but if it is, I can't seem to find any documentation on it.

**Comment by cocreature** [comment] 2015-09-23 18:39
duplicate of #783

**Closed by cocreature** 2015-09-23 18:39 UTC
