### ISSUE TITLE
stack setup fails (at least on travis.ci); says that GHC 7.8.4 failed sanity checks

### ISSUE THREAD

**Issue by tebello-thejane** [commercialhaskell/stack#320] opened 2015-06-15 20:58 UTC
See the following travis build: https://travis-ci.org/tebello-thejane/bitx-haskell/jobs/66911296

Incidentally, I added `stack setup` after the behaviour of stack changed and it insisted that `setup` has to be run before `build`, to download GHC. However, `setup` fails after downloading GHC.

```
Downloading lts-2.13 build plan ...
Downloaded lts-2.13 build plan.

Updating package index Hackage (mirrored at https://github.com/commercialhaskell/all-cabal-hashes.git) ...Fetching package index ...Fetched package index.

Populated index cache.

Preparing to download ghc-7.8.4 ...
ghc-7.8.4: download has begun 
ghc-7.8.4: 2801191 bytes downloaded..
[...]
ghc-7.8.4: 68845095 bytes downloaded...
Downloaded ghc-7.8.4.

Unpacking GHC ...
Configuring GHC ...
Installing GHC ...
Installed GHC.

The GHC located at /home/travis/.stack/programs/x86_64-linux/ghc-7.8.4/bin/ghc failed to compile a sanity check. Please see:

    https://github.com/commercialhaskell/stack/wiki/Downloads

for more information. Exception was:

Process exited with ExitFailure 1: /home/travis/.stack/programs/x86_64-linux/ghc-7.8.4/bin/ghc /tmp/stack-sanity-check3444/Main.hs
```

**Comment by snoyberg** [comment] 2015-06-16 05:12
@chrisdone recently improved things so that stderr will be printed on failures like this, which will let us know why the sanity check failed (my guess: missing system library like libgmp-dev, see #309 and d06c99cec04d4c20cf4322ccfd871b643f8d3d04). Options for now are:

* Trying building with stack from master
* Add some line to your Travis file that manually does a sanity check with GHC to see what's wrong
* Wait till we do a 0.0.3 later this week, and test again

Whatever you try, if you could provide feedback, it would be much appreciated.

On a completely separate note: nice .travis.yml! Would you consider adding a link to it from the FAQ wiki page, in the part about Travis?

**Comment by tebello-thejane** [comment] 2015-06-16 12:11
I seem to have "fixed" the issue in my repo.

* I was installing GMP before `stack build`, but the change in behaviour of stack meant that I needed to install GHC dependencies before `stack setup`, not just `stack build`. Adding `sudo apt-get build-dep ghc` to the travis script at least removed the sanity checks' issue.
* And then I started getting errors along the lines of `/home/travis/.stack/snapshots/x86_64-linux: createDirectory: does not exist (No such file or directory)`: https://travis-ci.org/tebello-thejane/bitx-haskell/jobs/66993648 . I "fixed" this by adding `sudo` all over the place until the error disappeared. :-|.

Stack now works well again in my travis build: https://travis-ci.org/tebello-thejane/bitx-haskell/jobs/67009497

The `.travis.yml` is a bit of a mess, as I was trying to figure out travis, stack, and bash at the same time. But I have tried to clean it up a bit more. I'll gladly add a few words about it to the FAQs (where, exactly?). Do I need to clone and then do a merge request?

**Comment by snoyberg** [comment] 2015-06-16 13:03
The FAQ is on the wiki: https://github.com/commercialhaskell/stack/wiki/FAQ . Feel free to edit to your heart's content :)

I'm glad the issue is worked out, we're also playing around right now with some usage of Travis's cached build stuff, which may be a nice addition as well. I'm going to close the issue for now, if more problems crop up, just let me know.

**Closed by snoyberg** 2015-06-16 13:03 UTC
Labels: bug
