### ISSUE TITLE
Explicitly building packages that aren't in a snapshot ignores --test and --bench

### ISSUE THREAD

**Issue by bergmark** [commercialhaskell/stack#2623] opened 2016-09-22 19:07 UTC
stack: Version 1.2.0 x86_64 hpack-0.14.0

If a package isn't in the specified snapshot stack will ignore `--test` and `--bench`. Even when it's the only package being installed.

A use case for this is testing your package before submitting it to stackage with `stack haddock --test --build --resolver nightly my-package`.

Currently:
```
$ stack haddock --test --resolver nightly-2016-09-22 cron
Run from outside a project, using implicit global project config
Using resolver: nightly-2016-09-22 specified on command line
old-locale-1.0.0.7: using precompiled package
primitive-0.6.1.0: using precompiled package
mtl-2.2.1: using precompiled package
semigroups-0.18.2: using precompiled package
text-1.2.2.1: using precompiled package
vector-0.11.0.0: using precompiled package
mtl-compat-0.2.1.3: using precompiled package
hashable-1.2.4.0: using precompiled package
scientific-0.3.4.9: using precompiled package
attoparsec-0.13.1.0: using precompiled package
cron-0.4.1.2: configure
cron-0.4.1.2: build
cron-0.4.1.2: haddock
cron-0.4.1.2: copy/register
Updating Haddock index for snapshot packages in
/Users/adam/.stack/snapshots/x86_64-osx/nightly-2016-09-22/8.0.1/doc/index.html
```

The test dependencies are not installed and the tests don't run. It
looks like the haddocks are generated but they don't show up in the
index.html that was listed, and I couldn't find them anywhere in
`~/.stack` either.

I would expect the tests to run. The haddocks should probably not show
up in the nightly's doc directory but building them for testing would
still be useful, it looks like that already happens but the message is confusing.

**Comment by mgsloan** [comment] 2016-09-26 01:06
Dupe of https://github.com/commercialhaskell/stack/issues/2382 .  I'm not sure how this should be addressed, because `--test` and `--bench` only apply to local packages.  Suggestions appreciated.

**Closed by mgsloan** 2016-09-26 01:06 UTC
