### ISSUE TITLE
Contrary to docs, not seeing warnings that were logged in multi-pkg project

### ISSUE THREAD

**Issue by metaleap** [commercialhaskell/stack#2997] opened 2017-02-11 13:44 UTC
The docs [state](https://docs.haskellstack.org/en/stable/build_command/#build-output):

> By default, when building multiple target packages, the output from these will end up in a log file instead of on the console unless it contains errors **or warnings**

Not the case at my end with 1.3.2 (latest I reckon, Win64 build), so I'd have to `dump-logs` to see those warnings.. errors **do** get properly emitted as described above however. Did GHC's output format for warnings change in 8.0.2 or something?  😁

**Comment by borsboom** [comment] 2017-02-12 01:03
Also possible the different line endings on Windows are interfering with warning detection.

**Comment by bucklereed** [comment] 2017-08-27 12:38
I'm also seeing this (or, rather, not seeing them) on Linux with GHC 8.2.1.

**Comment by heroin-moose** [comment] 2018-05-24 12:56
I can confirm that on GHC 8.2.x it shows me warnings only with

```
dump-logs: all
```

but in fact it should work out of the box because the defaults is

```
dump-logs: warning
```

**Comment by snoyberg** [comment] 2019-04-01 10:00
Should be fixed by #4679

**Closed** 2019-04-01 10:58 UTC
Labels: type: bug
