### ISSUE TITLE
[Fresh Install, Win64] Broken mintty package, potentially unwanted software (Win32/Beareuws.A!ml)

### ISSUE THREAD

**Issue by p-groarke** [commercialhaskell/stack#5661] opened 2021-12-30 20:02 UTC
### General summary/comments (optional)
Executing a fully fresh install (first time user) on windows latest. You get a compile error in mintty because of [this issue](https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework).

After fixing the mintty problem, Windows Defender detects a low severity potentially unwanted software `Win32/Beareuws.A!ml` in `C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_3.2.1.0_ghc-8.10.7.exe` 

### Steps to reproduce

Install stack latest on windows (x64).

```bash
stack new new-project rio
cd new-project
stack run
```
### Expected

It compiles and runs, no windows defender warning.

### Actual

mintty compile error. After fixing that, windows defender warning.

### Stack version

```
$ stack --version
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mpilgrem** [comment] 2022-04-13 20:49
I am going to close this issue, as the current official binary for `stack` is now version 2.7.5 and - with that version - I cannot reproduce the issue on Windows 11.

**Closed by mpilgrem** 2022-04-13 20:49 UTC

**Comment by p-groarke** [comment] 2022-04-14 04:37
Thanks for the prompt and timely response. Potentially spreading malware to your users isn't a high priority item 👍

**Comment by mpilgrem** [comment] 2022-04-14 18:27
I don't know if anybody looked at your issue before I did, but it is likely the Windows Defender report was a false positive and/or an upstream issue. The `Cabal-simple_[hash]_[version]_ghc-[version].exe` does not 'ship with' `stack.exe` - it is built by `stack.exe`, when it runs (see `Stack.Build.Execute.getSetupExe`), and the source code for the `.exe` (a two-line program, which has likely been the same 'for ever') is 'hard coded' into the source code for `stack.exe`.

**Comment by p-groarke** [comment] 2022-04-14 18:33
I understand this likely doesn't fall on you, but considering stack was installed on production machines, "probably false positive" doesn't really cut it ;)

Where to point the finger is a good question, and the finger should have been pointed at the right project a long time ago, accompanied by an official response.

Anyhow, take care.
