### ISSUE TITLE
Support arbitrary new project templates

### ISSUE THREAD

**Issue by FranklinChen** [commercialhaskell/stack#1081] opened 2015-09-30 06:49 UTC
Right now, `stack new` seems to only support official project templates at https://github.com/commercialhaskell/stack-templates but it would be nice to be able to reference one's own templates whether through a URL or on one's local file system.

**Comment by snoyberg** [comment] 2015-09-30 10:42
This looks like a dupe of #783.

**Closed** 2015-10-01 11:04 UTC
Labels: resolution: duplicate
