### ISSUE TITLE
stack build ignores ghc-options: -fforce-recomp

### ISSUE THREAD

**Issue by beala** [commercialhaskell/stack#1688] opened 2016-01-21 00:50 UTC
# Summary

`ghc-options: -fforce-recomp` is ignored when added to cabal file. `stack build` doesn't always rebuild.

# Reproduce:

```
stack new test simple
cd test
stack build # Project rebuilds as expected.
vim test.cabal # Add `ghc-options: -fforce-recomp` under `executable test`
stack build # Doesn't rebuild (unexpected)
stack build # Doesn't rebuild (unexpected)
```

**Comment by mgsloan** [comment] 2016-01-21 01:13
Hi, thanks for the report, but I cannot reproduce the issue.  What's your stack version?

```
mgsloan@computer:~/fpco/test-stack/issue1688$ stack build
issue1688-0.1.0.0: configure
Configuring issue1688-0.1.0.0...
issue1688-0.1.0.0: build
Preprocessing library issue1688-0.1.0.0...
[1 of 1] Compiling Lib              ( src/Lib.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Lib.o )
In-place registering issue1688-0.1.0.0...
Preprocessing executable 'issue1688-exe' for issue1688-0.1.0.0...
[1 of 1] Compiling Main             ( app/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/issue1688-exe/issue1688-exe-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/issue1688-exe/issue1688-exe ...
issue1688-0.1.0.0: copy/register
Installing library in
/home/mgsloan/fpco/test-stack/issue1688/.stack-work/install/x86_64-linux/lts-4.2/7.10.3/lib/x86_64-linux-ghc-7.10.3/issue1688-0.1.0.0-5Z2hf5RccjsEzIu7V3GH9i
Installing executable(s) in
/home/mgsloan/fpco/test-stack/issue1688/.stack-work/install/x86_64-linux/lts-4.2/7.10.3/bin
Registering issue1688-0.1.0.0...
mgsloan@computer:~/fpco/test-stack/issue1688$ vim issue1688.cabal 
mgsloan@computer:~/fpco/test-stack/issue1688$ stack build
issue1688-0.1.0.0: unregistering (local file changes: issue1688.cabal)
issue1688-0.1.0.0: configure
Configuring issue1688-0.1.0.0...
issue1688-0.1.0.0: build
Preprocessing library issue1688-0.1.0.0...
In-place registering issue1688-0.1.0.0...
Preprocessing executable 'issue1688-exe' for issue1688-0.1.0.0...
[1 of 1] Compiling Main             ( app/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/issue1688-exe/issue1688-exe-tmp/Main.o )
[1 of 1] Compiling Main             ( app/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/issue1688-exe/issue1688-exe-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/issue1688-exe/issue1688-exe ...
issue1688-0.1.0.0: copy/register
Installing library in
/home/mgsloan/fpco/test-stack/issue1688/.stack-work/install/x86_64-linux/lts-4.2/7.10.3/lib/x86_64-linux-ghc-7.10.3/issue1688-0.1.0.0-5Z2hf5RccjsEzIu7V3GH9i
Installing executable(s) in
/home/mgsloan/fpco/test-stack/issue1688/.stack-work/install/x86_64-linux/lts-4.2/7.10.3/bin
Registering issue1688-0.1.0.0...
Version 1.0.3, Git revision 6256054f93c43ba6be5345d556b0a4903b0b2151 (dirty) (3090 commits) x86_64
```

cabal file after modification:

```
name:                issue1688
version:             0.1.0.0
synopsis:            Initial project template from stack
description:         Please see README.md
homepage:            http://github.com/githubuser/issue1688#readme
license:             BSD3
license-file:        LICENSE
author:              Author name here
maintainer:          example@example.com
copyright:           2010 Author Here
category:            Web
build-type:          Simple
-- extra-source-files:
cabal-version:       >=1.10

library
  hs-source-dirs:      src
  exposed-modules:     Lib
  build-depends:       base >= 4.7 && < 5
  default-language:    Haskell2010

executable issue1688-exe
  hs-source-dirs:      app
  main-is:             Main.hs
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  build-depends:       base
                     , issue1688
  default-language:    Haskell2010
  ghc-options:         -fforce-recomp

test-suite issue1688-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             Spec.hs
  build-depends:       base
                     , issue1688
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010

source-repository head
  type:     git
  location: https://github.com/githubuser/issue1688
```

**Comment by mgsloan** [comment] 2016-01-24 23:27
Closing due to no repro.

**Closed by mgsloan** 2016-01-24 23:27 UTC
Labels: need repro
